package pack:name;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface component-name-api {
  add: func(value: u64);
  get: func() -> u64;
}

world component-name {
  include wasi:cli/imports@0.2.3;
  import wasi:cli/environment@0.2.3;

  export component-name-api;
}
