[package]
name = "direct-wire-preparation"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "direct-wire-preparation"
path = "../direct_wire_preparation.rs"

[dependencies]
golem-schema = { path = "../../../../../golem-schema", default-features = false, features = ["guest"] }

[profile.release]
debug = false
lto = true
opt-level = 's'
strip = "symbols"
