// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
const _: () = {
  
  #[doc(hidden)]
  #[export_name = "run"]
  #[allow(non_snake_case)]
  unsafe extern "C" fn __export_run() -> i32 {
    #[allow(unused_imports)]
    use wit_bindgen::rt::{alloc, vec::Vec, string::String};
    
    // Before executing any other code, use this function to run all static
    // constructors, if they have not yet been run. This is a hack required
    // to work around wasi-libc ctors calling import functions to initialize
    // the environment.
    //
    // This functionality will be removed once rust 1.69.0 is stable, at which
    // point wasi-libc will no longer have this behavior.
    //
    // See
    // https://github.com/bytecodealliance/preview2-prototyping/issues/99
    // for more details.
    #[cfg(target_arch="wasm32")]
    wit_bindgen::rt::run_ctors_once();
    
    let result0 = <_GuestImpl as Guest>::run();
    let ptr1 = _RET_AREA.0.as_mut_ptr() as i32;
    let (t2_0, t2_1, t2_2, ) = result0;
    *((ptr1 + 0) as *mut f64) = wit_bindgen::rt::as_f64(t2_0);
    *((ptr1 + 8) as *mut f64) = wit_bindgen::rt::as_f64(t2_1);
    let vec3 = (t2_2.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr() as i32;
    let len3 = vec3.len() as i32;
    ::core::mem::forget(vec3);
    *((ptr1 + 20) as *mut i32) = len3;
    *((ptr1 + 16) as *mut i32) = ptr3;
    ptr1
  }
  
  const _: () = {
    #[doc(hidden)]
    #[export_name = "cabi_post_run"]
    #[allow(non_snake_case)]
    unsafe extern "C" fn __post_return_run(arg0: i32,) {
      let l0 = *((arg0 + 16) as *const i32);
      let l1 = *((arg0 + 20) as *const i32);
      wit_bindgen::rt::dealloc(l0, (l1) as usize, 1);
    }
  };
};
const _: () = {
  
  #[doc(hidden)]
  #[export_name = "sleep-for"]
  #[allow(non_snake_case)]
  unsafe extern "C" fn __export_sleep_for(arg0: f64,) -> f64 {
    #[allow(unused_imports)]
    use wit_bindgen::rt::{alloc, vec::Vec, string::String};
    
    // Before executing any other code, use this function to run all static
    // constructors, if they have not yet been run. This is a hack required
    // to work around wasi-libc ctors calling import functions to initialize
    // the environment.
    //
    // This functionality will be removed once rust 1.69.0 is stable, at which
    // point wasi-libc will no longer have this behavior.
    //
    // See
    // https://github.com/bytecodealliance/preview2-prototyping/issues/99
    // for more details.
    #[cfg(target_arch="wasm32")]
    wit_bindgen::rt::run_ctors_once();
    
    let result0 = <_GuestImpl as Guest>::sleep_for(arg0);
    wit_bindgen::rt::as_f64(result0)
  }
};
use super::Component as _GuestImpl;
pub trait Guest {
  fn run() -> (f64,f64,wit_bindgen::rt::string::String,);
  fn sleep_for(seconds: f64,) -> f64;
}

#[allow(unused_imports)]
use wit_bindgen::rt::{alloc, vec::Vec, string::String};

#[repr(align(8))]
struct _RetArea([u8; 24]);
static mut _RET_AREA: _RetArea = _RetArea([0; 24]);

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:clocks"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 196] = [3, 0, 6, 99, 108, 111, 99, 107, 115, 0, 97, 115, 109, 13, 0, 1, 0, 7, 73, 1, 65, 2, 1, 65, 5, 1, 111, 3, 117, 117, 115, 1, 64, 0, 0, 0, 4, 0, 3, 114, 117, 110, 1, 1, 1, 64, 1, 7, 115, 101, 99, 111, 110, 100, 115, 117, 0, 117, 4, 0, 9, 115, 108, 101, 101, 112, 45, 102, 111, 114, 1, 2, 4, 1, 15, 103, 111, 108, 101, 109, 58, 105, 116, 47, 99, 108, 111, 99, 107, 115, 4, 0, 11, 12, 1, 0, 6, 99, 108, 111, 99, 107, 115, 3, 0, 0, 0, 16, 12, 112, 97, 99, 107, 97, 103, 101, 45, 100, 111, 99, 115, 0, 123, 125, 0, 70, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 49, 56, 46, 50, 16, 119, 105, 116, 45, 98, 105, 110, 100, 103, 101, 110, 45, 114, 117, 115, 116, 6, 48, 46, 49, 54, 46, 48];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
