package golem:it;

world js1 {
    import wasi:clocks/wall-clock@0.2.3;
    export hello: func(name: string) -> hello-record;

    record hello-record {
        random: f64,
        random-string: string,
        // milliseconds
        js-now: u64,
        // milliseconds
        wasi-now: u64,
    }
}
