package pack:name;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax
// See https://github.com/WebAssembly/wasi-http for an introduction to wasi-http

world component-name {
  include wasi:cli/imports@0.2.3;
  import wasi:http/outgoing-handler@0.2.3;
  export wasi:http/incoming-handler@0.2.3;
}
