/*
 * Copyright 2024-2026 Golem Cloud
 *
 * Licensed under the Golem Source License v1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://license.golem.cloud/LICENSE
 */

package golem.reflection

// Generated by scripts/sync-reflection-conformance.mjs. Do not edit.
private[reflection] object ReflectionConformanceCorpus {
  val json: String = """{
  "version": "1.0.0",
  "schemaKinds": [
    "ref",
    "bool",
    "s8",
    "s16",
    "s32",
    "s64",
    "u8",
    "u16",
    "u32",
    "u64",
    "f32",
    "f64",
    "char",
    "string",
    "record",
    "variant",
    "enum",
    "flags",
    "tuple",
    "list",
    "fixed-list",
    "map",
    "option",
    "result",
    "text",
    "binary",
    "path",
    "url",
    "datetime",
    "duration",
    "quantity",
    "union",
    "secret",
    "quota-token",
    "permission-card",
    "future",
    "stream"
  ],
  "restrictionKinds": [
    "numeric-minimum",
    "numeric-maximum",
    "numeric-unit",
    "text-languages",
    "text-min-length",
    "text-max-length",
    "text-regex",
    "binary-mime-types",
    "binary-min-bytes",
    "binary-max-bytes",
    "path-direction",
    "path-kind",
    "path-mime-types",
    "path-extensions",
    "url-schemes",
    "url-hosts",
    "quantity-base-unit",
    "quantity-suffixes",
    "quantity-minimum",
    "quantity-maximum",
    "union-prefix",
    "union-suffix",
    "union-regex",
    "union-field"
  ],
  "caseIds": [
    "canonical/s64-min",
    "canonical/s64-max",
    "canonical/u64-max",
    "canonical/duration-min",
    "canonical/duration-max",
    "canonical/quantity-wide-mantissa",
    "canonical/omitted-options",
    "canonical/binary-mime",
    "errors/s64-plus",
    "errors/s64-leading-zero",
    "errors/s64-negative-zero",
    "errors/s64-overflow",
    "errors/u64-negative",
    "errors/u64-overflow",
    "errors/wide-wrong-json-type",
    "errors/duration-legacy-string",
    "errors/quantity-negative-zero",
    "errors/quantity-extra-field",
    "errors/binary-noncanonical-base64",
    "json-schema/s64",
    "json-schema/s64-restrictions",
    "json-schema/u32-restrictions",
    "json-schema/f64-restrictions",
    "json-schema/text-restrictions",
    "json-schema/binary-restrictions",
    "json-schema/u64",
    "json-schema/duration-nanoseconds",
    "json-schema/quantity-mantissa",
    "json-schema/optional-required",
    "json-schema/unsupported-leaves",
    "schema/all-kinds",
    "schema/all-restrictions",
    "graph/references-validation-equivalence",
    "tool/canonical-input",
    "config/canonical-entry",
    "constraints/rejected-value",
    "compatibility/result",
    "compatibility/custom-error"
  ],
  "cases": [
    {
      "id": "canonical/s64-min",
      "operation": "roundtrip",
      "fixture": "s64",
      "input": "-9223372036854775808",
      "expected": "-9223372036854775808"
    },
    {
      "id": "canonical/s64-max",
      "operation": "roundtrip",
      "fixture": "s64",
      "input": "9223372036854775807",
      "expected": "9223372036854775807"
    },
    {
      "id": "canonical/u64-max",
      "operation": "roundtrip",
      "fixture": "u64",
      "input": "18446744073709551615",
      "expected": "18446744073709551615"
    },
    {
      "id": "canonical/duration-min",
      "operation": "roundtrip",
      "fixture": "duration",
      "input": {
        "nanoseconds": "-9223372036854775808"
      },
      "expected": {
        "nanoseconds": "-9223372036854775808"
      }
    },
    {
      "id": "canonical/duration-max",
      "operation": "roundtrip",
      "fixture": "duration",
      "input": {
        "nanoseconds": "9223372036854775807"
      },
      "expected": {
        "nanoseconds": "9223372036854775807"
      }
    },
    {
      "id": "canonical/quantity-wide-mantissa",
      "operation": "roundtrip",
      "fixture": "quantity",
      "input": {
        "mantissa": "-9223372036854775808",
        "scale": -9,
        "unit": "m"
      },
      "expected": {
        "mantissa": "-9223372036854775808",
        "scale": -9,
        "unit": "m"
      }
    },
    {
      "id": "canonical/omitted-options",
      "operation": "roundtrip",
      "fixture": "optional-record",
      "input": {},
      "expected": {
        "direct": null,
        "referenced": null
      }
    },
    {
      "id": "canonical/binary-mime",
      "operation": "roundtrip",
      "fixture": "binary",
      "input": {
        "bytes": "-_8",
        "mimeType": "application/octet-stream"
      },
      "expected": {
        "bytes": "-_8",
        "mimeType": "application/octet-stream"
      }
    },
    {
      "id": "errors/s64-plus",
      "operation": "reject",
      "fixture": "s64",
      "input": "+1",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/s64-leading-zero",
      "operation": "reject",
      "fixture": "s64",
      "input": "01",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/s64-negative-zero",
      "operation": "reject",
      "fixture": "s64",
      "input": "-0",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/s64-overflow",
      "operation": "reject",
      "fixture": "s64",
      "input": "9223372036854775808",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/u64-negative",
      "operation": "reject",
      "fixture": "u64",
      "input": "-1",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/u64-overflow",
      "operation": "reject",
      "fixture": "u64",
      "input": "18446744073709551616",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/wide-wrong-json-type",
      "operation": "reject",
      "fixture": "s64",
      "input": 1,
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/duration-legacy-string",
      "operation": "reject",
      "fixture": "duration",
      "input": "PT1S",
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/quantity-negative-zero",
      "operation": "reject",
      "fixture": "quantity",
      "input": {
        "mantissa": "-0",
        "scale": 0,
        "unit": "m"
      },
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/quantity-extra-field",
      "operation": "reject",
      "fixture": "quantity",
      "input": {
        "mantissa": "1",
        "scale": 0,
        "unit": "m",
        "extra": true
      },
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "errors/binary-noncanonical-base64",
      "operation": "reject",
      "fixture": "binary",
      "inputs": [
        {
          "bytes": "+/8",
          "mimeType": "application/octet-stream"
        },
        {
          "bytes": "-_8=",
          "mimeType": "application/octet-stream"
        },
        {
          "bytes": "-_9",
          "mimeType": "application/octet-stream"
        },
        {
          "bytes": "A",
          "mimeType": "application/octet-stream"
        },
        {
          "bytes": "-_8",
          "mime_type": "application/octet-stream"
        }
      ],
      "expected": {
        "kind": "invalid-json"
      }
    },
    {
      "id": "json-schema/s64",
      "operation": "json-schema",
      "fixture": "s64",
      "path": "",
      "expected": {
        "type": "string",
        "format": "int64",
        "pattern": "^(?:0|-[1-9][0-9]*|[1-9][0-9]*)$",
        "x-golem-minimum": "-9223372036854775808",
        "x-golem-maximum": "9223372036854775807"
      }
    },
    {
      "id": "json-schema/s64-restrictions",
      "operation": "json-schema",
      "fixture": "constrained-s64",
      "path": "",
      "expected": {
        "type": "string",
        "format": "int64",
        "pattern": "^(?:0|-[1-9][0-9]*|[1-9][0-9]*)$",
        "x-golem-minimum": "-9007199254740993",
        "x-golem-maximum": "9007199254740993"
      }
    },
    {
      "id": "json-schema/u64",
      "operation": "json-schema",
      "fixture": "u64",
      "path": "",
      "expected": {
        "type": "string",
        "format": "uint64",
        "pattern": "^(?:0|[1-9][0-9]*)$",
        "x-golem-minimum": "0",
        "x-golem-maximum": "18446744073709551615"
      }
    },
    {
      "id": "json-schema/u32-restrictions",
      "operation": "json-schema",
      "fixture": "constrained-u32",
      "path": "",
      "expected": {
        "type": "integer",
        "minimum": 2,
        "maximum": 10
      }
    },
    {
      "id": "json-schema/f64-restrictions",
      "operation": "json-schema",
      "fixture": "constrained-f64",
      "path": "",
      "expected": {
        "type": "number",
        "minimum": -1.5,
        "maximum": 2.5
      }
    },
    {
      "id": "json-schema/text-restrictions",
      "operation": "json-schema",
      "fixture": "constrained-text",
      "path": "",
      "expected": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "minLength": 2,
            "maxLength": 8,
            "pattern": "^[a-z]+$"
          },
          "language": {
            "type": "string",
            "enum": [
              "en",
              "de"
            ]
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "id": "json-schema/binary-restrictions",
      "operation": "json-schema",
      "fixture": "constrained-binary",
      "path": "",
      "expected": {
        "type": "object",
        "properties": {
          "bytes": {
            "type": "string",
            "contentEncoding": "base64url",
            "pattern": "^(?:[A-Za-z0-9_-]{4})*(?:[A-Za-z0-9_-][AQgw]|[A-Za-z0-9_-]{2}[AEIMQUYcgkosw048])?$",
            "minLength": 3,
            "maxLength": 6
          },
          "mimeType": {
            "type": "string",
            "enum": [
              "image/png",
              "application/octet-stream"
            ]
          }
        },
        "required": [
          "bytes"
        ],
        "additionalProperties": false
      }
    },
    {
      "id": "json-schema/duration-nanoseconds",
      "operation": "json-schema",
      "fixture": "duration",
      "path": "/properties/nanoseconds",
      "expected": {
        "type": "string",
        "format": "int64",
        "pattern": "^(?:0|-[1-9][0-9]*|[1-9][0-9]*)$",
        "x-golem-minimum": "-9223372036854775808",
        "x-golem-maximum": "9223372036854775807"
      }
    },
    {
      "id": "json-schema/quantity-mantissa",
      "operation": "json-schema",
      "fixture": "quantity",
      "path": "/properties/mantissa",
      "expected": {
        "type": "string",
        "format": "int64",
        "pattern": "^(?:0|-[1-9][0-9]*|[1-9][0-9]*)$",
        "x-golem-minimum": "-9223372036854775808",
        "x-golem-maximum": "9223372036854775807"
      }
    },
    {
      "id": "json-schema/optional-required",
      "operation": "json-schema",
      "fixture": "optional-record",
      "path": "/required",
      "expected": []
    },
    {
      "id": "json-schema/unsupported-leaves",
      "operation": "semantic",
      "fixture": "unsupported-leaves",
      "expected": {
        "count": 5,
        "schema": {
          "not": {}
        }
      }
    },
    {
      "id": "schema/all-kinds",
      "operation": "semantic",
      "fixture": "all-kinds",
      "expected": {
        "names": [
          "ref",
          "bool",
          "s8",
          "s16",
          "s32",
          "s64",
          "u8",
          "u16",
          "u32",
          "u64",
          "f32",
          "f64",
          "char",
          "string",
          "record",
          "variant",
          "enum",
          "flags",
          "tuple",
          "list",
          "fixed-list",
          "map",
          "option",
          "result",
          "text",
          "binary",
          "path",
          "url",
          "datetime",
          "duration",
          "quantity",
          "union",
          "secret",
          "quota-token",
          "permission-card",
          "future",
          "stream"
        ]
      }
    },
    {
      "id": "schema/all-restrictions",
      "operation": "semantic",
      "fixture": "all-restrictions",
      "expected": {
        "names": [
          "numeric-minimum",
          "numeric-maximum",
          "numeric-unit",
          "text-languages",
          "text-min-length",
          "text-max-length",
          "text-regex",
          "binary-mime-types",
          "binary-min-bytes",
          "binary-max-bytes",
          "path-direction",
          "path-kind",
          "path-mime-types",
          "path-extensions",
          "url-schemes",
          "url-hosts",
          "quantity-base-unit",
          "quantity-suffixes",
          "quantity-minimum",
          "quantity-maximum",
          "union-prefix",
          "union-suffix",
          "union-regex",
          "union-field"
        ]
      }
    },
    {
      "id": "graph/references-validation-equivalence",
      "operation": "semantic",
      "fixture": "graph",
      "expected": {
        "valid": true,
        "equivalent": true
      }
    },
    {
      "id": "tool/canonical-input",
      "operation": "roundtrip",
      "fixture": "tool-input",
      "input": {
        "pattern": "*.rs",
        "paths": [
          "src",
          "tests"
        ]
      },
      "expected": {
        "pattern": "*.rs",
        "paths": [
          "src",
          "tests"
        ],
        "ignoreCase": null
      }
    },
    {
      "id": "config/canonical-entry",
      "operation": "roundtrip",
      "fixture": "config-entry",
      "input": {
        "path": [
          "limits",
          "maximum"
        ],
        "value": "9223372036854775807"
      },
      "expected": {
        "path": [
          "limits",
          "maximum"
        ],
        "value": "9223372036854775807"
      }
    },
    {
      "id": "constraints/rejected-value",
      "operation": "reject",
      "fixture": "constrained-u32",
      "input": 11,
      "expected": {
        "kind": "constraint-violation"
      }
    },
    {
      "id": "compatibility/result",
      "operation": "roundtrip",
      "fixture": "result",
      "input": {
        "ok": "ready"
      },
      "expected": {
        "ok": "ready"
      }
    },
    {
      "id": "compatibility/custom-error",
      "operation": "roundtrip",
      "fixture": "custom-error",
      "input": {
        "err": {
          "code": "denied",
          "retryable": false
        }
      },
      "expected": {
        "err": {
          "code": "denied",
          "retryable": false
        }
      }
    }
  ]
}
"""
}
