package golem:it-python-http-client;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-it-python-http-client-api {
  run: func() -> string;
}

world golem-it-python-http-client {
  // Always required due to a limitation of the bindings generation in componentize-py.
  // This import will fail if removed https://github.com/bytecodealliance/componentize-py/blob/c50822c825b4333ff41a0ea3cd9e0c9bc3df49da/bundled/poll_loop.py#L15
  import wasi:http/outgoing-handler@0.2.0;
  import wasi:cli/environment@0.2.0;

  export golem-it-python-http-client-api;
}
