package golem:agent-ts;

world golem-agent  {
  import golem:api/host@1.1.7;
  import golem:rpc/types@0.2.2;
  import golem:agent/host;

  import golem:rdbms/postgres@0.0.1;
  import golem:rdbms/mysql@0.0.1;
  import golem:rdbms/types@0.0.1;

  import golem:exec/executor@1.0.0;
  import golem:exec/types@1.0.0;
  import golem:graph/connection@1.0.0;
  import golem:graph/errors@1.0.0;
  import golem:graph/schema@1.0.0;
  import golem:graph/transactions@1.0.0;
  import golem:graph/traversal@1.0.0;
  import golem:graph/types@1.0.0;
  import golem:graph/query@1.0.0;
  import golem:llm/llm@1.0.0;
  import golem:search/core@1.0.0;
  import golem:search/types@1.0.0;
  import golem:stt/languages@1.0.0;
  import golem:stt/transcription@1.0.0;
  import golem:stt/types@1.0.0;
  import golem:video-generation/advanced@1.0.0;
  import golem:video-generation/lip-sync@1.0.0;
  import golem:video-generation/types@1.0.0;
  import golem:video-generation/video-generation@1.0.0;
  import golem:web-search/types@1.0.0;
  import golem:web-search/web-search@1.0.0;

  export golem:agent/guest;
}
