/*
 * Copyright 2024-2026 Golem Cloud
 *
 * Licensed under the Golem Source License v1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://license.golem.cloud/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package golem.runtime.macros

import golem.schema.{GolemPath, SchemaGraph, SchemaType, SchemaTypeBody, SchemaValue, Url}
import golem.schema.validation.RefResolution
import golem.tool.*
import golem.runtime.annotations.*
import zio.blocks.schema.Schema
import zio.test.*

import java.time.Instant

/**
 * Verifies the tool descriptor generated by `ToolDefinitionMacro` from
 * `@toolDefinition` traits: parameter classification, docs, defaults,
 * constraints, result/error metadata, subtree grafting, inherited-global
 * de-projection, and cycle detection.
 */
object ToolDefinitionMacroSpec extends ZIOSpecDefault {

  // --- grep: an implicit-body tool exercising every parameter surface -------

  enum GrepError {

    /** The pattern did not parse. */
    @error(kind = "usage", exitCode = 2)
    case BadPattern(pattern: String)

    @error(kind = "runtime-error", exitCode = 1)
    case Failed
  }

  /**
   * Searches files for a pattern.
   *
   * The long grep description.
   */
  @toolDefinition(version = "1.2.3")
  trait Grep {

    /** Search for a pattern. */
    @annotations(readOnly = true, destructive = false)
    @arg("pattern", doc = "the regex pattern")
    @arg("case-sensitive", kind = "flag")
    @arg("max-count", scope = "option", short = 'm')
    @arg("context", scope = "option", default = 2)
    @constraint(requiresAll = Array("pattern"))
    @constraint(implies = Implies(lhs = "case-sensitive", rhs = Array(ValueIs("context", 2))))
    @result(formatters = Array("human", "json"), default = "json")
    @example(body = "grep foo src/", title = "basic")
    def grep(
      pattern: String,
      caseSensitive: Boolean,
      maxCount: Option[Int],
      context: Int,
      paths: Seq[String]
    ): Either[GrepError, String]
  }

  // --- git: a subtree tool with propagating parent globals ------------------

  @toolDefinition(version = "0.1.0")
  trait Remote {

    /** Adds a remote. */
    def add(name: String, url: String): String

    def remove(name: String): Unit
  }

  @toolDefinition(version = "0.2.0")
  trait Git {

    /** Manage the set of remotes. */
    @command(aliases = Array("rmt"))
    def remote(gitDir: String): Remote
  }

  // --- inherited-global de-projection within one trait ----------------------

  @toolDefinition(version = "0.0.1")
  trait Leveler {
    @arg("level", scope = "global", short = 'l')
    def leveler(level: Option[Int]): Unit

    def run(level: Option[Int], input: String): Unit
  }

  // --- subtree cycle ---------------------------------------------------------

  @toolDefinition(name = "a", version = "0.0.1")
  trait CycleA {
    def b(): CycleB
  }

  @toolDefinition(name = "b", version = "0.0.1")
  trait CycleB {
    def a(): CycleA
  }

  // --- @arg refinements -------------------------------------------------------

  @toolDefinition(version = "0.0.1")
  trait Refined {
    @arg("pattern", scope = "option", regex = "^.+$", minLength = 1, maxLength = 64)
    @arg("level", scope = "option", bounds = (0, 100))
    @arg("big", scope = "option", max = "18446744073709551615")
    @arg("target", scope = "option", kind = "dir", direction = "input")
    def refined(
      pattern: Option[String],
      level: Option[Int],
      big: Option[golem.ULong],
      target: Option[golem.schema.GolemPath]
    ): Unit
  }

  // --- subtree root name mismatch --------------------------------------------

  @toolDefinition(version = "0.0.1")
  trait Mismatched {
    def sub(): Remote
  }

  // --- canonical parity examples --------------------------------------------

  sealed trait ColorMode
  case object always extends ColorMode
  case object never  extends ColorMode
  case object auto   extends ColorMode
  object ColorMode {
    implicit val schema: Schema[ColorMode] = Schema.derived
  }

  final case class Hit(file: GolemPath, line: Int, text: String)
  object Hit {
    implicit val schema: Schema[Hit] = Schema.derived
  }

  enum CanonicalGrepError {
    @error(kind = "usage-error", exitCode = 2)
    case InvalidPattern(reason: String)

    @error(kind = "runtime-error", exitCode = 1)
    case NoMatch
  }

  /** Search files for a regex pattern. */
  @toolDefinition(name = "canonical-grep", version = "2.0.0")
  trait CanonicalGrep {

    /** Search files for a regex pattern. Bare `grep` runs this body. */
    @arg("case-sensitive", scope = "global", short = 'i', kind = "flag", doc = "match case exactly")
    @arg("color", scope = "global", default = "auto", doc = "when to colorize matches")
    @arg("pattern", scope = "positional", regex = "^.+$", doc = "regular expression")
    @arg("extra-patterns", scope = "option", short = 'e', repeatable = "either", delim = ',')
    @arg("max-count", scope = "option", short = 'n', min = 1)
    @arg("files", scope = "tail", acceptsStdio = true, doc = "files to search")
    def canonicalGrep(
      caseSensitive: Boolean,
      color: ColorMode,
      pattern: String,
      extraPatterns: Seq[String],
      maxCount: Option[Int],
      files: Seq[GolemPath],
      stdin: ToolInputStream,
      stdout: ToolOutputStream
    ): Either[CanonicalGrepError, Seq[Hit]]

    /** In-place text replacement. */
    def replace(
      caseSensitive: Boolean,
      color: ColorMode,
      pattern: String,
      replacement: String,
      files: Seq[GolemPath]
    ): Either[CanonicalGrepError, Long]
  }

  sealed trait OutputMode
  case object human     extends OutputMode
  case object porcelain extends OutputMode
  case object json      extends OutputMode
  object OutputMode {
    implicit val schema: Schema[OutputMode] = Schema.derived
  }

  final case class CommitResult(hash: String, filesChanged: Int, insertions: Int, deletions: Int)
  object CommitResult {
    implicit val schema: Schema[CommitResult] = Schema.derived
  }

  final case class LogEntry(hash: String, author: String, date: Instant, message: String)
  object LogEntry {
    implicit val schema: Schema[LogEntry] = Schema.derived
  }

  enum CommitError {
    @error(kind = "runtime-error", exitCode = 1)
    case NothingStaged

    @error(kind = "runtime-error", exitCode = 128)
    case DirtyMerge

    @error(kind = "usage-error", exitCode = 129)
    case BadAuthorFormat(author: String)
  }

  enum LogError {
    @error(kind = "usage-error", exitCode = 128)
    case BadRevision

    @error(kind = "usage-error", exitCode = 129)
    case NotARepository
  }

  enum CanonicalRemoteError {
    @error(kind = "usage-error", exitCode = 128)
    case NoSuchRemote(name: String)
  }

  enum StashError {
    @error(kind = "usage-error", exitCode = 128)
    case NoSuchStash(name: String)
  }

  /** Stupid content tracker. */
  @toolDefinition(name = "canonical-git")
  trait CanonicalGit {

    /** Record changes to the repository. */
    @command(aliases = Array("ci"))
    @annotations(destructive = true)
    @arg("verbose", scope = "global", short = 'v', kind = "count-flag", max = 3)
    @arg("git-dir", scope = "global", env = "GIT_DIR", default = ".git")
    @arg("paginate", scope = "global", kind = "flag", negatable = true, default = true)
    @arg("config", scope = "global", short = 'c', repeatable = "repeated")
    @arg("message", scope = "option", short = 'm', required = true, aliases = Array("msg"))
    @arg("author", scope = "option", env = "GIT_AUTHOR_NAME", regex = "^.+ <.+@.+>$")
    @arg("amend", kind = "flag", negatable = true, default = false)
    @arg("signoff", kind = "flag", negatable = true, default = false)
    @arg("reset-author", kind = "flag", default = false)
    @arg("output", scope = "option", default = "human")
    @constraint(implies = Implies(lhs = "reset-author", rhs = "amend"))
    @constraint(requiresAll = Array(ValueIs("output", "json")))
    @result(formatters = Array("human", "porcelain", "json"), default = "human")
    def commit(
      verbose: Int,
      gitDir: GolemPath,
      paginate: Boolean,
      config: Map[String, String],
      message: String,
      author: Option[String],
      amend: Boolean,
      signoff: Boolean,
      resetAuthor: Boolean,
      output: OutputMode
    ): Either[CommitError, CommitResult]

    /** Manage set of tracked repositories. Pure dispatcher. */
    @command(aliases = Array("rmt"))
    @arg("verbose", scope = "global", short = 'v', kind = "count-flag", max = 3)
    @arg("git-dir", scope = "global", env = "GIT_DIR", default = ".git")
    @arg("paginate", scope = "global", kind = "flag", negatable = true, default = true)
    @arg("config", scope = "global", short = 'c', repeatable = "repeated")
    def remote(
      verbose: Int,
      gitDir: GolemPath,
      paginate: Boolean,
      config: Map[String, String]
    ): CanonicalRemote

    /** Stash the changes in a dirty working directory away. */
    @arg("verbose", scope = "global", short = 'v', kind = "count-flag", max = 3)
    @arg("git-dir", scope = "global", env = "GIT_DIR", default = ".git")
    def stash(verbose: Int, gitDir: GolemPath): Stash

    /** Show commit logs. */
    @annotations(readOnly = true, idempotent = true)
    @arg("max-count", scope = "option", short = 'n', min = 0, max = "9223372036854775807")
    @arg("since", scope = "option")
    @arg("until", scope = "option")
    @arg("author", scope = "option", repeatable = "delimited", delim = ',')
    @arg("grep", scope = "option", repeatable = "either", delim = ',')
    @arg("all-match", kind = "flag")
    @arg("invert-grep", kind = "flag")
    @arg("oneline", kind = "flag")
    @arg("graph", kind = "flag")
    @arg("paths", scope = "tail", separator = "--", min = 0)
    @constraint(allOrNone = Array("all-match", "grep"))
    @result(formatters = Array("oneline", "short", "medium", "full"), default = "medium")
    def log(
      maxCount: Option[Long],
      since: Option[Instant],
      until: Option[Instant],
      author: Seq[String],
      grep: Seq[String],
      allMatch: Boolean,
      invertGrep: Boolean,
      oneline: Boolean,
      graph: Boolean,
      paths: Seq[GolemPath]
    ): Either[LogError, Seq[LogEntry]]
  }

  @toolDefinition(name = "remote")
  trait CanonicalRemote {

    /** Add a remote. */
    @annotations(destructive = false, idempotent = false)
    @arg("name", scope = "positional", regex = "^[a-zA-Z][a-zA-Z0-9_-]*$")
    @arg("url", scope = "positional")
    @arg("track", scope = "option", short = 't', repeatable = "repeated")
    @arg("master", scope = "option", short = 'm')
    @arg("tags", kind = "flag", negatable = true, default = true)
    @arg("fetch", kind = "flag", short = 'f', default = false)
    @arg("verbose", kind = "count-flag", max = 3)
    def add(
      verbose: Int,
      name: String,
      url: Url,
      track: Seq[String],
      master: Option[String],
      tags: Boolean,
      fetch: Boolean
    ): Either[CanonicalRemoteError, Unit]

    /** Remove a remote. */
    @command(aliases = Array("rm"))
    @annotations(destructive = true, idempotent = true)
    @arg("name", scope = "positional", regex = "^[a-zA-Z][a-zA-Z0-9_-]*$")
    def remove(name: String): Either[CanonicalRemoteError, Unit]
  }

  @toolDefinition(name = "stash")
  trait Stash {

    /** Stash the changes in a dirty working directory away. */
    @arg("message", scope = "option", short = 'm', required = true)
    @arg("keep-index", kind = "flag", short = 'k', default = false)
    @arg("verbose", kind = "count-flag", max = 3)
    def stash(message: String, keepIndex: Boolean, verbose: Int): Either[StashError, Unit]

    /** Remove and apply a single stashed state. */
    @arg("name", scope = "positional", required = false)
    @arg("index", scope = "option", short = 'i')
    def pop(name: Option[String], index: Option[Int]): Either[StashError, Unit]

    /** Apply a single stashed state without removing it. */
    @arg("name", scope = "positional", required = false)
    @arg("index", scope = "option", short = 'i')
    def apply(name: Option[String], index: Option[Int]): Either[StashError, Unit]
  }

  @toolDefinition(name = "canonical-big-bound")
  trait CanonicalBigBound {
    @arg("count", scope = "option", min = 0, max = "18446744073709551615")
    def canonicalBigBound(count: Option[golem.ULong]): Either[CanonicalGrepError, Unit]
  }

  private lazy val grep              = ToolDefinitionMacro.metadata[Grep]
  private lazy val git               = ToolDefinitionMacro.metadata[Git]
  private lazy val leveler           = ToolDefinitionMacro.metadata[Leveler]
  private lazy val canonicalGrep     = ToolDefinitionMacro.metadata[CanonicalGrep]
  private lazy val canonicalGit      = ToolDefinitionMacro.metadata[CanonicalGit]
  private lazy val canonicalBigBound = ToolDefinitionMacro.metadata[CanonicalBigBound]

  private def child(tool: ExtendedToolType, parent: Int, name: String): ExtendedCommandNode =
    tool.commands(
      tool
        .commands(parent)
        .subcommands
        .find(idx => tool.commands(idx).name == name)
        .getOrElse(sys.error(s"missing $name"))
    )

  private def childIndex(tool: ExtendedToolType, parent: Int, name: String): Int =
    tool
      .commands(parent)
      .subcommands
      .find(idx => tool.commands(idx).name == name)
      .getOrElse(sys.error(s"missing $name"))

  private def collectedGraph(shape: ExtendedOptionShape): SchemaGraph =
    shape match {
      case ExtendedOptionShape.Scalar(g)         => g
      case ExtendedOptionShape.OptionalScalar(g) => g
      case ExtendedOptionShape.RepeatableList(r) =>
        SchemaGraph(r.itemType.defs, SchemaType(SchemaTypeBody.ListType(r.itemType.root)))
      case ExtendedOptionShape.RepeatableMap(r) => r.mapType
    }

  private def rootBody(graph: SchemaGraph): SchemaTypeBody =
    RefResolution.resolveRef(graph, graph.root).toOption.get.body

  override def spec: Spec[TestEnvironment, Any] =
    suite("ToolDefinitionMacroSpec")(
      suite("grep descriptor")(
        test("tool name, version and docs") {
          assertTrue(
            grep.toolName == "grep",
            grep.version == "1.2.3",
            grep.commands(0).doc.summary == "Search for a pattern.",
            grep.commands(0).doc.examples == List(Example("basic", "grep foo src/"))
          )
        },
        test("parameter classification") {
          val body = grep.commands(0).body.get
          assertTrue(
            body.positionals.fixed.map(_.name) == List("pattern"),
            body.positionals.fixed.head.required,
            body.positionals.fixed.head.doc.summary == "the regex pattern",
            body.positionals.tail.map(_.name) == Some("paths"),
            body.options.map(_.long) == List("max-count", "context"),
            body.flags.map(_.long) == List("case-sensitive")
          )
        },
        test("option shapes, shorts and defaults") {
          val body     = grep.commands(0).body.get
          val maxCount = body.options.find(_.long == "max-count").get
          val context  = body.options.find(_.long == "context").get
          assertTrue(
            maxCount.short == Some('m'),
            !maxCount.required,
            maxCount.shape.isInstanceOf[ExtendedOptionShape.Scalar],
            context.default == Some(SchemaValue.S32Value(2))
          )
        },
        test("command annotations") {
          val ann = grep.commands(0).body.get.annotations.get
          assertTrue(ann.readOnly, !ann.destructive, !ann.idempotent, ann.openWorld)
        },
        test("constraints in declaration order with resolved value-is literal") {
          val constraints = grep.commands(0).body.get.constraints
          assertTrue(
            constraints.head == ExtendedConstraint.RequiresAll(List(ExtendedRef.Present("pattern"))),
            constraints(1) == ExtendedConstraint.Implies(
              ExtendedImpliesC(
                Quantifier.All,
                List(ExtendedRef.Present("case-sensitive")),
                Quantifier.All,
                List(
                  ExtendedRef.ValueIs(
                    ExtendedValueIsRef(
                      "context",
                      ExtendedValueIsLiteral.Resolved(SchemaValue.S32Value(2))
                    )
                  )
                )
              )
            )
          )
        },
        test("result formatters and error cases") {
          val body   = grep.commands(0).body.get
          val result = body.result.get
          assertTrue(
            result.formatters.map(_.name) == List("human", "json"),
            result.defaultFormatter == "json",
            body.errors.map(_.name) == List("bad-pattern", "failed"),
            body.errors.head.kind == ErrorKind.UsageError,
            body.errors.head.exitCode == 2,
            body.errors.head.payload.isDefined,
            body.errors.head.doc.summary == "The pattern did not parse.",
            body.errors(1).kind == ErrorKind.RuntimeError,
            body.errors(1).payload.isEmpty
          )
        },
        test("canonical input ordering") {
          val fields = grep.canonicalInputFields(0).map(_.name)
          assertTrue(
            fields == List("pattern", "paths", "max-count", "context", "case-sensitive")
          )
        },
        test("wire encoding succeeds") {
          assertTrue(grep.tryToTool.isRight)
        }
      ),
      suite("git subtree")(
        test("grafted subtree structure") {
          val root   = git.commands(0)
          val remote = git.commands(root.subcommands.head)
          assertTrue(
            git.toolName == "git",
            root.body.isEmpty,
            remote.name == "remote",
            remote.aliases == List("rmt"),
            remote.doc.summary == "Manage the set of remotes.",
            remote.globals.options.map(_.long) == List("git-dir"),
            remote.subcommands.map(git.commands(_).name).sorted == List("add", "remove")
          )
        },
        test("subtree command paths resolve") {
          assertTrue(
            git.commandIndexByPath(List("remote", "add")).isDefined,
            git.commandIndexByPath(List("rmt", "remove")).isDefined,
            git.commandIndexByPath(List("remote")).isEmpty
          )
        },
        test("parent global appears in the subtree's canonical input") {
          val idx    = git.commandIndexByPath(List("remote", "add")).get
          val fields = git.canonicalInputFields(idx).map(_.name)
          assertTrue(fields == List("git-dir", "name", "url"))
        },
        test("wire encoding succeeds") {
          assertTrue(git.tryToTool.isRight)
        }
      ),
      suite("inherited globals")(
        test("compatible re-declaration is de-projected onto the root global") {
          val runIdx = leveler.commandIndexByPath(List("run")).get
          val run    = leveler.commands(runIdx)
          assertTrue(
            run.body.get.positionals.fixed.map(_.name) == List("input"),
            leveler.canonicalInputFields(runIdx).map(_.name) == List("level", "input")
          )
        }
      ),
      suite("@arg refinements")(
        test("text, numeric, u64 and path refinements are applied to the value graphs") {
          import golem.schema.{NumericBound, TextRestrictions}
          val refined               = ToolDefinitionMacro.metadata[Refined]
          val body                  = refined.commands(0).body.get
          def graphOf(name: String) =
            body.options.find(_.long == name).get.shape match {
              case ExtendedOptionShape.Scalar(g) => g.root.body
              case other                         => sys.error(s"unexpected shape $other")
            }
          assertTrue(
            graphOf("pattern") == SchemaTypeBody.TextType(
              TextRestrictions(regex = Some("^.+$"), minLength = Some(1), maxLength = Some(64))
            ),
            graphOf("level") match {
              case SchemaTypeBody.S32Type(Some(r)) =>
                r.min == Some(NumericBound.Signed(0)) && r.max == Some(NumericBound.Signed(100))
              case _ => false
            },
            graphOf("big") match {
              case SchemaTypeBody.U64Type(Some(r)) =>
                r.max == Some(NumericBound.Unsigned(-1L)) // raw bits of 2^64 - 1
              case _ => false
            },
            graphOf("target") match {
              case SchemaTypeBody.PathType(spec) =>
                spec.kind == golem.schema.PathKind.Directory &&
                spec.direction == golem.schema.PathDirection.Input
              case _ => false
            }
          )
        }
      ),
      suite("canonical parity examples")(
        test("grep descriptor covers globals, injected streams and errors") {
          val root = canonicalGrep.commands(0)
          val body = root.body.get
          assertTrue(
            canonicalGrep.toolName == "canonical-grep",
            canonicalGrep.version == "2.0.0",
            root.name == "canonical-grep",
            root.globals.options.map(_.long) == List("color"),
            root.globals.options.head.default == Some(SchemaValue.EnumValue(2)),
            root.globals.flags.map(_.long) == List("case-sensitive"),
            body.positionals.fixed.map(_.name) == List("pattern"),
            body.positionals.tail.map(_.name) == Some("files"),
            body.positionals.tail.exists(_.acceptsStdio),
            body.options.map(_.long) == List("extra-patterns", "max-count"),
            body.stdin.isDefined,
            body.stdout.isDefined,
            body.errors.map(_.name) == List("invalid-pattern", "no-match"),
            body.errors.head.kind == ErrorKind.UsageError,
            body.errors(1).kind == ErrorKind.RuntimeError,
            canonicalGrep.tryToTool.isRight
          )
        },
        test("grep subcommand de-projects inherited globals and preserves canonical order") {
          val replace = child(canonicalGrep, 0, "replace")
          val body    = replace.body.get
          assertTrue(
            body.flags.forall(_.long != "case-sensitive"),
            body.options.forall(_.long != "color"),
            body.positionals.fixed.map(_.name) == List("pattern", "replacement"),
            body.positionals.tail.map(_.name) == Some("files"),
            canonicalGrep.canonicalInputFields(0).map(_.name) ==
              List("color", "case-sensitive", "pattern", "files", "extra-patterns", "max-count"),
            canonicalGrep.canonicalInputFields(childIndex(canonicalGrep, 0, "replace")).map(_.name) ==
              List("color", "case-sensitive", "pattern", "replacement", "files")
          )
        },
        test("grep help renders at root, subcommand and argument depth") {
          val rootHelp    = ToolHelp.renderHelp(canonicalGrep, Nil).toOption.get
          val replaceHelp = ToolHelp.renderHelp(canonicalGrep, List("replace")).toOption.get
          val colorHelp   = ToolHelp.renderArgumentHelp(canonicalGrep, Nil, "color").toOption.get
          val patternHelp = ToolHelp.renderArgumentHelp(canonicalGrep, Nil, "pattern").toOption.get
          assertTrue(
            rootHelp.contains("Usage: canonical-grep"),
            rootHelp.contains("Globals:"),
            rootHelp.contains("--color"),
            rootHelp.contains("--case-sensitive"),
            rootHelp.contains("files..."),
            rootHelp.contains("Subcommands:"),
            rootHelp.contains("replace"),
            replaceHelp.contains("Usage: replace"),
            colorHelp.contains("--color (option, global)"),
            patternHelp.contains("pattern (positional")
          )
        },
        test("git top-level commands, annotations and formatter metadata match the canonical shape") {
          val root    = canonicalGit.commands(0)
          val commit  = child(canonicalGit, 0, "commit")
          val remote  = child(canonicalGit, 0, "remote")
          val log     = child(canonicalGit, 0, "log")
          val body    = commit.body.get
          val output  = body.options.find(_.long == "output").get
          val valueIs = body.constraints.collectFirst { case ExtendedConstraint.RequiresAll(refs) =>
            refs.collectFirst { case ExtendedRef.ValueIs(v) => v }
          }.flatten.get
          assertTrue(
            root.body.isEmpty,
            root.subcommands.map(canonicalGit.commands(_).name).toSet == Set("commit", "remote", "stash", "log"),
            commit.aliases == List("ci"),
            commit.body.flatMap(_.annotations).exists(_.destructive),
            remote.aliases == List("rmt"),
            remote.body.isEmpty,
            log.body.flatMap(_.annotations).exists(a => a.readOnly && a.idempotent),
            body.options
              .find(_.long == "message")
              .exists(o => o.short == Some('m') && o.required && o.aliases == List("msg")),
            rootBody(collectedGraph(output.shape)).isInstanceOf[SchemaTypeBody.EnumType],
            output.default == Some(SchemaValue.EnumValue(0)),
            valueIs.name == "output",
            valueIs.value == ExtendedValueIsLiteral.Resolved(SchemaValue.EnumValue(2)),
            body.result.exists(r =>
              r.formatters.map(_.name) == List("human", "porcelain", "json") && r.defaultFormatter == "human"
            ),
            body.errors.map(_.exitCode).toSet == Set(1, 128, 129)
          )
        },
        test("git subtree globals dedup through remote and stash implicit-body subtree") {
          val remoteIdx = childIndex(canonicalGit, 0, "remote")
          val addIdx    = childIndex(canonicalGit, remoteIdx, "add")
          val stashIdx  = childIndex(canonicalGit, 0, "stash")
          val popIdx    = childIndex(canonicalGit, stashIdx, "pop")
          val add       = canonicalGit.commands(addIdx)
          val stash     = canonicalGit.commands(stashIdx)
          assertTrue(
            canonicalGit.effectiveGlobals(addIdx).map {
              case EffectiveCommandField.OptionField(o) => o.long
              case EffectiveCommandField.FlagField(f)   => f.long
            } == List("git-dir", "config", "verbose", "paginate"),
            add.body.get.flags.forall(_.long != "verbose"),
            canonicalGit.canonicalInputFields(addIdx).map(_.name) ==
              List("git-dir", "config", "verbose", "paginate", "name", "url", "track", "master", "tags", "fetch"),
            stash.body.isDefined,
            stash.body.get.options.map(_.long) == List("message"),
            stash.body.get.flags.map(_.long) == List("keep-index"),
            canonicalGit.canonicalInputFields(stashIdx).map(_.name) ==
              List("git-dir", "verbose", "message", "keep-index"),
            canonicalGit.canonicalInputFields(popIdx).map(_.name) == List("git-dir", "verbose", "name", "index")
          )
        },
        test("git log covers bounds, datetime, repeatable modes, tail separator and constraints") {
          import golem.schema.NumericBound
          val log       = child(canonicalGit, 0, "log")
          val body      = log.body.get
          val maxCount  = body.options.find(_.long == "max-count").get
          val since     = body.options.find(_.long == "since").get
          val author    = body.options.find(_.long == "author").get
          val grep      = body.options.find(_.long == "grep").get
          val pathsTail = body.positionals.tail.get
          assertTrue(
            rootBody(collectedGraph(maxCount.shape)) match {
              case SchemaTypeBody.S64Type(Some(r)) => r.max == Some(NumericBound.Signed(Long.MaxValue))
              case _                               => false
            },
            rootBody(collectedGraph(since.shape)) == SchemaTypeBody.DatetimeType,
            author.shape match {
              case ExtendedOptionShape.RepeatableList(ExtendedRepeatableListShape(Repetition.Delimited(','), _)) => true
              case _                                                                                             => false
            },
            grep.shape match {
              case ExtendedOptionShape.RepeatableList(ExtendedRepeatableListShape(Repetition.Either(','), _)) => true
              case _                                                                                          => false
            },
            pathsTail.separator == Some("--"),
            pathsTail.min == 0,
            body.constraints.exists(_.isInstanceOf[ExtendedConstraint.AllOrNone]),
            body.result.exists(_.defaultFormatter == "medium"),
            canonicalGit.tryToTool.isRight
          )
        },
        test("u64 maximum option bound is preserved and wire-encodable") {
          import golem.schema.NumericBound
          val body  = canonicalBigBound.commands(0).body.get
          val count = body.options.find(_.long == "count").get
          assertTrue(
            rootBody(collectedGraph(count.shape)) match {
              case SchemaTypeBody.U64Type(Some(r)) =>
                r.min == Some(NumericBound.Unsigned(0L)) && r.max == Some(NumericBound.Unsigned(-1L))
              case _ => false
            },
            canonicalBigBound.tryToTool.isRight
          )
        }
      ),
      suite("failures")(
        test("subtree cycle is reported") {
          val result = ToolDefinitionMacro.tryMetadata[CycleA]
          assertTrue(result.swap.exists(_.isInstanceOf[ToolBuildError.SubtreeCycle]))
        },
        test("subtree root name mismatch is reported") {
          val result = ToolDefinitionMacro.tryMetadata[Mismatched]
          assertTrue(
            result == Left(ToolBuildError.SubtreeRootNameMismatch("sub", "remote"))
          )
        }
      )
    )
}
