/*
 * Copyright 2024-2026 Golem Cloud
 *
 * Licensed under the Golem Source License v1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://license.golem.cloud/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package golem.runtime.macros

import golem.schema.SchemaValue
import golem.tool.*
import golem.runtime.annotations.*
import zio.test.*

/**
 * Verifies the tool descriptor generated by `ToolDefinitionMacro` from
 * `@toolDefinition` traits: parameter classification, docs, defaults,
 * constraints, result/error metadata, subtree grafting, inherited-global
 * de-projection, and cycle detection.
 */
object ToolDefinitionMacroSpec extends ZIOSpecDefault {

  // --- grep: an implicit-body tool exercising every parameter surface -------

  enum GrepError {

    /** The pattern did not parse. */
    @error(kind = "usage", exitCode = 2)
    case BadPattern(pattern: String)

    @error(kind = "runtime-error", exitCode = 1)
    case Failed
  }

  /**
   * Searches files for a pattern.
   *
   * The long grep description.
   */
  @toolDefinition(version = "1.2.3")
  trait Grep {

    /** Search for a pattern. */
    @annotations(readOnly = true, destructive = false)
    @arg("pattern", doc = "the regex pattern")
    @arg("case-sensitive", kind = "flag")
    @arg("max-count", scope = "option", short = 'm')
    @arg("context", scope = "option", default = 2)
    @constraint(requiresAll = Array("pattern"))
    @constraint(implies = Implies(lhs = "case-sensitive", rhs = Array(ValueIs("context", 2))))
    @result(formatters = Array("human", "json"), default = "json")
    @example(body = "grep foo src/", title = "basic")
    def grep(
      pattern: String,
      caseSensitive: Boolean,
      maxCount: Option[Int],
      context: Int,
      paths: Seq[String]
    ): Either[GrepError, String]
  }

  // --- git: a subtree tool with propagating parent globals ------------------

  @toolDefinition(version = "0.1.0")
  trait Remote {

    /** Adds a remote. */
    def add(name: String, url: String): String

    def remove(name: String): Unit
  }

  @toolDefinition(version = "0.2.0")
  trait Git {

    /** Manage the set of remotes. */
    @command(aliases = Array("rmt"))
    def remote(gitDir: String): Remote
  }

  // --- inherited-global de-projection within one trait ----------------------

  @toolDefinition(version = "0.0.1")
  trait Leveler {
    @arg("level", scope = "global", short = 'l')
    def leveler(level: Option[Int]): Unit

    def run(level: Option[Int], input: String): Unit
  }

  // --- subtree cycle ---------------------------------------------------------

  @toolDefinition(name = "a", version = "0.0.1")
  trait CycleA {
    def b(): CycleB
  }

  @toolDefinition(name = "b", version = "0.0.1")
  trait CycleB {
    def a(): CycleA
  }

  // --- @arg refinements -------------------------------------------------------

  @toolDefinition(version = "0.0.1")
  trait Refined {
    @arg("pattern", scope = "option", regex = "^.+$", minLength = 1, maxLength = 64)
    @arg("level", scope = "option", bounds = (0, 100))
    @arg("big", scope = "option", max = "18446744073709551615")
    @arg("target", scope = "option", kind = "dir", direction = "input")
    def refined(
      pattern: Option[String],
      level: Option[Int],
      big: Option[golem.ULong],
      target: Option[golem.schema.GolemPath]
    ): Unit
  }

  // --- subtree root name mismatch --------------------------------------------

  @toolDefinition(version = "0.0.1")
  trait Mismatched {
    def sub(): Remote
  }

  private lazy val grep    = ToolDefinitionMacro.metadata[Grep]
  private lazy val git     = ToolDefinitionMacro.metadata[Git]
  private lazy val leveler = ToolDefinitionMacro.metadata[Leveler]

  override def spec: Spec[TestEnvironment, Any] =
    suite("ToolDefinitionMacroSpec")(
      suite("grep descriptor")(
        test("tool name, version and docs") {
          assertTrue(
            grep.toolName == "grep",
            grep.version == "1.2.3",
            grep.commands(0).doc.summary == "Search for a pattern.",
            grep.commands(0).doc.examples == List(Example("basic", "grep foo src/"))
          )
        },
        test("parameter classification") {
          val body = grep.commands(0).body.get
          assertTrue(
            body.positionals.fixed.map(_.name) == List("pattern"),
            body.positionals.fixed.head.required,
            body.positionals.fixed.head.doc.summary == "the regex pattern",
            body.positionals.tail.map(_.name) == Some("paths"),
            body.options.map(_.long) == List("max-count", "context"),
            body.flags.map(_.long) == List("case-sensitive")
          )
        },
        test("option shapes, shorts and defaults") {
          val body     = grep.commands(0).body.get
          val maxCount = body.options.find(_.long == "max-count").get
          val context  = body.options.find(_.long == "context").get
          assertTrue(
            maxCount.short == Some('m'),
            !maxCount.required,
            maxCount.shape.isInstanceOf[ExtendedOptionShape.Scalar],
            context.default == Some(SchemaValue.S32Value(2))
          )
        },
        test("command annotations") {
          val ann = grep.commands(0).body.get.annotations.get
          assertTrue(ann.readOnly, !ann.destructive, !ann.idempotent, ann.openWorld)
        },
        test("constraints in declaration order with resolved value-is literal") {
          val constraints = grep.commands(0).body.get.constraints
          assertTrue(
            constraints.head == ExtendedConstraint.RequiresAll(List(ExtendedRef.Present("pattern"))),
            constraints(1) == ExtendedConstraint.Implies(
              ExtendedImpliesC(
                Quantifier.All,
                List(ExtendedRef.Present("case-sensitive")),
                Quantifier.All,
                List(
                  ExtendedRef.ValueIs(
                    ExtendedValueIsRef(
                      "context",
                      ExtendedValueIsLiteral.Resolved(SchemaValue.S32Value(2))
                    )
                  )
                )
              )
            )
          )
        },
        test("result formatters and error cases") {
          val body   = grep.commands(0).body.get
          val result = body.result.get
          assertTrue(
            result.formatters.map(_.name) == List("human", "json"),
            result.defaultFormatter == "json",
            body.errors.map(_.name) == List("bad-pattern", "failed"),
            body.errors.head.kind == ErrorKind.UsageError,
            body.errors.head.exitCode == 2,
            body.errors.head.payload.isDefined,
            body.errors.head.doc.summary == "The pattern did not parse.",
            body.errors(1).kind == ErrorKind.RuntimeError,
            body.errors(1).payload.isEmpty
          )
        },
        test("canonical input ordering") {
          val fields = grep.canonicalInputFields(0).map(_.name)
          assertTrue(
            fields == List("pattern", "paths", "max-count", "context", "case-sensitive")
          )
        },
        test("wire encoding succeeds") {
          assertTrue(grep.tryToTool.isRight)
        }
      ),
      suite("git subtree")(
        test("grafted subtree structure") {
          val root   = git.commands(0)
          val remote = git.commands(root.subcommands.head)
          assertTrue(
            git.toolName == "git",
            root.body.isEmpty,
            remote.name == "remote",
            remote.aliases == List("rmt"),
            remote.doc.summary == "Manage the set of remotes.",
            remote.globals.options.map(_.long) == List("git-dir"),
            remote.subcommands.map(git.commands(_).name).sorted == List("add", "remove")
          )
        },
        test("subtree command paths resolve") {
          assertTrue(
            git.commandIndexByPath(List("remote", "add")).isDefined,
            git.commandIndexByPath(List("rmt", "remove")).isDefined,
            git.commandIndexByPath(List("remote")).isEmpty
          )
        },
        test("parent global appears in the subtree's canonical input") {
          val idx    = git.commandIndexByPath(List("remote", "add")).get
          val fields = git.canonicalInputFields(idx).map(_.name)
          assertTrue(fields == List("git-dir", "name", "url"))
        },
        test("wire encoding succeeds") {
          assertTrue(git.tryToTool.isRight)
        }
      ),
      suite("inherited globals")(
        test("compatible re-declaration is de-projected onto the root global") {
          val runIdx = leveler.commandIndexByPath(List("run")).get
          val run    = leveler.commands(runIdx)
          assertTrue(
            run.body.get.positionals.fixed.map(_.name) == List("input"),
            leveler.canonicalInputFields(runIdx).map(_.name) == List("level", "input")
          )
        }
      ),
      suite("@arg refinements")(
        test("text, numeric, u64 and path refinements are applied to the value graphs") {
          import golem.schema.{NumericBound, SchemaTypeBody, TextRestrictions}
          val refined               = ToolDefinitionMacro.metadata[Refined]
          val body                  = refined.commands(0).body.get
          def graphOf(name: String) =
            body.options.find(_.long == name).get.shape match {
              case ExtendedOptionShape.Scalar(g) => g.root.body
              case other                         => sys.error(s"unexpected shape $other")
            }
          assertTrue(
            graphOf("pattern") == SchemaTypeBody.TextType(
              TextRestrictions(regex = Some("^.+$"), minLength = Some(1), maxLength = Some(64))
            ),
            graphOf("level") match {
              case SchemaTypeBody.S32Type(Some(r)) =>
                r.min == Some(NumericBound.Signed(0)) && r.max == Some(NumericBound.Signed(100))
              case _ => false
            },
            graphOf("big") match {
              case SchemaTypeBody.U64Type(Some(r)) =>
                r.max == Some(NumericBound.Unsigned(-1L)) // raw bits of 2^64 - 1
              case _ => false
            },
            graphOf("target") match {
              case SchemaTypeBody.PathType(spec) =>
                spec.kind == golem.schema.PathKind.Directory &&
                spec.direction == golem.schema.PathDirection.Input
              case _ => false
            }
          )
        }
      ),
      suite("failures")(
        test("subtree cycle is reported") {
          val result = ToolDefinitionMacro.tryMetadata[CycleA]
          assertTrue(result.swap.exists(_.isInstanceOf[ToolBuildError.SubtreeCycle]))
        },
        test("subtree root name mismatch is reported") {
          val result = ToolDefinitionMacro.tryMetadata[Mismatched]
          assertTrue(
            result == Left(ToolBuildError.SubtreeRootNameMismatch("sub", "remote"))
          )
        }
      )
    )
}
