[package]
name = "conformance_caller"
version = "0.0.1"
edition = "2024"

[profile.dev]
debug = 0

[profile.release]
opt-level = "s"
lto = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
golem-rust = { path = "__GOLEM_RUST_PATH__", features = ["export_golem_agentic"] }
manifest-probe-tool-guest-client = { path = "../golem-temp/bridge-sdk/rust/internal/manifest-probe-tool-guest-client" }
compat-leaf-tool-guest-client = { path = "../golem-temp/bridge-sdk/rust/internal/compat-leaf-tool-guest-client" }

[workspace]
