// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://license.golem.cloud/LICENSE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// End-to-end proof that recursive and mutually-recursive types work through the
// *live* agent boundary (the Slice-3 headline deliverable). Unlike
// `schema-mapping/recursion.test.ts` — which drives the mapper with hand-built
// `buildTypeFromJSON` fixtures — this test goes through the real path: reflected
// metadata generated by `golem-typegen` for `RecursiveAgent` -> `@agent`
// registration -> the per-agent `SchemaGraph` with `ref` defs -> dynamic
// `ResolvedAgent.invoke`. It asserts (1) the agent type is published, (2) each
// method's resolved schema graph contains a self-referential def (one def per
// recursive type, no infinite expansion), and (3) finite values round-trip.

import { expect, test } from 'vitest';
import { AgentClassName } from '../src';
import { AgentInitiatorRegistry } from '../src/internal/registry/agentInitiatorRegistry';
import { AgentTypeRegistry } from '../src/internal/registry/agentTypeRegistry';
import { AgentConstructorParamRegistry } from '../src/internal/registry/agentConstructorParamRegistry';
import { AgentMethodParamRegistry } from '../src/internal/registry/agentMethodParamRegistry';
import { AgentMethodRegistry } from '../src/internal/registry/agentMethodRegistry';
import { ResolvedAgent } from '../src/internal/resolvedAgent';
import { RuntimeParam } from '../src/internal/typeInfoInternal';
import { SchemaValue } from '../src/internal/schema-model';
import { SchemaValueTree } from 'golem:core/types@2.0.0';
import {
  decodeOutputFromWit,
  encodeInputRecord,
  encodeInputRecordToWit,
} from '../src/internal/mapping/values/boundaryValue';
import { ResolvedGraph, ResolvedType, TypeId } from '../src/internal/mapping/types/resolvedType';
import type { RecTree, MutualA } from './validAgents';
import type { ImportedRecTree } from './importedTestTypes';

const RECURSIVE_AGENT = 'RecursiveAgent';

// --- helpers ---------------------------------------------------------------

function initiateRecursiveAgent(name: string): ResolvedAgent {
  (globalThis as any).currentAgentId = `${RECURSIVE_AGENT}()`;
  const input = buildConstructorInput(RECURSIVE_AGENT, new Map([['name', name]]));
  const initiator = AgentInitiatorRegistry.lookup(RECURSIVE_AGENT);
  if (!initiator) {
    throw new Error(`${RECURSIVE_AGENT} not found in AgentInitiatorRegistry`);
  }
  const result = initiator.initiate(input, { tag: 'anonymous' });
  if (result.tag !== 'ok') {
    throw new Error(`Agent initiation failed: ${JSON.stringify(result.val)}`);
  }
  return result.val;
}

function buildConstructorInput(
  agentClassName: string,
  valuesByName: Map<string, any>,
): SchemaValue {
  const classMeta = AgentConstructorParamRegistry.get(agentClassName);
  if (!classMeta) {
    throw new Error(`Constructor metadata for ${agentClassName} not found`);
  }
  const userParams: RuntimeParam[] = [];
  const args: any[] = [];
  for (const [name, meta] of classMeta) {
    const type = meta.typeInfo;
    if (!type) {
      throw new Error(`Unresolved type for constructor parameter ${name} in ${agentClassName}`);
    }
    if (type.tag === 'principal' || type.tag === 'config') continue;
    userParams.push({ name, type });
    args.push(valuesByName.has(name) ? valuesByName.get(name) : undefined);
  }
  return encodeInputRecord(args, userParams);
}

function buildMethodInput(methodName: string, nameValues: [string, any][]): SchemaValueTree {
  const valueByName = new Map(nameValues);
  const paramTypes = AgentMethodParamRegistry.getParametersAndType(RECURSIVE_AGENT, methodName);
  const userParams: RuntimeParam[] = [];
  const args: any[] = [];
  for (const [name, type] of paramTypes) {
    userParams.push({ name, type });
    args.push(valueByName.has(name) ? valueByName.get(name) : undefined);
  }
  return encodeInputRecordToWit(args, userParams);
}

function decodeReturn(methodName: string, value: SchemaValueTree | undefined): any {
  const returnType = AgentMethodRegistry.getReturnType(RECURSIVE_AGENT, methodName);
  if (!returnType) {
    throw new Error(`Unsupported return type for method ${methodName}`);
  }
  return decodeOutputFromWit(value, returnType);
}

/** Single method-parameter resolved graph (every recursive method here takes one param). */
function methodParamGraph(methodName: string): ResolvedGraph {
  const params = AgentMethodParamRegistry.getParametersAndType(RECURSIVE_AGENT, methodName);
  const types = Array.from(params.values());
  expect(types).toHaveLength(1);
  const t = types[0];
  if (t.tag !== 'schema') {
    throw new Error(`Expected a schema parameter for ${methodName}, got '${t.tag}'`);
  }
  return t.graph;
}

/** Collect the def ids directly referenced (structurally) from a resolved type. */
function collectRefs(rt: ResolvedType, acc: Set<TypeId>): void {
  const b = rt.body;
  switch (b.tag) {
    case 'ref':
      acc.add(b.id);
      break;
    case 'list':
    case 'option':
      collectRefs(b.element, acc);
      break;
    case 'map':
      collectRefs(b.key, acc);
      collectRefs(b.value, acc);
      break;
    case 'tuple':
      b.elements.forEach((e) => collectRefs(e, acc));
      break;
    case 'record':
      b.fields.forEach((f) => collectRefs(f.type, acc));
      break;
    case 'variant':
      b.cases.forEach((c) => c.payload && collectRefs(c.payload, acc));
      break;
    case 'result':
      if (b.ok) collectRefs(b.ok, acc);
      if (b.err) collectRefs(b.err, acc);
      break;
    default:
      break;
  }
}

/** True if the def-reference graph contains a cycle (i.e. the type is recursive). */
function graphIsRecursive(graph: ResolvedGraph): boolean {
  const edges = new Map<TypeId, Set<TypeId>>();
  for (const [id, def] of graph.defs) {
    const refs = new Set<TypeId>();
    collectRefs(def, refs);
    edges.set(id, refs);
  }
  const visiting = new Set<TypeId>();
  const done = new Set<TypeId>();
  const dfs = (id: TypeId): boolean => {
    if (visiting.has(id)) return true; // back-edge -> cycle
    if (done.has(id)) return false;
    visiting.add(id);
    for (const next of edges.get(id) ?? []) {
      if (edges.has(next) && dfs(next)) return true;
    }
    visiting.delete(id);
    done.add(id);
    return false;
  };
  for (const id of edges.keys()) {
    if (dfs(id)) return true;
  }
  return false;
}

// --- tests -----------------------------------------------------------------

test('RecursiveAgent is published with a recursive schema graph (direct recursion)', () => {
  const agentType = AgentTypeRegistry.get(new AgentClassName(RECURSIVE_AGENT));
  expect(agentType).toBeDefined();
  // The published per-agent schema graph and constructor are present.
  expect(agentType!.schema).toBeDefined();
  expect(agentType!.constructor.inputSchema.tag).toEqual('parameters');

  const graph = methodParamGraph('echoTree');
  // Exactly one def for the single recursive type — no infinite expansion.
  expect(graph.defs.size).toEqual(1);
  expect(graphIsRecursive(graph)).toBe(true);
});

test('echoTree round-trips a finite recursive tree through the live boundary', async () => {
  const agent = initiateRecursiveAgent('rec');

  const cases: RecTree[] = [
    { value: 7, children: [] }, // base case
    {
      value: 1,
      children: [
        { value: 2, children: [] },
        { value: 3, children: [{ value: 4, children: [] }] },
      ],
    },
  ];

  for (const tree of cases) {
    const input = buildMethodInput('echoTree', [['tree', tree]]);
    const result = await agent.invoke('echoTree', input, { tag: 'anonymous' });
    expect(result.tag).toEqual('ok');
    if (result.tag !== 'ok') return;
    expect(decodeReturn('echoTree', result.val)).toEqual(tree);
  }
});

test('echoMutual publishes a mutually-recursive schema graph and round-trips a finite value', async () => {
  // Two defs (MutualA, MutualB) forming a cycle — proves mutual recursion.
  const graph = methodParamGraph('echoMutual');
  expect(graph.defs.size).toEqual(2);
  expect(graphIsRecursive(graph)).toBe(true);

  const agent = initiateRecursiveAgent('rec');

  const cases: MutualA[] = [
    { label: 'leaf', bs: [] }, // base case
    {
      label: 'a',
      bs: [
        { count: 1, as: [] },
        { count: 2, as: [{ label: 'a2', bs: [] }] },
      ],
    },
  ];

  for (const a of cases) {
    const input = buildMethodInput('echoMutual', [['a', a]]);
    const result = await agent.invoke('echoMutual', input, { tag: 'anonymous' });
    expect(result.tag).toEqual('ok');
    if (result.tag !== 'ok') return;
    expect(decodeReturn('echoMutual', result.val)).toEqual(a);
  }
});

// A recursive type whose definition lives in a *different module* than the agent
// that references it (`ImportedRecTree` from `./importedTestTypes`). The recursive
// back-edge must resolve to the same type id as the imported root definition —
// regression guard for cross-module recursive type resolution.
test('echoImportedTree resolves a recursive type imported from another module', async () => {
  const graph = methodParamGraph('echoImportedTree');
  expect(graph.defs.size).toEqual(1);
  expect(graphIsRecursive(graph)).toBe(true);

  const agent = initiateRecursiveAgent('rec');

  const cases: ImportedRecTree[] = [
    { value: 7, children: [] }, // base case
    {
      value: 1,
      children: [
        { value: 2, children: [] },
        { value: 3, children: [{ value: 4, children: [] }] },
      ],
    },
  ];

  for (const tree of cases) {
    const input = buildMethodInput('echoImportedTree', [['tree', tree]]);
    const result = await agent.invoke('echoImportedTree', input, { tag: 'anonymous' });
    expect(result.tag).toEqual('ok');
    if (result.tag !== 'ok') return;
    expect(decodeReturn('echoImportedTree', result.val)).toEqual(tree);
  }
});
