// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://license.golem.cloud/LICENSE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Post-process Go bindings generated by `wit-bindgen`'s `crates/go` backend, working
//! around codegen bugs that produce Go which does not compile.
//!
//! Two independent fixups are applied; both are upstream bugs and both should be deleted
//! from here once fixed upstream (see `tmp/plan` → "Upstream candidates").
//!
//! # 1. Variant tag constants colliding with record types
//!
//! **The bug** (wit-bindgen 0.58.0): a variant's case tag constants are named
//! `<Variant><Case>`, which collides with the record type generated for a WIT record
//! named `<variant>-<case>`. Golem's WIT uses exactly that convention:
//!
//! ```wit
//! record  queued-card-event-install { card-id: card-id }
//! variant queued-card-event { install(queued-card-event-install), ... }
//! ```
//!
//! which generates both `type QueuedCardEventInstall struct` and
//! `const QueuedCardEventInstall uint8 = 0`, so Go rejects the package with
//! "X redeclared in this block" and "X (type) is not an expression".
//!
//! `golem:api/oplog` (where this occurs) is pulled in transitively via
//! `golem:durability`, so it cannot be avoided by trimming the world.
//!
//! **The fix**: rename the colliding *constant* to `<Name>Tag` and update the four call
//! shapes the generator emits. The record type keeps its name, so nothing user-facing
//! changes.
//!
//! Collision detection is generic — declared struct type names are intersected with
//! declared tag constants; no names are hardcoded.
//!
//! # 2. Missing `empty.s` in the exports package
//!
//! Go only allows a function declaration **without a body** if the package contains at
//! least one `.s` file (the compiler assumes assembly supplies it). `//go:wasmimport`
//! declarations are bodyless by nature, so the generator drops a small `empty.s` stub
//! into each package — its own comment says it exists "for testing this package without
//! WebAssembly".
//!
//! It emits that stub for *import* packages but **not** for the exports package, which
//! nevertheless contains one bodyless `[task-return]` `//go:wasmimport` per async export.
//! Without it, that package (and therefore anything importing the SDK) cannot be compiled
//! for the host at all — which would rule out native `go test`.
//!
//! **The fix**: write the same stub into any package that has a `//go:wasmimport` but no
//! `.s` file. Calling a host import on the host is still a *link* error naming the missing
//! symbol, so the host/guest boundary stays enforced by the toolchain.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub const USAGE: &str = "Usage: go-bindgen-fixup <dir> [<dir> ...]\n\
     \n\
     Applies workarounds for wit-bindgen crates/go codegen bugs, recursively, in each\n\
     <dir>:\n\
     \n\
     1. renames variant tag constants that collide with a struct type of the same\n\
     name to <Name>Tag;\n\
     2. adds the missing empty.s stub to any package that has a bodyless\n\
     //go:wasmimport but no assembly file (without it the package cannot be\n\
     compiled for the host, which would rule out native `go test`).";

/// Integer types wit-bindgen uses for variant discriminants.
const TAG_TYPES: [&str; 3] = ["uint8", "uint16", "uint32"];

/// Names of struct types declared in `src` (`type Foo struct {`).
fn struct_types(src: &str) -> Vec<&str> {
    src.lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("type ")?;
            let (name, tail) = rest.split_once(' ')?;
            tail.starts_with("struct {").then_some(name)
        })
        .collect()
}

/// Names of tag constants declared in `src` (`\tFoo uint8 = 0`, possibly gofmt-aligned
/// with extra spaces).
fn tag_constants(src: &str) -> Vec<&str> {
    src.lines()
        .filter_map(parse_tag_const)
        .map(|(n, _, _)| n)
        .collect()
}

/// Parse `\tName<ws>uintN = <digits>` into (name, int type, value).
fn parse_tag_const(line: &str) -> Option<(&str, &str, &str)> {
    if !line.starts_with('\t') {
        return None;
    }
    // `split_whitespace` already skips leading/trailing whitespace.
    let mut parts = line.split_whitespace();
    let name = parts.next()?;
    let int_ty = parts.next()?;
    if !TAG_TYPES.contains(&int_ty) || parts.next()? != "=" {
        return None;
    }
    let value = parts.next()?;
    if parts.next().is_some() || value.is_empty() || !value.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    Some((name, int_ty, value))
}

/// Rewrite `src`, renaming every tag constant whose name collides with a struct type.
/// Returns the new source and the names that were renamed (sorted, deduplicated).
pub fn fix_source(src: &str) -> (String, Vec<String>) {
    let types = struct_types(src);
    let mut collisions: Vec<String> = tag_constants(src)
        .into_iter()
        .filter(|c| types.contains(c))
        .map(str::to_string)
        .collect();
    collisions.sort();
    collisions.dedup();

    if collisions.is_empty() {
        return (src.to_string(), collisions);
    }

    let mut out = src.to_string();
    for name in &collisions {
        let tag = format!("{name}Tag");

        // 1. the declaration inside the const block
        out = out
            .lines()
            .map(|line| match parse_tag_const(line) {
                Some((n, int_ty, value)) if n == name => format!("\t{tag} {int_ty} = {value}"),
                _ => line.to_string(),
            })
            .collect::<Vec<_>>()
            .join("\n");
        if src.ends_with('\n') && !out.ends_with('\n') {
            out.push('\n');
        }

        // 2..4: usages where the constant (not the type) is meant. Each pattern carries
        // its own delimiter, so a longer identifier sharing this prefix cannot match.
        out = out.replace(&format!(".tag != {name} {{"), &format!(".tag != {tag} {{"));
        out = out.replace(&format!("{{{name}, "), &format!("{{{tag}, "));
        out = out.replace(&format!("case {name}:"), &format!("case {tag}:"));
    }
    (out, collisions)
}

/// Byte-identical to the stub the generator writes into import packages (no trailing
/// newline), so a fixed-up tree is indistinguishable from a correctly generated one.
const EMPTY_S: &str = "// This file exists for testing this package without WebAssembly,\n\
     // allowing empty function bodies with a //go:wasmimport directive.\n\
     // See https://pkg.go.dev/cmd/compile for more information.";

const EMPTY_S_NAME: &str = "empty.s";

/// Does this package directory declare a `//go:wasmimport` (i.e. contain bodyless
/// function declarations)? `//go:wasmexport` functions have bodies and do not count.
fn needs_assembly_stub(dir: &Path) -> io::Result<bool> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|e| e == "go")
            && fs::read_to_string(&path)?.contains("//go:wasmimport")
        {
            return Ok(true);
        }
    }
    Ok(false)
}

fn has_assembly_file(dir: &Path) -> io::Result<bool> {
    for entry in fs::read_dir(dir)? {
        if entry?.path().extension().is_some_and(|e| e == "s") {
            return Ok(true);
        }
    }
    Ok(false)
}

/// Write the `empty.s` stub into every package under `root` that needs one and lacks it.
/// Returns the paths written.
pub fn add_missing_assembly_stubs(root: &Path) -> io::Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    let mut dirs = vec![root.to_path_buf()];
    while let Some(dir) = dirs.pop() {
        for entry in fs::read_dir(&dir)? {
            let path = entry?.path();
            if path.is_dir() {
                dirs.push(path);
            }
        }
        if needs_assembly_stub(&dir)? && !has_assembly_file(&dir)? {
            let path = dir.join(EMPTY_S_NAME);
            fs::write(&path, EMPTY_S)?;
            written.push(path);
        }
    }
    written.sort();
    Ok(written)
}

/// Recursively collect `*.go` files under `dir`.
fn go_files(dir: &Path, out: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            go_files(&path, out)?;
        } else if path.extension().is_some_and(|e| e == "go") {
            out.push(path);
        }
    }
    out.sort();
    Ok(())
}

pub fn run(args: &[String]) -> io::Result<()> {
    if args.is_empty() || args.iter().any(|a| a == "-h" || a == "--help") {
        println!("{USAGE}");
        return Ok(());
    }

    let mut total = 0usize;
    let mut stubs = 0usize;
    for dir in args {
        for path in add_missing_assembly_stubs(Path::new(dir))? {
            stubs += 1;
            println!(
                "  {}: added {EMPTY_S_NAME} (bodyless //go:wasmimport)",
                path.display()
            );
        }

        let mut files = Vec::new();
        go_files(Path::new(dir), &mut files)?;
        for path in files {
            let src = fs::read_to_string(&path)?;
            let (fixed, renamed) = fix_source(&src);
            if renamed.is_empty() {
                continue;
            }
            fs::write(&path, fixed)?;
            total += renamed.len();
            println!(
                "  {}: renamed {} colliding tag const(s) -> *Tag ({})",
                path.display(),
                renamed.len(),
                renamed.join(", ")
            );
        }
    }
    println!("go-bindgen-fixup: {total} constant(s) renamed, {stubs} assembly stub(s) added");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    /// Minimal std-only temp directory, removed on drop (so dev-tools stays dependency-free).
    struct TmpDir(PathBuf);

    impl TmpDir {
        fn new() -> Self {
            static COUNTER: AtomicU64 = AtomicU64::new(0);
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let n = COUNTER.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "go-bindgen-fixup-test-{}-{nanos}-{n}",
                std::process::id()
            ));
            fs::create_dir_all(&path).unwrap();
            TmpDir(path)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TmpDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn write_go(dir: &Path, name: &str, contents: &str) {
        fs::create_dir_all(dir).unwrap();
        fs::write(dir.join(name), contents).unwrap();
    }

    /// The real shape emitted for golem's `queued-card-event`, including the gofmt
    /// alignment padding that makes the second constant easy to miss.
    const SAMPLE: &str = "type QueuedCardEventInstall struct {\n\
         \tCardId golem_core_types.CardId\n\
         }\n\
         \n\
         type QueuedCardEventRevoke struct {\n\
         \tCardId golem_core_types.CardId\n\
         }\n\
         \n\
         const (\n\
         \tQueuedCardEventInstall uint8 = 0\n\
         \tQueuedCardEventRevoke  uint8 = 1\n\
         )\n\
         \n\
         func (self QueuedCardEvent) Install() QueuedCardEventInstall {\n\
         \tif self.tag != QueuedCardEventInstall {\n\
         \t\tpanic(\"tag mismatch\")\n\
         \t}\n\
         \treturn self.value.(QueuedCardEventInstall)\n\
         }\n\
         \n\
         func MakeQueuedCardEventInstall(value QueuedCardEventInstall) QueuedCardEvent {\n\
         \treturn QueuedCardEvent{QueuedCardEventInstall, value}\n\
         }\n\
         \n\
         \t\t\tcase QueuedCardEventInstall:\n";

    #[test]
    fn detects_both_collisions_including_gofmt_aligned_one() {
        let (_, renamed) = fix_source(SAMPLE);
        assert_eq!(
            renamed,
            vec!["QueuedCardEventInstall", "QueuedCardEventRevoke"]
        );
    }

    #[test]
    fn renames_the_constant_declarations_only() {
        let (out, _) = fix_source(SAMPLE);
        assert!(out.contains("\tQueuedCardEventInstallTag uint8 = 0"));
        assert!(out.contains("\tQueuedCardEventRevokeTag uint8 = 1"));
        // the record types keep their names
        assert!(out.contains("type QueuedCardEventInstall struct {"));
        assert!(out.contains("type QueuedCardEventRevoke struct {"));
    }

    #[test]
    fn rewrites_constant_usages_but_not_type_usages() {
        let (out, _) = fix_source(SAMPLE);
        // constant positions
        assert!(out.contains("if self.tag != QueuedCardEventInstallTag {"));
        assert!(out.contains("QueuedCardEvent{QueuedCardEventInstallTag, value}"));
        assert!(out.contains("case QueuedCardEventInstallTag:"));
        // type positions must be untouched
        assert!(out.contains("Install() QueuedCardEventInstall {"));
        assert!(out.contains("self.value.(QueuedCardEventInstall)"));
        assert!(out.contains("func MakeQueuedCardEventInstall(value QueuedCardEventInstall)"));
    }

    #[test]
    fn is_idempotent() {
        let (once, _) = fix_source(SAMPLE);
        let (twice, renamed) = fix_source(&once);
        assert_eq!(once, twice);
        assert!(renamed.is_empty(), "second pass must find nothing to do");
    }

    #[test]
    fn leaves_non_colliding_files_untouched() {
        let src = "type Foo struct {\n\tA string\n}\n\nconst (\n\tBarInstall uint8 = 0\n)\n";
        let (out, renamed) = fix_source(src);
        assert_eq!(out, src);
        assert!(renamed.is_empty());
    }

    #[test]
    fn does_not_treat_arbitrary_constants_as_tags() {
        // not a tag constant: wrong int type / not a plain integer literal
        let src =
            "type Foo struct {\n\tA string\n}\n\nconst (\n\tFoo int = 3\n\tBaz uint8 = x\n)\n";
        let (_, renamed) = fix_source(src);
        assert!(renamed.is_empty());
    }

    #[test]
    fn adds_stub_to_a_package_with_bodyless_wasmimport() {
        let tmp = TmpDir::new();
        let pkg = tmp.path().join("wit_exports");
        write_go(
            &pkg,
            "wit_exports.go",
            "package wit_exports\n\n//go:wasmimport [export]x [task-return]save\nfunc f(a uintptr)\n",
        );

        let written = add_missing_assembly_stubs(tmp.path()).unwrap();
        assert_eq!(written, vec![pkg.join("empty.s")]);
        // byte-identical to what the generator writes for import packages
        assert_eq!(fs::read_to_string(pkg.join("empty.s")).unwrap(), EMPTY_S);
    }

    #[test]
    fn does_not_add_a_stub_when_one_already_exists() {
        let tmp = TmpDir::new();
        let pkg = tmp.path().join("imports");
        write_go(
            &pkg,
            "b.go",
            "package imports\n//go:wasmimport env f\nfunc f()\n",
        );
        fs::write(pkg.join("empty.s"), "// pre-existing").unwrap();

        assert!(add_missing_assembly_stubs(tmp.path()).unwrap().is_empty());
        assert_eq!(
            fs::read_to_string(pkg.join("empty.s")).unwrap(),
            "// pre-existing"
        );
    }

    #[test]
    fn does_not_add_a_stub_for_wasmexport_only_packages() {
        // //go:wasmexport functions have bodies, so no assembly file is required.
        let tmp = TmpDir::new();
        let pkg = tmp.path().join("exports_only");
        write_go(
            &pkg,
            "c.go",
            "package x\n//go:wasmexport run\nfunc run() {}\n",
        );

        assert!(add_missing_assembly_stubs(tmp.path()).unwrap().is_empty());
        assert!(!pkg.join("empty.s").exists());
    }

    #[test]
    fn stub_addition_is_idempotent_and_recurses() {
        let tmp = TmpDir::new();
        let nested = tmp.path().join("a/b/deep_pkg");
        write_go(
            &nested,
            "d.go",
            "package deep\n//go:wasmimport env g\nfunc g()\n",
        );

        assert_eq!(add_missing_assembly_stubs(tmp.path()).unwrap().len(), 1);
        assert!(add_missing_assembly_stubs(tmp.path()).unwrap().is_empty());
    }

    #[test]
    fn preserves_trailing_newline() {
        let (out, _) = fix_source(SAMPLE);
        assert!(out.ends_with('\n'));
    }
}
