package rpc:counters;

interface api {
  resource counter {
    constructor(name: string);
    inc-by: func(value: u64);
    get-value: func() -> u64;

    get-args: func() -> list<string>;
    get-env: func() -> list<tuple<string, string>>;
  }

  inc-global-by: func(value: u64);
  get-global-value: func() -> u64;
}

world counters {
  import wasi:cli/environment@0.2.0;

  export api;
}
