package golem:itrpc;

interface rpc-api {
  use golem:it-exports/api.{data};

  echo: func(input: string) -> string;

  calculate: func(input: u64) -> u64;

  process: func(input: list<data>) -> list<data>;
}

world parent-component {
  export rpc-api;
}
