package golem:rust;

world golem-rust {
  import golem:api/host@1.5.0;
  import golem:api/oplog@1.5.0;
  import golem:api/context@1.5.0;

  import golem:agent/host@1.5.0;

  import golem:durability/durability@1.5.0;
  import golem:rdbms/mysql@1.5.0;
  import golem:rdbms/postgres@1.5.0;

  import wasi:blobstore/blobstore;
  import wasi:blobstore/container;
  import wasi:keyvalue/eventual-batch@0.1.0;
  import wasi:keyvalue/eventual@0.1.0;
  import wasi:logging/logging;
  import wasi:config/store@0.2.0-draft;
}

world golem-rust-load-snapshot {
  include golem-rust;

  export golem:api/load-snapshot@1.5.0;
}

world golem-rust-save-snapshot {
    include golem-rust;
    export golem:api/save-snapshot@1.5.0;
}

world golem-rust-oplog-processor {
    include golem-rust;
    export golem:api/oplog-processor@1.5.0;
}

world golem-agentic {
   include golem-rust;
   export golem:agent/guest@1.5.0;
}
