package golem:it;

world tinygo-wasi {
    include wasi:cli/imports@0.2.3;

    import wasi:cli/environment@0.2.3;
    import wasi:io/poll@0.2.3;
    import wasi:io/streams@0.2.3;

    export example1: func(s: string) -> s32;
}
