package golem:it;

interface api {
  get: func() -> list<string>;
}

world networking {
  import golem:api/host@1.1.7;
  import wasi:sockets/ip-name-lookup@0.2.3;
  import wasi:sockets/instance-network@0.2.3;

  export api;
}