package cloud.golem.runtime

/**
 * Byte-level snapshot codec for one agent type, generated by KSP when the agent mixes in
 * `Snapshotted<S>`. [save]/[load] operate on the live agent instance (cast to the concrete class
 * inside the generated bodies). Null on the descriptor ⇒ the agent didn't opt in (empty snapshot).
 * Mirrors Scala's `SnapshotCodec`.
 */
class SnapshotCodec(
    val save: (Any) -> ByteArray,
    val load: (Any, ByteArray) -> Unit,
)
