// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://license.golem.cloud/LICENSE

use crate::durable_host::tool::attachment::{AttachmentConsumer, AttachmentRead, AttachmentWriter};
use crate::workerctx::WorkerCtx;
use async_trait::async_trait;
use golem_common::model::agent::Principal;
use golem_common::model::oplog::payload::types::{
    SerializableToolError, SerializableToolResultValue, SerializableToolRpcError,
    SerializableToolStructuredResult,
};
use golem_common::model::tool::{CompiledToolBinding, HostToolId};
use golem_common::schema::TypedSchemaValue;
use golem_service_base::error::worker_executor::WorkerExecutorError;
use std::collections::BTreeMap;
use std::sync::Arc;

/// The exact, deployment-pinned identity of a native implementation.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub struct NativeToolKey {
    pub host_tool_id: HostToolId,
    pub implementation_version: String,
}

/// Invocation data generated by the native authoring macro and passed to its handler.
pub struct NativeToolInvocation {
    pub command_path: Vec<String>,
    pub input: TypedSchemaValue,
    pub principal: Principal,
    pub cancellation: Option<tokio_util::sync::CancellationToken>,
    pub stdin: Option<NativeToolStdin>,
    pub stdout: Option<NativeToolStdout>,
}

/// Safe native view of a tool input attachment.
pub struct NativeToolStdin {
    pub(crate) consumer: AttachmentConsumer,
}

impl NativeToolStdin {
    pub async fn read(&self) -> Option<Result<Vec<u8>, String>> {
        match self.consumer.read_next().await {
            AttachmentRead::Item(Ok(bytes)) => Some(Ok(bytes)),
            AttachmentRead::Item(Err(error)) => Some(Err(format!("{error:?}"))),
            AttachmentRead::End => None,
        }
    }
}

/// Safe native view of a tool output attachment.
#[derive(Clone)]
pub struct NativeToolStdout {
    pub(crate) writer: AttachmentWriter,
}

impl NativeToolStdout {
    pub async fn write(&self, bytes: Vec<u8>) -> Result<(), String> {
        self.writer
            .write(bytes)
            .await
            .map_err(|error| format!("{error:?}"))
    }

    pub fn finish(&self) -> Result<(), String> {
        self.writer.finish().map_err(|error| format!("{error:?}"))
    }
}

pub type NativeToolResult = Result<SerializableToolStructuredResult, SerializableToolRpcError>;

/// Executor-side contract generated for a native tool implementation.
///
/// Implementations call the same host functions on `Ctx` that component imports call. Therefore
/// durable effects, policy checks, and panic behavior are shared with executor host functions.
#[async_trait]
pub trait NativeToolHandler<Ctx: WorkerCtx>: Send + Sync + 'static {
    async fn invoke(
        &self,
        ctx: &mut Ctx,
        invocation: NativeToolInvocation,
    ) -> Result<NativeToolResult, WorkerExecutorError>;
}

/// Connects a typed macro-generated invoker to the executor's durable tool operation.
pub struct NativeToolAdapter<T>(pub T);

impl golem_native_tool::NativeToolStdinHandle for NativeToolStdin {
    fn read<'a>(&'a mut self) -> golem_native_tool::NativeToolReadFuture<'a> {
        Box::pin(NativeToolStdin::read(self))
    }
}

impl golem_native_tool::NativeToolStdoutHandle for NativeToolStdout {
    fn write<'a>(
        &'a mut self,
        bytes: Vec<u8>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), String>> + Send + 'a>> {
        Box::pin(NativeToolStdout::write(self, bytes))
    }

    fn finish(&mut self) -> Result<(), String> {
        NativeToolStdout::finish(self)
    }
}

#[async_trait]
impl<Ctx, T> NativeToolHandler<Ctx> for NativeToolAdapter<T>
where
    Ctx: WorkerCtx,
    T: golem_native_tool::NativeToolInvoker<Ctx, anyhow::Error>,
{
    async fn invoke(
        &self,
        ctx: &mut Ctx,
        invocation: NativeToolInvocation,
    ) -> Result<NativeToolResult, WorkerExecutorError> {
        let result = self
            .0
            .invoke(
                ctx,
                golem_native_tool::NativeToolInvocation {
                    command_path: invocation.command_path,
                    input: invocation.input,
                    principal: invocation.principal,
                    stdin: invocation.stdin.map(|input| Box::new(input) as _),
                    stdout: invocation.stdout.map(|output| Box::new(output) as _),
                },
            )
            .await
            .map_err(|error| {
                error
                    .downcast_ref::<WorkerExecutorError>()
                    .cloned()
                    .unwrap_or_else(|| WorkerExecutorError::runtime(error.to_string()))
            })?;
        Ok(match result {
            Ok(value) => Ok(SerializableToolStructuredResult {
                result: value
                    .result
                    .as_ref()
                    .map(SerializableToolResultValue::from_typed)
                    .transpose()
                    .map_err(WorkerExecutorError::runtime)?,
            }),
            Err(error) => {
                use golem_native_tool::NativeToolRpcError;
                let error = match error {
                    NativeToolRpcError::InvalidCommandPath(path) => {
                        SerializableToolError::InvalidCommandPath(path)
                    }
                    NativeToolRpcError::InvalidInput(details) => {
                        SerializableToolError::InvalidInput(details)
                    }
                    NativeToolRpcError::InvalidResult(details) => {
                        SerializableToolError::InvalidResult(details)
                    }
                    NativeToolRpcError::Custom(value) => {
                        SerializableToolError::CustomError(Box::new(value))
                    }
                };
                Err(SerializableToolRpcError::RemoteToolError(Box::new(error)))
            }
        })
    }
}

pub struct NativeToolRegistration<Ctx: WorkerCtx> {
    pub definition: golem_native_tool::NativeToolDefinition,
    pub handler: Arc<dyn NativeToolHandler<Ctx>>,
}

impl<Ctx: WorkerCtx> Clone for NativeToolRegistration<Ctx> {
    fn clone(&self) -> Self {
        Self {
            definition: self.definition.clone(),
            handler: self.handler.clone(),
        }
    }
}

/// Immutable catalog. Construction rejects ambiguous exact identities before workers start.
pub struct NativeToolCatalog<Ctx: WorkerCtx> {
    registrations: BTreeMap<NativeToolKey, NativeToolRegistration<Ctx>>,
}

impl<Ctx: WorkerCtx> NativeToolCatalog<Ctx> {
    pub fn new(
        registrations: impl IntoIterator<Item = NativeToolRegistration<Ctx>>,
    ) -> Result<Self, String> {
        let mut entries = BTreeMap::new();
        for registration in registrations {
            registration.definition.validate()?;
            let key = NativeToolKey {
                host_tool_id: HostToolId::try_from(registration.definition.id.clone())?,
                implementation_version: registration.definition.implementation_version.clone(),
            };
            if entries.insert(key.clone(), registration).is_some() {
                return Err(format!(
                    "duplicate native tool implementation '{:?}@{}'",
                    key.host_tool_id, key.implementation_version
                ));
            }
        }
        Ok(Self {
            registrations: entries,
        })
    }

    pub fn empty() -> Self {
        Self {
            registrations: BTreeMap::new(),
        }
    }

    pub fn get(&self, key: &NativeToolKey) -> Option<NativeToolRegistration<Ctx>> {
        self.registrations.get(key).cloned()
    }
}

impl<Ctx: WorkerCtx> NativeToolRegistration<Ctx> {
    pub fn validate_dispatch(&self, binding: &CompiledToolBinding) -> Result<(), String> {
        let source_matches = matches!(
            &binding.source,
            golem_common::model::tool::ToolSource::Host { host_tool_id, implementation_version }
                if host_tool_id.as_str() == self.definition.id
                    && implementation_version == &self.definition.implementation_version
        );
        let digest_matches =
            binding.metadata_digest.as_blake3_hash().as_bytes() == &self.definition.metadata_digest;
        if !source_matches
            || binding.metadata_version != self.definition.metadata_version
            || !digest_matches
            || binding.version != self.definition.tool.version
        {
            return Err(format!(
                "native tool '{}@{}' does not match the deployment metadata identity",
                self.definition.id, self.definition.implementation_version
            ));
        }
        Ok(())
    }
}

/// Native implementations compiled into the production executor binary.
pub fn compiled_native_tools<Ctx: WorkerCtx>() -> Vec<NativeToolRegistration<Ctx>> {
    Vec::new()
}

impl<Ctx: WorkerCtx> Default for NativeToolCatalog<Ctx> {
    fn default() -> Self {
        Self::new(compiled_native_tools()).expect("compiled native tool inventory is invalid")
    }
}
