// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     golem:core@2.0.0
//     wasi:clocks@0.3.0
//     golem:api@1.5.0
//     golem:agent@2.0.0
//     golem:rdbms@1.5.0
//     golem:durability@1.5.0
//     golem:quota@1.5.0
//     golem:secrets@0.1.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:blobstore
//     wasi:keyvalue@0.1.0
//     wasi:config@0.2.0-draft
//     wasi:logging
//     golem:websocket@1.5.0
//     wasi:http@0.3.0
//     golem:agent-guest
//     golem:tool@0.1.0
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6

package golem_secrets_reveal

import (
	"github.com/golemcloud/golem/sdks/go/golem/internal/wit/golem_core_types"
	"github.com/golemcloud/golem/sdks/go/golem/internal/wit/golem_secrets_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type SecretError = golem_secrets_types.SecretError
type Secret = golem_core_types.Secret
type SchemaGraph = golem_core_types.SchemaGraph
type SchemaValueTree = golem_core_types.SchemaValueTree

//go:wasmimport golem:secrets/reveal@0.1.0 reveal
func wasm_import_reveal(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 int32, arg6 uintptr)

func Reveal(s *golem_core_types.Secret, expected golem_core_types.SchemaGraph) witTypes.Result[golem_core_types.SchemaValueTree, golem_secrets_types.SecretError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice114 := (expected).TypeNodes
	length116 := uint32(len(slice114))
	result115 := witRuntime.Allocate(pinner, uintptr(length116*(56+22*4)), 8)
	for index, element := range slice114 {
		base := unsafe.Add(result115, index*(56+22*4))

		switch (element).Body.Tag() {
		case golem_core_types.SchemaTypeBodyRefType:
			payload := (element).Body.RefType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case golem_core_types.SchemaTypeBodyBoolType:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))

		case golem_core_types.SchemaTypeBodyS8Type:
			payload := (element).Body.S8Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf8 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf8)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf8)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyS16Type:
			payload := (element).Body.S16Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf80 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf80)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf80)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyS32Type:
			payload := (element).Body.S32Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf81 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf81)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf81)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyS64Type:
			payload := (element).Body.S64Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf82 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf82)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf82)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyU8Type:
			payload := (element).Body.U8Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf83 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf83)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf83)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyU16Type:
			payload := (element).Body.U16Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf84 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf84)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf84)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyU32Type:
			payload := (element).Body.U32Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf85 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf85)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf85)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyU64Type:
			payload := (element).Body.U64Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf86 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf86)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf86)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyF32Type:
			payload := (element).Body.F32Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf87 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf87)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf87)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyF64Type:
			payload := (element).Body.F64Type()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

				switch (payload).Min.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Min.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Max.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Max.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.NumericBoundSigned:
						payload := payload.Signed()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(0))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = payload

					case golem_core_types.NumericBoundUnsigned:
						payload := payload.Unsigned()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(1))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					case golem_core_types.NumericBoundFloatBits:
						payload := payload.FloatBits()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), 48)) = int8(int32(2))
						*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64(payload)

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

				switch (payload).Unit.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Unit.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 64)) = int8(int32(1))
					utf88 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf88)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 2*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 1*4))) = uint32(uintptr(uintptr(utf88)))

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyCharType:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))

		case golem_core_types.SchemaTypeBodyStringType:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		case golem_core_types.SchemaTypeBodyRecordType:
			payload := (element).Body.RecordType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(14))
			slice18 := payload
			length20 := uint32(len(slice18))
			result19 := witRuntime.Allocate(pinner, uintptr(length20*(17*4)), 4)
			for index, element := range slice18 {
				base := unsafe.Add(result19, index*(17*4))
				utf89 := unsafe.Pointer(unsafe.StringData((element).Name))
				pinner.Pin(utf89)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf89)))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = (element).Body

				switch ((element).Metadata).Doc.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Doc.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(1))
					utf810 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf810)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf810)))

				default:
					panic("unreachable")
				}
				slice := ((element).Metadata).Aliases
				length := uint32(len(slice))
				result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
				for index, element := range slice {
					base := unsafe.Add(result, index*(2*4))
					utf811 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf811)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf811)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = uint32(length)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uintptr(uintptr(result)))
				slice13 := ((element).Metadata).Examples
				length15 := uint32(len(slice13))
				result14 := witRuntime.Allocate(pinner, uintptr(length15*(2*4)), 4)
				for index, element := range slice13 {
					base := unsafe.Add(result14, index*(2*4))
					utf812 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf812)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf812)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = uint32(length15)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))) = uint32(uintptr(uintptr(result14)))

				switch ((element).Metadata).Deprecated.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Deprecated.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = int8(int32(1))
					utf816 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf816)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (12 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (11 * 4))) = uint32(uintptr(uintptr(utf816)))

				default:
					panic("unreachable")
				}

				switch ((element).Metadata).Role.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (13 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Role.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (13 * 4))) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.RoleMultimodal:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (14 * 4))) = int8(int32(0))

					case golem_core_types.RoleUnstructuredText:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (14 * 4))) = int8(int32(1))

					case golem_core_types.RoleUnstructuredBinary:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (14 * 4))) = int8(int32(2))

					case golem_core_types.RoleOther:
						payload := payload.Other()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (14 * 4))) = int8(int32(3))
						utf817 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf817)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 * 4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (15 * 4))) = uint32(uintptr(uintptr(utf817)))

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length20)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result19)))

		case golem_core_types.SchemaTypeBodyVariantType:
			payload := (element).Body.VariantType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(15))
			slice33 := payload
			length35 := uint32(len(slice33))
			result34 := witRuntime.Allocate(pinner, uintptr(length35*(8+16*4)), 4)
			for index, element := range slice33 {
				base := unsafe.Add(result34, index*(8+16*4))
				utf821 := unsafe.Pointer(unsafe.StringData((element).Name))
				pinner.Pin(utf821)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf821)))

				switch (element).Payload.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).Payload.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(1))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 2*4))) = payload

				default:
					panic("unreachable")
				}

				switch ((element).Metadata).Doc.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Doc.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(1))
					utf822 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf822)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = uint32(uintptr(uintptr(utf822)))

				default:
					panic("unreachable")
				}
				slice24 := ((element).Metadata).Aliases
				length26 := uint32(len(slice24))
				result25 := witRuntime.Allocate(pinner, uintptr(length26*(2*4)), 4)
				for index, element := range slice24 {
					base := unsafe.Add(result25, index*(2*4))
					utf823 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf823)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf823)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))) = uint32(length26)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))) = uint32(uintptr(uintptr(result25)))
				slice28 := ((element).Metadata).Examples
				length30 := uint32(len(slice28))
				result29 := witRuntime.Allocate(pinner, uintptr(length30*(2*4)), 4)
				for index, element := range slice28 {
					base := unsafe.Add(result29, index*(2*4))
					utf827 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf827)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf827)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 8*4))) = uint32(length30)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = uint32(uintptr(uintptr(result29)))

				switch ((element).Metadata).Deprecated.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 9*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Deprecated.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 9*4))) = int8(int32(1))
					utf831 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf831)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 11*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 10*4))) = uint32(uintptr(uintptr(utf831)))

				default:
					panic("unreachable")
				}

				switch ((element).Metadata).Role.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 12*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Role.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 12*4))) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.RoleMultimodal:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 13*4))) = int8(int32(0))

					case golem_core_types.RoleUnstructuredText:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 13*4))) = int8(int32(1))

					case golem_core_types.RoleUnstructuredBinary:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 13*4))) = int8(int32(2))

					case golem_core_types.RoleOther:
						payload := payload.Other()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 13*4))) = int8(int32(3))
						utf832 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf832)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 15*4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 14*4))) = uint32(uintptr(uintptr(utf832)))

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length35)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result34)))

		case golem_core_types.SchemaTypeBodyEnumType:
			payload := (element).Body.EnumType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(16))
			slice37 := payload
			length39 := uint32(len(slice37))
			result38 := witRuntime.Allocate(pinner, uintptr(length39*(2*4)), 4)
			for index, element := range slice37 {
				base := unsafe.Add(result38, index*(2*4))
				utf836 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf836)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf836)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length39)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result38)))

		case golem_core_types.SchemaTypeBodyFlagsType:
			payload := (element).Body.FlagsType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(17))
			slice41 := payload
			length43 := uint32(len(slice41))
			result42 := witRuntime.Allocate(pinner, uintptr(length43*(2*4)), 4)
			for index, element := range slice41 {
				base := unsafe.Add(result42, index*(2*4))
				utf840 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf840)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf840)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length43)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result42)))

		case golem_core_types.SchemaTypeBodyTupleType:
			payload := (element).Body.TupleType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(18))
			slice44 := payload
			length46 := uint32(len(slice44))
			result45 := witRuntime.Allocate(pinner, uintptr(length46*4), 4)
			for index, element := range slice44 {
				base := unsafe.Add(result45, index*4)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = element

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length46)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result45)))

		case golem_core_types.SchemaTypeBodyListType:
			payload := (element).Body.ListType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(19))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case golem_core_types.SchemaTypeBodyFixedListType:
			payload := (element).Body.FixedListType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(20))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).Element
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).Length)

		case golem_core_types.SchemaTypeBodyMapType:
			payload := (element).Body.MapType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(21))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).Key
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).Value

		case golem_core_types.SchemaTypeBodyOptionType:
			payload := (element).Body.OptionType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(22))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case golem_core_types.SchemaTypeBodyResultType:
			payload := (element).Body.ResultType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(23))

			switch (payload).Ok.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Ok.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = payload

			default:
				panic("unreachable")
			}

			switch (payload).Err.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Err.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = payload

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyTextType:
			payload := (element).Body.TextType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(24))

			switch (payload).Languages.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Languages.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				slice48 := payload
				length50 := uint32(len(slice48))
				result49 := witRuntime.Allocate(pinner, uintptr(length50*(2*4)), 4)
				for index, element := range slice48 {
					base := unsafe.Add(result49, index*(2*4))
					utf847 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf847)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf847)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(length50)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(result49)))

			default:
				panic("unreachable")
			}

			switch (payload).MinLength.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).MinLength.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 3*4))) = int32(payload)

			default:
				panic("unreachable")
			}

			switch (payload).MaxLength.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).MaxLength.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 3*4))) = int32(payload)

			default:
				panic("unreachable")
			}

			switch (payload).Regex.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Regex.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 3*4))) = int8(int32(1))
				utf851 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf851)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 5*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 4*4))) = uint32(uintptr(uintptr(utf851)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyBinaryType:
			payload := (element).Body.BinaryType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(25))

			switch (payload).MimeTypes.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).MimeTypes.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				slice53 := payload
				length55 := uint32(len(slice53))
				result54 := witRuntime.Allocate(pinner, uintptr(length55*(2*4)), 4)
				for index, element := range slice53 {
					base := unsafe.Add(result54, index*(2*4))
					utf852 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf852)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf852)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(length55)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(result54)))

			default:
				panic("unreachable")
			}

			switch (payload).MinBytes.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).MinBytes.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 3*4))) = int32(payload)

			default:
				panic("unreachable")
			}

			switch (payload).MaxBytes.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).MaxBytes.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 3*4))) = int32(payload)

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyPathType:
			payload := (element).Body.PathType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(26))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32((payload).Direction))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32((payload).Kind))

			switch (payload).AllowedMimeTypes.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).AllowedMimeTypes.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = int8(int32(1))
				slice57 := payload
				length59 := uint32(len(slice57))
				result58 := witRuntime.Allocate(pinner, uintptr(length59*(2*4)), 4)
				for index, element := range slice57 {
					base := unsafe.Add(result58, index*(2*4))
					utf856 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf856)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf856)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = uint32(length59)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uintptr(uintptr(result58)))

			default:
				panic("unreachable")
			}

			switch (payload).AllowedExtensions.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).AllowedExtensions.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = int8(int32(1))
				slice61 := payload
				length63 := uint32(len(slice61))
				result62 := witRuntime.Allocate(pinner, uintptr(length63*(2*4)), 4)
				for index, element := range slice61 {
					base := unsafe.Add(result62, index*(2*4))
					utf860 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf860)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf860)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))) = uint32(length63)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))) = uint32(uintptr(uintptr(result62)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyUrlType:
			payload := (element).Body.UrlType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(27))

			switch (payload).AllowedSchemes.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).AllowedSchemes.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				slice65 := payload
				length67 := uint32(len(slice65))
				result66 := witRuntime.Allocate(pinner, uintptr(length67*(2*4)), 4)
				for index, element := range slice65 {
					base := unsafe.Add(result66, index*(2*4))
					utf864 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf864)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf864)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(length67)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(result66)))

			default:
				panic("unreachable")
			}

			switch (payload).AllowedHosts.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).AllowedHosts.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = int8(int32(1))
				slice69 := payload
				length71 := uint32(len(slice69))
				result70 := witRuntime.Allocate(pinner, uintptr(length71*(2*4)), 4)
				for index, element := range slice69 {
					base := unsafe.Add(result70, index*(2*4))
					utf868 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf868)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf868)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))) = uint32(length71)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = uint32(uintptr(uintptr(result70)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyDatetimeType:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(28))

		case golem_core_types.SchemaTypeBodyDurationType:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(29))

		case golem_core_types.SchemaTypeBodyQuantityType:
			payload := (element).Body.QuantityType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(30))
			utf872 := unsafe.Pointer(unsafe.StringData((payload).BaseUnit))
			pinner.Pin(utf872)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len((payload).BaseUnit)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf872)))
			slice74 := (payload).AllowedSuffixes
			length76 := uint32(len(slice74))
			result75 := witRuntime.Allocate(pinner, uintptr(length76*(2*4)), 4)
			for index, element := range slice74 {
				base := unsafe.Add(result75, index*(2*4))
				utf873 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf873)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf873)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = uint32(length76)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uintptr(uintptr(result75)))

			switch (payload).Min.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Min.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = int8(int32(1))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))) = (payload).Mantissa
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (24 + 4*4))) = (payload).Scale
				utf877 := unsafe.Pointer(unsafe.StringData((payload).Unit))
				pinner.Pin(utf877)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 6*4))) = uint32(uint32(len((payload).Unit)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 5*4))) = uint32(uintptr(uintptr(utf877)))

			default:
				panic("unreachable")
			}

			switch (payload).Max.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 6*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Max.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 6*4))) = int8(int32(1))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (40 + 6*4))) = (payload).Mantissa
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (48 + 6*4))) = (payload).Scale
				utf878 := unsafe.Pointer(unsafe.StringData((payload).Unit))
				pinner.Pin(utf878)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 8*4))) = uint32(uint32(len((payload).Unit)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 7*4))) = uint32(uintptr(uintptr(utf878)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyUnionType:
			payload := (element).Body.UnionType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(31))
			slice98 := (payload).Branches
			length100 := uint32(len(slice98))
			result99 := witRuntime.Allocate(pinner, uintptr(length100*(23*4)), 4)
			for index, element := range slice98 {
				base := unsafe.Add(result99, index*(23*4))
				utf879 := unsafe.Pointer(unsafe.StringData((element).Tag))
				pinner.Pin(utf879)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Tag)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf879)))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = (element).Body

				switch (element).Discriminator.Tag() {
				case golem_core_types.DiscriminatorRulePrefix:
					payload := (element).Discriminator.Prefix()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(0))
					utf880 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf880)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf880)))

				case golem_core_types.DiscriminatorRuleSuffix:
					payload := (element).Discriminator.Suffix()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(1))
					utf881 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf881)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf881)))

				case golem_core_types.DiscriminatorRuleContains:
					payload := (element).Discriminator.Contains()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(2))
					utf882 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf882)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf882)))

				case golem_core_types.DiscriminatorRuleRegex:
					payload := (element).Discriminator.Regex()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(3))
					utf883 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf883)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf883)))

				case golem_core_types.DiscriminatorRuleFieldEquals:
					payload := (element).Discriminator.FieldEquals()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(4))
					utf884 := unsafe.Pointer(unsafe.StringData((payload).FieldName))
					pinner.Pin(utf884)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len((payload).FieldName)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf884)))

					switch (payload).Literal.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).Literal.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = int8(int32(1))
						utf885 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf885)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = uint32(uintptr(uintptr(utf885)))

					default:
						panic("unreachable")
					}

				case golem_core_types.DiscriminatorRuleFieldAbsent:
					payload := (element).Discriminator.FieldAbsent()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(5))
					utf886 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf886)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uintptr(uintptr(utf886)))

				default:
					panic("unreachable")
				}

				switch ((element).Metadata).Doc.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Doc.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = int8(int32(1))
					utf887 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf887)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (11 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = uint32(uintptr(uintptr(utf887)))

				default:
					panic("unreachable")
				}
				slice89 := ((element).Metadata).Aliases
				length91 := uint32(len(slice89))
				result90 := witRuntime.Allocate(pinner, uintptr(length91*(2*4)), 4)
				for index, element := range slice89 {
					base := unsafe.Add(result90, index*(2*4))
					utf888 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf888)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf888)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (13 * 4))) = uint32(length91)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (12 * 4))) = uint32(uintptr(uintptr(result90)))
				slice93 := ((element).Metadata).Examples
				length95 := uint32(len(slice93))
				result94 := witRuntime.Allocate(pinner, uintptr(length95*(2*4)), 4)
				for index, element := range slice93 {
					base := unsafe.Add(result94, index*(2*4))
					utf892 := unsafe.Pointer(unsafe.StringData(element))
					pinner.Pin(utf892)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf892)))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (15 * 4))) = uint32(length95)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (14 * 4))) = uint32(uintptr(uintptr(result94)))

				switch ((element).Metadata).Deprecated.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Deprecated.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 * 4))) = int8(int32(1))
					utf896 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf896)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (18 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (17 * 4))) = uint32(uintptr(uintptr(utf896)))

				default:
					panic("unreachable")
				}

				switch ((element).Metadata).Role.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (19 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := ((element).Metadata).Role.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (19 * 4))) = int8(int32(1))

					switch payload.Tag() {
					case golem_core_types.RoleMultimodal:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (20 * 4))) = int8(int32(0))

					case golem_core_types.RoleUnstructuredText:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (20 * 4))) = int8(int32(1))

					case golem_core_types.RoleUnstructuredBinary:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (20 * 4))) = int8(int32(2))

					case golem_core_types.RoleOther:
						payload := payload.Other()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (20 * 4))) = int8(int32(3))
						utf897 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf897)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (22 * 4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (21 * 4))) = uint32(uintptr(uintptr(utf897)))

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length100)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result99)))

		case golem_core_types.SchemaTypeBodySecretType:
			payload := (element).Body.SecretType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(32))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).Inner

			switch (payload).Category.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).Category.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = int8(int32(1))
				utf8101 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf8101)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uintptr(uintptr(utf8101)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyQuotaTokenType:
			payload := (element).Body.QuotaTokenType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(33))

			switch (payload).ResourceName.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).ResourceName.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				utf8102 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf8102)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(utf8102)))

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyFutureType:
			payload := (element).Body.FutureType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(34))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = payload

			default:
				panic("unreachable")
			}

		case golem_core_types.SchemaTypeBodyStreamType:
			payload := (element).Body.StreamType()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(35))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = payload

			default:
				panic("unreachable")
			}

		default:
			panic("unreachable")
		}

		switch ((element).Metadata).Doc.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 8*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := ((element).Metadata).Doc.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 8*4))) = int8(int32(1))
			utf8103 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8103)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 10*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 9*4))) = uint32(uintptr(uintptr(utf8103)))

		default:
			panic("unreachable")
		}
		slice105 := ((element).Metadata).Aliases
		length107 := uint32(len(slice105))
		result106 := witRuntime.Allocate(pinner, uintptr(length107*(2*4)), 4)
		for index, element := range slice105 {
			base := unsafe.Add(result106, index*(2*4))
			utf8104 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf8104)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8104)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 12*4))) = uint32(length107)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 11*4))) = uint32(uintptr(uintptr(result106)))
		slice109 := ((element).Metadata).Examples
		length111 := uint32(len(slice109))
		result110 := witRuntime.Allocate(pinner, uintptr(length111*(2*4)), 4)
		for index, element := range slice109 {
			base := unsafe.Add(result110, index*(2*4))
			utf8108 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf8108)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8108)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 14*4))) = uint32(length111)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 13*4))) = uint32(uintptr(uintptr(result110)))

		switch ((element).Metadata).Deprecated.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 15*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := ((element).Metadata).Deprecated.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 15*4))) = int8(int32(1))
			utf8112 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8112)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 17*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 16*4))) = uint32(uintptr(uintptr(utf8112)))

		default:
			panic("unreachable")
		}

		switch ((element).Metadata).Role.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 18*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := ((element).Metadata).Role.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 18*4))) = int8(int32(1))

			switch payload.Tag() {
			case golem_core_types.RoleMultimodal:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 19*4))) = int8(int32(0))

			case golem_core_types.RoleUnstructuredText:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 19*4))) = int8(int32(1))

			case golem_core_types.RoleUnstructuredBinary:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 19*4))) = int8(int32(2))

			case golem_core_types.RoleOther:
				payload := payload.Other()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (56 + 19*4))) = int8(int32(3))
				utf8113 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf8113)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 21*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 20*4))) = uint32(uintptr(uintptr(utf8113)))

			default:
				panic("unreachable")
			}

		default:
			panic("unreachable")
		}

	}

	slice119 := (expected).Defs
	length121 := uint32(len(slice119))
	result120 := witRuntime.Allocate(pinner, uintptr(length121*(6*4)), 4)
	for index, element := range slice119 {
		base := unsafe.Add(result120, index*(6*4))
		utf8117 := unsafe.Pointer(unsafe.StringData((element).Id))
		pinner.Pin(utf8117)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Id)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8117)))

		switch (element).Name.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (element).Name.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(1))
			utf8118 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8118)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uintptr(uintptr(utf8118)))

		default:
			panic("unreachable")
		}
		*(*int32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = (element).Body

	}

	wasm_import_reveal((s).Handle(), uintptr(result115), length116, uintptr(result120), length121, (expected).Root, returnArea)
	var result147 witTypes.Result[golem_core_types.SchemaValueTree, golem_secrets_types.SecretError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result142 := make([]golem_core_types.SchemaValueNode, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(16+4*4))
			var variant141 golem_core_types.SchemaValueNode
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				variant141 = golem_core_types.MakeSchemaValueNodeBoolValue((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

			case 1:

				variant141 = golem_core_types.MakeSchemaValueNodeS8Value(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

			case 2:

				variant141 = golem_core_types.MakeSchemaValueNodeS16Value(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

			case 3:

				variant141 = golem_core_types.MakeSchemaValueNodeS32Value(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 4:

				variant141 = golem_core_types.MakeSchemaValueNodeS64Value(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 5:

				variant141 = golem_core_types.MakeSchemaValueNodeU8Value(uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

			case 6:

				variant141 = golem_core_types.MakeSchemaValueNodeU16Value(uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

			case 7:

				variant141 = golem_core_types.MakeSchemaValueNodeU32Value(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

			case 8:

				variant141 = golem_core_types.MakeSchemaValueNodeU64Value(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8))))

			case 9:

				variant141 = golem_core_types.MakeSchemaValueNodeF32Value(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 10:

				variant141 = golem_core_types.MakeSchemaValueNodeF64Value(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 11:

				variant141 = golem_core_types.MakeSchemaValueNodeCharValue(rune(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

			case 12:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant141 = golem_core_types.MakeSchemaValueNodeStringValue(value)

			case 13:
				result122 := make([]int32, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*4)

					result122 = append(result122, *(*int32)(unsafe.Add(unsafe.Pointer(base), 0)))
				}

				variant141 = golem_core_types.MakeSchemaValueNodeRecordValue(result122)

			case 14:
				var option witTypes.Option[int32]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12))) {
				case 0:

					option = witTypes.None[int32]()
				case 1:

					option = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)))
				default:
					panic("unreachable")
				}

				variant141 = golem_core_types.MakeSchemaValueNodeVariantValue(golem_core_types.VariantValuePayload{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))), option})

			case 15:

				variant141 = golem_core_types.MakeSchemaValueNodeEnumValue(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

			case 16:
				result123 := make([]bool, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*1)

					result123 = append(result123, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) != 0))
				}

				variant141 = golem_core_types.MakeSchemaValueNodeFlagsValue(result123)

			case 17:
				result124 := make([]int32, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*4)

					result124 = append(result124, *(*int32)(unsafe.Add(unsafe.Pointer(base), 0)))
				}

				variant141 = golem_core_types.MakeSchemaValueNodeTupleValue(result124)

			case 18:
				result125 := make([]int32, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*4)

					result125 = append(result125, *(*int32)(unsafe.Add(unsafe.Pointer(base), 0)))
				}

				variant141 = golem_core_types.MakeSchemaValueNodeListValue(result125)

			case 19:
				result126 := make([]int32, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*4)

					result126 = append(result126, *(*int32)(unsafe.Add(unsafe.Pointer(base), 0)))
				}

				variant141 = golem_core_types.MakeSchemaValueNodeFixedListValue(result126)

			case 20:
				result127 := make([]golem_core_types.MapEntry, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*8)

					result127 = append(result127, golem_core_types.MapEntry{*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)), *(*int32)(unsafe.Add(unsafe.Pointer(base), 4))})
				}

				variant141 = golem_core_types.MakeSchemaValueNodeMapValue(result127)

			case 21:
				var option128 witTypes.Option[int32]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
				case 0:

					option128 = witTypes.None[int32]()
				case 1:

					option128 = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)))
				default:
					panic("unreachable")
				}

				variant141 = golem_core_types.MakeSchemaValueNodeOptionValue(option128)

			case 22:
				var variant golem_core_types.ResultValuePayload
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
				case 0:
					var option129 witTypes.Option[int32]
					switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12))) {
					case 0:

						option129 = witTypes.None[int32]()
					case 1:

						option129 = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)))
					default:
						panic("unreachable")
					}

					variant = golem_core_types.MakeResultValuePayloadOkValue(option129)

				case 1:
					var option130 witTypes.Option[int32]
					switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12))) {
					case 0:

						option130 = witTypes.None[int32]()
					case 1:

						option130 = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)))
					default:
						panic("unreachable")
					}

					variant = golem_core_types.MakeResultValuePayloadErrValue(option130)

				default:
					panic("unreachable")
				}

				variant141 = golem_core_types.MakeSchemaValueNodeResultValue(variant)

			case 23:
				value131 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				var option133 witTypes.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))) {
				case 0:

					option133 = witTypes.None[string]()
				case 1:
					value132 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))

					option133 = witTypes.Some[string](value132)
				default:
					panic("unreachable")
				}

				variant141 = golem_core_types.MakeSchemaValueNodeTextValue(golem_core_types.TextValuePayload{value131, option133})

			case 24:
				value134 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
				var option136 witTypes.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))) {
				case 0:

					option136 = witTypes.None[string]()
				case 1:
					value135 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))

					option136 = witTypes.Some[string](value135)
				default:
					panic("unreachable")
				}

				variant141 = golem_core_types.MakeSchemaValueNodeBinaryValue(golem_core_types.BinaryValuePayload{value134, option136})

			case 25:
				value137 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant141 = golem_core_types.MakeSchemaValueNodePathValue(value137)

			case 26:
				value138 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant141 = golem_core_types.MakeSchemaValueNodeUrlValue(value138)

			case 27:

				variant141 = golem_core_types.MakeSchemaValueNodeDatetimeValue(golem_core_types.Datetime{*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)))})

			case 28:

				variant141 = golem_core_types.MakeSchemaValueNodeDurationValue(golem_core_types.DurationValuePayload{*(*int64)(unsafe.Add(unsafe.Pointer(base), 8))})

			case 29:
				value139 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))))

				variant141 = golem_core_types.MakeSchemaValueNodeQuantityValueNode(golem_core_types.QuantityValue{*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)), *(*int32)(unsafe.Add(unsafe.Pointer(base), 16)), value139})

			case 30:
				value140 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant141 = golem_core_types.MakeSchemaValueNodeUnionValue(golem_core_types.UnionValuePayload{value140, *(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))})

			case 31:

				variant141 = golem_core_types.MakeSchemaValueNodeSecretValue(golem_core_types.SecretFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))))

			case 32:

				variant141 = golem_core_types.MakeSchemaValueNodeQuotaTokenHandle(golem_core_types.QuotaTokenFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))))

			default:
				panic("unreachable")
			}

			result142 = append(result142, variant141)
		}

		result147 = witTypes.Ok[golem_core_types.SchemaValueTree, golem_secrets_types.SecretError](golem_core_types.SchemaValueTree{result142, *(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))})
	case 1:
		var variant146 golem_secrets_types.SecretError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value143 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant146 = golem_secrets_types.MakeSecretErrorUnavailable(value143)

		case 1:
			value144 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant146 = golem_secrets_types.MakeSecretErrorVersionNotFound(golem_secrets_types.SecretVersion{value144})

		case 2:
			value145 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant146 = golem_secrets_types.MakeSecretErrorInternal(value145)

		default:
			panic("unreachable")
		}

		result147 = witTypes.Err[golem_core_types.SchemaValueTree, golem_secrets_types.SecretError](variant146)
	default:
		panic("unreachable")
	}
	result148 := result147
	return result148

}
