package rpc-grpc:api-caller;

interface rpc-grpc-api-caller-api {

  record output {
    name : string
  }
  
  unary-rpc: func() -> output;
  client-streaming-rpc: func() -> output;
  server-streaming-rpc: func() -> output;
  bidirectional-streaming-rpc: func() -> output;
  empty-unary-rpc: func() -> output;

}

world rpc-grpc-api-caller {
  export rpc-grpc-api-caller-api;
}