[config]
default_to_workspace = false

[tasks.add-stub-dependency-child-component-parent-component]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "child-component-stub/wit", "--dest-wit-root", "parent-component/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-child-component-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-parent-component]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/parent_component.wasm", "--stub-wasm", "target/wasm32-wasi/debug/child_component_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/parent_component_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-release-parent-component]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/parent_component.wasm", "--stub-wasm", "target/wasm32-wasi/release/child_component_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/parent_component_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-child-component-stub]
args = ["stubgen", "generate", "-s", "child-component/wit", "-d", "child-component-stub"]
command = "golem-cli"
cwd = "."

[tasks.post-build]
dependencies = ["compose-parent-component"]

[tasks.post-build-release]
dependencies = ["compose-release-parent-component"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-child-component-parent-component"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
