[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/golemcloud/brush",
    "https://github.com/golemcloud/coreutils",
    "https://github.com/golemcloud/jaq",
    "https://github.com/golemcloud/sed",
    "https://github.com/golemcloud/wit-bindgen",
    "https://github.com/uutils/diffutils",
]
