"""Edge inputs: every reachable error path. Missing files, directories where files are expected,
empty and not-a-directory paths, bad options and option arguments, missing and extra operands,
builtin misuse, expansion and redirection errors, and how errors propagate through pipelines,
substitutions and errexit.

GNU quotes some names with curly quotes under the oracle's UTF-8 locale where this shell (like GNU
without a locale) uses ASCII quotes; special_paths.py documents that as deliberate. Utility cases
therefore merge stderr into stdout and fold the curly quotes to ASCII, so everything else about
the diagnostic and the status is still compared. sed's and jq's diagnostics are documented to differ
in wording (sed.py, jq.py), so their cases compare the status only.

Generated from fixed tables with plain loops, so every Python 3 produces the same scripts.
"""

TIER = "sweep"
ERROR_PATHS = True

QUOTES = " 2>&1 | sed \"s/[‘’]/'/g\""


def util(script):
    """A utility error case: status and diagnostic on stdout, curly quotes folded."""
    return "{ " + script + "; echo \"status=$?\"; }" + QUOTES


def status_only(script):
    return script + " 2>/dev/null; echo \"status=$?\""


# Commands that read file operands: (label, command).
READERS = [
    ("cat", "cat"), ("head", "head"), ("tail", "tail"), ("wc", "wc"), ("sort", "sort"),
    ("uniq", "uniq"), ("cut", "cut -c1"), ("nl", "nl"), ("od", "od -c"), ("rev", "rev"),
    ("tac", "tac"), ("fold", "fold"), ("fmt", "fmt"), ("paste", "paste"), ("expand", "expand"),
    ("unexpand", "unexpand"), ("base64", "base64"), ("base32", "base32"),
    ("basenc", "basenc --base64"), ("md5sum", "md5sum"), ("sha256sum", "sha256sum"),
    ("cksum", "cksum"), ("grep", "grep x"), ("file", "file"), ("stat", "stat -c %n"),
    ("tsort", "tsort"), ("shuf", "shuf -n 1"), ("ls", "ls"), ("realpath", "realpath"),
    ("readlink -e", "readlink -e"), ("rm", "rm"), ("rmdir", "rmdir"), ("find", "find"),
    ("truncate", "truncate -s 0"), ("diff", "diff /dev/null"), ("cmp", "cmp /dev/null"),
    ("comm", "comm /dev/null"), ("join", "join /dev/null"), ("split", "split"),
    ("csplit", "csplit -s"), ("xargs -a", "xargs echo -a"),
]
KINDS = [
    ("missing file", "{c} /tmp/nosuch"),
    ("directory", "mkdir -p /tmp/d; {c} /tmp/d"),
    ("missing after a good file", "echo a > /tmp/f; {c} /tmp/f /tmp/nosuch"),
    ("empty name", "{c} ''"),
    ("path through a file", "echo a > /tmp/f; {c} /tmp/f/x"),
    ("bad short option", "{c} -@ /dev/null"),
    ("bad long option", "{c} --bogus-option /dev/null"),
]

CASES = []
for label, command in READERS:
    for kind, template in KINDS:
        CASES.append((f"edge errors: {label} {kind}", util(template.replace("{c}", command))))

# sed and jq: the same error kinds, compared by status only.
for label, command in [("sed", "sed p"), ("sed -i", "sed -i p"), ("jq", "jq .")]:
    for kind, template in KINDS:
        CASES.append((f"edge errors: {label} {kind}", status_only(template.replace("{c}", command))))

# Option arguments, operands and command-specific failures.
SPECIFIC = [
    ("head -n x", "head -n x /dev/null"),
    ("head -c x", "head -c x /dev/null"),
    ("head -n missing argument", "head -n"),
    ("head -c suffix", "head -c 1Q /dev/null"),
    ("tail -n x", "tail -n x /dev/null"),
    ("tail -c x", "tail -c x /dev/null"),
    ("tail -n missing argument", "tail -n"),
    ("wc --files0-from missing", "wc --files0-from=/tmp/nosuch"),
    ("wc --files0-from with operand", "wc --files0-from=/dev/null /dev/null"),
    ("sort -k 0", "sort -k 0 /dev/null"),
    ("sort -k x", "sort -k x /dev/null"),
    ("sort -k missing argument", "sort -k"),
    ("sort -t multi", "sort -t ab /dev/null"),
    ("sort -o missing argument", "sort -o"),
    ("sort --sort bogus", "sort --sort=bogus /dev/null"),
    ("sort -c disorder", "printf 'b\\na\\n' | sort -c"),
    ("sort -C disorder", "printf 'b\\na\\n' | sort -C"),
    ("sort -c -u duplicate", "printf 'a\\na\\n' | sort -c -u"),
    ("sort incompatible options", "sort -n -g /dev/null"),
    ("sort -o directory", "mkdir /tmp/d; echo a | sort -o /tmp/d"),
    ("uniq -f x", "uniq -f x /dev/null"),
    ("uniq -s x", "uniq -s x /dev/null"),
    ("uniq -w x", "uniq -w x /dev/null"),
    ("uniq extra operand", "uniq /dev/null /tmp/o /tmp/extra"),
    ("uniq output directory", "mkdir /tmp/d; uniq /dev/null /tmp/d"),
    ("cut no list", "cut /dev/null"),
    ("cut -c 0", "cut -c 0 /dev/null"),
    ("cut decreasing range", "cut -c 3-1 /dev/null"),
    ("cut -f x", "cut -f x /dev/null"),
    ("cut -d multi", "cut -d ab -f1 /dev/null"),
    ("cut two list types", "cut -b1 -c1 /dev/null"),
    ("cut -d with -c", "cut -d , -c1 /dev/null"),
    ("cut -s with -c", "cut -s -c1 /dev/null"),
    ("cut empty list", "cut -f '' /dev/null"),
    ("tr no operand", "tr"),
    ("tr one operand", "tr a"),
    ("tr extra operand", "tr a b c"),
    ("tr -d extra operand", "tr -d a b"),
    ("tr reversed range", "echo a | tr 'z-a' x"),
    ("tr bogus class", "echo a | tr '[:bogus:]' x"),
    ("tr class in string2", "echo a | tr a '[:upper:]'"),
    ("tr -s no operand", "tr -s"),
    ("tr repeat in string1", "echo a | tr '[a*]' b"),
    ("tr equivalence class", "echo a | tr '[=ab=]' x"),
    ("tr backslash at end", "echo a | tr 'a\\' x"),
    ("nl -v x", "nl -v x /dev/null"),
    ("nl -b bogus", "nl -b q /dev/null"),
    ("nl -i 0", "nl -i 0 /dev/null"),
    ("nl -w 0", "nl -w 0 /dev/null"),
    ("nl -n bogus", "nl -n xx /dev/null"),
    ("od -t bogus", "od -t z /dev/null"),
    ("od -N x", "od -N x /dev/null"),
    ("od -j x", "od -j x /dev/null"),
    ("od -A bogus", "od -A q /dev/null"),
    ("od -j past end", "echo abc | od -j 10"),
    ("od -w 0", "od -w0 /dev/null"),
    ("fold -w 0", "echo abc | fold -w 0"),
    ("fold -w x", "fold -w x /dev/null"),
    ("fmt -w x", "fmt -w x /dev/null"),
    ("fmt -w 0", "echo a | fmt -w 0"),
    ("fmt goal over width", "fmt -w 10 -g 20 /dev/null"),
    ("expand -t 0", "expand -t 0 /dev/null"),
    ("expand -t descending", "expand -t 3,2 /dev/null"),
    ("expand -t x", "expand -t x /dev/null"),
    ("unexpand -t 0", "unexpand -t 0 /dev/null"),
    ("base64 -d invalid", "echo '@@@' | base64 -d"),
    ("base64 -d bad padding", "echo 'YQ=' | base64 -d | od -An -c"),
    ("base64 -d -i", "echo 'Y@Q==' | base64 -d -i"),
    ("base64 -w x", "base64 -w x /dev/null"),
    ("base32 -d invalid", "echo '1111' | base32 -d"),
    ("basenc no encoding", "basenc /dev/null"),
    ("basenc two encodings", "echo a | basenc --base64 --base32"),
    ("basenc -d base16 odd", "echo abc | basenc -d --base16"),
    ("md5sum -c improper", "echo junk | md5sum -c"),
    ("md5sum -c mismatch", "echo x > /tmp/f; echo '00000000000000000000000000000000  /tmp/f' | md5sum -c"),
    ("md5sum -c unreadable", "echo 'd41d8cd98f00b204e9800998ecf8427e  /tmp/nosuch' | md5sum -c"),
    ("md5sum -c --quiet mismatch", "echo x > /tmp/f; echo '00000000000000000000000000000000  /tmp/f' | md5sum -c --quiet"),
    ("md5sum -c --status", "echo x > /tmp/f; echo '00000000000000000000000000000000  /tmp/f' | md5sum -c --status"),
    ("md5sum -c --strict", "echo x > /tmp/f; md5sum /tmp/f > /tmp/s; echo junk >> /tmp/s; md5sum -c --strict /tmp/s"),
    ("md5sum -c --warn", "echo x > /tmp/f; md5sum /tmp/f > /tmp/s; echo junk >> /tmp/s; md5sum -c -w /tmp/s"),
    ("md5sum -c --ignore-missing", "echo 'd41d8cd98f00b204e9800998ecf8427e  /tmp/nosuch' | md5sum -c --ignore-missing"),
    ("sha256sum -c mismatch", "echo x > /tmp/f; sha256sum /tmp/f | sed 's/^./0/' | sha256sum -c"),
    ("sha256sum --tag -c", "echo x > /tmp/f; sha256sum --tag /tmp/f | sed 's/= ./= 0/' | sha256sum -c"),
    ("cksum -a bogus", "cksum -a bogus /dev/null"),
    ("cksum --check without algorithm", "echo junk | cksum -c"),
    ("grep no pattern", "grep"),
    ("grep -E unmatched paren", "echo a | grep -E '('"),
    ("grep BRE unmatched group", "echo a | grep '\\('"),
    ("grep BRE unmatched brace", "echo a | grep 'a\\{1'"),
    ("grep unmatched bracket", "echo a | grep '['"),
    ("grep bogus class", "echo a | grep '[[:bogus:]]'"),
    ("grep class without brackets", "echo a | grep '[:space:]'"),
    ("grep trailing backslash", "echo a | grep 'a\\'"),
    ("grep -E bad interval", "echo a | grep -E 'a{2,1}'"),
    ("grep -P unmatched", "echo a | grep -P '('"),
    ("grep -P bad lookbehind", "echo a | grep -P '(?<=a+)b'"),
    ("grep -e missing argument", "grep -e"),
    ("grep -m x", "grep -m x a /dev/null"),
    ("grep -A x", "grep -A x a /dev/null"),
    ("grep -C negative", "grep -C -1 a /dev/null"),
    ("grep --binary-files bogus", "grep --binary-files=bogus a /dev/null"),
    ("grep --color bogus", "grep --color=bogus a /dev/null"),
    ("grep -f missing", "grep -f /tmp/nosuch /dev/null"),
    ("grep -s missing", "grep -s x /tmp/nosuch"),
    ("grep -q match and missing", "echo x > /tmp/f; grep -q x /tmp/nosuch /tmp/f"),
    ("grep -r missing", "grep -r x /tmp/nosuch"),
    ("grep -d skip directory", "mkdir /tmp/d; grep -d skip x /tmp/d"),
    ("grep -d bogus", "grep -d bogus x /dev/null"),
    ("grep -E and -F", "echo a | grep -E -F a"),
    ("grep -P and -E", "echo a | grep -P -E a"),
    ("seq no operand", "seq"),
    ("seq x", "seq x"),
    ("seq zero increment", "seq 1 0 5"),
    ("seq extra operand", "seq 1 2 3 4"),
    ("seq -f two directives", "seq -f '%d %d' 1"),
    ("seq -f no directive", "seq -f 'x' 1"),
    ("seq -f %s", "seq -f '%s' 1"),
    ("seq -w with -f", "seq -w -f '%g' 1"),
    ("seq nan", "seq nan"),
    ("seq -s missing argument", "seq -s"),
    ("expr no operand", "expr"),
    ("expr division by zero", "expr 1 / 0"),
    ("expr modulo by zero", "expr 1 % 0"),
    ("expr non-integer", "expr 1 + x"),
    ("expr unbalanced paren", "expr '(' 1"),
    ("expr missing argument", "expr 1 +"),
    ("expr bad regex", "expr a : '\\('"),
    ("expr syntax error", "expr 1 2"),
    ("expr zero result status", "expr 0 + 0"),
    ("expr empty result status", "expr '' : 'a'"),
    ("factor x", "factor x"),
    ("factor negative", "factor -- -1"),
    ("factor float", "factor 1.5"),
    ("numfmt x", "numfmt x"),
    ("numfmt --to bogus", "numfmt --to=bogus 1"),
    ("numfmt --from si bad suffix", "numfmt --from=si 1X"),
    ("numfmt --from none suffix", "numfmt 1K"),
    ("numfmt --field bogus", "numfmt --field=x 1"),
    ("numfmt --invalid ignore", "numfmt --invalid=ignore x 5"),
    ("numfmt --invalid warn", "numfmt --invalid=warn x 5"),
    ("sleep x", "sleep x"),
    ("sleep no operand", "sleep"),
    ("sleep negative", "sleep -1"),
    ("sleep bad suffix", "sleep 1q"),
    ("split -l 0", "split -l 0 /dev/null"),
    ("split -b x", "split -b x /dev/null"),
    ("split -n 0", "split -n 0 /dev/null"),
    ("split suffixes exhausted", "cd /tmp && seq 30 | split -a 1 -l 1"),
    ("split extra operand", "split /dev/null a b"),
    ("csplit missing pattern", "csplit /dev/null"),
    ("csplit out of range", "cd /tmp && seq 5 > f && csplit f 99"),
    ("csplit no match", "cd /tmp && seq 5 > f && csplit f /x/"),
    ("csplit bad repeat", "cd /tmp && seq 5 > f && csplit f 2 '{x}'"),
    ("csplit -k", "cd /tmp && seq 5 > f && csplit -k f 2 '{9}'; ls xx*"),
    ("mkdir existing", "mkdir /tmp/d; mkdir /tmp/d"),
    ("mkdir missing parent", "mkdir /tmp/a/b"),
    ("mkdir -p through a file", "echo x > /tmp/f; mkdir -p /tmp/f/g"),
    ("mkdir no operand", "mkdir"),
    ("mkdir -m bogus", "mkdir -m q /tmp/d"),
    ("mkdir existing file", "echo x > /tmp/f; mkdir /tmp/f"),
    ("mkdir one of two fails", "mkdir /tmp/ok /tmp/no/sub; ls -d /tmp/ok"),
    ("rmdir non-empty", "mkdir -p /tmp/d/e; rmdir /tmp/d"),
    ("rmdir file", "echo x > /tmp/f; rmdir /tmp/f"),
    ("rmdir -p stops", "mkdir -p /tmp/a/b; touch /tmp/a/f; rmdir -p /tmp/a/b"),
    ("rmdir --ignore-fail-on-non-empty", "mkdir -p /tmp/d/e; rmdir --ignore-fail-on-non-empty /tmp/d"),
    ("rmdir no operand", "rmdir"),
    ("rm directory without -r", "mkdir /tmp/d; rm /tmp/d"),
    ("rm -f missing", "rm -f /tmp/nosuch"),
    ("rm -r missing", "rm -r /tmp/nosuch"),
    ("rm no operand", "rm"),
    ("rm -f no operand", "rm -f"),
    ("rm -d non-empty", "mkdir -p /tmp/d/e; rm -d /tmp/d"),
    ("rm dot", "mkdir /tmp/d; cd /tmp/d; rm -r ."),
    ("rm dot-dot", "mkdir -p /tmp/d/e; cd /tmp/d/e; rm -r .."),
    ("rm trailing dot", "mkdir -p /tmp/d; rm -r /tmp/d/."),
    ("rm -v mixed", "echo x > /tmp/f; rm -v /tmp/f /tmp/nosuch"),
    ("cp missing source", "cp /tmp/nosuch /tmp/x"),
    ("cp directory without -r", "mkdir /tmp/d; cp /tmp/d /tmp/e"),
    ("cp into missing directory", "echo x > /tmp/f; cp /tmp/f /tmp/no/f"),
    ("cp same file", "echo x > /tmp/f; cp /tmp/f /tmp/f"),
    ("cp many to a file", "echo x > /tmp/f; echo y > /tmp/g; cp /tmp/f /tmp/g /tmp/h"),
    ("cp no operand", "cp"),
    ("cp one operand", "echo x > /tmp/f; cp /tmp/f"),
    ("cp -r into itself", "mkdir -p /tmp/d; cp -r /tmp/d /tmp/d/e"),
    ("cp file over directory", "echo x > /tmp/f; mkdir -p /tmp/d/f; cp /tmp/f /tmp/d"),
    ("cp directory over file", "mkdir /tmp/d; echo x > /tmp/f; cp -r /tmp/d /tmp/f"),
    ("cp -n existing", "echo x > /tmp/f; echo y > /tmp/g; cp -n /tmp/f /tmp/g; cat /tmp/g"),
    ("cp -t missing", "echo x > /tmp/f; cp -t /tmp/nosuch /tmp/f"),
    ("cp -T with directory", "echo x > /tmp/f; mkdir /tmp/d; cp -T /tmp/f /tmp/d"),
    ("mv missing source", "mv /tmp/nosuch /tmp/x"),
    ("mv into itself", "mkdir -p /tmp/d; mv /tmp/d /tmp/d/e"),
    ("mv same file", "echo x > /tmp/f; mv /tmp/f /tmp/f"),
    ("mv directory onto file", "mkdir /tmp/d; echo x > /tmp/f; mv /tmp/d /tmp/f"),
    ("mv file onto directory", "echo x > /tmp/f; mkdir -p /tmp/d/f/g; mv /tmp/f /tmp/d"),
    ("mv no operand", "mv"),
    ("mv one operand", "echo x > /tmp/f; mv /tmp/f"),
    ("mv many to a file", "echo x > /tmp/f; echo y > /tmp/g; mv /tmp/f /tmp/g /tmp/h"),
    ("mv -n existing", "echo x > /tmp/f; echo y > /tmp/g; mv -n /tmp/f /tmp/g; cat /tmp/f /tmp/g"),
    ("ln existing target", "echo x > /tmp/f; echo y > /tmp/g; ln /tmp/f /tmp/g"),
    ("ln -s existing target", "echo y > /tmp/g; ln -s f /tmp/g"),
    ("ln missing source", "ln /tmp/nosuch /tmp/l"),
    ("ln no operand", "ln"),
    ("ln directory hard link", "mkdir /tmp/d; ln /tmp/d /tmp/e"),
    ("ln into missing directory", "echo x > /tmp/f; ln -s f /tmp/no/l"),
    ("link extra operand", "link a b c"),
    ("link missing", "link /tmp/nosuch /tmp/l"),
    ("unlink missing", "unlink /tmp/nosuch"),
    ("unlink directory", "mkdir /tmp/d; unlink /tmp/d"),
    ("unlink no operand", "unlink"),
    ("touch missing parent", "touch /tmp/no/f"),
    ("touch no operand", "touch"),
    ("touch -d bogus", "touch -d bogus /tmp/f"),
    ("touch -r missing", "touch -r /tmp/nosuch /tmp/f"),
    ("touch -t bogus", "touch -t 12345 /tmp/f"),
    ("ls missing and present", "echo x > /tmp/f; ls /tmp/nosuch /tmp/f"),
    ("ls --sort bogus", "ls --sort=bogus /tmp"),
    ("ls -w x", "ls -w x /tmp"),
    ("ls --quoting-style bogus", "ls --quoting-style=bogus /tmp"),
    ("find -name missing argument", "find /tmp -name"),
    ("find unknown predicate", "find /tmp -bogus"),
    ("find -maxdepth x", "find /tmp -maxdepth x"),
    ("find -type bogus", "find /tmp -type z"),
    ("find -newer missing", "find /tmp -newer /tmp/nosuch"),
    ("find -exec unterminated", "find /tmp -exec echo"),
    ("find -exec plus not last", "find /tmp -exec echo {} x +"),
    ("find unbalanced paren", "find /tmp '('"),
    ("find -size x", "find /tmp -size x"),
    ("find -regextype bogus", "find /tmp -regextype bogus"),
    ("find -mindepth negative", "find /tmp -mindepth -1"),
    ("find path after expression", "find -name x /tmp"),
    ("find missing and present", "find /tmp/nosuch /tmp -maxdepth 0"),
    ("find -exec failing command", "find /tmp -maxdepth 0 -exec false \\;"),
    ("find -exec + failing command", "find /tmp -maxdepth 0 -exec false {} +"),
    ("find -delete non-empty", "mkdir -p /tmp/d/e; touch /tmp/d/e/f; find /tmp/d -maxdepth 1 -name e -delete"),
    ("xargs -n 0", "echo a | xargs -n 0"),
    ("xargs -n x", "echo a | xargs -n x"),
    ("xargs -a missing", "xargs -a /tmp/nosuch echo"),
    ("xargs command not found", "echo a | xargs nosuchcommand"),
    ("xargs command exits 3", "echo a | xargs sh -c 'exit 3'"),
    ("xargs -I missing argument", "echo a | xargs -I"),
    ("xargs -L x", "echo a | xargs -L x"),
    ("xargs -s too small", "echo aaaa | xargs -s 1 echo"),
    # xargs runs the command on what it read before reporting the quote and exiting, without
    # waiting for it: the command's output and xargs's error race, so they are kept apart.
    ("xargs unmatched single quote",
     "echo \"a 'b\" | xargs echo 2>/tmp/err; st=$?; cat /tmp/err; (exit $st)"),
    ("xargs unmatched double quote",
     "echo 'a \"b' | xargs echo 2>/tmp/err; st=$?; cat /tmp/err; (exit $st)"),
    ("xargs -d bad", "echo a | xargs -d ab echo"),
    ("xargs -E stops", "printf 'a\\nSTOP\\nb\\n' | xargs -E STOP echo"),
    ("diff missing", "diff /tmp/nosuch /dev/null"),
    ("diff both missing", "diff /tmp/nosuch /tmp/nosuch2"),
    ("diff -U x", "diff -U x /dev/null /dev/null"),
    ("diff no operand", "diff"),
    ("diff extra operand", "diff /dev/null /dev/null /dev/null"),
    ("diff directory and file", "mkdir /tmp/d; echo x > /tmp/f; diff /tmp/d /tmp/f"),
    ("diff -r missing in one", "mkdir -p /tmp/a /tmp/b; echo x > /tmp/a/f; diff -r /tmp/a /tmp/b"),
    ("diff -rN missing in one", "mkdir -p /tmp/a /tmp/b; echo x > /tmp/a/f; diff -rN /tmp/a /tmp/b"),
    ("cmp missing", "cmp /tmp/nosuch /dev/null"),
    ("cmp -n x", "cmp -n x /dev/null /dev/null"),
    ("cmp -i x", "cmp -i x /dev/null /dev/null"),
    ("cmp no operand", "cmp"),
    ("cmp -s differ", "echo a > /tmp/a; echo b > /tmp/b; cmp -s /tmp/a /tmp/b"),
    ("cmp EOF on shorter", "echo a > /tmp/a; echo ab > /tmp/b; cmp /tmp/a /tmp/b"),
    ("comm missing", "comm /tmp/nosuch /dev/null"),
    ("comm no operand", "comm"),
    ("comm one operand", "comm /dev/null"),
    ("comm unsorted", "printf 'b\\na\\n' > /tmp/a; comm /tmp/a /dev/null"),
    ("comm --check-order", "printf 'b\\na\\n' > /tmp/a; comm --check-order /tmp/a /dev/null"),
    ("comm --nocheck-order", "printf 'b\\na\\n' > /tmp/a; comm --nocheck-order /tmp/a /tmp/a"),
    ("join missing", "join /tmp/nosuch /dev/null"),
    ("join unsorted", "printf '2 a\\n1 b\\n' > /tmp/a; printf '1 x\\n2 y\\n' > /tmp/b; join /tmp/a /tmp/b"),
    ("join --check-order", "printf '2 a\\n1 b\\n' > /tmp/a; join --check-order /tmp/a /tmp/a"),
    ("join -1 0", "join -1 0 /dev/null /dev/null"),
    ("join -t multi", "join -t ab /dev/null /dev/null"),
    ("join -o bogus", "join -o x /dev/null /dev/null"),
    ("join no operand", "join"),
    ("paste -d empty", "printf 'a\\n' > /tmp/a; paste -d '' /tmp/a /tmp/a"),
    ("patch missing input", "patch -i /tmp/nosuch"),
    ("patch garbage", "cd /tmp && echo garbage | patch"),
    ("patch hunk fails", "cd /tmp && printf 'a\\n' > f && printf -- '--- f\\n+++ f\\n@@ -1 +1 @@\\n-z\\n+y\\n' | patch f; ls f*"),
    ("patch -p x", "cd /tmp && echo | patch -p x"),
    ("patch reversed", "cd /tmp && printf 'y\\n' > f && printf -- '--- f\\n+++ f\\n@@ -1 +1 @@\\n-x\\n+y\\n' | patch -N f; cat f"),
    ("patch missing target", "cd /tmp && printf -- '--- nosuch\\n+++ nosuch\\n@@ -1 +1 @@\\n-x\\n+y\\n' | patch -f"),
    ("patch --dry-run fail", "cd /tmp && printf 'a\\n' > f && printf -- '--- f\\n+++ f\\n@@ -1 +1 @@\\n-z\\n+y\\n' | patch --dry-run f; ls f*"),
    ("tee to directory", "echo x | tee /tmp"),
    ("tee to missing directory", "echo x | tee /tmp/no/f"),
    ("tee one of two fails", "echo x | tee /tmp/ok /tmp/no/f; cat /tmp/ok"),
    ("truncate no operand", "truncate -s 0"),
    ("truncate -s x", "truncate -s x /tmp/f"),
    ("truncate no size", "truncate /tmp/f"),
    ("truncate missing parent", "truncate -s 0 /tmp/no/f"),
    ("truncate -c missing", "truncate -c -s 0 /tmp/nosuch; ls /tmp"),
    ("truncate -r missing", "truncate -r /tmp/nosuch /tmp/f"),
    ("readlink missing", "readlink /tmp/nosuch"),
    ("readlink regular file", "echo x > /tmp/f; readlink /tmp/f"),
    ("readlink no operand", "readlink"),
    ("readlink -f missing parent", "readlink -f /tmp/no/f/g"),
    ("realpath -e missing", "realpath -e /tmp/nosuch"),
    ("realpath -m missing", "realpath -m /tmp/no/../x"),
    ("realpath no operand", "realpath"),
    ("dirname no operand", "dirname"),
    ("basename no operand", "basename"),
    ("basename extra operand", "basename a b c"),
    ("mktemp too few X", "mktemp /tmp/XX"),
    ("mktemp missing directory", "mktemp /tmp/nosuch/XXXXXX"),
    ("mktemp -p missing", "mktemp -p /tmp/nosuch"),
    ("mktemp suffix with slash", "mktemp --suffix=/x /tmp/aXXXXXX"),
    ("mktemp two templates", "mktemp /tmp/aXXXXXX /tmp/bXXXXXX"),
    ("stat missing", "stat /tmp/nosuch"),
    ("stat -c missing argument", "stat -c"),
    ("stat no operand", "stat"),
    ("stat --printf missing", "stat --printf '%n\\n' /tmp/nosuch"),
    ("date -d bogus", "date -d bogus"),
    ("date bad option", "date --bogus"),
    ("date two formats", "date +%Y +%m"),
    ("date -d with -r", "echo x > /tmp/f; date -d now -r /tmp/f"),
    ("env command not found", "env nosuchcommand"),
    ("env -u missing argument", "env -u"),
    ("env -C missing directory", "env -C /tmp/nosuch true"),
    ("env bad option", "env --bogus"),
    ("which missing", "which nosuchcommand"),
    ("file no operand", "file"),
    ("shuf -n x", "shuf -n x /dev/null"),
    ("shuf -i bogus", "shuf -i 5-1"),
    ("shuf -e -i", "shuf -e a -i 1-2"),
    ("tsort odd tokens", "echo a | tsort"),
    ("tsort cycle", "printf 'a b\\nb a\\n' | tsort"),
    ("cat directory then file", "mkdir /tmp/d; echo x > /tmp/f; cat /tmp/d /tmp/f"),
    ("head many missing", "head /tmp/n1 /tmp/n2"),
    ("wc missing and present", "echo x > /tmp/f; wc /tmp/f /tmp/nosuch"),
    ("sort missing and present", "echo x > /tmp/f; sort /tmp/f /tmp/nosuch"),
    ("tail missing and present", "echo x > /tmp/f; tail /tmp/nosuch /tmp/f"),
    ("od missing and present", "echo x > /tmp/f; od -c /tmp/f /tmp/nosuch"),
    ("printf utility missing format", "command printf"),
    ("yes to closed stdout", "yes >&-"),
    ("seq to closed stdout", "seq 3 >&-"),
    ("cat to closed stdout", "echo x | cat >&-"),
]
for label, script in SPECIFIC:
    CASES.append((f"edge errors: {label}", util(script)))

# sed and jq failures: status only.
STATUS_ONLY = [
    ("sed no script", "sed"),
    ("sed -n no script", "sed -n"),
    ("sed unmatched group", "echo a | sed 's/\\(/x/'"),
    ("sed -E unmatched paren", "echo a | sed -E 's/(/x/'"),
    ("sed unknown s option", "echo a | sed 's/a/b/z'"),
    ("sed unterminated address", "echo a | sed '/a'"),
    ("sed y length mismatch", "echo a | sed 'y/ab/c/'"),
    ("sed line zero", "echo a | sed '0p'"),
    ("sed unknown command", "echo a | sed 'k'"),
    ("sed missing command", "echo a | sed '1'"),
    ("sed unmatched brace", "echo a | sed '{p'"),
    ("sed unexpected brace", "echo a | sed 'p}'"),
    ("sed extra characters", "echo a | sed 'pq'"),
    ("sed undefined label", "echo a | sed 'b nowhere'"),
    ("sed bad back-reference", "echo a | sed 's/a/\\1/'"),
    ("sed -i no file", "sed -i p"),
    ("sed -i on a directory", "mkdir /tmp/d; sed -i p /tmp/d"),
    ("sed -f missing", "echo a | sed -f /tmp/nosuch"),
    ("sed w to missing directory", "echo a | sed 'w /tmp/no/f'"),
    ("sed r missing file", "echo a | sed 'r /tmp/nosuch'"),
    ("sed q exit code", "printf 'a\\nb\\n' | sed '1q5'"),
    ("sed Q exit code", "printf 'a\\nb\\n' | sed '2Q7'"),
    ("sed missing file continues", "echo x > /tmp/f; sed -n p /tmp/nosuch /tmp/f"),
    ("sed -s missing file", "echo x > /tmp/f; sed -s -n '$p' /tmp/f /tmp/nosuch"),
    ("jq no filter", "jq"),
    ("jq error builtin", "jq -n 'error(\"x\")'"),
    ("jq -e false", "jq -e -n 'false'"),
    ("jq -e null", "jq -e -n 'null'"),
    ("jq -e no output", "jq -e -n 'empty'"),
    ("jq --arg missing value", "jq -n --arg x"),
    ("jq undefined variable", "jq -n '$undefined'"),
    ("jq undefined function", "jq -n 'nosuchfn'"),
    ("jq division by zero", "jq -n '1 / 0'"),
    ("jq indent too large", "jq --indent 9 -n 1"),
    ("jq syntax error", "jq -n '.['"),
    ("jq index array with string", "echo '[1]' | jq '.a'"),
    ("jq invalid json", "echo '{' | jq ."),
    ("jq invalid json after value", "echo '1 }' | jq ."),
    ("jq error then continue", "printf '1\\n\"a\"\\n2\\n' | jq '. + 1'"),
    ("jq halt_error", "jq -n '\"bye\\n\" | halt_error(4)'"),
    ("jq halt", "jq -n 'halt'"),
    ("jq --argjson invalid", "jq -n --argjson v '{' '$v'"),
    ("jq --slurpfile missing", "jq -n --slurpfile v /tmp/nosuch '$v'"),
    ("jq -f missing", "jq -f /tmp/nosuch"),
    ("jq bad option", "jq --bogus ."),
    ("jq tonumber invalid", "jq -n '\"x\" | tonumber'"),
    ("jq keys on number", "jq -n '1 | keys'"),
    ("jq has on string", "jq -n '\"a\" | has(0)'"),
    ("jq implode invalid", "jq -n '[-1] | implode'"),
    ("jq @base64d invalid", "jq -rn '\"@@\" | @base64d'"),
    ("jq fromjson invalid", "jq -n '\"{\" | fromjson'"),
    ("jq limit negative", "jq -n '[limit(-1; 1, 2)]'"),
    ("jq -e last false", "jq -e -n '1, false'"),
]
for label, script in STATUS_ONLY:
    CASES.append((f"edge errors: {label}", status_only(script)))

# The shell's own errors: builtins, expansions and redirections. Bash words these itself, so
# stderr stays separate and exact.
SHELL = [
    ("cd missing", "cd /tmp/nosuch; echo $?"),
    ("cd file", "echo x > /tmp/f; cd /tmp/f; echo $?"),
    ("cd too many arguments", "cd /tmp /; echo $?; pwd"),
    ("cd bad option", "cd -Z; echo $?"),
    ("cd dash without OLDPWD", "cd -; echo $?"),
    ("cd -P missing", "cd -P /tmp/nosuch; echo $?"),
    ("cd CDPATH miss", "CDPATH=/tmp; cd nosuch; echo $?"),
    ("cd through a file", "echo x > /tmp/f; cd /tmp/f/x; echo $?"),
    ("pushd no other directory", "pushd; echo $?"),
    ("pushd index out of range", "pushd +5; echo $?"),
    ("pushd missing", "pushd /tmp/nosuch; echo $?"),
    ("pushd too many arguments", "pushd /tmp /; echo $?"),
    ("popd empty stack", "popd; echo $?"),
    ("popd index out of range", "popd +3; echo $?"),
    ("popd bad argument", "popd x; echo $?"),
    ("dirs index out of range", "dirs +9; echo $?"),
    ("dirs bad option", "dirs -Z; echo $?"),
    ("read bad descriptor", "read -u 9 x; echo $?"),
    ("read -n x", "read -n x v < /dev/null; echo $?"),
    ("read -t x", "read -t x v < /dev/null; echo $?"),
    ("read bad option", "read -Z v; echo $?"),
    ("read bad identifier", "read 1abc <<< x; echo $?"),
    ("read -a missing argument", "read -a; echo $?"),
    ("read -d missing argument", "read -d; echo $?"),
    ("read readonly variable", "readonly r=1; read r <<< 2; echo $? $r"),
    ("read from a directory", "read x < /tmp; echo $?"),
    ("read -u non-number", "read -u x v; echo $?"),
    ("mapfile bad descriptor", "mapfile -u 9 a; echo $?"),
    ("mapfile -n x", "mapfile -n x a < /dev/null; echo $?"),
    ("mapfile bad option", "mapfile -Z a; echo $?"),
    ("mapfile bad identifier", "mapfile 1x < /dev/null; echo $?"),
    ("mapfile -C missing argument", "mapfile -C; echo $?"),
    ("mapfile readonly array", "readonly -a ro=(1); mapfile ro <<< x; echo $?"),
    ("mapfile -O x", "mapfile -O x a < /dev/null; echo $?"),
    ("source no argument", "source; echo $?"),
    ("source missing", "source /tmp/nosuch; echo $?"),
    ("source directory", ". /tmp; echo $?"),
    ("source syntax error", "printf 'echo in\\nif then\\n' > /tmp/s; . /tmp/s; echo $?"),
    ("source returns status", "echo 'return 4' > /tmp/s; . /tmp/s; echo $?"),
    ("source exit", "echo 'exit 5' > /tmp/s; . /tmp/s; echo not-reached"),
    ("shift too many", "set -- a b; shift 5; echo $? $#"),
    ("shift non-number", "shift x; echo $?"),
    ("shift negative", "shift -1; echo $?"),
    ("shift_verbose", "shopt -s shift_verbose; set -- a; shift 3; echo $?"),
    ("set bad option", "set -Z; echo $?"),
    ("set -o bogus", "set -o bogus; echo $?"),
    ("set +o bogus", "set +o bogus; echo $?"),
    ("shopt -s bogus", "shopt -s bogus; echo $?"),
    ("shopt bad option", "shopt -Z; echo $?"),
    ("shopt query bogus", "shopt bogus; echo $?"),
    ("shopt -s and -u", "shopt -s -u extglob; echo $?"),
    ("declare bad option", "declare -Z x; echo $?"),
    ("declare bad identifier", "declare 1x=2; echo $?"),
    ("declare assoc to indexed", "declare -A a; declare -a a; echo $?"),
    ("declare indexed to assoc", "declare -a a; declare -A a; echo $?"),
    ("declare readonly reassign", "readonly x=1; declare x=2; echo $? $x"),
    ("declare -p missing", "declare -p nosuch; echo $?"),
    ("declare -f missing", "declare -f nosuch; echo $?"),
    ("declare -F missing", "declare -F nosuch; echo $?"),
    ("declare nameref to itself", "declare -n r=r; echo $?"),
    ("declare nameref bad name", "declare -n r='1x'; echo $?"),
    ("declare +r", "readonly x=1; declare +r x; echo $?"),
    ("local outside function", "local x=1; echo $?"),
    ("local bad identifier", "f() { local 1x=2; echo $?; }; f"),
    ("export bad identifier", "export 1x; echo $?"),
    ("export -f not a function", "export -f nosuch; echo $?"),
    ("export bad option", "export -Z; echo $?"),
    ("export -n missing", "export -n nosuch; echo $?"),
    ("readonly assignment", "readonly r=1; r=2; echo $? $r"),
    ("readonly unset", "readonly r=1; unset r; echo $?"),
    ("readonly -f missing", "readonly -f nosuch; echo $?"),
    ("readonly in arithmetic", "readonly r=1; (( r++ )); echo $? $r"),
    ("readonly in for", "readonly r=1; for r in 2; do :; done; echo $? $r"),
    ("readonly array element", "readonly -a a=(1 2); a[0]=5; echo $? ${a[0]}"),
    ("readonly assignment prefix", "readonly r=1; r=2 true; echo $?"),
    ("unset bad option", "unset -Z x; echo $?"),
    ("unset bad identifier", "unset 1x; echo $?"),
    ("unset -f missing", "unset -f nosuch; echo $?"),
    ("unset -v readonly", "readonly r=1; unset -v r; echo $?"),
    ("unset -f and -v", "unset -f -v x; echo $?"),
    ("unset bad subscript", "a=(1); unset 'a[x'; echo $?"),
    ("alias missing", "alias nosuch; echo $?"),
    ("alias bad option", "alias -Z; echo $?"),
    ("alias bad name", "alias 'a b=c'; echo $?"),
    ("unalias missing", "unalias nosuch; echo $?"),
    ("unalias no argument", "unalias; echo $?"),
    ("unalias -a nothing", "unalias -a; echo $?"),
    ("type missing", "type nosuch; echo $?"),
    ("type bad option", "type -Z ls; echo $?"),
    ("type -t missing", "type -t nosuch; echo $?"),
    ("type -P missing", "type -P nosuch; echo $?"),
    ("type mixed", "type echo nosuch; echo $?"),
    ("command -v missing", "command -v nosuch; echo $?"),
    ("command -V missing", "command -V nosuch; echo $?"),
    ("command missing", "command nosuch; echo $?"),
    ("command bad option", "command -Z ls; echo $?"),
    ("hash missing", "hash nosuch; echo $?"),
    ("hash -d missing", "hash -d nosuch; echo $?"),
    ("hash -t missing", "hash -t nosuch; echo $?"),
    ("hash empty", "hash; echo $?"),
    ("hash bad option", "hash -Z; echo $?"),
    ("kill no argument", "kill; echo $?"),
    ("kill bad signal", "kill -BOGUS 1; echo $?"),
    ("kill -s bogus", "kill -s BOGUS 1; echo $?"),
    ("kill no such job", "kill %1; echo $?"),
    ("kill no such process", "kill 999999; echo $?"),
    ("kill -l bogus number", "kill -l 999; echo $?"),
    ("kill -l bogus name", "kill -l BOGUS; echo $?"),
    ("kill non-number", "kill abc; echo $?"),
    ("kill -0 missing", "kill -0 999999; echo $?"),
    ("kill -s missing argument", "kill -s; echo $?"),
    ("wait no such job", "wait %1; echo $?"),
    ("wait not a child", "wait 999999; echo $?"),
    ("wait bad option", "wait -Z; echo $?"),
    ("wait -n without jobs", "wait -n; echo $?"),
    ("wait non-number", "wait abc; echo $?"),
    ("jobs no such job", "jobs %1; echo $?"),
    ("jobs bad option", "jobs -Z; echo $?"),
    ("disown no such job", "disown %1; echo $?"),
    ("disown without jobs", "disown; echo $?"),
    ("trap bad signal", "trap 'echo x' BOGUS; echo $?"),
    ("trap bad option", "trap -Z; echo $?"),
    ("trap -p bad signal", "trap -p BOGUS; echo $?"),
    ("trap signal number out of range", "trap 'echo x' 999; echo $?"),
    ("trap missing action", "trap EXIT; echo $?"),
    ("let no expression", "let; echo $?"),
    ("let syntax error", "let '1+'; echo $?"),
    ("let division by zero", "let 'x=1/0'; echo $?"),
    ("let zero status", "let 0; echo $?"),
    ("arith command division by zero", "(( 1 / 0 )); echo $?"),
    ("arith command syntax error", "(( 1 + )); echo $?"),
    ("arith value too great for base", "echo $(( 08 )); echo after"),
    ("arith invalid digit for base", "echo $(( 2#12 )); echo after"),
    ("arith invalid base", "echo $(( 99#1 )); echo after"),
    ("arith incomplete conditional", "echo $(( 1 ? 2 )); echo after"),
    ("arith assignment to non-variable", "echo $(( 1 = 2 )); echo after"),
    ("arith negative exponent", "echo $(( 2 ** -1 )); echo after"),
    ("arith recursion", "a=a; echo $(( a )); echo after"),
    ("arith bad variable value", "x='1 +'; echo $(( x )); echo after"),
    ("arith bad operator", "echo $(( 1 @ 2 )); echo after"),
    ("arith in subshell keeps going", "( echo $(( 1 / 0 )) ); echo status=$?"),
    ("arith in if", "if (( 1 / 0 )); then echo yes; else echo no; fi; echo after"),
    ("arith for bad expression", "for (( i = 0; i < ; i++ )); do echo $i; done; echo status=$?"),
    ("arith array bad subscript", "a[1/0]=1; echo $?"),
    ("printf no format", "printf; echo $?"),
    ("printf invalid number", "printf '%d\\n' abc; echo $?"),
    ("printf trailing garbage", "printf '%d\\n' 1a; echo $?"),
    ("printf invalid format character", "printf '%z\\n' 1; echo $?"),
    ("printf -v bad identifier", "printf -v 1x x; echo $?"),
    ("printf bad width argument", "printf '%*d\\n' x 1; echo $?"),
    ("printf empty number", "printf '%d\\n' ''; echo $?"),
    ("printf out of range", "printf '%d\\n' 99999999999999999999; echo $?"),
    ("printf invalid float", "printf '%f\\n' abc; echo $?"),
    ("printf missing precision digits", "printf '%.d|\\n' 5; echo $?"),
    ("printf unterminated escape", "printf '\\x\\n'; echo $?"),
    ("printf %b bad escape", "printf '%b\\n' '\\q'; echo $?"),
    ("printf more arguments than format", "printf '%s\\n' a b c; echo $?"),
    ("printf format without directives reused", "printf 'x\\n' a b; echo $?"),
    ("printf %c empty", "printf '[%c]\\n' ''; echo $?"),
    ("printf bad option", "printf -Z x; echo $?"),
    ("printf %n", "printf 'a%nb\\n' x; echo $?"),
    ("test integer expected", "[ 1 -eq x ]; echo $?"),
    ("test missing bracket", "[ a = a; echo $?"),
    ("test binary operator expected", "[ a b c ]; echo $?"),
    ("test unary operator expected", "[ -Q a ]; echo $?"),
    ("test too many arguments", "[ a = b = c ]; echo $?"),
    ("test missing argument", "[ 1 -gt ]; echo $?"),
    ("test extra closing paren", "[ a ')' ]; echo $?"),
    ("test integer overflow", "[ 99999999999999999999 -eq 1 ]; echo $?"),
    ("test -nt missing", "[ /tmp/nosuch -nt /tmp ]; echo $?"),
    ("test builtin extra argument", "test a b; echo $?"),
    ("cond integer from string", "[[ x -eq 0 ]]; echo $?"),
    ("cond bad regex", "[[ a =~ ( ]]; echo $?"),
    ("cond bad regex bracket", "re='['; [[ a =~ $re ]]; echo $?"),
    ("cond arithmetic error", "[[ 1/0 -eq 1 ]]; echo $?"),
    ("exit non-number", "exit abc"),
    ("exit too many arguments", "exit 1 2; echo still-running $?"),
    ("exit negative", "exit -1"),
    ("exit 256", "exit 256"),
    ("exit large", "exit 99999999999"),
    ("return outside function", "return 3; echo $?"),
    ("return non-number", "f() { return abc; }; f; echo $?"),
    ("return too many arguments", "f() { return 1 2; }; f; echo $?"),
    ("return 256", "f() { return 256; }; f; echo $?"),
    ("return negative", "f() { return -1; }; f; echo $?"),
    ("break outside loop", "break; echo $?"),
    ("break zero", "for i in 1; do break 0; done; echo $?"),
    ("break non-number", "for i in 1; do break x; done; echo $?"),
    ("break too many levels", "for i in 1 2; do break 5; done; echo $? $i"),
    ("continue outside loop", "continue; echo $?"),
    ("continue in function outside loop", "f() { continue; }; for i in 1 2; do f; echo $i; done"),
    ("getopts no arguments", "getopts; echo $?"),
    ("getopts one argument", "getopts ab; echo $?"),
    ("getopts illegal option", "set -- -z; getopts ab o; echo \"$? $o [$OPTARG]\""),
    ("getopts missing argument", "set -- -a; getopts a: o; echo \"$? $o [$OPTARG]\""),
    ("getopts silent illegal", "set -- -z; getopts :ab o; echo \"$? $o [$OPTARG]\""),
    ("getopts silent missing", "set -- -a; getopts :a: o; echo \"$? $o [$OPTARG]\""),
    ("getopts OPTERR off", "OPTERR=0; set -- -z; getopts ab o; echo \"$? $o\""),
    ("getopts bad variable name", "set -- -a; getopts a 1x; echo $?"),
    ("eval syntax error", "eval 'if'; echo $?"),
    ("eval unexpected token", "eval ')'; echo $?"),
    ("eval error in the middle", "eval 'echo a; ) ; echo b'; echo $?"),
    ("exec missing command", "exec nosuchcommand; echo not-reached"),
    ("exec missing path", "exec /tmp/nosuch; echo not-reached"),
    ("builtin not a builtin", "builtin nosuch; echo $?"),
    ("builtin not a builtin utility", "builtin ls; echo $?"),
    ("enable not a builtin", "enable nosuch; echo $?"),
    ("caller outside function", "caller; echo $?"),
    ("caller non-number", "f() { caller x; echo $?; }; f"),
    ("compgen bad option", "compgen -Z; echo $?"),
    ("compgen bad action", "compgen -A bogus; echo $?"),
    ("compgen no match", "compgen -c nosuchprefixzz; echo $?"),
    ("times extra argument", "times x > /dev/null; echo $?"),
    ("true with arguments", "true --bogus; echo $?; false --bogus; echo $?"),
    ("echo to closed stdout", "echo x >&- 2>/dev/null; echo $? >&2"),
    ("pwd bad option", "pwd -Z; echo $?"),
    ("pwd extra argument", "pwd extra; echo $?"),
    # Expansions.
    ("unset variable colon question", "echo ${nope:?is missing}; echo not-reached"),
    ("unset variable question", "echo ${nope?}; echo not-reached"),
    ("empty variable colon question", "x=; echo ${x:?}; echo not-reached"),
    ("question in subshell", "( : ${nope:?gone} ); echo status=$?"),
    ("question in command substitution", "x=$(: ${nope:?gone}); echo status=$?"),
    ("question in function", "f() { : ${1:?need an argument}; }; f; echo not-reached"),
    ("indirect unset", "echo \"[${!nope}]\"; echo $?"),
    ("indirect invalid name", "x='a b'; echo ${!x}; echo $?"),
    ("substring negative length", "x=abc; echo ${x:1:-5}; echo after"),
    ("substring bad expression", "x=abc; echo ${x:1+}; echo after"),
    ("bad substitution", "echo ${x!}; echo after"),
    ("bad substitution in quotes", "echo \"${x:}\"; echo after"),
    ("bad substitution operator", "echo ${x@Z}; echo after"),
    ("nounset variable", "set -u; echo $nope; echo not-reached"),
    ("nounset positional", "set -u; echo $3; echo not-reached"),
    ("nounset array element", "set -u; a=(); echo ${a[5]}; echo not-reached"),
    ("nounset at sign", "set -u; set --; echo \"[$@]\"; echo reached"),
    ("nounset default", "set -u; echo ${nope-default}; echo reached"),
    ("nounset length", "set -u; echo ${#nope}; echo not-reached"),
    ("nounset in arithmetic", "set -u; echo $(( nope + 1 )); echo not-reached"),
    ("bad array subscript", "declare -A m; m[]=x; echo $?"),
    ("negative array index", "a=(1 2); a[-5]=x; echo $?"),
    ("negative array index read", "a=(1 2); echo \"[${a[-5]}]\"; echo $?"),
    ("assoc assignment without subscript", "declare -A m; m=(x); echo $? ${#m[@]}"),
    ("failglob", "shopt -s failglob; echo /tmp/nomatch*; echo status=$?"),
    ("failglob in for", "shopt -s failglob; for f in /tmp/nomatch*; do echo $f; done; echo status=$?"),
    ("brace expansion bad range", "echo {1..x} {a..1} {1..2..0}"),
    ("tilde unknown user", "echo ~nosuchuser"),
    ("command substitution status", "x=$(exit 7); echo $?"),
    ("command substitution missing command", "x=$(nosuchcommand); echo $? [$x]"),
    ("assignment status from substitution", "x=$(false) y=1; echo $?"),
    ("process substitution failing", "cat <(exit 3); echo $?"),
    # Redirections.
    ("redirect to a directory", "echo x > /tmp; echo $?"),
    ("append to a directory", "echo x >> /tmp; echo $?"),
    ("redirect into a missing directory", "echo x > /tmp/no/f; echo $?"),
    ("redirect from missing", "cat < /tmp/nosuch; echo $?"),
    ("redirect from a directory", "cat < /tmp; echo $?"),
    ("redirect to empty name", "echo x > ''; echo $?"),
    ("ambiguous redirect empty", "x=; echo x > $x; echo $?"),
    ("ambiguous redirect words", "x='a b'; echo x > $x; echo $?"),
    ("ambiguous redirect glob", "touch /tmp/g1 /tmp/g2; echo x > /tmp/g*; echo $?"),
    ("redirect bad descriptor", "echo x >&9; echo $?"),
    ("redirect read bad descriptor", "cat <&9; echo $?"),
    ("redirect closed descriptor read", "exec 3<&-; read -u 3 x; echo $?"),
    ("redirect descriptor out of range", "echo x >&99999999999; echo $?"),
    ("redirect descriptor word", "echo x >&abc; echo $?"),
    ("noclobber existing", "echo a > /tmp/f; set -C; echo b > /tmp/f; echo $?; cat /tmp/f"),
    ("noclobber force", "echo a > /tmp/f; set -C; echo b >| /tmp/f; cat /tmp/f"),
    ("noclobber both", "echo a > /tmp/f; set -C; echo b &> /tmp/f; echo $?"),
    ("noclobber null", "set -C; echo b > /dev/null; echo $?"),
    ("redirect failure skips command", "echo ran > /tmp/marker < /tmp/nosuch; ls /tmp"),
    ("redirect failure in pipeline", "echo a | cat < /tmp/nosuch | wc -l; echo ${PIPESTATUS[@]}"),
    ("redirect failure on group", "{ echo in; } > /tmp/no/f; echo $?"),
    ("redirect failure on while", "while false; do :; done < /tmp/nosuch; echo $?"),
    ("redirect failure on function", "f() { echo in; }; f > /tmp/no/f; echo $?"),
    ("redirect failure with errexit", "set -e; echo x > /tmp/no/f; echo not-reached"),
    ("redirect failure on special builtin", "set -o posix; : > /tmp/no/f; echo reached"),
    ("fd variable bad", "exec {fd}>&-; echo $?"),
    ("fd variable readonly", "readonly fd=1; exec {fd}> /tmp/o; echo $?"),
    ("here string to closed stdin reader", "read -u 0 x <&- <<< v; echo $?"),
    # Commands that cannot be found or run.
    ("command not found", "nosuchcommand; echo $?"),
    ("command not found with slash", "./nosuch; echo $?"),
    ("absolute command not found", "/tmp/nosuch/cmd; echo $?"),
    ("directory as command", "/tmp; echo $?"),
    ("empty command name", "''; echo $?"),
    ("empty command from variable", "x=; $x; echo $?"),
    ("command not found in pipeline", "nosuchcommand | cat; echo ${PIPESTATUS[@]}"),
    ("command not found in substitution", "echo \"[$(nosuchcommand 2>&1)]\""),
    ("command not found with empty PATH", "PATH=; nosuchcommand; echo $?"),
    ("command not found handler", "command_not_found_handle() { echo \"handled $1\"; return 9; }; nosuchcommand arg; echo $?"),
    ("reserved word as command", "then; echo $?"),
    ("function named like a path", "f/g() { echo x; }; echo $?"),
    # Propagation.
    ("pipestatus of failures", "cat /tmp/nosuch | wc -l | false; echo ${PIPESTATUS[@]}"),
    ("pipefail picks last failure", "set -o pipefail; (exit 2) | (exit 3) | true; echo $?"),
    ("errexit in command substitution assignment", "set -e; x=$(false); echo not-reached"),
    ("errexit in command substitution argument", "set -e; echo \"[$(false)]\"; echo reached"),
    ("errexit in pipeline head", "set -e; false | true; echo reached"),
    ("errexit negated", "set -e; ! true; echo reached"),
    ("errexit in or-list function", "set -e; f() { false; echo in-f; }; f || echo handled"),
    ("errexit in subshell", "set -e; (false); echo not-reached"),
    ("errexit in and-list", "set -e; false && true; echo reached"),
    ("errexit in while condition", "set -e; while false; do :; done; echo reached"),
    ("errexit local assignment", "set -e; f() { local x=$(false); echo in-f; }; f"),
    ("errexit inherit substitution", "set -e; shopt -s inherit_errexit; echo \"[$(false; echo x)]\"; echo reached"),
    ("errexit no inherit substitution", "set -e; echo \"[$(false; echo x)]\"; echo reached"),
    ("errexit trap ERR", "set -e; trap 'echo trapped $?' ERR; false; echo not-reached"),
    ("errtrace in function", "set -E; trap 'echo trapped' ERR; f() { false; }; f; echo after"),
    ("ERR trap not inherited", "trap 'echo trapped' ERR; f() { false; }; f; echo after"),
    ("errexit with arithmetic zero", "set -e; (( 0 )); echo not-reached"),
    ("errexit with let zero", "set -e; let 0; echo not-reached"),
    ("errexit with test in if", "set -e; if [ 1 -eq 2 ]; then :; fi; echo reached"),
    ("errexit last command of list", "set -e; true && false; echo not-reached"),
]
for label, script in SHELL:
    CASES.append((f"edge errors shell: {label}", script))

# Divergences that are decisions, not bugs.
ALL_OR_NOTHING = "fixture: bash-tool's documented all-or-nothing handling of syntax errors (README) runs nothing of a sourced file with a syntax error, where bash runs the commands before it as it reads them; the same decision as ALL_OR_NOTHING in refusals.py"
EXPECTED = {
    'edge errors shell: source syntax error': (
        0, b'2\n', b"/tmp/s: line 2: syntax error near unexpected token `then'\n/tmp/s: line 2: `if then'\n",
        ALL_OR_NOTHING,
    ),
}
