"""Edge inputs: separate calls split at `#--call-- DIR` markers. Only the working directory crosses
calls; each case changes it (or fails to) a different way, or checks that some other state does
not carry, or carries state the supported way, through files.

Every marker names the directory Bash ends the previous call in.
"""

TIER = "sweep"
TAGS = ["state.cross-call"]

M = "\n#--call--\n"


def IN(directory):
    return f"\n#--call-- {directory}\n"


W = "mkdir -p /tmp/w/x; "

CASES = [
    # How the directory changes in the first call, and whether it carries.
    ("edge calls: cd relative from root", W + "cd tmp/w" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd dot-dot", W + "cd /tmp/w/x && cd .." + IN("/tmp/w") + "pwd"),
    ("edge calls: cd dash", W + "cd /tmp/w; cd /; cd -" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in a subshell does not carry", W + "(cd /tmp/w)" + M + "pwd"),
    ("edge calls: cd in a pipeline stage does not carry", W + "cd /tmp/w | true" + M + "pwd"),
    ("edge calls: cd in a function carries", W + "f() { cd /tmp/w; }; f" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in command substitution does not carry", W + "x=$(cd /tmp/w; pwd); echo $x" + M + "pwd"),
    ("edge calls: cd through eval carries", W + "eval 'cd /tmp/w'" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in a sourced file carries", W + "echo 'cd /tmp/w' > /tmp/s; . /tmp/s" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in the EXIT trap", W + "trap 'cd /tmp/w' EXIT; echo body" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in the ERR trap", W + "trap 'cd /tmp/w' ERR; false; echo after" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd then exit in a function", W + "f() { cd /tmp/w; exit 4; }; f" + IN("/tmp/w") + "echo $?; pwd"),
    ("edge calls: cd then errexit", W + "set -e; cd /tmp/w; false; cd /" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd then nounset failure", W + "set -u; cd /tmp/w; echo $nope; cd /" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd then exec", W + "cd /tmp/w; exec true" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd then command not found", W + "cd /tmp/w; nosuchcommand" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd then parameter error", W + "cd /tmp/w; : ${v:?unset}; cd /" + IN("/tmp/w") + "pwd"),
    ("edge calls: failed cd stays", "cd /nosuch" + M + "pwd"),
    ("edge calls: cd to a file stays", "echo x > /tmp/f; cd /tmp/f" + M + "pwd"),
    ("edge calls: cd with no HOME stays", W + "cd /tmp/w; cd" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd empty argument", W + "cd /tmp/w; cd ''; echo $?" + IN("/tmp/w") + "pwd"),
    ("edge calls: pushd carries", W + "pushd /tmp/w >/dev/null" + IN("/tmp/w") + "pwd; dirs"),
    ("edge calls: pushd then popd", W + "cd /tmp; pushd /tmp/w >/dev/null; popd >/dev/null" + IN("/tmp") + "pwd"),
    ("edge calls: CDPATH lookup carries", "mkdir -p /tmp/c/sub; CDPATH=/tmp/c; cd sub" + IN("/tmp/c/sub") + "pwd"),
    ("edge calls: CDPATH does not carry", "mkdir -p /tmp/c/sub; CDPATH=/tmp/c" + M + "cd sub; echo $?; pwd"),
    ("edge calls: cd -P through a symlink", "mkdir /tmp/real; ln -s real /tmp/link; cd -P /tmp/link" + IN("/tmp/real") + "pwd"),
    ("edge calls: cd through a symlink then pwd -P", "mkdir /tmp/real; ln -s real /tmp/link; cd /tmp/link; pwd" + IN("/tmp/link") + "pwd -P"),
    ("edge calls: cd symlink dot-dot logical", "mkdir -p /tmp/a/b; ln -s a/b /tmp/l; cd /tmp/l/..; pwd" + IN("/tmp") + "pwd"),
    ("edge calls: cd -P symlink dot-dot", "mkdir -p /tmp/a/b; ln -s a/b /tmp/l; cd -P /tmp/l/..; pwd" + IN("/tmp/a") + "pwd"),
    ("edge calls: cd unicode directory", "mkdir -p '/tmp/日本/é'; cd '/tmp/日本/é'" + IN("/tmp/日本/é") + "pwd; ls .."),
    ("edge calls: cd directory with spaces", "mkdir -p '/tmp/a b/c d'; cd '/tmp/a b/c d'" + IN("/tmp/a b/c d") + "pwd; echo \"$PWD\""),
    ("edge calls: cd directory with glob characters", "mkdir -p '/tmp/[x]*'; cd '/tmp/[x]*'" + IN("/tmp/[x]*") + "pwd; ls -d ../*"),
    ("edge calls: cd trailing slash", W + "cd /tmp/w/" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd dot components", W + "cd /tmp/w/../w/./x/.." + IN("/tmp/w") + "pwd"),
    ("edge calls: cd dot-dot at root", "cd /..; pwd" + M + "pwd"),
    ("edge calls: cd double slash", "cd //; pwd; cd ///tmp; pwd" + IN("/tmp") + "pwd"),
    ("edge calls: cd deep", "d=/tmp$(printf '/d%.0s' $(seq 30)); mkdir -p $d; cd $d" + IN("/tmp" + "/d" * 30) + "pwd | wc -c"),
    ("edge calls: command cd carries", W + "command cd /tmp/w" + IN("/tmp/w") + "pwd"),
    ("edge calls: builtin cd carries", W + "builtin cd /tmp/w" + IN("/tmp/w") + "pwd"),
    ("edge calls: sh -c cd does not carry", W + "sh -c 'cd /tmp/w; pwd'" + M + "pwd"),
    ("edge calls: bash -c cd does not carry", W + "bash -c 'cd /tmp/w'" + M + "pwd"),
    ("edge calls: find -exec cd does not carry", W + "find /tmp/w -maxdepth 0 -exec sh -c 'cd \"$1\"' sh {} \\;" + M + "pwd"),
    ("edge calls: xargs cd does not carry", W + "echo /tmp/w | xargs sh -c 'cd \"$0\"'" + M + "pwd"),
    ("edge calls: cd in a while pipeline does not carry", W + "echo /tmp/w | while read -r d; do cd \"$d\"; done" + M + "pwd"),
    ("edge calls: cd in lastpipe carries", W + "shopt -s lastpipe; echo /tmp/w | while read -r d; do cd \"$d\"; done" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in process substitution does not carry", W + "cat <(cd /tmp/w; pwd)" + M + "pwd"),
    ("edge calls: cd in a background job does not carry", W + "cd /tmp/w & wait" + M + "pwd"),
    ("edge calls: cd in a brace group carries", W + "{ cd /tmp/w; }" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in an if condition", W + "if cd /tmp/w; then :; fi" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in a for loop", "mkdir -p /tmp/a/b/c; for d in /tmp/a /tmp/a/b /tmp/a/b/c; do cd $d; done" + IN("/tmp/a/b/c") + "pwd"),
    ("edge calls: cd in a case arm", W + "case x in x) cd /tmp/w;; esac" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd in and-list after failure", W + "false && cd /tmp/w" + M + "pwd"),
    ("edge calls: cd in or-list after failure", W + "false || cd /tmp/w" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd with redirection", W + "cd /tmp/w > /dev/null 2>&1" + IN("/tmp/w") + "pwd"),
    ("edge calls: cd with a failing redirection", W + "cd /tmp/w > /nosuch/f" + M + "pwd"),
    ("edge calls: assigning PWD does not move", W + "PWD=/tmp/w" + M + "pwd; echo \"$PWD\""),
    ("edge calls: assigning PWD after cd", W + "cd /tmp/w; PWD=/" + IN("/tmp/w") + "pwd"),
    ("edge calls: unset PWD after cd", W + "cd /tmp/w; unset PWD" + IN("/tmp/w") + "pwd"),
    ("edge calls: readonly PWD", W + "cd /tmp; readonly PWD; cd /tmp/w; echo $?" + IN("/tmp/w") + "pwd"),
    ("edge calls: OLDPWD assignment then cd dash", W + "OLDPWD=/tmp/w; cd - > /dev/null" + IN("/tmp/w") + "pwd"),
    ("edge calls: exit in a subshell keeps cd", W + "cd /tmp/w; (exit 4); echo $?" + IN("/tmp/w") + "pwd"),
    ("edge calls: return at top level", W + "cd /tmp/w; return 3; echo after" + IN("/tmp/w") + "echo $?; pwd"),
    # State other than the directory that must not carry.
    ("edge calls: OLDPWD does not carry", W + "cd /tmp/w; cd /tmp" + IN("/tmp") + "cd -; echo $?; pwd"),
    ("edge calls: PWD is the new directory", W + "cd /tmp/w" + IN("/tmp/w") + "echo \"$PWD\""),
    ("edge calls: directory stack does not carry", W + "cd /tmp; pushd /tmp/w >/dev/null; pushd /tmp >/dev/null" + IN("/tmp") + "dirs; echo ${#DIRSTACK[@]}"),
    ("edge calls: noclobber does not carry", "echo a > /tmp/f; set -C" + M + "echo b > /tmp/f; cat /tmp/f"),
    ("edge calls: noglob does not carry", "touch /tmp/g1; set -f" + M + "echo /tmp/g*"),
    ("edge calls: failglob does not carry", "shopt -s failglob" + M + "echo /tmp/nomatch*; echo status=$?"),
    ("edge calls: nullglob does not carry", "shopt -s nullglob" + M + "echo /tmp/nomatch*"),
    ("edge calls: extglob off in a new call", "shopt -s extglob" + M + "shopt extglob"),
    ("edge calls: IFS does not carry", "IFS=:" + M + "x='a b:c'; set -- $x; echo $#"),
    ("edge calls: PATH does not carry", "PATH=/nowhere" + M + "ls -d / && echo found"),
    ("edge calls: hash table does not carry", "hash ls 2>/dev/null; hash -p /x/fake cat" + M + "hash; echo status=$?"),
    ("edge calls: exported function does not carry", "f() { echo f; }; export -f f" + M + "type f; echo status=$?"),
    ("edge calls: LINENO restarts", "echo $LINENO\necho $LINENO" + M + "echo $LINENO"),
    ("edge calls: BASH_REMATCH does not carry", "[[ abc =~ b ]]" + M + "echo \"[${BASH_REMATCH[0]}] ${#BASH_REMATCH[@]}\""),
    ("edge calls: PIPESTATUS does not carry", "false | true | (exit 3)" + M + "echo ${PIPESTATUS[@]}"),
    ("edge calls: open descriptors do not carry", "exec 3> /tmp/o" + M + "echo x >&3; echo status=$?"),
    ("edge calls: exec stdout redirect does not carry", "exec > /tmp/o; echo hidden" + M + "echo shown; cat /tmp/o"),
    ("edge calls: jobs do not carry", "{ echo bg > /tmp/o; } & wait" + M + "jobs; echo \"[$!]\"; cat /tmp/o"),
    ("edge calls: set -x does not carry", "set -x" + M + "echo traced?"),
    ("edge calls: set -v does not carry", "set -v" + M + "echo verbose?"),
    ("edge calls: pipefail does not carry", "set -o pipefail" + M + "false | true; echo $?"),
    ("edge calls: nocasematch does not carry", "shopt -s nocasematch" + M + "[[ A == a ]]; echo $?"),
    ("edge calls: getopts state does not carry", "set -- -a -b; getopts ab o; echo $o $OPTIND" + M + "echo \"[$OPTIND]\""),
    ("edge calls: SHLVL each call", "echo $SHLVL" + M + "echo $SHLVL"),
    ("edge calls: shift does not carry", "set -- a b c; shift" + M + "echo $#"),
    ("edge calls: integer attribute does not carry", "declare -i n; n=1+1" + M + "n=1+1; echo $n"),
    ("edge calls: nameref does not carry", "a=1; declare -n r=a" + M + "echo \"[${r-unset}]\""),
    ("edge calls: local-only variable does not carry", "f() { local v=1; g=2; }; f" + M + "echo \"[${v-unset}] [${g-unset}]\""),
    ("edge calls: environment export does not carry", "export E=1" + M + "sh -c 'echo \"[${E-unset}]\"'"),
    # State carried the supported way: through files.
    ("edge calls: set +o restores options", "set -o pipefail -o noclobber; set +o > /tmp/opts" + M + ". /tmp/opts; set -o | grep -E '^(pipefail|noclobber)'"),
    ("edge calls: shopt -p restores shopts", "shopt -s nullglob extglob; shopt -p nullglob extglob > /tmp/sh" + M + ". /tmp/sh; shopt nullglob extglob"),
    ("edge calls: alias -p restores aliases", "alias ll='echo long'; alias -p > /tmp/al" + M + "shopt -s expand_aliases; . /tmp/al\nll"),
    ("edge calls: trap -p restores traps", "trap 'echo bye' EXIT; trap -p > /tmp/tr" + M + ". /tmp/tr; echo body"),
    ("edge calls: declare -p restores arrays", "a=(1 'two words' 3); declare -A m=([k]=v); declare -p a m > /tmp/vars" + M + ". /tmp/vars; echo ${#a[@]} \"${a[1]}\" ${m[k]}"),
    ("edge calls: export -p restores exports", "export Q=1; export -p | grep ' Q=' > /tmp/ex" + M + ". /tmp/ex; sh -c 'echo $Q'"),
    ("edge calls: declare -f restores functions", "f() { echo \"f:$1\"; }; declare -f f > /tmp/fn" + M + ". /tmp/fn; f arg"),
    ("edge calls: saved cwd restored", "cd /tmp; pwd > /tmp/cwd" + IN("/tmp") + "cd /" + M + "cd \"$(cat /tmp/cwd)\"; pwd"),
    ("edge calls: counter file across calls", "echo 0 > /tmp/n" + M + "echo $(( $(cat /tmp/n) + 1 )) > /tmp/n" + M + "echo $(( $(cat /tmp/n) + 1 )) > /tmp/n" + M + "cat /tmp/n"),
    ("edge calls: append across calls", "echo one > /tmp/log" + M + "echo two >> /tmp/log" + M + "echo three >> /tmp/log; cat /tmp/log"),
    ("edge calls: relative files follow the directory", W + "cd /tmp/w; echo data > rel" + IN("/tmp/w") + "cat rel; cd x" + IN("/tmp/w/x") + "cat ../rel"),
    ("edge calls: remove in a later call", "echo x > /tmp/f" + M + "rm /tmp/f" + M + "ls /tmp; cat /tmp/f; echo status=$?"),
    ("edge calls: move in a later call", "echo x > /tmp/f" + M + "mv /tmp/f /tmp/g" + M + "cat /tmp/g"),
    ("edge calls: symlink across calls", "echo t > /tmp/t; ln -s t /tmp/l" + M + "cat /tmp/l; readlink /tmp/l"),
    ("edge calls: binary file across calls", "printf 'a\\377\\000b' > /tmp/b" + M + "od -An -tx1 /tmp/b"),
    ("edge calls: unicode file across calls", "echo x > '/tmp/é日'" + M + "ls /tmp; cat '/tmp/é日'"),
    ("edge calls: no-newline file across calls", "printf 'a' > /tmp/n" + M + "cat /tmp/n; echo" + M + "wc -c < /tmp/n"),
    ("edge calls: noclobber across calls", "echo a > /tmp/f" + M + "set -C; echo b > /tmp/f; echo status=$?" + M + "cat /tmp/f"),
    ("edge calls: find in the carried directory", W + "cd /tmp/w; touch a b" + IN("/tmp/w") + "find . | sort"),
    ("edge calls: glob in the carried directory", W + "cd /tmp/w; touch a b" + IN("/tmp/w") + "echo *"),
    ("edge calls: realpath in the carried directory", W + "cd /tmp/w" + IN("/tmp/w") + "realpath . .. x"),
    ("edge calls: remove the carried directory's parent contents", W + "cd /tmp/w/x" + IN("/tmp/w/x") + "cd /; rm -r /tmp/w; ls /tmp" + M + "pwd"),
    # Statuses and output across calls.
    ("edge calls: status is the last call's", "exit 7" + M + "true"),
    ("edge calls: last call exits nonzero", "true" + M + "exit 3"),
    ("edge calls: last call exit wraps", "true" + M + "exit 300"),
    ("edge calls: last call exits negative", "true" + M + "exit -1"),
    ("edge calls: last call has a syntax error", "echo first" + M + "echo second; fi"),
    ("edge calls: first call has a syntax error", "echo first; fi" + M + "echo second"),
    ("edge calls: output accumulates", "echo out1; echo err1 >&2" + M + "echo out2; echo err2 >&2"),
    ("edge calls: stdin is empty in every call", "cat; echo first" + M + "read -r x; echo status=$? [$x]"),
    ("edge calls: exec replaces only its call", "exec echo replaced" + M + "echo next"),
    ("edge calls: errexit failure then next call", "set -e; false; echo no" + M + "echo yes"),
    ("edge calls: many calls", "echo 1" + M + "echo 2" + M + "echo 3" + M + "echo 4" + M + "echo 5" + M + "echo 6"),
    ("edge calls: empty call in the middle", "echo 1" + M + "" + M + "echo 3"),
    ("edge calls: comment-only call", "echo 1" + M + "# only a comment" + M + "echo $?"),
]
