"""Edge inputs: empty input and input with no trailing newline, through every text filter and the
shell's own readers, as a pipe, as /dev/null on stdin and as an empty file operand.

Generated from fixed tables with plain loops, so every Python 3 produces the same scripts.
"""

TIER = "sweep"

# Input shapes: (label, how to feed a command). {c} is the command.
SHAPES = [
    ("empty pipe", "printf '' | {c}"),
    ("null stdin", "{c} < /dev/null"),
    ("empty file", ": > /tmp/e; {c} /tmp/e"),
    ("no newline", "printf 'b a' | {c}"),
    ("no newline two lines", "printf 'b a\\n1 c' | {c}"),
    ("only newline", "printf '\\n' | {c}"),
    ("blank lines", "printf '\\n\\n\\n' | {c}"),
    ("whitespace only", "printf ' \\t \\n' | {c}"),
]

# (label, command, takes a file operand)
COMMANDS = [
    ("cat", "cat", True),
    ("cat -n", "cat -n", True),
    ("cat -s", "cat -s", True),
    ("head -n 1", "head -n 1", True),
    ("head -c 1", "head -c 1", True),
    ("head -n -1", "head -n -1", True),
    ("tail -n 1", "tail -n 1", True),
    ("tail -c 1", "tail -c 1", True),
    ("tail -n +2", "tail -n +2", True),
    ("wc", "wc", True),
    ("wc -l", "wc -l", True),
    ("wc -w", "wc -w", True),
    ("wc -c", "wc -c", True),
    ("wc -m", "wc -m", True),
    ("wc -L", "wc -L", True),
    ("sort", "sort", True),
    ("sort -n", "sort -n", True),
    ("sort -u", "sort -u", True),
    ("sort -c", "sort -c", True),
    ("uniq", "uniq", True),
    ("uniq -c", "uniq -c", True),
    ("cut -c1", "cut -c1", True),
    ("cut -f1", "cut -f1", True),
    ("cut -d -f2", "cut -d ' ' -f2", True),
    ("cut -s", "cut -s -d ' ' -f1", True),
    ("tr upper", "tr a-z A-Z", False),
    ("tr -d newline", "tr -d '\\n'", False),
    ("rev", "rev", True),
    ("tac", "tac", True),
    ("nl", "nl", True),
    ("fold", "fold -w 1", True),
    ("fmt", "fmt", True),
    ("paste -s", "paste -s", True),
    ("paste two columns", "paste - -", False),
    ("expand", "expand", True),
    ("unexpand -a", "unexpand -a", True),
    ("od -c", "od -c", True),
    ("od -tx1", "od -An -tx1", True),
    ("base64", "base64", True),
    ("base64 -d", "base64 -d", True),
    ("md5sum", "md5sum", True),
    ("cksum", "cksum", True),
    ("md5sum -c", "md5sum -c", True),
    ("sed p", "sed p", True),
    ("sed $d", "sed '$d'", True),
    ("sed line count", "sed -n '$='", True),
    ("sed N", "sed 'N;s/\\n/+/'", True),
    ("sed $a", "sed '$a end'", True),
    ("sed -z", "sed -z 's/^/>/'", True),
    ("grep dot", "grep .", True),
    ("grep -c dot", "grep -c .", True),
    ("grep -c empty", "grep -c ''", True),
    ("grep -v", "grep -v x", True),
    ("grep -o", "grep -o '[a-z]'", True),
    ("jq", "jq .", True),
    ("jq -s", "jq -c -s .", True),
    ("jq -R", "jq -R .", True),
    ("jq -Rs", "jq -Rs .", True),
    ("jq -e", "jq -e .", True),
    ("xargs", "xargs echo run", False),
    ("xargs -r", "xargs -r echo run", False),
    ("tee", "tee /tmp/t | wc -c", False),
    ("tsort", "tsort", True),
    ("numfmt", "numfmt", False),
    ("factor", "factor", False),
    ("file", "file -b", True),
    ("read", "{ read -r l; echo \"read=$? [$l]\"; }", False),
    ("read -d empty", "{ IFS= read -r -d '' l; echo \"read=$? ${#l}\"; }", False),
    ("read -n", "{ read -r -n 1 l; echo \"read=$? [$l]\"; }", False),
    ("mapfile", "{ mapfile -t a; echo \"n=${#a[@]}\"; printf '[%s]' \"${a[@]}\"; echo; }", False),
    ("while read", "while IFS= read -r l; do echo \"[$l]\"; done", False),
    ("while read or last", "while IFS= read -r l || [ -n \"$l\" ]; do echo \"[$l]\"; done", False),
    ("command substitution", "{ x=$(cat); echo \"[$x] ${#x}\"; }", False),
    ("wc -c via cat", "cat | wc -c", False),
]

CASES = []
for label, command, operand in COMMANDS:
    for shape, template in SHAPES:
        if shape == "empty file" and not operand:
            script = ": > /tmp/e; " + command + " < /tmp/e"
        else:
            script = template.replace("{c}", command)
        CASES.append((f"edge empty: {label} {shape}", script + "; echo \"status=$?\""))

# Two-operand commands with an empty side, and a side with no trailing newline.
PAIR_SETUP = ": > /tmp/e; printf 'a\\nb' > /tmp/n; printf 'a\\nb\\n' > /tmp/f; "
PAIRS = [
    ("comm", "comm"), ("comm -3", "comm -3"), ("join", "join"), ("join -a1", "join -a1"),
    ("paste", "paste"), ("diff", "diff"), ("diff -u", "diff -u"), ("cmp", "cmp"),
]
for label, command in PAIRS:
    for left, right in (("e", "f"), ("f", "e"), ("e", "e"), ("n", "f"), ("f", "n"), ("n", "n")):
        CASES.append((
            f"edge empty pairs: {label} {left} {right}",
            PAIR_SETUP + f"{command} /tmp/{left} /tmp/{right} | sed 's/[0-9-]* [0-9:.]* [-+][0-9]*$//'; echo \"status=${{PIPESTATUS[0]}}\"".replace("{{", "{").replace("}}", "}"),
        ))

# Shell constructs over empty and unterminated data.
MISC = [
    ("heredoc empty", "cat <<EOF\nEOF\necho status=$?"),
    ("heredoc empty wc", "wc -c <<EOF\nEOF"),
    ("herestring empty", "wc -c <<< ''"),
    ("herestring unset", "od -An -c <<< \"$unset\""),
    ("command substitution empty", "x=$(true); echo \"[${x}] ${#x}\""),
    ("command substitution newlines only", "x=$(printf '\\n\\n\\n'); echo \"[${x}] ${#x}\""),
    ("command substitution keeps inner newlines", "x=$(printf 'a\\n\\nb\\n\\n'); echo \"[${x}]\""),
    ("file substitution empty", ": > /tmp/e; x=$(</tmp/e); echo \"[${x}] $?\""),
    ("file substitution no newline", "printf 'a' > /tmp/n; x=$(</tmp/n); echo \"[${x}]\""),
    ("file substitution missing", "x=$(</tmp/missing); echo \"[${x}] $?\""),
    ("semicolon only", ";"),
    ("empty function body call", "f() { :; }; f; echo $?"),
    ("empty array", "a=(); echo \"${#a[@]} [${a[*]}]\"; for x in \"${a[@]}\"; do echo in; done; echo done"),
    ("empty positional", "set --; echo \"$# [$*] [$@]\"; for x; do echo in; done; echo done"),
    ("empty string argument", "printf '[%s]\\n' '' \"\" $''"),
    ("empty word removed", "x=; printf '[%s]\\n' $x a $x"),
    ("empty quoted kept", "x=; printf '[%s]\\n' \"$x\" a"),
    ("empty IFS", "IFS=; x='a b'; set -- $x; echo $#"),
    ("unset IFS", "unset IFS; x=' a  b '; set -- $x; echo $#"),
    ("empty case", "case '' in '') echo empty;; *) echo other;; esac"),
    ("empty test", "[ '' ]; echo $?; [ -n '' ]; echo $?; [ -z '' ]; echo $?; test; echo $?"),
    ("empty cond", "[[ '' ]]; echo $?; [[ -z '' ]]; echo $?"),
    ("empty arith", "echo $(( )); x=; echo $((x + 1))"),
    ("empty for list", "for x in; do echo in; done; echo done"),
    ("empty glob literal", "cd /tmp && echo *"),
    ("empty glob nullglob", "cd /tmp && shopt -s nullglob && echo * && echo end"),
    ("empty directory ls", "mkdir /tmp/d && ls /tmp/d; echo status=$?"),
    ("empty directory find", "mkdir /tmp/d && find /tmp/d; echo status=$?"),
    ("empty directory rmdir", "mkdir /tmp/d && rmdir /tmp/d && echo gone"),
    ("empty file test -s", ": > /tmp/e; [ -s /tmp/e ]; echo $?; [ -f /tmp/e ]; echo $?"),
    ("empty file stat", ": > /tmp/e; stat -c %s /tmp/e"),
    ("empty file truncate", "printf abc > /tmp/f; truncate -s 0 /tmp/f; wc -c < /tmp/f"),
    ("empty file cp", ": > /tmp/e; cp /tmp/e /tmp/c; wc -c /tmp/c"),
    ("empty file split", "cd /tmp && : > e && split e && ls x* 2>&1; echo status=$?"),
    ("empty file csplit", "cd /tmp && : > e && csplit e 1; echo status=$?"),
    ("empty file grep -L", ": > /tmp/e; grep -L x /tmp/e; echo status=$?"),
    ("empty file sed -i", ": > /tmp/e; sed -i 's/^/x/' /tmp/e; wc -c < /tmp/e"),
    ("no newline sed -i", "printf 'a' > /tmp/n; sed -i 's/a/b/' /tmp/n; od -An -c /tmp/n"),
    ("no newline sed $a", "printf 'a' | sed '$a z' | od -An -c"),
    ("no newline sed -s", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; sed -s '$a z' /tmp/x /tmp/y | od -An -c"),
    ("no newline cat two files", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; cat /tmp/x /tmp/y | od -An -c"),
    ("no newline sort two files", "printf 'b' > /tmp/x; printf 'a' > /tmp/y; sort /tmp/x /tmp/y"),
    ("no newline head two files", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; head /tmp/x /tmp/y"),
    ("no newline tail two files", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; tail -n 1 /tmp/x /tmp/y"),
    ("no newline grep two files", "printf 'a' > /tmp/x; printf 'a' > /tmp/y; grep a /tmp/x /tmp/y"),
    ("no newline wc two files", "printf 'a' > /tmp/x; printf 'b\\nc' > /tmp/y; wc /tmp/x /tmp/y"),
    ("no newline nl two files", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; nl /tmp/x /tmp/y"),
    ("no newline tac two files", "printf 'a\\nb' > /tmp/x; tac /tmp/x /tmp/x | od -An -c"),
    ("no newline uniq", "printf 'a\\na' | uniq -c"),
    ("no newline diff", "printf 'a' > /tmp/x; printf 'a\\n' > /tmp/y; diff /tmp/x /tmp/y; echo status=$?"),
    ("no newline diff both", "printf 'a' > /tmp/x; printf 'b' > /tmp/y; diff /tmp/x /tmp/y; echo status=$?"),
    ("no newline patch", "printf 'a\\n' > /tmp/x; printf 'b' > /tmp/y; diff -u /tmp/x /tmp/y > /tmp/p; cd /tmp && patch x < p; od -An -c x"),
    ("no newline cmp", "printf 'a' > /tmp/x; printf 'a\\n' > /tmp/y; cmp /tmp/x /tmp/y; echo status=$?"),
    ("no newline comm", "printf 'a\\nb' > /tmp/x; printf 'b\\n' > /tmp/y; comm /tmp/x /tmp/y"),
    ("no newline join", "printf '1 a' > /tmp/x; printf '1 b' > /tmp/y; join /tmp/x /tmp/y"),
    ("no newline paste", "printf 'a' > /tmp/x; printf 'b\\nc' > /tmp/y; paste /tmp/x /tmp/y"),
    ("no newline jq values", "printf '1 2' | jq -c ."),
    ("no newline jq object", "printf '{\"a\":1}' | jq -c .a"),
    ("no newline jq truncated", "printf '{\"a\":' | jq -c . 2>/dev/null; echo status=$?"),
    ("no newline xargs", "printf 'a b' | xargs -n 1 echo"),
    ("no newline mapfile", "printf 'a\\nb' | { mapfile a; printf '[%s]' \"${a[@]}\"; }"),
    ("no newline read -d", "printf 'a,b' | { while IFS= read -r -d , x; do echo \"[$x]\"; done; echo \"last [$x]\"; }"),
    ("no newline source", "printf 'echo sourced' > /tmp/s; . /tmp/s"),
    ("no newline sh -c", "sh -c 'printf done'; echo"),
    ("no newline heredoc body", "cat <<'EOF' | od -An -c\na\nEOF"),
    ("no newline base64 -d", "printf 'YQ==' | base64 -d | od -An -c"),
    ("no newline md5sum -c", "printf 'a' > /tmp/x; md5sum /tmp/x | tr -d '\\n' > /tmp/s; md5sum -c /tmp/s"),
    ("no newline factor", "printf '6\\n10' | factor; echo status=$?"),
    ("no newline tr", "printf 'abc' | tr b '\\n' | od -An -c"),
    ("no newline fold", "printf 'abcde' | fold -w 2 | od -An -c"),
    ("no newline fmt", "printf 'a b c' | fmt -w 3 | od -An -c"),
    ("no newline expand", "printf 'a\\tb' | expand | od -An -c"),
    ("no newline tail -c", "printf 'abc' | tail -c 2 | od -An -c"),
    ("no newline tail -n 0", "printf 'a\\nb' | tail -n 0 | od -An -c; echo status=$?"),
    ("no newline head -n 0", "printf 'a\\nb' | head -n 0 | od -An -c; echo status=$?"),
    ("echo -n then wc", "echo -n | wc -c; echo -n '' | wc -l"),
    ("printf empty format", "printf ''; echo status=$?"),
    ("printf missing format", "printf; echo status=$?"),
    ("echo nothing", "echo | od -An -c"),
    ("true pipe", "true | cat; echo status=$?"),
    ("empty pipeline stage", "echo a | : | cat; echo status=$?"),
]
for label, script in MISC:
    CASES.append((f"edge empty: {label}", script))
