package golem-it:high-volume-logging;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-it-high-volume-logging-api {
  run: func();
}

world golem-it-high-volume-logging {
  export golem-it-high-volume-logging-api;
}
