package cloud.golem.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import javax.inject.Inject

/**
 * Produces the single agent ESM bundle (the "user" slot the wasm host injects + calls `guest`
 * on). Generates a wrapper entry that (1) imports the agent module for its side effect —
 * KSP-generated main() registers the agents — and (2) builds the flat `guest` namespace from
 * the SDK's GolemAgentRuntime singleton, then rollup-bundles it (SDK compiled in; only the
 * configured externals, e.g. the Golem host interface, are left external).
 */
abstract class BundleJsTask @Inject constructor(
    private val exec: ExecOperations
) : DefaultTask() {

    /** The agent's compiled Kotlin/JS entry (`<module>.mjs`). */
    @get:InputFile
    abstract val jsEntry: RegularFileProperty

    /** The SDK's compiled Kotlin/JS entry (`golem-kotlin-sdk.mjs`), bundled in. */
    @get:InputFile
    abstract val sdkEntry: RegularFileProperty

    @get:Input
    abstract val externals: ListProperty<String>

    @get:Input
    abstract val rollup: Property<String>

    @get:OutputFile
    abstract val outputBundle: RegularFileProperty

    @TaskAction
    fun bundle() {
        val agent = jsEntry.get().asFile
        val sdk = sdkEntry.get().asFile
        require(agent.exists()) { "Agent Kotlin/JS entry not found: $agent — did the prod compile run?" }
        require(sdk.exists()) { "SDK Kotlin/JS entry not found: $sdk — is golem-kotlin-sdk a dependency?" }
        val out = outputBundle.get().asFile
        out.parentFile.mkdirs()

        // Wrapper entry: run the agent module (main() registers), expose guest from the SDK runtime.
        val wrapper = out.parentFile.resolve("golem-agent-entry.mjs")
        wrapper.writeText(
            """
            import { GolemAgentRuntime } from ${jsLiteral(sdk.absolutePath)};
            import ${jsLiteral(agent.absolutePath)};
            const rt = GolemAgentRuntime.getInstance();
            export const guest = {
              initialize: (a, i, p) => rt.initialize(a, i, p),
              invoke: (m, i, p) => rt.invoke(m, i, p),
              getDefinition: () => rt.getDefinition(),
              discoverAgentTypes: () => rt.discoverAgentTypes(),
            };
            """.trimIndent() + "\n"
        )

        val externalList = externals.get().joinToString(", ") { "'${it}'" }
        val configFile = out.parentFile.resolve("golem-rollup.config.mjs")
        configFile.writeText(
            """
            // AUTO-GENERATED by cloud.golem.wasm-component — do not edit.
            export default {
              input: ${jsLiteral(wrapper.absolutePath)},
              external: [$externalList],
              output: { file: ${jsLiteral(out.absolutePath)}, format: 'es', inlineDynamicImports: true },
              onwarn(w, warn) {
                if (w.code === 'CIRCULAR_DEPENDENCY') return;
                if (w.code === 'UNRESOLVED_IMPORT') return;
                warn(w);
              },
            };
            """.trimIndent() + "\n"
        )

        exec.exec {
            it.commandLine(rollup.get(), "-c", configFile.absolutePath, "--silent")
        }
        require(out.exists()) { "rollup did not produce $out" }
        logger.lifecycle("golem: bundled ${out.name} (${out.length()} bytes); SDK in, externals: $externalList")
    }

    private fun jsLiteral(s: String): String = "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"
}
