package golem:it;

interface api {
  sleep: func(secs: u64) -> result<_, string>;
  sleep-during-request: func(secs: u64) -> string;
  sleep-during-parallel-requests: func(secs: u64) -> string;
  sleep-between-requests: func(secs: u64, n: u64) -> string;
  healthcheck: func() -> bool;
}

world clock-service {
  export api;
}
