package golem:component;

interface api {
  get-version-from-env-var: func() -> string;
}

world update-test-env-var {
  import wasi:cli/environment@0.2.3;

  export golem:api/save-snapshot@1.3.0;
  export golem:api/load-snapshot@1.3.0;

  export api;
}
