package golem:it;

interface api {
  fail-with-custom-max-retries: func(max-retries: u32) -> ();
  explicit-commit: func(replicas: u8) -> ();

  fallible-transaction-test: func() -> bool;
  infallible-transaction-test: func() -> u32;
}

world golem-ts-tests {
  import golem:api/host@0.2.0;
  export api;
}