package golem:it;

interface api {
  get-self-uri: func(function-name: string) -> string;
  jump: func() -> u64;
  fail-with-custom-max-retries: func(max-retries: u64) -> ();
  explicit-commit: func(replicas: u8) -> ();
  atomic-region: func() -> ();
}

world runtime-service {
  import golem:api/host@0.2.0;
  export api;
}