package golem-it:ifs-update-inside-exported-function;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-it-ifs-update-inside-exported-function-api {
  run: func() -> tuple<string, string>;
}

world golem-it-ifs-update-inside-exported-function {
  import wasi:io/poll@0.2.3;
  import wasi:io/streams@0.2.3;
  import wasi:http/types@0.2.3;
  import wasi:http/outgoing-handler@0.2.3;


  export golem-it-ifs-update-inside-exported-function-api;
}
