import fc from "fast-check"
import { describe, expect, it } from "vitest"
import { SchemaBuilder, mergeGraphDefs } from "../src/internal/schema-model/builder.js"
import {
  canonicalSchemaBytesV1,
  schemaFingerprintV1,
} from "../src/internal/schema-model/fingerprint.js"
import {
  emptyMetadata,
  field,
  schemaType,
  t,
  type DiscriminatorRule,
  type SchemaGraph,
  type SchemaType,
} from "../src/internal/schema-model/model.js"
import { validateSchemaGraph } from "../src/internal/schema-model/validation.js"

const hex = (bytes: Uint8Array): string =>
  [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("")
const graph = (root: SchemaType): SchemaGraph => ({ defs: new Map(), root })
const metadata = emptyMetadata()
const branch = (tag: string, body: SchemaType, discriminator: DiscriminatorRule) => ({
  tag,
  body,
  discriminator,
  metadata: emptyMetadata(),
})
const codes = (root: SchemaType): string[] =>
  validateSchemaGraph(graph(root)).map((error) => error.code)

// These vectors are copied from the platform-owned Rust golden corpus and are also exercised by
// the canonical TypeScript, Scala, Rust SDK re-export, and MoonBit suites. The bytes below are
// constants rather than output generated by another implementation in this test.
describe("SchemaFingerprintV1 platform golden fixtures", () => {
  it.each([
    {
      name: "unit",
      root: t.tuple([]),
      element: undefined,
      bytes: "847818676f6c656d2d736368656d612d66696e6765727072696e7401820085f68080f6f680",
      digest: "b50494cf0f33961c703d5f6e6af3d3159e528c4d09c1d801172cdf8f022dcafa",
    },
    {
      name: "string",
      root: t.string(),
      element: t.string(),
      bytes: "847818676f6c656d2d736368656d612d66696e6765727072696e7401820e85f68080f6f680",
      digest: "61c50c0a3c6ffd63529621ada78afc0d4d8e5fe691f8b0993035f847c660a307",
    },
    {
      name: "list<string>",
      root: t.list(t.string()),
      element: t.list(t.string()),
      bytes:
        "847818676f6c656d2d736368656d612d66696e6765727072696e74018314820e85f68080f6f685f68080f6f680",
      digest: "4939707f8ef97e9d4b31b568332eaf5a3011f2be7c358f7546966fadfb9416d4",
    },
    {
      name: "permission-card",
      root: t.permissionCard({ polymorphic: true }),
      element: t.permissionCard({ polymorphic: true }),
      bytes: "847818676f6c656d2d736368656d612d66696e6765727072696e7401831825f585f68080f6f680",
      digest: "b7d3c09af5db4e56b527051f561689f451dfdb21213cd70aabd11618e244da8b",
    },
  ])("matches $name bytes and digest", ({ root, element, bytes, digest }) => {
    expect(hex(canonicalSchemaBytesV1(graph(root), element))).toBe(bytes)
    expect(hex(schemaFingerprintV1(graph(root), element))).toBe(digest)
  })

  it("matches the recursive-record platform vector", () => {
    const ref = t.ref("example.node")
    const recursive: SchemaGraph = {
      root: ref,
      defs: new Map([
        [
          "example.node",
          {
            name: "Node",
            body: t.record([field("value", t.string()), field("next", t.option(ref))]),
          },
        ],
      ]),
    }
    expect(canonicalSchemaBytesV1(recursive, recursive.root)).toHaveLength(140)
    expect(hex(schemaFingerprintV1(recursive, recursive.root))).toBe(
      "3931585d2d02a2b7d5c99e3da1082ac8fe904c535e2700bd45e29a95ff2399fa",
    )
  })

  it("matches constrained metadata/restrictions bytes", () => {
    const constrained = schemaType(
      {
        tag: "text",
        restrictions: {
          languages: ["fr", "en"],
          minLength: 1,
          maxLength: 64,
          regex: "^[a-z]+$",
        },
      },
      {
        doc: "text",
        aliases: ["z", "a"],
        examples: ['"hello"'],
        deprecated: "use-v2",
        role: { tag: "other", val: "prompt" },
      },
    )
    expect(hex(canonicalSchemaBytesV1(graph(constrained), constrained))).toBe(
      "847818676f6c656d2d736368656d612d66696e6765727072696e74018618198262656e626672011840685e5b612d7a5d2b24856474657874826161617a81672268656c6c6f22667573652d763282036670726f6d707480",
    )
    expect(hex(schemaFingerprintV1(graph(constrained), constrained))).toBe(
      "b985cdb5445862be90e8dca06bbfa9c46b50cf40edc84ed34205bb3a214c5bb0",
    )
  })
})

describe("schema category and graph parity", () => {
  const validCategories: ReadonlyArray<[string, SchemaType]> = [
    ["ref", t.ref("leaf")],
    ["bool", t.bool()],
    ["s8", t.s8()],
    ["s16", t.s16()],
    ["s32", t.s32()],
    ["s64", t.s64()],
    ["u8", t.u8()],
    ["u16", t.u16()],
    ["u32", t.u32()],
    ["u64", t.u64()],
    ["f32", t.f32()],
    ["f64", t.f64()],
    ["char", t.char()],
    ["string", t.string()],
    ["record", t.record([field("x", t.string())])],
    ["variant", t.variant([{ name: "none", metadata }])],
    ["enum", t.enum(["a"])],
    ["flags", t.flags(["a"])],
    ["tuple", t.tuple([t.string()])],
    ["list", t.list(t.string())],
    ["fixed-list", t.fixedList(t.u8(), 4)],
    ["map", t.map(t.string(), t.bool())],
    ["option", t.option(t.string())],
    ["result", t.result(t.string(), t.u32())],
    ["text", t.text({ minLength: 1 })],
    ["binary", t.binary({ maxBytes: 8 })],
    ["path", t.path({ direction: "input", kind: "file" })],
    ["url", t.url({ allowedSchemes: ["https"] })],
    ["datetime", t.datetime()],
    ["duration", t.duration()],
    ["quantity", t.quantity({ baseUnit: "kg", allowedSuffixes: ["kg"] })],
    ["union", t.union([branch("s", t.string(), { tag: "prefix", val: "s:" })])],
    ["secret", t.secret(t.string(), { category: "api" })],
    ["quota-token", t.quotaToken({ resourceName: "calls" })],
    ["permission-card", t.permissionCard({ polymorphic: false })],
    ["future", t.future(t.string())],
    ["future<void>", t.future()],
    ["stream", t.stream(t.string())],
    ["stream<void>", t.stream()],
  ]

  it.each(validCategories)("validates and fingerprints %s", (_name, root) => {
    const defs = root.body.tag === "ref" ? new Map([["leaf", { body: t.string() }]]) : new Map()
    const value = { defs, root }
    expect(validateSchemaGraph(value)).toEqual([])
    expect(schemaFingerprintV1(value, root)).toHaveLength(32)
  })

  it("closes recursive and mutually recursive builder definitions", () => {
    const builder = new SchemaBuilder()
    builder.reserve("A")
    builder.reserve("B")
    builder.commit("A", t.record([field("b", t.option(builder.ref("B")))]))
    builder.commit("B", t.record([field("a", t.option(builder.ref("A")))]))
    const recursive = builder.buildGraph(builder.ref("A"))
    expect(validateSchemaGraph(recursive)).toEqual([])
    expect(recursive.defs.size).toBe(2)
  })

  it("deduplicates equal definitions and rejects conflicting definitions", () => {
    const left = { defs: new Map([["T", { body: t.string() }]]), root: t.ref("T") }
    expect(mergeGraphDefs([left, left]).size).toBe(1)
    const right = { defs: new Map([["T", { body: t.u32() }]]), root: t.ref("T") }
    expect(() => mergeGraphDefs([left, right])).toThrow(/T/)
  })
})

describe("bounded schema properties", () => {
  it("definition insertion order and unreachable definitions do not affect fingerprints", () => {
    fc.assert(
      fc.property(fc.array(fc.string({ maxLength: 8 }), { maxLength: 12 }), (names) => {
        const ids = [...new Set(names.map((name, index) => `d${index}:${name}`))]
        const defs = ids.map((id) => [id, { body: t.string() }] as const)
        const root = t.string()
        const forward = { defs: new Map(defs), root }
        const reverse = { defs: new Map([...defs].reverse()), root }
        expect(hex(schemaFingerprintV1(forward, root))).toBe(
          hex(schemaFingerprintV1(reverse, root)),
        )
        expect(hex(schemaFingerprintV1(forward, root))).toBe(
          hex(schemaFingerprintV1(graph(root), root)),
        )
      }),
      { numRuns: 80 },
    )
  })

  it("numeric bounds accept exact ranges and reject one step outside", () => {
    const ranges = [
      ["s8", -128n, 127n, "signed"],
      ["s16", -32768n, 32767n, "signed"],
      ["s32", -(2n ** 31n), 2n ** 31n - 1n, "signed"],
      ["s64", -(2n ** 63n), 2n ** 63n - 1n, "signed"],
      ["u8", 0n, 255n, "unsigned"],
      ["u16", 0n, 65535n, "unsigned"],
      ["u32", 0n, 2n ** 32n - 1n, "unsigned"],
      ["u64", 0n, 2n ** 64n - 1n, "unsigned"],
    ] as const
    fc.assert(
      fc.property(fc.constantFrom(...ranges), ([tag, min, max, family]) => {
        const make = t[tag]
        expect(
          codes(make({ min: { tag: family, val: min }, max: { tag: family, val: max } })),
        ).toEqual([])
        expect(codes(make({ min: { tag: family, val: min - 1n } }))).toContain(
          "invalid-numeric-restriction",
        )
        expect(codes(make({ max: { tag: family, val: max + 1n } }))).toContain(
          "invalid-numeric-restriction",
        )
      }),
      { numRuns: 32 },
    )
  })

  it("canonicalizes both IEEE negative-zero encodings", () => {
    fc.assert(
      fc.property(fc.constantFrom("f32", "f64"), (tag) => {
        const make = t[tag]
        const positive = make({ min: { tag: "float-bits", val: 0n } })
        const negative = make({ min: { tag: "float-bits", val: 0x8000000000000000n } })
        expect(schemaFingerprintV1(graph(positive), positive)).toEqual(
          schemaFingerprintV1(graph(negative), negative),
        )
      }),
    )
  })
})

describe("real malformed schema inputs", () => {
  it.each([
    ["empty-variant", t.variant([])],
    ["empty-enum", t.enum([])],
    ["empty-flags", t.flags([])],
    ["empty-union", t.union([])],
    ["duplicate-field-name", t.record([field("x", t.string()), field("x", t.bool())])],
    [
      "duplicate-variant-case",
      t.variant([
        { name: "x", metadata },
        { name: "x", metadata },
      ]),
    ],
    ["duplicate-enum-case", t.enum(["x", "x"])],
    ["duplicate-flag-name", t.flags(["x", "x"])],
    ["invalid-fixed-list-length", t.fixedList(t.u8(), 0)],
    ["invalid-fixed-list-length", t.fixedList(t.u8(), 2 ** 32)],
    ["map-key-not-primitive", t.map(t.list(t.string()), t.bool())],
    ["nullable-nesting", t.option(t.option(t.string()))],
    ["invalid-text-length-range", t.text({ minLength: 2, maxLength: 1 })],
    ["invalid-text-regex", t.text({ regex: "(" })],
    ["invalid-binary-byte-range", t.binary({ minBytes: 2, maxBytes: 1 })],
    [
      "quantity-min-greater-than-max",
      t.quantity({
        baseUnit: "m",
        allowedSuffixes: [],
        min: { mantissa: 2n, scale: 0, unit: "m" },
        max: { mantissa: 1n, scale: 0, unit: "m" },
      }),
    ],
    [
      "quantity-min-unit-mismatch",
      t.quantity({
        baseUnit: "m",
        allowedSuffixes: [],
        min: { mantissa: 1n, scale: 0, unit: "cm" },
      }),
    ],
    [
      "duplicate-union-tag",
      t.union([
        branch("x", t.string(), { tag: "prefix", val: "a" }),
        branch("x", t.string(), { tag: "prefix", val: "b" }),
      ]),
    ],
    [
      "union-ambiguous-discriminators",
      t.union([
        branch("a", t.string(), { tag: "prefix", val: "x" }),
        branch("b", t.string(), { tag: "prefix", val: "xy" }),
      ]),
    ],
    ["invalid-union-regex", t.union([branch("x", t.string(), { tag: "regex", val: "(" })])],
    [
      "union-string-rule-on-non-string-body",
      t.union([branch("x", t.u32(), { tag: "prefix", val: "x" })]),
    ],
    [
      "union-field-rule-on-non-record-body",
      t.union([branch("x", t.string(), { tag: "field-absent", val: "kind" })]),
    ],
  ] as ReadonlyArray<readonly [string, SchemaType]>)("reports %s", (code, root) => {
    expect(codes(root)).toContain(code)
  })

  it("reports both dangling reference and invalid map key", () => {
    expect(codes(t.map(t.ref("missing"), t.string()))).toEqual([
      "map-key-not-primitive",
      "dangling-ref",
    ])
  })

  it("fingerprinting rejects duplicate set values in restrictions and metadata", () => {
    const fixtures = [
      t.text({ languages: ["en", "en"] }),
      t.binary({ mimeTypes: ["image/png", "image/png"] }),
      schemaType({ tag: "string" }, { aliases: ["name", "name"], examples: [] }),
    ]
    for (const root of fixtures) {
      expect(() => canonicalSchemaBytesV1(graph(root), root)).toThrow(/duplicate value/)
    }
  })
})
