[package]
name = "golem-codec-measurements"
version = "0.0.0"
edition = "2024"
publish = false

[features]
transports = ["dep:golem-schema", "dep:prost"]

[dependencies]
golem-common = { workspace = true }
golem-schema = { workspace = true, features = ["full"], optional = true }
prost = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "golem-codec-measurements"
path = "src/main.rs"
test = false
