package golem:api;

world golem {
  import golem:api/host@1.1.7;
  import golem:api/context@1.1.7;
  import golem:api/oplog@1.1.7;
  import golem:durability/durability@1.2.1;
  import wasi:blobstore/blobstore;
  import wasi:blobstore/container;
  import wasi:blobstore/types;
  import wasi:keyvalue/atomic@0.1.0;
  import wasi:keyvalue/eventual-batch@0.1.0;
  import wasi:keyvalue/cache@0.1.0;
  import wasi:keyvalue/eventual@0.1.0;
  import wasi:keyvalue/types@0.1.0;
  import wasi:keyvalue/wasi-keyvalue-error@0.1.0;
  import wasi:logging/logging;
  import wasi:config/store@0.2.0-draft;
  import golem:rdbms/mysql@0.0.1;
  import golem:rdbms/postgres@0.0.1;
  import golem:rdbms/types@0.0.1;
}
