/*
 * Copyright 2024-2026 John A. De Goes and the ZIO Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package golem.codegen.rpc

import golem.codegen.discovery.SourceDiscovery
import golem.codegen.ir.AgentSurfaceIR._

import scala.meta._
import scala.meta.dialects.Scala213
import scala.meta.parsers._

/**
 * Code generator for Golem RPC client objects.
 *
 * Given agent surface metadata, generates client objects with:
 *   - `XRemote` trait with per-method wrapper classes for natural call syntax
 *   - Mode-aware constructors: durable agents get `get`/`getWithConfig` plus
 *     `getPhantom`/`newPhantom`/`getPhantomWithConfig`/`newPhantomWithConfig`;
 *     ephemeral agents get only the phantom variants
 *
 * Call syntax on the returned `XRemote`:
 *   - `remote.process(1, "hello")` — await the result via `apply`
 *   - `remote.process.trigger(1, "hello")` — fire-and-forget
 *   - `remote.process.scheduleAt(1, "hello", when)` — schedule at a time
 *
 * Generated clients extend `golem.AgentCompanionBase[Trait]` so the existing
 * macro infrastructure can locate the trait type parameter.
 */
object RpcCodegen {

  final case class GeneratedFile(relativePath: String, content: String)

  final case class Warning(message: String)

  final case class Result(
    files: Seq[GeneratedFile],
    warnings: Seq[Warning]
  )

  def generate(
    agents: List[AgentSurface],
    existingObjects: Seq[SourceDiscovery.ExistingObject]
  ): Result = {
    val warnings = List.newBuilder[Warning]
    val files    = List.newBuilder[GeneratedFile]

    val existingByFqn: Set[String] = existingObjects.map { obj =>
      if (obj.pkg.isEmpty) obj.name else s"${obj.pkg}.${obj.name}"
    }.toSet

    agents.foreach { agent =>
      val clientName = s"${agent.simpleName}Client"
      val clientFqn  =
        if (agent.packageName.isEmpty) clientName
        else s"${agent.packageName}.$clientName"

      if (existingByFqn.contains(clientFqn)) {
        warnings += Warning(
          s"Skipping RPC client generation for ${agent.traitFqn}: " +
            s"object $clientFqn already exists. Remove the handwritten client to enable codegen."
        )
      } else {
        val content     = generateCompanion(agent)
        val packagePath =
          if (agent.packageName.isEmpty) ""
          else agent.packageName.replace('.', '/') + "/"
        val path = s"$packagePath${clientName}.scala"
        files += GeneratedFile(relativePath = path, content = content)
      }
    }

    Result(files = files.result(), warnings = warnings.result())
  }

  /** Filter out Principal parameters from a method surface. */
  private def remoteParams(method: MethodSurface): List[ParamSurface] =
    method.params.zip(method.principalParams).collect { case (p, false) =>
      p
    }

  /** Capitalize the first character of a string. */
  private def capitalize(s: String): String =
    if (s.isEmpty) s else s.head.toUpper.toString + s.tail

  /**
   * Unwrap `Future[T]` to get `T`. Returns the original type if not a Future
   * wrapper.
   */
  private[rpc] def unwrapFutureType(returnTypeExpr: String): String = {
    val tpe =
      try {
        dialects.Scala213(returnTypeExpr).parse[Type].get
      } catch {
        case _: Exception =>
          try {
            dialects.Scala3(returnTypeExpr).parse[Type].get
          } catch {
            case _: Exception => return returnTypeExpr
          }
      }

    tpe match {
      case Type.Apply(name, args) if args.size == 1 =>
        val nameStr = name.syntax
        if (
          nameStr == "Future" ||
          nameStr == "scala.concurrent.Future" ||
          nameStr == "_root_.scala.concurrent.Future"
        ) {
          args.head.syntax
        } else {
          returnTypeExpr
        }
      case _ => returnTypeExpr
    }
  }

  private def generateCompanion(agent: AgentSurface): String = {
    val packageName = agent.packageName
    val simpleName  = agent.simpleName
    val typeName    = agent.typeName

    val constructorType = constructorTypeExpr(agent.constructor)

    // Filter methods with valid principalParams
    val remoteMethods = agent.methods.filter { m =>
      m.principalParams.length == m.params.length
    }

    val sb = new StringBuilder

    // Package declaration
    if (packageName.nonEmpty) {
      sb.append(s"package $packageName\n\n")
    }

    sb.append("/** Generated by Golem RPC codegen. Do not edit. */\n")
    sb.append(s"object ${simpleName}Client extends _root_.golem.AgentCompanionBase[$simpleName] {\n\n")

    // type Id (private — implementation detail)
    sb.append(s"  private type Id = $constructorType\n\n")

    // typeName
    sb.append(s"""  val typeName: _root_.scala.Predef.String = "$typeName"\n\n""")

    // agentType
    sb.append(s"  lazy val agentType: _root_.golem.runtime.AgentType[$simpleName, Id] =\n")
    sb.append(s"    _root_.golem.runtime.rpc.AgentClient.agentType[$simpleName]\n")
    sb.append(s"      .asInstanceOf[_root_.golem.runtime.AgentType[$simpleName, Id]]\n\n")

    // Generate XRemote trait, per-method classes, and mode-aware constructors
    if (remoteMethods.nonEmpty) {
      generateRemoteTrait(sb, agent, remoteMethods)
    }

    sb.append("}\n")

    sb.toString
  }

  private def generateRemoteTrait(
    sb: StringBuilder,
    agent: AgentSurface,
    remoteMethods: List[MethodSurface]
  ): Unit = {
    val simpleName = agent.simpleName
    val remoteName = s"${simpleName}Remote"

    // Per-method wrapper classes
    remoteMethods.foreach { method =>
      generateRemoteMethodClass(sb, simpleName, method)
    }

    // XRemote trait
    sb.append(s"  trait $remoteName {\n")
    remoteMethods.foreach { method =>
      val className = s"${capitalize(method.name)}RemoteMethod"
      sb.append(s"    val ${method.name}: $className\n")
    }
    sb.append(s"  }\n\n")

    // Private bindRemote
    sb.append(s"  private def bindRemote(\n")
    sb.append(s"    resolved: _root_.golem.runtime.rpc.AgentClientRuntime.ResolvedAgent[$simpleName]\n")
    sb.append(s"  ): $remoteName =\n")
    sb.append(s"    new $remoteName {\n")
    remoteMethods.foreach { method =>
      val className = s"${capitalize(method.name)}RemoteMethod"
      sb.append(s"""      val ${method.name} = new $className(resolved)\n""")
    }
    sb.append(s"    }\n\n")

    // Mode-aware constructors
    generateModeAwareConstructors(sb, agent, remoteName)
  }

  private def generateRemoteMethodClass(
    sb: StringBuilder,
    simpleName: String,
    method: MethodSurface
  ): Unit = {
    val className  = s"${capitalize(method.name)}RemoteMethod"
    val rParams    = remoteParams(method)
    val resultType = unwrapFutureType(method.returnTypeExpr)

    // Input type for the packed method call
    val packedInputType = rParams match {
      case Nil      => "_root_.scala.Unit"
      case p :: Nil => p.typeExpr
      case _        => "_root_.scala.collection.immutable.Vector[_root_.scala.Any]"
    }

    val outputType = resultType

    sb.append(s"  final class $className private[$simpleName" + "Client] (\n")
    sb.append(s"    resolved: _root_.golem.runtime.rpc.AgentClientRuntime.ResolvedAgent[$simpleName]\n")
    val methodNameLit = "\"" + method.name + "\""
    sb.append(
      s"  ) extends _root_.golem.runtime.rpc.AbstractRemoteMethod[$simpleName, $packedInputType, $outputType](resolved, $methodNameLit) {\n"
    )

    val packExpr = rParams match {
      case Nil      => "()"
      case p :: Nil => p.name
      case ps       => "_root_.scala.Vector[_root_.scala.Any](" + ps.map(_.name).mkString(", ") + ")"
    }

    val paramDecls = rParams.map(p => s"${p.name}: ${p.typeExpr}").mkString(", ")
    sb.append(s"    def apply($paramDecls): _root_.scala.concurrent.Future[$outputType] =\n")
    sb.append(s"      awaitWith($packExpr)\n\n")

    sb.append(s"    def trigger($paramDecls): _root_.scala.concurrent.Future[_root_.scala.Unit] =\n")
    sb.append(s"      triggerWith($packExpr)\n\n")

    val scheduleParamDecls =
      if (paramDecls.isEmpty) "when: _root_.golem.Datetime"
      else s"$paramDecls, when: _root_.golem.Datetime"
    sb.append(s"    def scheduleAt($scheduleParamDecls): _root_.scala.concurrent.Future[_root_.scala.Unit] =\n")
    sb.append(s"      scheduleWith($packExpr, when)\n\n")

    val scheduleCancelableParamDecls = scheduleParamDecls
    sb.append(s"    def scheduleCancelableAt($scheduleCancelableParamDecls): _root_.scala.concurrent.Future[_root_.golem.runtime.rpc.CancellationToken] =\n")
    sb.append(s"      scheduleCancelableWith($packExpr, when)\n\n")

    sb.append(s"  }\n\n")
  }

  /**
   * Build the packed constructor input expression from unpacked param names.
   */
  private def constructorPackExpr(ctorParams: List[ParamSurface]): String =
    ctorParams match {
      case Nil      => "()"
      case p :: Nil => p.name
      case ps       => "(" + ps.map(_.name).mkString(", ") + ")"
    }

  /**
   * Build a camelCase parameter name from a config field path, e.g. List("db",
   * "host") → "dbHost".
   */
  private def configParamName(path: List[String]): String =
    path match {
      case Nil      => ""
      case h :: Nil => h
      case h :: t   => h + t.map(capitalize).mkString
    }

  private def generateModeAwareConstructors(
    sb: StringBuilder,
    agent: AgentSurface,
    remoteName: String
  ): Unit = {
    val simpleName   = agent.simpleName
    val ctorParams   = agent.constructor.params
    val mode         = agent.metadata.mode
    val configFields = agent.configFields

    val paramDecls = ctorParams.map(p => s"${p.name}: ${p.typeExpr}").mkString(", ")
    val packExpr   = constructorPackExpr(ctorParams)

    def resolveCall(phantom: Option[String], config: Option[String]): String =
      (phantom, config) match {
        case (None, None) =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolve[$simpleName, Id](agentType, $packExpr)"
        case (Some(ph), None) =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolveWithPhantom[$simpleName, Id](\n" +
            s"      agentType, $packExpr, phantom = _root_.scala.Some($ph)\n    )"
        case (None, Some(cfg)) =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolveWithConfig[$simpleName, Id](\n" +
            s"      agentType, $packExpr, $cfg\n    )"
        case (Some(ph), Some(cfg)) =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolveWithPhantomAndConfig[$simpleName, Id](\n" +
            s"      agentType, $packExpr, phantom = _root_.scala.Some($ph), $cfg\n    )"
      }

    def emitConstructor(
      name: String,
      extraParamsBefore: String,
      extraParamsAfter: String,
      phantom: Option[String],
      config: Option[String]
    ): Unit = {
      val allParams = Seq(extraParamsBefore, paramDecls, extraParamsAfter).filter(_.nonEmpty).mkString(", ")
      sb.append(s"  def $name($allParams): $remoteName =\n")
      sb.append(s"    ${resolveCall(phantom, config)} match {\n")
      sb.append(s"      case _root_.scala.Right(resolved) => bindRemote(resolved)\n")
      sb.append(s"      case _root_.scala.Left(err) => throw _root_.scala.scalajs.js.JavaScriptException(err)\n")
      sb.append(s"    }\n\n")
    }

    /** Generate the config override parameters as `Option[T] = None` */
    def configParamDecls: String =
      configFields.map { cf =>
        val pName = configParamName(cf.path)
        s"$pName: _root_.scala.Option[${cf.typeExpr}] = _root_.scala.None"
      }.mkString(", ")

    /**
     * Generate the body that builds a List[ConfigOverride] from non-None params
     */
    def configOverrideListExpr: String = {
      val builders = configFields.map { cf =>
        val pName   = configParamName(cf.path)
        val pathLit = cf.path.map(p => s""""$p"""").mkString(", ")
        s"$pName.map(v => _root_.golem.config.ConfigOverride[${cf.typeExpr}](_root_.scala.List($pathLit), v))"
      }
      "_root_.scala.List(" + builders.mkString(", ") + ").flatten"
    }

    def emitWithConfigConstructor(
      name: String,
      extraParamsBefore: String,
      extraParamsAfter: String,
      phantom: Option[String]
    ): Unit = {
      val configParams  = configParamDecls
      val allExtra      = Seq(extraParamsAfter, configParams).filter(_.nonEmpty).mkString(", ")
      val allParams     = Seq(extraParamsBefore, paramDecls, allExtra).filter(_.nonEmpty).mkString(", ")
      val overridesExpr = configOverrideListExpr
      val resolveExpr   = (phantom) match {
        case None =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolveWithConfig[$simpleName, Id](\n" +
            s"      agentType, $packExpr, $overridesExpr\n    )"
        case Some(ph) =>
          s"_root_.golem.runtime.rpc.AgentClientRuntime.resolveWithPhantomAndConfig[$simpleName, Id](\n" +
            s"      agentType, $packExpr, phantom = _root_.scala.Some($ph), $overridesExpr\n    )"
      }
      sb.append(s"  def $name($allParams): $remoteName =\n")
      sb.append(s"    $resolveExpr match {\n")
      sb.append(s"      case _root_.scala.Right(resolved) => bindRemote(resolved)\n")
      sb.append(s"      case _root_.scala.Left(err) => throw _root_.scala.scalajs.js.JavaScriptException(err)\n")
      sb.append(s"    }\n\n")
    }

    // Durable agents get: get, getPhantom, newPhantom
    // Ephemeral agents get: getPhantom, newPhantom
    // WithConfig variants only generated when configFields is non-empty
    if (mode == "durable" || mode == "") {
      emitConstructor("get", "", "", phantom = None, config = None)
      if (configFields.nonEmpty) {
        emitWithConfigConstructor("getWithConfig", "", "", phantom = None)
      }
    }

    // Both durable and ephemeral get phantom constructors
    emitConstructor("getPhantom", "", "phantom: _root_.golem.Uuid", phantom = Some("phantom"), config = None)
    val ctorRefs         = if (ctorParams.isEmpty) "" else ctorParams.map(_.name).mkString(", ") + ", "
    val newPhantomParams = if (paramDecls.isEmpty) "" else paramDecls
    sb.append(s"  def newPhantom($newPhantomParams): $remoteName =\n")
    sb.append(s"    getPhantom(${ctorRefs}_root_.golem.HostApi.generateIdempotencyKey())\n\n")
    if (configFields.nonEmpty) {
      emitWithConfigConstructor("getPhantomWithConfig", "", "phantom: _root_.golem.Uuid", phantom = Some("phantom"))
      val newPhantomWithConfigParams = {
        val configParams = configParamDecls
        val extra        =
          Seq("phantom: _root_.golem.Uuid" +: Nil, configParams +: Nil).flatten.filter(_.nonEmpty).mkString(", ")
        Seq(paramDecls, extra).filter(_.nonEmpty).mkString(", ")
      }
      // newPhantomWithConfig delegates, need to forward config params
      val configParamNames = configFields.map(cf => configParamName(cf.path))
      val forwardArgs      = configParamNames.map(n => s"$n = $n").mkString(", ")
      val phantomAndConfig = s"_root_.golem.HostApi.generateIdempotencyKey(), $forwardArgs"
      val delegateArgs     =
        if (ctorParams.isEmpty) phantomAndConfig
        else ctorParams.map(_.name).mkString(", ") + ", " + phantomAndConfig
      val npcParams = {
        val configParams = configParamDecls
        Seq(paramDecls, configParams).filter(_.nonEmpty).mkString(", ")
      }
      sb.append(s"  def newPhantomWithConfig($npcParams): $remoteName =\n")
      sb.append(s"    getPhantomWithConfig($delegateArgs)\n\n")
    }
  }

  private def constructorTypeExpr(ctor: ConstructorSurface): String =
    ctor.params match {
      case Nil      => "_root_.scala.Unit"
      case p :: Nil => p.typeExpr
      case ps       => ps.map(_.typeExpr).mkString("(", ", ", ")")
    }
}
