package cloud.golem.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

/**
 * Generates the native (Kotlin/Wasm) registration + `@WasmExport` entry points.
 *
 * The agent is compiled against `golem-kotlin-sdk` as a normal Kotlin/Wasm dependency, so the
 * generated code uses the SDK's real `NativeAgentDescriptor`/`SchemaValue` types directly.
 *
 * Two outputs:
 *  - `<ClassName>Registration.kt` : `fun register<ClassName>()` per `@Agent` class, calling
 *    `NativeAgentRuntime.registerAgent(NativeAgentDescriptor(...))` with handler/factory lambdas
 *    that read `List<SchemaValue>` (via `.asString()`/`.asInt()`) and return a `SchemaValue`.
 *  - `GolemGeneratedGuest.kt` : the actual `@WasmExport("golem:agent/guest@2.0.0#...")` functions.
 *
 * WHY the wrappers live here, not in the SDK's `Guest.kt` (see that file's doc comment for the
 * full rationale): a Kotlin/Wasm reactor component does not run top-level `val` initializers
 * automatically at instantiation, and unreferenced top-level code is dead-code-eliminated -- so
 * agent registration (which the SDK cannot see ahead of time) needs a guaranteed-reachable
 * trigger. Generating the real `@WasmExport` functions here guarantees a call to
 * `registerAllAgents()` happens before any SDK logic runs, because the host is contractually
 * required to call these exports to talk to the agent at all.
 */
class NativeRegistrationEmitter(private val codeGenerator: CodeGenerator) {

    /** Per-agent registration function. */
    fun emit(model: AgentModel) {
        val code = buildString {
            appendLine("// AUTO-GENERATED by golem-kotlin-ksp — do not edit")
            appendLine("package ${model.packageName}")
            appendLine()
            appendLine("import cloud.golem.runtime.NativeAgentRuntime")
            appendLine("import cloud.golem.runtime.NativeAgentDescriptor")
            appendLine("import cloud.golem.runtime.NativeMethodDescriptor")
            appendLine("import cloud.golem.runtime.NativeParamSchema")
            appendLine("import cloud.golem.runtime.NativeHttpEndpoint")
            appendLine("import cloud.golem.runtime.SchemaValue")
            appendLine()
            appendLine("fun register${model.className}() {")
            appendLine("    NativeAgentRuntime.registerAgent(")
            appendLine("        NativeAgentDescriptor(")
            appendLine("            ${lit(model.className)},")
            appendLine("            ${lit(model.classDescription)},")
            appendLine("            ${lit(model.mountPath)},")
            appendLine("            ${paramSchemaList(model.constructorParams)},")
            appendLine("            listOf(")
            model.methods.forEachIndexed { i, m ->
                val comma = if (i < model.methods.size - 1) "," else ""
                appendLine("                ${methodDescriptor(model.className, m)}$comma")
            }
            appendLine("            ),")
            appendLine("            ${factoryLambda(model)},")
            appendLine("            ${model.mountAuth},")
            appendLine("            ${corsList(model.mountCors)},")
            appendLine("            ${lit(model.mode)},")
            append("            ${lit(model.snapshotting)}")
            appendLine(snapshotArg(model))
            appendLine("        )")
            appendLine("    )")
            appendLine("}")
        }
        write(model.packageName, "${model.className}Registration", code)
    }

    /** Single entry point: idempotent registration + the real @WasmExport guest functions. */
    fun emitEntryPoint(models: List<AgentModel>) {
        val pkg = models.first().packageName
        val code = buildString {
            appendLine("// AUTO-GENERATED by golem-kotlin-ksp — do not edit")
            appendLine("package $pkg")
            appendLine()
            appendLine("import kotlin.wasm.WasmExport")
            appendLine()
            // cabi_realloc must be declared HERE (the agent's own module), not in the SDK: a
            // Kotlin/Wasm library dependency's @WasmExport declarations do not survive into the
            // consuming executable's final linked module (verified empirically -- the same
            // cross-module DCE limitation as the golem:agent/guest exports below).
            appendLine("@WasmExport(\"cabi_realloc\")")
            appendLine("fun golemGuestCabiRealloc(oldPtr: Int, oldSize: Int, align: Int, newSize: Int): Int =")
            appendLine("    cloud.golem.wasm.cabiRealloc(oldPtr, oldSize, align, newSize)")
            appendLine()
            appendLine("private var golemAgentsRegistered = false")
            appendLine()
            appendLine("fun registerAllAgents() {")
            appendLine("    if (golemAgentsRegistered) return")
            appendLine("    golemAgentsRegistered = true")
            models.forEach { m ->
                appendLine("    ${m.packageName}.register${m.className}()")
            }
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:agent/guest@2.0.0#initialize\")")
            appendLine("fun golemGuestInitialize(argsPtr: Int): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.initialize(argsPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:agent/guest@2.0.0#initialize\")")
            appendLine("fun golemGuestCabiPostInitialize(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostInitialize(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:agent/guest@2.0.0#invoke\")")
            appendLine("fun golemGuestInvoke(argsPtr: Int): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.invoke(argsPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:agent/guest@2.0.0#invoke\")")
            appendLine("fun golemGuestCabiPostInvoke(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostInvoke(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:agent/guest@2.0.0#get-definition\")")
            appendLine("fun golemGuestGetDefinition(): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.getDefinition()")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:agent/guest@2.0.0#get-definition\")")
            appendLine("fun golemGuestCabiPostGetDefinition(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostGetDefinition(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:agent/guest@2.0.0#discover-agent-types\")")
            appendLine("fun golemGuestDiscoverAgentTypes(): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.discoverAgentTypes()")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:agent/guest@2.0.0#discover-agent-types\")")
            appendLine("fun golemGuestCabiPostDiscoverAgentTypes(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostDiscoverAgentTypes(resultPtr)")
            appendLine("}")
            appendLine()
            // wit-native's shared world always includes golem:tool/tool-guest@0.1.0 (component
            // embed requires every world export to exist), so these are emitted unconditionally
            // -- even a project with zero @Tool-annotated methods needs a (functionally empty)
            // tool interface. cloud.golem.runtime's tool functions already handle an empty
            // NativeToolRuntime registry gracefully (discover-tools -> ok([]), get-tool/invoke ->
            // "unknown tool" errors). No @Tool KSP parsing exists yet (a follow-up), so no
            // registerAllTools() call is emitted here.
            appendLine("@WasmExport(\"golem:tool/guest@0.1.0#discover-tools\")")
            appendLine("fun golemToolDiscoverTools(): Int = cloud.golem.runtime.discoverTools()")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:tool/guest@0.1.0#discover-tools\")")
            appendLine("fun golemToolCabiPostDiscoverTools(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostDiscoverTools(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:tool/guest@0.1.0#get-tool\")")
            appendLine("fun golemToolGetTool(namePtr: Int, nameLen: Int): Int =")
            appendLine("    cloud.golem.runtime.getTool(namePtr, nameLen)")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:tool/guest@0.1.0#get-tool\")")
            appendLine("fun golemToolCabiPostGetTool(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostGetTool(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:tool/guest@0.1.0#invoke\")")
            appendLine("fun golemToolInvoke(argsPtr: Int): Int = cloud.golem.runtime.invokeTool(argsPtr)")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:tool/guest@0.1.0#invoke\")")
            appendLine("fun golemToolCabiPostInvoke(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostInvokeTool(resultPtr)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"golem:api/save-snapshot@1.5.0#save\")")
            appendLine("fun golemSaveSnapshot(): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.saveSnapshot()")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:api/save-snapshot@1.5.0#save\")")
            appendLine("fun golemCabiPostSaveSnapshot(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostSaveSnapshot(resultPtr)")
            appendLine("}")
            appendLine()
            // Canonical ABI flattens record { payload: list<u8>, mime-type: string } into
            // four I32 params; wasm-tools component embed expects [I32,I32,I32,I32] -> [I32].
            appendLine("@WasmExport(\"golem:api/load-snapshot@1.5.0#load\")")
            appendLine("fun golemLoadSnapshot(payloadPtr: Int, payloadLen: Int, mimeTypePtr: Int, mimeTypeLen: Int): Int {")
            appendLine("    registerAllAgents()")
            appendLine("    return cloud.golem.runtime.loadSnapshotFlat(payloadPtr, payloadLen, mimeTypePtr, mimeTypeLen)")
            appendLine("}")
            appendLine()
            appendLine("@WasmExport(\"cabi_post_golem:api/load-snapshot@1.5.0#load\")")
            appendLine("fun golemCabiPostLoadSnapshot(resultPtr: Int) {")
            appendLine("    cloud.golem.runtime.cabiPostLoadSnapshot(resultPtr)")
            appendLine("}")
        }
        write(pkg, "GolemGeneratedGuest", code)
    }

    // -- code generation -----------------------------------------------------

    private fun methodDescriptor(className: String, m: MethodModel): String {
        val inputs = paramSchemaList(m.inputParams)
        val endpoints = if (m.httpEndpoints.isEmpty()) {
            "emptyList()"
        } else {
            "listOf(${m.httpEndpoints.joinToString(", ") {
                "NativeHttpEndpoint(${lit(it.verb)}, ${lit(it.path)}, ${it.auth}, ${corsList(it.cors)})"
            }})"
        }
        val readOnly = m.readOnlyCache?.let { lit(it) } ?: "null"
        return "NativeMethodDescriptor(${lit(m.name)}, ${lit(m.outputWitType)}, $inputs, $endpoints, ${lit(m.promptHint)}, $readOnly) ${handlerLambda(className, m)}"
    }

    private fun handlerLambda(className: String, m: MethodModel): String {
        val args = m.inputParams.mapIndexed { i, p -> decode(p.typeDesc, "input[$i]") }.joinToString(", ")
        val secondParam = if (m.inputParams.isEmpty()) "_" else "input"
        val call = "(instance as $className).${m.name}($args)"
        return when (m.outputTypeDesc) {
            is TypeDesc.UnitT -> "{ instance, $secondParam -> $call; SchemaValue.Unit_ }"
            is TypeDesc.Prim -> "{ instance, $secondParam -> ${encode(m.outputTypeDesc, call)} }" // single-use, inline
            else -> // bind the result so composite encoders can reference its fields without re-invoking
                "{ instance, $secondParam -> val golemResult = $call; ${encode(m.outputTypeDesc, "golemResult")} }"
        }
    }

    /**
     * The `snapshotCodec = SnapshotCodec(...)` argument for the `NativeAgentDescriptor(...)` call,
     * or "" when the agent doesn't mix in `Snapshotted<S>`. Composes ConverterCodegen (Kotlin <->
     * SchemaValue) with SchemaValueBytes (SchemaValue <-> ByteArray). Fully-qualifies the runtime
     * references so no extra imports are needed in the generated file.
     */
    private fun snapshotArg(model: AgentModel): String {
        val td = model.snapshotStateType ?: return ""
        val enc = encode(td, "(inst as ${model.className}).state")
        val dec = decode(td, "cloud.golem.runtime.SchemaValueBytes.decode(bytes)")
        return ",\n" +
            "            snapshotCodec = cloud.golem.runtime.SnapshotCodec(\n" +
            "                save = { inst -> cloud.golem.runtime.SchemaValueBytes.encode($enc) },\n" +
            "                load = { inst, bytes -> (inst as ${model.className}).state = $dec },\n" +
            "            )"
    }

    private fun factoryLambda(model: AgentModel): String {
        if (model.constructorParams.isEmpty()) return "{ _ -> ${model.className}() }"
        val args = model.constructorParams.mapIndexed { i, p -> decode(p.typeDesc, "input[$i]") }.joinToString(", ")
        return "{ input -> ${model.className}($args) }"
    }

    private fun decode(td: TypeDesc, sv: String): String = ConverterCodegen.decode(td, sv)
    private fun encode(td: TypeDesc, k: String): String = ConverterCodegen.encode(td, k)

    private fun paramSchemaList(params: List<ParamModel>): String = if (params.isEmpty()) {
        "emptyList()"
    } else {
        "listOf(${params.joinToString(", ") { "NativeParamSchema(${lit(it.name)}, ${lit(it.witType)})" }})"
    }

    private fun corsList(patterns: List<String>): String = if (patterns.isEmpty()) {
        "emptyList()"
    } else {
        "listOf(${patterns.joinToString(", ") { lit(it) }})"
    }

    /** Kotlin string literal with escaping. */
    private fun lit(s: String): String {
        val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }

    private fun write(packageName: String, fileName: String, code: String) {
        codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = packageName,
            fileName = fileName,
            extensionName = "kt",
        ).bufferedWriter().use { it.write(code) }
    }
}
