package cloud.golem.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

/**
 * Generates the Kotlin/JS registration glue.
 *
 * The agent is compiled against `golem-kotlin-sdk` as a NORMAL Kotlin dependency (the SDK is
 * bundled into the agent's JS bundle), so the generated code uses the SDK's real types
 * directly — no JS-module boundary, no string-array marshalling:
 *   GolemAgentRuntime.registerAgent(
 *     AgentDescriptor(typeName, description, mountPath,
 *       constructorParams: List<ParamSchema>,
 *       methods: List<MethodDescriptor>,        // each with output WIT type, input params,
 *                                               // http endpoints, and a handler lambda
 *       factory))
 *
 * Two outputs:
 *  - <ClassName>Registration.kt  : `fun register<ClassName>()` per @Agent class
 *  - GolemGeneratedMain.kt        : a single `fun main()` calling every register fn (Kotlin/JS
 *    `binaries.executable()` invokes main() on module import, when registration must run).
 */
class RegistrationEmitter(private val codeGenerator: CodeGenerator) {

    /** Per-agent registration function. */
    fun emit(model: AgentModel) {
        val code = buildString {
            appendLine("// AUTO-GENERATED by golem-kotlin-ksp — do not edit")
            appendLine("package ${model.packageName}")
            appendLine()
            appendLine("import cloud.golem.runtime.GolemAgentRuntime")
            appendLine("import cloud.golem.runtime.AgentDescriptor")
            appendLine("import cloud.golem.runtime.MethodDescriptor")
            appendLine("import cloud.golem.runtime.ParamSchema")
            appendLine("import cloud.golem.runtime.HttpEndpoint")
            usedHelpers(model).forEach { appendLine("import cloud.golem.runtime.$it") }
            appendLine()
            appendLine("fun register${model.className}() {")
            appendLine("    GolemAgentRuntime.registerAgent(")
            appendLine("        AgentDescriptor(")
            appendLine("            ${lit(model.className)},")
            appendLine("            ${lit(model.classDescription)},")
            appendLine("            ${lit(model.mountPath)},")
            appendLine("            ${paramSchemaList(model.constructorParams)},")
            appendLine("            listOf(")
            model.methods.forEachIndexed { i, m ->
                val comma = if (i < model.methods.size - 1) "," else ""
                appendLine("                ${methodDescriptor(model.className, m)}$comma")
            }
            appendLine("            ),")
            appendLine("            ${factoryLambda(model)}")
            appendLine("        )")
            appendLine("    )")
            appendLine("}")
        }
        write(model.packageName, "${model.className}Registration", code)
    }

    /** Single entry point that registers all agents on module load. */
    fun emitEntryPoint(models: List<AgentModel>) {
        val pkg = models.first().packageName
        val code = buildString {
            appendLine("// AUTO-GENERATED by golem-kotlin-ksp — do not edit")
            appendLine("package $pkg")
            appendLine()
            appendLine("fun registerAllAgents() {")
            models.forEach { m ->
                appendLine("    ${m.packageName}.register${m.className}()")
            }
            appendLine("}")
            appendLine()
            appendLine("fun main() {")
            appendLine("    registerAllAgents()")
            appendLine("}")
        }
        write(pkg, "GolemGeneratedMain", code)
    }

    // -- code generation -----------------------------------------------------

    private fun methodDescriptor(className: String, m: MethodModel): String {
        val inputs = paramSchemaList(m.inputParams)
        val endpoints = if (m.httpEndpoints.isEmpty()) "emptyList()"
        else "listOf(${m.httpEndpoints.joinToString(", ") { "HttpEndpoint(${lit(it.verb)}, ${lit(it.path)})" }})"
        return "MethodDescriptor(${lit(m.name)}, ${lit(m.outputWitType)}, $inputs, $endpoints) ${handlerLambda(className, m)}"
    }

    private fun handlerLambda(className: String, m: MethodModel): String {
        val args = m.inputParams.mapIndexed { i, p -> "${extractFn(p.witType)}(input, $i)" }.joinToString(", ")
        val secondParam = if (m.inputParams.isEmpty()) "_" else "input"
        val call = "(instance as $className).${m.name}($args)"
        return if (m.outputWitType == "()") {
            "{ instance, $secondParam -> $call; wrapUnit() }"
        } else {
            "{ instance, $secondParam -> ${wrapFn(m.outputWitType)}($call) }"
        }
    }

    private fun factoryLambda(model: AgentModel): String {
        if (model.constructorParams.isEmpty()) return "{ _ -> ${model.className}() }"
        val args = model.constructorParams.mapIndexed { i, p -> "${extractFn(p.witType)}(input, $i)" }.joinToString(", ")
        return "{ input -> ${model.className}($args) }"
    }

    private fun paramSchemaList(params: List<ParamModel>): String =
        if (params.isEmpty()) "emptyList()"
        else "listOf(${params.joinToString(", ") { "ParamSchema(${lit(it.name)}, ${lit(it.witType)})" }})"

    /** DataValue wrap/extract helpers (normal Kotlin functions in cloud.golem.runtime). */
    private fun wrapFn(wit: String): String = when (wit) {
        "s32", "s16", "s8", "u32", "u16", "u8" -> "wrapInt"
        "s64", "u64" -> "wrapLong"
        "string" -> "wrapString"
        else -> error("golem-kotlin-sdk has no DataValue wrap helper for WIT return type '$wit' (extend DataValue.kt)")
    }

    private fun extractFn(wit: String): String = when (wit) {
        "string" -> "extractString"
        "s32", "s16", "s8", "u32", "u16", "u8" -> "extractInt"
        "s64", "u64" -> "extractLong"
        else -> error("golem-kotlin-sdk has no DataValue extract helper for WIT param type '$wit' (extend DataValue.kt)")
    }

    /** The set of wrap/extract helper imports the generated code needs. */
    private fun usedHelpers(model: AgentModel): Set<String> {
        val s = sortedSetOf<String>()
        model.constructorParams.forEach { s += extractFn(it.witType) }
        model.methods.forEach { m ->
            m.inputParams.forEach { s += extractFn(it.witType) }
            if (m.outputWitType == "()") s += "wrapUnit" else s += wrapFn(m.outputWitType)
        }
        return s
    }

    /** Kotlin string literal with escaping. */
    private fun lit(s: String): String {
        val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }

    private fun write(packageName: String, fileName: String, code: String) {
        codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = packageName,
            fileName = fileName,
            extensionName = "kt"
        ).bufferedWriter().use { it.write(code) }
    }
}
