package cloud.golem.ksp

import com.google.devtools.ksp.getDeclaredFunctions
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType

/**
 * Generates a typed RPC client (`<Iface>Rpc`) for a `@RemoteAgent`-annotated interface. Each of
 * the interface's abstract methods becomes an override that encodes its arguments to a
 * `schema-value-tree` (via [ConverterCodegen]), invokes the remote agent through [WasmRpc], and
 * decodes the result back to the method's Kotlin return type. The client's constructor takes the
 * remote agent's constructor arguments as a `SchemaValue` (typically a `Record`); method calls are
 * fully typed.
 */
class RemoteAgentEmitter(private val codeGenerator: CodeGenerator) {

    fun emit(iface: KSClassDeclaration, typeName: String) {
        val pkg = iface.packageName.asString()
        val ifaceFqn = iface.qualifiedName?.asString() ?: error("@RemoteAgent interface has no qualified name")
        val clientName = "${iface.simpleName.asString()}Rpc"
        val methods = iface.getDeclaredFunctions().filter { it.isAbstract }.toList()

        val code = buildString {
            appendLine("// AUTO-GENERATED by golem-kotlin-ksp — do not edit")
            appendLine("package $pkg")
            appendLine()
            appendLine("import cloud.golem.runtime.SchemaValue")
            appendLine("import cloud.golem.runtime.WasmRpc")
            appendLine("import cloud.golem.runtime.RpcResult")
            appendLine("import cloud.golem.runtime.RpcException")
            appendLine()
            appendLine("/** Typed RPC client for the remote agent \"$typeName\" (implements $ifaceFqn). */")
            appendLine("class $clientName(constructorArgs: SchemaValue) : $ifaceFqn {")
            appendLine("    private val rpc = WasmRpc(${lit(typeName)}, constructorArgs)")
            appendLine()
            methods.forEach { appendLine(renderMethod(it)) }
            appendLine("    /** Releases the underlying wasm-rpc handle. */")
            appendLine("    fun close() = rpc.close()")
            appendLine("}")
        }
        write(pkg, clientName, code)
    }

    private fun renderMethod(fn: KSFunctionDeclaration): String {
        val name = fn.simpleName.asString()
        val params = fn.parameters.map { (it.name?.asString() ?: error("unnamed param")) to it.type.resolve() }
        val returnType = fn.returnType?.resolve() ?: error("method $name has no return type")
        val retTd = TypeMapper.resolve(returnType)

        val sig = params.joinToString(", ") { (n, t) -> "$n: ${renderType(t)}" }
        val argsList = params.joinToString(", ") { (n, t) -> ConverterCodegen.encode(TypeMapper.resolve(t), n) }

        return buildString {
            appendLine("    override fun $name($sig): ${renderType(returnType)} {")
            appendLine("        val golemArgs = SchemaValue.Record(listOf($argsList))")
            appendLine("        val golemR = rpc.invokeAndAwait(${lit(name)}, golemArgs, ${lit(retTd.toWit())})")
            if (retTd is TypeDesc.UnitT) {
                appendLine("        when (golemR) { is RpcResult.Ok -> Unit; is RpcResult.Err -> throw RpcException(golemR.error) }")
            } else {
                appendLine("        return when (golemR) {")
                appendLine("            is RpcResult.Ok -> ${ConverterCodegen.decode(retTd, "golemR.value!!")}")
                appendLine("            is RpcResult.Err -> throw RpcException(golemR.error)")
                appendLine("        }")
            }
            append("    }")
        }
    }

    /** Renders a [KSType] back to fully-qualified Kotlin source (handles generics + nullability). */
    private fun renderType(type: KSType): String {
        val fqn = type.declaration.qualifiedName?.asString() ?: type.declaration.simpleName.asString()
        val args = if (type.arguments.isEmpty()) {
            ""
        } else {
            "<" + type.arguments.joinToString(", ") { arg -> arg.type?.resolve()?.let { renderType(it) } ?: "*" } + ">"
        }
        return fqn + args + (if (type.isMarkedNullable) "?" else "")
    }

    private fun lit(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private fun write(packageName: String, fileName: String, code: String) {
        codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = packageName,
            fileName = fileName,
            extensionName = "kt",
        ).bufferedWriter().use { it.write(code) }
    }
}
