package rpc:caller;

world caller {
  use rpc:counters-exports/api.{timeline-node};

  export test1: func() -> list<tuple<string, u64>>;
  export test2: func() -> u64;
  export test3: func() -> u64;
  export test4: func() -> tuple<list<string>, list<tuple<string, string>>>;
  export test5: func() -> list<u64>;

  export bug-wasm-rpc-i32: func(in: timeline-node) -> timeline-node;

  export ephemeral-test1: func() -> list<tuple<string, string>>;
}
