package golem-it:wasi-config;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-it-wasi-config-api {
  get: func(key: string) -> option<string>;
  get-all: func() -> list<tuple<string, string>>;
}

world golem-it-wasi-config {
  import wasi:config/store@0.2.0-draft;
  export golem-it-wasi-config-api;
}
