package rpc:caller;

world caller {
  import wasi:cli/environment@0.2.0;

  export test1: func() -> u64;
  export test2: func() -> u64;
  export test3: func() -> tuple<list<string>, list<tuple<string, string>>>;
}
