"""Compound commands, functions and conditionals."""

CASES = [
    ("compound: if elif else", 'for n in 1 2 3; do if [ $n = 1 ]; then echo one; elif [ $n = 2 ]; then echo two; else echo other; fi; done'),
    ("compound: if status of the last command", 'if false; then :; fi; echo $?; if false; then :; else (exit 4); fi; echo $?'),
    ("compound: case patterns", 'for w in apple Banana 42 x.tar.gz ""; do case $w in a*) echo a;; [Bb]*) echo b;; [0-9]*) echo num;; *.tar.*|*.zip) echo archive;; "") echo empty;; esac; done'),
    ("compound: case fallthrough", 'case a in a) echo one;& b) echo two;;& a) echo three;; *) echo four;; esac'),
    ("compound: case with quoted and variable patterns", 'p="*"; case x in "$p") echo literal;; $p) echo glob;; esac'),
    ("compound: case no match status", 'case z in a) echo a;; esac; echo status=$?'),
    ("compound: for over words and default", 'for x in a "b c" d; do echo "[$x]"; done; set -- p q; for y; do echo $y; done'),
    ("compound: arithmetic for", 'for ((i=0; i<3; i++)); do echo $i; done; for ((;;)); do echo once; break; done; for ((j=10; j>0; j-=4)); do echo $j; done'),
    ("compound: while and until", 'i=0; while [ $i -lt 3 ]; do i=$((i+1)); done; echo $i; until [ $i -eq 0 ]; do i=$((i-1)); done; echo $i'),
    ("compound: until status", 'until true; do :; done; echo status=$?; n=0; until (( n++ >= 2 )); do echo loop$n; done'),
    ("compound: loop status and output redirection", 'for x in 1 2; do echo $x; done >/tmp/o; cat /tmp/o; while false; do :; done; echo status=$?'),
    ("compound: select from stdin", 'select v in alpha beta; do echo "picked $v $REPLY"; break; done <<< 2 2>/dev/null'),
    ("compound: select invalid choice", 'printf "9\\n1\\n" | { select v in a b; do echo "[$v] $REPLY"; [ -n "$v" ] && break; done 2>/dev/null; }'),
    ("compound: negated pipelines", '! false; echo $?; ! true; echo $?; ! false | true; echo $?; if ! grep -q x <<< y; then echo absent; fi', ["compound.pipeline.negate"]),
    ("compound: groups and subshells", 'x=1; { x=2; }; echo $x; (x=3); echo $x; { echo a; echo b; } | wc -l; (cd /tmp; pwd); pwd'),
    ("compound: lists and short circuits", 'true && echo a || echo b; false && echo c || echo d; false || false || echo e; true; false; echo $?'),
    ("compound: cond string and pattern", '[[ abc == a* ]] && echo glob; [[ abc == "a*" ]] || echo literal; [[ -z "" && -n x ]] && echo both; [[ b > a ]] && echo gt'),
    ("compound: cond regex and rematch", '[[ "key=value" =~ ^([a-z]+)=(.*)$ ]] && echo "${BASH_REMATCH[1]} ${BASH_REMATCH[2]} ${#BASH_REMATCH[@]}"; re="a+b"; [[ aab =~ $re ]] && echo var-re; [[ aab =~ "a+b" ]] || echo quoted-literal'),
    ("compound: cond variable and file tests", 'x=1; [[ -v x ]] && echo set; [[ -v nope ]] || echo unset; [[ -d /tmp && ! -e /nope ]] && echo files; a=(1); [[ -v a[0] ]] && echo elem'),
    ("compound: cond arithmetic comparison", '[[ 10 -gt 9 ]] && echo num; [[ 10 > 9 ]] || echo string-order; [[ 1+1 -eq 2 ]] && echo arith'),
    ("compound: cond nocasematch", 'shopt -s nocasematch; [[ ABC == abc ]] && echo match; case HELLO in hello) echo case;; esac', ["option.nocasematch"]),
    ("compound: function forms", 'f() { echo f; }; function g { echo g; }; function h() { echo h; }; f; g; h; k() ( echo subshell-body ); k'),
    ("compound: function arguments and status", 'f() { echo "$# $1 ${2-none}"; return 3; }; f a; echo $?; f "x y" z'),
    ("compound: recursion", 'fact() { if (( $1 <= 1 )); then echo 1; else echo $(( $1 * $(fact $(( $1 - 1 ))) )); fi; }; fact 10; fib() { local n=$1; (( n < 2 )) && { echo $n; return; }; echo $(( $(fib $((n-1))) + $(fib $((n-2))) )); }; fib 12', ["compound.function.recursion"]),
    ("compound: function redefinition and unset", 'f() { echo one; }; f; f() { echo two; }; f; unset -f f; type f 2>/dev/null || echo gone'),
    ("compound: function with redirections", 'f() { echo body; echo err >&2; } >/tmp/out 2>&1; f; cat /tmp/out'),
    ("compound: FUNCNAME and LINENO", 'outer() { inner; }; inner() { echo "${FUNCNAME[0]} ${FUNCNAME[1]} ${#FUNCNAME[@]}"; }; outer\necho line=$LINENO', ["param.callstack"]),
    ("compound: nested function definitions", 'outer() { inner() { echo inner; }; }; inner 2>/dev/null || echo not-yet; outer; inner'),
    ("compound: here document in a loop", 'for i in 1 2; do cat <<EOF\nitem $i\nEOF\ndone'),
    ("compound: pipeline into a loop keeps variables local", 'n=0; printf "a\\nb\\n" | while read l; do n=$((n+1)); done; echo $n'),
    ("compound: time keyword output is on stderr", '{ time true; } 2>/dev/null; echo status=$?'),
]
