"""jq conformance: jq 1.8.2 in the oracle is the reference for status, stdout and stderr."""

OBJ = """'{"name":"ada","age":36,"tags":["x","y"],"nested":{"k":[1,2,{"z":null}]}}'"""
PEOPLE = """'[{"name":"ada","age":36,"team":"a"},{"name":"bob","age":25,"team":"b"},{"name":"cy","age":41,"team":"a"}]'"""

CASES = [
    ("jq: pretty print", f"echo {OBJ} | jq ."),
    ("jq: default filter", f"echo {OBJ} | jq"),
    ("jq: raw field", f"echo {OBJ} | jq -r .name"),
    ("jq: nested path", f"echo {OBJ} | jq -c '.nested.k[2]'"),
    ("jq: array iteration", f"echo {PEOPLE} | jq -r '.[].name'"),
    ("jq: select map", f"echo {PEOPLE} | jq -c '[.[] | select(.age > 30) | .name]'"),
    ("jq: object construction", f"echo {PEOPLE} | jq -c '.[] | {{who: .name, old: (.age > 30)}}'"),
    ("jq: keys length type", f"echo {OBJ} | jq -c '[keys, length, (.tags|length), (.age|type), (.nested|type)]'"),
    ("jq: entries", f"echo {OBJ} | jq -c 'del(.nested) | to_entries | map(.key)'"),
    ("jq: with entries", """echo '{"a":1,"b":2}' | jq -c 'with_entries(.value |= tostring)'"""),
    ("jq: group sort unique", f"echo {PEOPLE} | jq -c '(group_by(.team) | map(length)), (sort_by(.age) | map(.name)), (map(.team) | unique), (max_by(.age).name)'"),
    ("jq: update operators", f"echo {OBJ} | jq -c '.age += 1 | .tags |= map(ascii_upcase) | del(.nested) | .new.deep = true'"),
    ("jq: alternative and optional", """echo '{"a":null}' | jq -c '[.a // "d", .b // 1, (.c?.d?), (try error("x") catch .)]'"""),
    ("jq: conditionals", """echo '[1,5,10]' | jq -c 'map(if . < 3 then "s" elif . < 8 then "m" else "l" end)'"""),
    ("jq: reduce foreach", """echo '[1,2,3,4]' | jq -c 'reduce .[] as $x (0; . + $x), [foreach .[] as $x (0; . + $x)]'"""),
    ("jq: limit first last range", "jq -nc '[limit(3; range(10))], first(range(5;9)), [range(0;10;4)], ([1,2,3]|last)'"),
    ("jq: recurse paths", """echo '{"a":{"b":[1,{"c":2}]}}' | jq -c '[paths], [.. | numbers], [leaf_paths], getpath(["a","b",1,"c"])'"""),
    ("jq: strings", """jq -nc '"Hello, World" | [ascii_downcase, (split(", ")), (ltrimstr("Hello")), (startswith("He")), (test("world"; "i")), (sub("o"; "0")), (gsub("o"; "0")), (explode|implode), (length)]'"""),
    ("jq: regex capture", """jq -nc '"id=42 name=ada" | capture("id=(?<id>[0-9]+) name=(?<name>[a-z]+)"), [scan("[0-9]+")], (match("n.me").offset)'"""),
    ("jq: conversions", """jq -nc '["1", 2, "x"] | [(.[0]|tonumber), (.[1]|tostring), tojson, ("[1,2]"|fromjson), (10/4|tostring), (6/3|tojson)]'"""),
    ("jq: formats", """jq -nr '["a,b", 1, "x y"] | @csv, @tsv, @sh, @json, @text, (.[2]|@uri), (.[2]|@base64), (.[2]|@base64|@base64d), ("<&>"|@html)'"""),
    ("jq: string interpolation", """echo '{"n":"ada","a":36}' | jq -r '"\\(.n) is \\(.a)"'"""),
    ("jq: aggregate", """jq -nc '[3,1,2] | [add, min, max, (add/length), any(. > 2), all(. > 0), (map(.*2)), sort, reverse, (index(1)), (indices(2)), flatten]'"""),
    ("jq: contains inside has", """jq -nc '{"a":[1,2],"b":"xyz"} | [has("a"), (.a|contains([1])), ("x"|inside("xyz")), ([.b]|inside(["xyz","q"])), (keys_unsorted)]'"""),
    ("jq: type selectors", """jq -nc '[1,"a",null,true,[1],{"a":1}] | [(.[]|numbers), (.[]|strings), (.[]|nulls), (.[]|booleans), (.[]|arrays), (.[]|objects), (.[]|scalars)]'"""),
    ("jq: arg and argjson", f"""echo {PEOPLE} | jq -c --arg n bob --argjson min 30 '[.[] | select(.name == $n or .age > $min) | .name]'"""),
    ("jq: named args object", """jq -nc --arg a 1 --argjson b '{"c":[2]}' '$ARGS'"""),
    ("jq: positional args", "jq -nc '$ARGS.positional' --args a 'b c'"),
    ("jq: json positional args", """jq -nc '$ARGS.positional' --jsonargs 1 '{"a":2}' null"""),
    ("jq: slurp", "printf '1 2\\n3\\n' | jq -c -s 'add, length'"),
    ("jq: raw input lines", "printf 'a\\nb c\\n\\nlast' | jq -R ."),
    ("jq: raw input slurp", "printf 'a\\nb\\n' | jq -Rs 'split(\"\\n\")'"),
    ("jq: raw input to json", "printf '{\"a\":1}\\n' | jq -R 'fromjson | .a'"),
    ("jq: null input inputs", "printf '1 2 3' | jq -nc '[inputs]'"),
    ("jq: null input reduce inputs", "printf '1 2 3' | jq -n 'reduce inputs as $x (0; . + $x)'"),
    ("jq: input pairs", "printf '1 2 3 4' | jq -c '[., input]'"),
    ("jq: exit status null", "jq -ne null; echo status=$?"),
    ("jq: exit status false then true", "jq -ne 'false, 1'; echo status=$?"),
    ("jq: exit status no output", "jq -ne empty; echo status=$?"),
    ("jq: exit status truthy", """echo '{"ok":true}' | jq -e .ok >/dev/null && echo yes"""),
    ("jq: compact tab indent", """echo '{"a":[1,{"b":2}]}' | jq --tab . && echo '{"a":[1]}' | jq --indent 1 . && echo '{"a":[1]}' | jq --indent 0 ."""),
    ("jq: sort keys", """echo '{"b":1,"a":{"d":1,"c":2}}' | jq -S -c ."""),
    ("jq: join output", "jq -nj '\"a\", 1, \"b\"'; echo"),
    ("jq: raw output0", "jq -n --raw-output0 '\"a\",\"b\"' | cat -v; echo"),
    ("jq: ascii output", "jq -nac '\"é😀\", {\"ü\":1}'"),
    ("jq: seq", "jq -nc --seq '1, [2]' | cat -v"),
    ("jq: combined short flags", "echo '[\"a\",\"b\"]' | jq -rc '.[]'"),
    ("jq: file operands", """printf '{"x":1}' > /tmp/a.json; printf '{"x":2}' > /tmp/b.json; jq .x /tmp/a.json /tmp/b.json"""),
    ("jq: input filename", """echo 1 > /tmp/a.json; echo 2 > /tmp/b.json; jq -c '[., input_filename]' /tmp/a.json /tmp/b.json; echo 3 | jq -c '[., input_filename]'; jq -nc input_filename"""),
    ("jq: slurp files", """printf '[1]' > /tmp/a.json; printf '[2]' > /tmp/b.json; jq -c -s . /tmp/a.json /tmp/b.json"""),
    ("jq: stdin operand", """echo '{"a":1}' | jq .a -"""),
    ("jq: filter from file", """echo '.a | . * 2' > /tmp/p.jq; echo '{"a":21}' | jq -f /tmp/p.jq"""),
    ("jq: slurpfile rawfile", """printf '1 2' > /tmp/v.json; printf 'text\\n' > /tmp/t.txt; jq -nc --slurpfile s /tmp/v.json --rawfile r /tmp/t.txt '[$s, $r]'"""),
    ("jq: env", "export JQ_T=val; jq -nr 'env.JQ_T, $ENV.JQ_T'"),
    ("jq: unexported var is not env", "JQ_U=hidden; jq -nc 'env.JQ_U'"),
    ("jq: debug", "jq -nc '1 | debug | . + 1'"),
    ("jq: debug message", "jq -nc '1 | debug(\"msg\", .) | . + 1'"),
    ("jq: stderr", "jq -n '\"s\" | stderr | empty'; jq -n '{a:1} | stderr | empty'; echo"),
    ("jq: halt", "jq -n 'halt'; echo status=$?"),
    ("jq: halt error string", "jq -n '\"bye\\n\" | halt_error'; echo status=$?"),
    ("jq: halt error object", "jq -n '{a:1} | halt_error(3)'; echo status=$?"),
    ("jq: error continues", """printf '1 {"a":2}' | jq .a; echo status=$?"""),
    ("jq: error message", """jq -n 'error("boom")'; echo status=$?"""),
    ("jq: error object", """jq -n 'error({a:1})'; echo status=$?"""),
    ("jq: an uncaught error ends that input's outputs", """jq -n '1, error("x"), 2'; echo status=$?"""),
    ("jq: array index too large", """for i in 536870912 2147483648 4294967295; do jq -nc "[] | .[$i] = 1 | length"; echo status=$?; done"""),
    ("jq: invalid input", "printf '1 abc 2' | jq .; echo status=$?"),
    ("jq: undefined function", "jq -n '1 | foo'; echo status=$?"),
    ("jq: undefined variable", "jq -n '$x'; echo status=$?"),
    ("jq: syntax error", "jq -n '.['; echo status=$?"),
    ("jq: unknown option", "jq --bogus .; echo status=$?"),
    ("jq: missing file", "echo 1 > /tmp/a.json; jq . /tmp/a.json /tmp/nope.json; echo status=$?"),
    ("jq: bad argjson", "jq -n --argjson x '{bad' '$x'; echo status=$?"),
    ("jq: indent limit", "jq --indent 9 -n 1; echo status=$?"),
    ("jq: stream refused", "echo 1 | jq --stream .; echo status=$?"),
    ("jq: loc", "jq -nc '$__loc__'"),
    ("jq: numbers", "jq -nc '[1.0, 1.5, 100000000000000000000, 3.0e2, -0, 0.1 + 0.2, 1e1000, infinite, nan]'"),
    ("jq: number literals pass through", "echo '[1.0, 1.50, 3e2, 100000000000000000001]' | jq -c ."),
    ("jq: unicode", """echo '{"k":"ø \\u00e9 \\ud83d\\ude00"}' | jq -c . && jq -nr '"tab\\there"'"""),
    ("jq: dates", """jq -nc '"2015-03-05T23:51:47Z" | [fromdate, (fromdate | todate), (fromdate | strftime("%Y-%m-%d %H:%M"))], (now | type)'"""),
    ("jq: paths and delete", """echo '{"a":1,"b":null,"c":{"d":null,"e":2}}' | jq -c 'del(.. | nulls), [paths(type == "number")]'"""),
    ("jq: endless producer", """while :; do echo '{"a":1}'; done | jq -c .a | head -n 2"""),
    ("jq: endless raw producer", "while :; do echo line; done | jq -R . | head -n 1"),
    ("jq: early null input ignores stdin", "while :; do echo 1; done | jq -n '\"ready\"' | head -n 1"),
    ("jq: help", "jq --help | head -n 1"),
    ("jq: nested assignment", """echo '{}' | jq -c '.config.retries = 3 | .list[2] = "x" | .n.m |= 5'"""),
    ("jq: array extension", "jq -nc '[1] | .[3] = 4'"),
    ("jq: null slice", "jq -nc 'null | .[1:]'"),
    ("jq: number output", "jq -nc '[10/2, 1/3, 100/3, 0.00001*1, 1e17*1, 2e21*1, 1000000000000000.5, 1.5*2, (7|./2)]'"),
    ("jq: number literals", "echo '[1e-5, 1E5, 0.00, 1.500e3, -0.0, 12e-9, 5e-7, 0.050]' | jq -c ."),
    ("jq: join", """jq -nr '[1,null,"a",true,1.5] | join("-")' && jq -nc '[] | join(",")'"""),
    ("jq: join rejects arrays", """jq -nr '[[1]] | join("-")'; echo status=$?"""),
    ("jq: csv tsv", """jq -nr '[1.5, 2, "a\\"b", null, true, (10/2)] | @csv, @tsv' && jq -nr '["a\\tb\\\\c\\nd"] | @tsv'"""),
    ("jq: csv of objects", """jq -nr '[{}] | @csv'; echo status=$?; jq -nr '"x" | @csv'; echo status=$?"""),
    ("jq: format interpolation", """jq -nr '@csv "row: \\([1,"a"])"' && jq -nr '@base64 "x=\\("hi")"'"""),
]

EXPECTED = {
    "jq: stream refused": (
        0, b"status=2\n", b"jq: --stream is unsupported in bash-tool\n",
        "bash-tool refuses --stream rather than emulating jq's streaming parser",
    ),
    "jq: help": (
        0, b"Usage:\tjq [OPTIONS] FILTER [FILES...]\n", b"", "our help text is jaq's, not jq's",
    ),
}
