"""Redirection forms beyond `exec`: order, duplication, noclobber, here-documents, fd variables."""

CASES = [
    ("redirect: order of dup and file", 'cd /tmp; { echo out; echo err >&2; } >f 2>&1; cat f; { echo out; echo err >&2; } 2>&1 >g | sed s/^/pipe:/; cat g'),
    ("redirect: append and truncate", 'cd /tmp; echo one >f; echo two >>f; cat f; : >f; wc -c <f; >f2 echo pre; cat f2'),
    ("redirect: both streams", 'cd /tmp; { echo o; echo e >&2; } &>f; cat f; { echo o2; echo e2 >&2; } &>>f; cat f', ["redirection.both"]),
    ("redirect: noclobber", 'cd /tmp; echo a >f; set -C; echo b >f; echo status=$?; echo c >|f; cat f; echo d >>f; cat f; set +C', ["redirection.noclobber"]),
    ("redirect: read and write descriptor", 'cd /tmp; echo hello >f; exec 3<>f; read -u 3 w; echo $w; exec 3>&-'),
    ("redirect: duplicate input", 'cd /tmp; echo line >f; exec 4<f; cat <&4; exec 4<&-'),
    ("redirect: move descriptors", 'cd /tmp; exec 5>f; exec 6>&5-; echo moved >&6; exec 6>&-; cat f; echo x >&5; echo status=$?'),
    ("redirect: close stdout", '{ echo gone; } >&-; echo status=$?; echo visible'),
    ("redirect: descriptor variables", 'cd /tmp; exec {fd}>f; echo "via $fd" >&$fd; [ $fd -ge 10 ] && echo high; exec {fd}>&-; cat f', ["redirection.fd-variable"]),
    ("redirect: descriptor variable read", 'cd /tmp; printf "a\\nb\\n" >f; exec {in}<f; read -u $in x; read -u $in y; echo $x$y; exec {in}<&-', ["redirection.fd-variable"]),
    ("redirect: here document expansion", 'x=val; cat <<EOF\n$x $(echo sub) $((1+1)) \\$literal\nEOF'),
    ("redirect: quoted here document", 'x=val; cat <<\'EOF\'\n$x $(echo no)\nEOF\ncat <<"E2"\n$x\nE2', ["redirection.heredoc.quoted"]),
    ("redirect: here document tab stripping", 'cat <<-EOF\n\tindented\n\t\tdeeper\n\tEOF', ["redirection.heredoc.strip"]),
    ("redirect: here documents on one command", 'cat <<A - <<B\nfirst\nA\nsecond\nB'),
    ("redirect: here document unterminated", 'cat <<EOF\nno end'),
    ("redirect: here string forms", 'x="a b"; cat <<< $x; cat <<< "$x"; wc -l <<< ""; read -r v <<< "  spaced  "; echo "[$v]"'),
    ("redirect: missing input file", 'cat </tmp/nosuch; echo status=$?; echo after'),
    ("redirect: missing output directory", 'echo x >/tmp/nodir/f; echo status=$?'),
    ("redirect: ambiguous redirect", 'e=; echo x >$e; echo status=$?; s="a b"; echo x >$s; echo status=$?'),
    ("redirect: redirect a directory", 'echo x >/tmp; echo status=$?; cat </tmp; echo status=$?'),
    ("redirect: stdin stdout stderr paths", 'echo out >/dev/stdout; echo err >/dev/stderr 2>&1; echo in | cat /dev/stdin; echo fd | cat /dev/fd/0', ["redirection.dev-paths"]),
    ("redirect: redirections on compound commands", 'cd /tmp; for i in 1 2; do echo $i; done >loop; if true; then echo if; fi >>loop; { echo grp; } >>loop; cat loop'),
    ("redirect: input to a loop", 'cd /tmp; printf "1\\n2\\n" >nums; while read n; do echo n$n; done <nums; s=0; while read n; do s=$((s+n)); done <nums; echo $s'),
    ("redirect: per-command redirect does not persist", 'cd /tmp; echo a >f 2>/dev/null; echo shown; ls nosuch 2>/dev/null; echo status=$?'),
    ("redirect: numbered descriptor to file", 'cd /tmp; { echo three >&3; } 3>f; cat f; echo x 1>&2 2>/dev/null'),
    ("redirect: bad descriptor", 'echo x >&7; echo status=$?; cat <&8; echo status=$?'),
]
