"""Edge inputs: Unicode text (multi-byte, combining, wide, RTL, ZWJ, BOM, no-break space) in data,
file names, IFS, patterns, case mapping and every text filter.

Generated from fixed tables with plain loops, so every Python 3 produces the same scripts.
"""

TIER = "sweep"


def sq(text):
    """Single-quote `text` for the shell."""
    return "'" + text.replace("'", "'\\''") + "'"


# Unicode input classes: each exercises a different byte length, width or property.
SAMPLES = [
    ("latin", "h\u00e9llo w\u00f6rld"),            # 2-byte letters
    ("cjk", "\u65e5\u672c\u8a9e \u30c6\u30ad\u30b9\u30c8"),  # 3-byte, double width
    ("emoji", "a\U0001F600b\U0001F44D\U0001F3FDc"),     # 4-byte, skin-tone modifier
    ("combining", "e\u0301te\u0301"),                  # decomposed accents, zero width
    ("hebrew", "\u05e9\u05dc\u05d5\u05dd \u05e2\u05d5\u05dc\u05dd"),  # right-to-left
    ("zwj", "\U0001F468\u200d\U0001F469\u200d\U0001F467 fam"),  # zero-width joiner sequence
    ("bom", "\ufeffbom text"),                         # byte-order mark at the start
    ("nbsp", "a\u00a0b c"),                            # no-break space between words
    ("greek", "\u0391\u03bb\u03c6\u03b1 \u0392\u0397\u03a4\u0391"),  # case pairs outside ASCII
]

# Operations on one line of text: (label, script with {d} the quoted sample).
PIPE = "printf '%s\\n' {d} | "
VAR = "x={d}; "
TEXT_OPS = [
    ("wc -c", PIPE + "wc -c"),
    ("wc -m", PIPE + "wc -m"),
    ("wc -w", PIPE + "wc -w"),
    ("wc -L", PIPE + "wc -L"),
    ("cut -c", PIPE + "cut -c1-3"),
    ("cut -b", PIPE + "cut -b1-3 | od -An -tx1"),
    ("head -c", PIPE + "head -c 4 | od -An -tx1"),
    ("tail -c", PIPE + "tail -c 4 | od -An -tx1"),
    ("rev", PIPE + "rev"),
    ("fold -w", PIPE + "fold -w 3"),
    ("sed any char", PIPE + "sed 's/./<&>/g'"),
    ("sed swap first two", PIPE + "sed 's/^\\(.\\)\\(.\\)/\\2\\1/'"),
    ("sed -n l", PIPE + "sed -n l"),
    ("grep -o dot", PIPE + "grep -o . | head -n 5"),
    ("grep -E interval", PIPE + "grep -E -o '^.{3}'"),
    ("grep alpha class", PIPE + "grep -o '[[:alpha:]]*'"),
    ("grep space class", PIPE + "grep -o '[[:space:]]' | wc -l"),
    ("sed alpha class", PIPE + "sed 's/[[:alpha:]]/A/g'"),
    ("od -c", PIPE + "od -An -c"),
    ("cat -A", PIPE + "cat -A"),
    ("tr delete ascii", PIPE + "tr -d 'a-z'"),
    ("tr upper classes", PIPE + "tr '[:lower:]' '[:upper:]'"),
    ("tr complement", PIPE + "tr -c 'a-z\\n' '_'"),
    ("base64", PIPE + "base64"),
    ("sha256sum", PIPE + "sha256sum"),
    ("jq length", PIPE + "jq -R 'length'"),
    ("jq explode", PIPE + "jq -c -R 'explode'"),
    ("jq ascii output", PIPE + "jq -a -R '.'"),
    ("jq slice", PIPE + "jq -R '.[1:3]'"),
    ("jq utf8bytelength", PIPE + "jq -R 'utf8bytelength'"),
    ("jq ascii_downcase", PIPE + "jq -R 'ascii_downcase'"),
    ("expr length", VAR + 'expr length "$x"'),
    ("expr substr", VAR + 'expr substr "$x" 2 3'),
    ("length", VAR + 'echo "${#x}"'),
    ("substring", VAR + 'echo "${x:1:3}"'),
    ("negative substring", VAR + 'echo "${x: -2}"'),
    ("upper", VAR + 'echo "${x^^}"'),
    ("lower", VAR + 'echo "${x,,}"'),
    ("upper first", VAR + 'echo "${x^}"'),
    ("lower first", VAR + 'echo "${x,}"'),
    ("trim one char front", VAR + 'echo "${x#?}"'),
    ("trim one char back", VAR + 'echo "${x%?}"'),
    ("char loop", VAR + 'n=0; while [ -n "$x" ]; do x=${x#?}; n=$((n+1)); done; echo $n'),
    ("transform Q", VAR + 'echo "${x@Q}"'),
    ("printf q", VAR + "printf '%q\\n' \"$x\""),
    ("declare -p", VAR + "declare -p x"),
    ("printf width", VAR + "printf '[%12s]\\n' \"$x\""),
    ("printf left width", VAR + "printf '[%-8s]\\n' \"$x\""),
    ("printf precision", VAR + "printf '[%.3s]\\n' \"$x\""),
    ("read -n", VAR + "IFS= read -r -n 3 y <<< \"$x\"; printf '%s\\n' \"$y\""),
    ("read -N", VAR + "IFS= read -r -N 2 y <<< \"$x\"; printf '%s\\n' \"$y\""),
    ("word split", VAR + "set -- $x; echo $#"),
    ("regex groups", VAR + '[[ $x =~ ^(.)(.) ]] && echo "${BASH_REMATCH[2]}"'),
    ("case space class", VAR + "case $x in *[[:space:]]*) echo space;; *) echo none;; esac"),
    ("xtrace", VAR + "set -x; : \"$x\""),
]

CASES = []
for op, template in TEXT_OPS:
    for sample, text in SAMPLES:
        CASES.append((f"edge unicode: {op} {sample}", template.replace("{d}", sq(text))))

# File names in several scripts, in one directory.
NAMES = ["h\u00e9llo.txt", "\u65e5\u672c.txt", "\U0001F600.txt", "\u05e9\u05dc\u05d5\u05dd.txt",
         "abc.txt", "e\u0301.txt", "a b.txt", "\u0394\u03b9\u03ac.txt"]
SETUP = "mkdir /tmp/u && cd /tmp/u && touch " + " ".join(sq(n) for n in NAMES) + "; "
FILE_OPS = [
    ("ls", "ls"),
    ("ls -r", "ls -r"),
    ("ls -1 | wc -l", "ls -1 | wc -l"),
    ("ls -b", "ls -b"),
    ("ls quoting escape", "ls --quoting-style=escape"),
    ("ls quoting c", "ls --quoting-style=c"),
    ("ls quoting shell-escape", "ls --quoting-style=shell-escape"),
    ("ls -Q", "ls -Q"),
    ("ls -m", "ls -m"),
    ("ls -x", "ls -x -w 40"),
    ("ls -C", "ls -C -w 30"),
    ("echo glob", "echo *"),
    ("glob one char", "printf '%s\\n' ?.txt"),
    ("glob two chars", "printf '%s\\n' ??.txt"),
    ("glob bracket", "printf '%s\\n' [\u65e5\U0001F600]*"),
    ("glob alpha class", "printf '%s\\n' [[:alpha:]]*"),
    ("glob upper class", "printf '%s\\n' [[:upper:]]*"),
    ("glob range", "printf '%s\\n' [\u0391-\u03a9]*"),
    ("extglob", "shopt -s extglob; printf '%s\\n' @(\u65e5\u672c|abc).txt"),
    ("extglob negation", "shopt -s extglob; printf '%s\\n' !(*[a-z]*).txt"),
    ("nocaseglob", "shopt -s nocaseglob; printf '%s\\n' H*"),
    ("nocaseglob greek", "shopt -s nocaseglob; printf '%s\\n' \u03b4*"),
    ("find -name", "find . -name '?.txt' | sort"),
    ("find -name bracket", "find . -name '[\u65e5\u05e9]*' | sort"),
    ("find -iname", "find . -iname 'H\u00c9*' | sort"),
    ("find -iname greek", "find . -iname '\u03b4*' | sort"),
    ("find -regex", "find . -regex '.*/..txt' | sort"),
    ("find -print0", "find . -name '*.txt' -print0 | sort -z | tr '\\0' '\\n'"),
    ("name lengths", "for f in *; do echo \"${#f} $f\"; done"),
    ("basename suffix", "basename /tmp/u/\u65e5\u672c.txt .txt"),
    ("basename suffix option", "basename -s .txt \u65e5\u672c.txt \U0001F600.txt"),
    ("dirname", "dirname /tmp/\u65e5/\u672c.txt"),
    ("realpath", "realpath \u65e5\u672c.txt"),
    ("readlink -f", "readlink -f ./\U0001F600.txt"),
    ("stat -c %n", "stat -c %n *.txt"),
    ("wc on names", "printf 'x\\n' > \u65e5\u672c.txt; wc -l \u65e5\u672c.txt abc.txt"),
    ("grep -l", "echo hit > \U0001F600.txt; grep -l hit *"),
    ("grep -H", "echo hit > \u05e9\u05dc\u05d5\u05dd.txt; grep -H hit \u05e9\u05dc\u05d5\u05dd.txt"),
    ("cp and ls", "cp \u65e5\u672c.txt \u672c.txt && ls \u672c.txt"),
    ("mv and ls", "mv \U0001F600.txt \U0001F601.txt && ls"),
    ("rm glob", "rm -v *\u00e9*; ls"),
    ("mkdir -v", "mkdir -v \u0434\u0438\u0440; mkdir -pv \u0434\u0438\u0440/\u5b50/\U0001F333"),
    ("find -type d", "mkdir -p \u0434/\u5b50; find . -type d | sort"),
    ("cd and pwd", "mkdir \u0434\u0438\u0440 && cd \u0434\u0438\u0440 && pwd && echo \"$PWD\""),
    ("ls -R", "mkdir \u5b50 && touch \u5b50/\u00e9; ls -R"),
    ("ln relative", "ln -s \u65e5\u672c.txt \u94fe && readlink \u94fe"),
    ("xargs names", "printf '%s\\n' * | xargs -n 3 echo"),
    ("xargs -I", "ls | xargs -I{} echo '<{}>'"),
    ("tsort names", "printf '\u65e5 \u672c\\n\u672c \u8a9e\\n' | tsort"),
    ("split prefix", "printf '1\\n2\\n3\\n' | split -l 1 - \u5206; ls \u5206*"),
    ("diff names", "echo a > \u65e5\u672c.txt; echo b > abc.txt; diff \u65e5\u672c.txt abc.txt"),
    ("cmp names", "echo a > \u65e5\u672c.txt; echo b > abc.txt; cmp \u65e5\u672c.txt abc.txt"),
    ("file names", "echo text > \u65e5\u672c.txt; file \u65e5\u672c.txt"),
    ("sha256sum names", "sha256sum \u65e5\u672c.txt"),
    ("md5sum -c names", "md5sum \u65e5\u672c.txt abc.txt > /tmp/sums; md5sum -c /tmp/sums"),
    ("touch missing parent", "touch \u65e0/\u6587\u4ef6"),
    ("cat missing name", "cat \u65e0\u6587\u4ef6.txt"),
    ("ls missing name", "ls \u65e0\u6587\u4ef6.txt"),
    ("cd missing name", "cd \u65e0\u6587\u4ef6"),
    ("rmdir missing name", "rmdir \u65e0\u6587\u4ef6"),
]
for op, script in FILE_OPS:
    CASES.append((f"edge unicode names: {op}", SETUP + script + "; echo status=$?"))

# Patterns, IFS and case mapping with non-ASCII characters, one construct each.
MISC = [
    ("case alpha class", "case \u00e9 in [[:alpha:]]) echo alpha;; *) echo other;; esac"),
    ("case upper class", "case \u00c9 in [[:upper:]]) echo upper;; *) echo other;; esac"),
    ("case range", "case \u03b2 in [\u03b1-\u03c9]) echo greek;; *) echo other;; esac"),
    ("case digit class", "case \u0663 in [[:digit:]]) echo digit;; *) echo other;; esac"),
    ("cond nocasematch", "shopt -s nocasematch; [[ \u00c9t\u00c9 == \u00e9t\u00e9 ]] && echo same || echo differ"),
    ("cond nocasematch greek", "shopt -s nocasematch; [[ \u0391\u0392 == \u03b1\u03b2 ]] && echo same || echo differ"),
    ("cond less than", "[[ \u00f6 < z ]] && echo less || echo more"),
    ("cond sort order", "[[ \u00e9 < \u00ea ]] && echo less || echo more"),
    ("cond regex alpha", "[[ \u00e9 =~ ^[[:alpha:]]$ ]] && echo one || echo no"),
    ("cond regex two chars", "[[ \u65e5\u672c =~ ^..$ ]] && echo two || echo no"),
    ("cond regex range", "[[ \u03b3 =~ ^[\u03b1-\u03c9]+$ ]] && echo yes || echo no"),
    ("cond glob question", "[[ \U0001F600 == ? ]] && echo one || echo no"),
    ("cond glob combining", "[[ e\u0301 == ? ]] && echo one || echo two"),
    ("replace char", "x=\u03b1\u03b2\u03b3; echo \"${x/\u03b2/b}\""),
    ("replace range", "x=\u03b1\u03b2\u03b3a; echo \"${x//[\u03b1-\u03b3]/x}\""),
    ("replace anchored", "x=\u00e9t\u00e9; echo \"${x/#\u00e9/E} ${x/%\u00e9/E}\""),
    ("trim pattern", "x=\u65e5\u672c\u8a9e.txt; echo \"${x%.*} ${x##*\u672c}\""),
    ("upper sharp s", "x=stra\u00dfe; echo \"${x^^}\""),
    ("lower dotted I", "x=\u0130; echo \"${x,,}\" | od -An -tx1"),
    ("upper dotless i", "x=\u0131; echo \"${x^^}\""),
    ("upper final sigma", "x=\u03bf\u03c2; echo \"${x^^}\""),
    ("lower final sigma", "x=\u039f\u03a3; echo \"${x,,}\""),
    ("upper ligature", "x=\ufb01; echo \"${x^^}\""),
    ("upper digraph", "x=\u01c6; echo \"${x^} ${x^^}\""),
    ("toggle case", "x=\u00e9\u00c9; echo \"${x~~}\""),
    ("upper pattern", "x=\u00e9t\u00e9; echo \"${x^^\u00e9}\""),
    ("declare -u", "declare -u x=\u00e9t\u00e9; echo \"$x\""),
    ("declare -l", "declare -l x=\u00c9T\u00c9; echo \"$x\""),
    ("IFS multibyte split", "IFS=\u00e9; x=a\u00e9b\u00e9c; set -- $x; echo $#; echo \"$2\""),
    ("IFS multibyte read", "IFS=\u65e5 read -r a b c <<< '1\u65e52\u65e53'; echo \"$a|$b|$c\""),
    ("IFS multibyte join", "IFS=\u00e9x; set -- a b c; echo \"$*\""),
    ("IFS array join", "a=(1 2 3); IFS=\u2192; echo \"${a[*]}\""),
    ("IFS space and multibyte", "IFS=' \u00e9'; x='a \u00e9 b'; set -- $x; echo $#"),
    ("IFS nbsp", "IFS=$'\\u00a0'; x=$'a\\u00a0b'; set -- $x; echo $#"),
    ("read -a unicode", "read -r -a arr <<< '\u03b1 \u03b2 \u03b3'; echo \"${#arr[@]} ${arr[1]}\""),
    ("read -d multibyte", "IFS= read -r -d \u00e9 x <<< 'ab\u00e9cd'; echo \"$x\""),
    ("mapfile -d multibyte", "mapfile -t -d \u00e9 arr <<< 'a\u00e9b\u00e9c'; echo \"${#arr[@]}\"; printf '[%s]' \"${arr[@]}\"; echo"),
    ("printf char code", "printf '%d %d %d\\n' \"'\u00e9\" \"'\u65e5\" \"'\U0001F600\""),
    ("printf hex char code", "printf '%x\\n' \"'\u20ac\""),
    ("printf %c", "printf '%c|\\n' \u00e9 \u65e5"),
    ("printf \\u", "printf '\\u20ac \\u00e9\\n'"),
    ("printf \\U", "printf '\\U0001F600\\n' | od -An -tx1"),
    ("printf %b \\u", "printf '%b\\n' '\\u20ac'"),
    ("echo -e \\u", "echo -e '\\u20ac\\U0001F600'"),
    ("ansi-c \\u", "x=$'\\u20ac\\U0001F600'; echo \"${#x} $x\""),
    ("ansi-c \\u surrogate", "x=$'\\ud800'; printf %s \"$x\" | od -An -tx1"),
    ("ansi-c \\U out of range", "x=$'\\U00110000'; printf %s \"$x\" | od -An -tx1"),
    ("printf \\u zero", "printf 'a\\u0000b\\n' | od -An -tx1"),
    ("printf \\u short", "printf '\\u41\\n'"),
    ("printf \\u no digits", "printf '\\uXYZ\\n'"),
    ("echo -e \\x high", "echo -e '\\xc3\\xa9'"),
    ("sort code points", "printf '%s\\n' \u00e9 z e \u00c9 \u65e5 a | sort"),
    ("sort -r", "printf '%s\\n' \u00e9 z e \u00c9 | sort -r"),
    ("sort -f", "printf '%s\\n' \u00e9 \u00c9 e E | sort -f"),
    ("sort -d", "printf '%s\\n' '\u00e9b' 'a-c' '!z' | sort -d"),
    ("sort -u", "printf '%s\\n' \u00e9 \u00e9 e | sort -u"),
    ("sort -k", "printf '%s\\n' 'x \u00e9' 'y a' 'z \u65e5' | sort -k2"),
    ("sort -t multibyte", "printf '%s\\n' 'a\u00e9b' | sort -t \u00e9 -k2"),
    ("uniq -i", "printf '%s\\n' \u00e9 \u00c9 e | uniq -i"),
    ("uniq -c", "printf '%s\\n' \u65e5 \u65e5 \u672c | uniq -c"),
    ("comm", "printf '%s\\n' a \u00e9 > /tmp/a; printf '%s\\n' \u00e9 \u65e5 > /tmp/b; comm /tmp/a /tmp/b"),
    ("join", "printf '%s\\n' '\u00e9 1' '\u65e5 2' > /tmp/a; printf '%s\\n' '\u00e9 x' '\u65e5 y' > /tmp/b; join /tmp/a /tmp/b"),
    ("join -t multibyte", "printf 'a\u00e9b\\n' > /tmp/a; join -t \u00e9 /tmp/a /tmp/a"),
    ("cut -d multibyte", "printf 'a\u00e9b\\n' | cut -d \u00e9 -f2"),
    ("paste -d multibyte", "printf '1\\n2\\n' > /tmp/a; paste -d \u00e9 /tmp/a /tmp/a"),
    ("paste -s -d multibyte", "printf '1\\n2\\n3\\n' | paste -s -d '\u00e9\u65e5'"),
    ("nl -s multibyte", "printf 'a\\nb\\n' | nl -s '\u2192 '"),
    ("seq -s multibyte", "seq -s '\u2192' 3"),
    ("expand after multibyte", "printf '\u00e9\\tb\\n' | expand -t 4"),
    ("expand after wide", "printf '\u65e5\\tb\\n' | expand -t 4"),
    ("unexpand multibyte", "printf '\u00e9       b\\n' | unexpand -a"),
    ("fmt multibyte", "printf '\u00e9t\u00e9 \u00e0 la plage \u00e9t\u00e9\\n' | fmt -w 10"),
    ("fold -s multibyte", "printf '\u00e9t\u00e9 \u00e0 la plage\\n' | fold -s -w 6"),
    ("fold -b", "printf '\u00e9t\u00e9\\n' | fold -b -w 3 | od -An -tx1"),
    ("tr multibyte sets", "printf 'ab\\n' | tr 'ab' '\u03b1\u03b2'"),
    ("tr multibyte source", "printf '\u03b1\u03b2\\n' | tr '\u03b1\u03b2' 'ab'"),
    ("tr -s multibyte", "printf '\u00f6\u00f6\u00f6\\n' | tr -s '\u00f6'"),
    ("tr -d multibyte", "printf 'h\u00e9llo\\n' | tr -d '\u00e9'"),
    ("sed y multibyte", "printf '\u03b1\u03b2\\n' | sed 'y/\u03b1\u03b2/ab/'"),
    ("sed range class", "printf '\u03b1\u03b2 x\\n' | sed -E 's/[\u03b1-\u03c9]+/G/g'"),
    ("sed case conversion", "printf '\u00e9t\u00e9\\n' | sed 's/.*/\\U&/'"),
    ("sed I flag", "printf '\u00c9T\u00c9\\n' | sed 's/\u00e9t\u00e9/ok/I'"),
    ("grep -i", "printf '\u00c9T\u00c9\\n' | grep -i '\u00e9t\u00e9'"),
    ("grep -i sharp s", "printf 'STRASSE\\nstra\u00dfe\\n' | grep -i 'stra\u00dfe'"),
    ("grep -w", "printf 'w\u00f6rld\\nw\u00f6rlds\\n' | grep -w 'w\u00f6rld'"),
    ("grep -b -o", "printf '\u00e9 \u65e5 x\\n' | grep -b -o '[^ ]*'"),
    ("grep -P word", "printf '\u00e9t\u00e9 abc\\n' | grep -P -o '\\w+'"),
    ("grep -P digit", "printf '\u0663 3\\n' | grep -P -o '\\d'"),
    ("grep digit class", "printf '\u0663 3\\n' | grep -o '[[:digit:]]'"),
    ("grep range", "printf '\u03b1\u03b2\u03b3 abc\\n' | grep -E -o '[\u03b1-\u03c9]+'"),
    ("grep -c line", "printf '\u00e9\\n\u65e5\\n\\n' | grep -c '^.$'"),
    ("grep -x", "printf '\U0001F600\\n' | grep -x '.'"),
    ("jq string length", "jq -n '\"\u00e9\U0001F600\" | length'"),
    ("jq implode", "jq -n '[233, 128512] | implode'"),
    ("jq surrogate pair", "jq -n '\"\\ud83d\\ude00\"' | od -An -tx1"),
    ("jq lone surrogate", "jq -n '\"\\ud800\"' | od -An -tx1"),
    ("jq ascii_upcase", "jq -n '\"\u00e9cole\" | ascii_upcase'"),
    ("jq @uri", "jq -rn '\"\u00e9 \u65e5\" | @uri'"),
    ("jq @base64", "jq -rn '\"\u00e9\" | @base64'"),
    ("jq @base64d", "jq -rn '\"w6k=\" | @base64d'"),
    ("jq @sh", "jq -rn '\"\u00e9 x\" | @sh'"),
    ("jq @html", "jq -rn '\"<\u00e9>\" | @html'"),
    ("jq @json", "jq -rn '\"\u00e9\\u0001\" | @json'"),
    ("jq tojson", "jq -n '\"\u2028\" | tojson'"),
    ("jq split", "jq -c -n '\"\u65e5\u672c\u8a9e\" | split(\"\u672c\")'"),
    ("jq split empty", "jq -c -n '\"\u00e9\U0001F600\" | split(\"\")'"),
    ("jq index", "jq -n '\"h\u00e9llo\" | index(\"l\")'"),
    ("jq indices", "jq -c -n '\"\u00e9a\u00e9a\" | indices(\"a\")'"),
    ("jq ltrimstr", "jq -n '\"\u65e5\u672c\" | ltrimstr(\"\u65e5\")'"),
    ("jq test regex", "jq -n '\"\u00e9\" | test(\"^.$\")'"),
    ("jq test ignore case", "jq -n '\"\u00c9\" | test(\"\u00e9\"; \"i\")'"),
    ("jq sort strings", "jq -c -n '[\"\u00e9\",\"e\",\"z\",\"\u00c9\"] | sort'"),
    ("jq keys order", "jq -c -n '{\"b\":1,\"\u00e9\":2,\"a\":3} | keys'"),
    ("jq sort_keys output", "jq -S -c -n '{\"\u65e5\":1,\"a\":2}'"),
    ("jq raw unicode output", "jq -r -n '\"\\u00e9\\u65e5\"'"),
    ("jq -a escapes", "jq -a -n '\"\u00e9\U0001F600\"'"),
    ("jq -j", "jq -j -n '\"\u00e9\", \"\u65e5\"'"),
    ("jq string compare", "jq -n '\"\u00e9\" < \"z\"'"),
    ("jq input unicode escapes", "printf '\"\\\\u00e9\"\\n' | jq ."),
    ("jq raw input slurp", "printf '\u00e9\\n\u65e5' | jq -Rs 'length'"),
    ("expr index", "expr index '\u00e9t\u00e9' 't'"),
    ("expr match", "expr '\u00e9t\u00e9' : '\\(..\\)'"),
    ("expr compare", "expr '\u00e9' '<' 'z'"),
    ("diff -i", "printf '\u00c9\\n' > /tmp/a; printf '\u00e9\\n' > /tmp/b; diff -i /tmp/a /tmp/b; echo $?"),
    ("diff unified", "printf '\u00e9\\n' > /tmp/a; printf '\u65e5\\n' > /tmp/b; diff -u /tmp/a /tmp/b | tail -n 2"),
    ("diff -y", "printf '\u65e5\u672c\\n' > /tmp/a; printf 'ab\\n' > /tmp/b; diff -y -W 20 /tmp/a /tmp/b"),
    ("cmp -l", "printf '\u00e9' > /tmp/a; printf '\u00ea' > /tmp/b; cmp -l /tmp/a /tmp/b"),
    ("cmp -b", "printf '\u00e9' > /tmp/a; printf '\u00ea' > /tmp/b; cmp -b /tmp/a /tmp/b"),
    ("od -tc wide", "printf '\u65e5' | od -An -tc"),
    ("cat -v", "printf '\u00e9\\n' | cat -v"),
    ("xargs -d multibyte", "printf 'a\u00e9b' | xargs -d \u00e9 echo"),
    ("xargs quoted unicode", "printf '\"\u00e9 \u65e5\" x\\n' | xargs -n 1 echo"),
    ("basenc base16", "printf '\u00e9' | basenc --base16"),
    ("base32", "printf '\u00e9\\n' | base32"),
    ("printf %s width wide", "printf '[%4s]\\n' \u65e5"),
    ("printf %-s width emoji", "printf '[%-4s]\\n' \U0001F600"),
    ("printf %.2s cjk", "printf '[%.2s]\\n' \u65e5\u672c\u8a9e"),
    ("echo -n bytes", "echo -n \u00e9 | wc -c"),
    ("heredoc unicode", "cat <<EOF\n\u00e9 \u65e5 \U0001F600\nEOF"),
    ("heredoc unicode expansion", "x=\u65e5; cat <<EOF\n${x}\u672c ${#x}\nEOF"),
    ("herestring unicode", "wc -m <<< '\u00e9\u65e5'"),
    ("brace unicode", "echo {\u03b1,\u03b2}{1,2}"),
    ("brace unicode range", "echo {\u03b1..\u03b3}"),
    ("array unicode keys", "declare -A m=([\u00e9]=1 [\u65e5]=2); echo \"${m[\u00e9]} ${m[\u65e5]} ${#m[@]}\""),
    ("function unicode body", "f() { echo \"\u00e9$1\"; }; f \u65e5"),
    ("printf %s multiple", "printf '%s-' \u00e9 \u65e5 \U0001F600; echo"),
    ("getopts unicode arg", "set -- -a \u00e9 x; while getopts a: o; do echo \"$o $OPTARG\"; done"),
    ("test -n unicode", "[ -n \u00e9 ] && [ \u00e9 = \u00e9 ] && [ \u00e9 != e ] && echo ok"),
    ("test string compare", "[ \u00e9 \\< z ] && echo less || echo more"),
    ("let unicode var error", "let '\u00e9=1'; echo $?"),
    ("unicode variable name", "\u00e9=1; echo $?"),
    ("unicode function name", "\u00e9() { echo called; }; \u00e9"),
    ("unicode alias", "shopt -s expand_aliases; alias \u00e9='echo aliased'\n\u00e9"),
    ("command not found unicode", "\u65e5\u672c; echo $?"),
]
for op, script in MISC:
    CASES.append((f"edge unicode: {op}", script))
