"""Grammar sweep: the reduced case for each divergence the generated grammar sweep found, one
per root cause, so each finding is pinned by the smallest script that shows it."""

TIER = "sweep"

MINIMAL = [
    ("C2-01", "expansion after a here-document operator on the same line",
     'f=/tmp/out.txt; cat <<EOF > "${f}"\nhello\nEOF\ncat /tmp/out.txt'),
    ("C2-02", "recursive function thirty calls deep",
     'd() { if [ $1 -gt 0 ]; then d $(($1-1)); fi; }; d 30; echo ok'),
    ("C2-03", "arithmetic command error continues the list",
     '((1/0)); echo "after $?"'),
    ("C2-04", "arithmetic constant too great for its base",
     'echo $((08))'),
    ("C2-05", "associative element in arithmetic",
     'declare -A m=([k]=5); echo $((m[k] * 2))'),
    ("C2-06", "quotes inside arithmetic",
     "a=7; echo $(( 'a' + 1 ))"),
    ("C2-07", "legacy arithmetic with a subscript and a comparison",
     'a=(5 6); echo $[a[0] < 9]'),
    ("C2-08", "subscript with an operator in an assignment word",
     'cd /tmp; x=3; b[x>2]=y; echo "keys=${!b[@]}"; echo *'),
    ("C2-09", "nameref to an array element",
     "a=(x y); declare -n r='a[1]'; echo \"[$r]\"; r=z; echo \"${a[1]}\""),
    ("C2-10", "self-referencing nameref",
     'declare -n r=r; echo "status=$?"'),
    ("C2-11", "readonly array element assignment",
     'a=(x); readonly a; a[1]=y; echo "status=$? ${a[*]}"'),
    ("C2-12", "readonly assignment in arithmetic",
     'readonly k=1; (( k = 2 )); echo "after status=$?"'),
    ("C2-13", "unset of a quoted associative key",
     "declare -A m=([k]=v); unset \"m['k']\"; echo ${#m[@]}"),
    ("C2-14", "associative array key order",
     'declare -A m=([one]=1 [two]=2 [three]=3 [four]=4); echo ${!m[@]}'),
    ("C2-15", "unset of every element with an at subscript",
     "a=(x y); unset 'a[@]'; echo ${#a[@]}"),
    ("C2-16", "read into an array element",
     "read -r 'a[1]' <<< line; echo \"[${a[1]}]\""),
    ("C2-17", "exported array in a child shell",
     "export a=(x); bash -c 'echo \"[${a-unset}]\"'"),
    ("C2-18", "export of an expanded assignment",
     "v='x=1'; export $v; echo \"[${x-unset}]\""),
    ("C2-19", "key-value transform of an associative array",
     'declare -A m=([k]=v); echo ${m[@]@K}'),
    ("C2-20", "case toggle operator",
     'v=abC; echo ${v~~}'),
    ("C2-21", "bad substitution",
     'v=abcd; echo "${v:}"; echo after'),
    ("C2-22", "shortest trim with a star",
     'v=abc; echo "${v#*} ${v%*}"'),
    ("C2-23", "ampersand in a pattern replacement",
     'v=abc; echo "${v/b/[&]}"'),
    ("C2-24", "alternative of an empty array",
     'a=(); set -- "${a[@]:+W}"; echo $#'),
    ("C2-25", "assignment operator on a positional parameter",
     'set --; : ${1:=x}'),
    ("C2-26", "length of the status parameter",
     'false; echo "${#?}"'),
    ("C2-27", "prefix names include declared unset variables",
     'declare pre_x; pre_y=1; echo ${!pre*}'),
    ("C2-28", "indirection through an invalid name",
     "r='a b'; echo ${!r}"),
    ("C2-29", "character class against a non-ASCII letter",
     'v=éa; echo "${v#[[:alpha:]]}"'),
    ("C2-30", "octal escape above 255",
     "x=$'\\777'; echo ${#x}"),
    ("C2-31", "escaped dollar inside backquotes",
     'v=V; echo `echo \\$v`'),
    ("C2-32", "case statement inside command substitution",
     'echo $(case a in a) echo m;; esac)'),
    ("C2-33", "function substitution",
     'x=${ echo hi; }; echo "[$x]"'),
    ("C2-34", "letter sequence across punctuation",
     'echo {Z..a}'),
    ("C2-35", "read with an escaped IFS character",
     "IFS=: read x y <<< 'a\\:b:c'; echo \"$x|$y\""),
    ("C2-36", "mapfile callback",
     "mapfile -t -C 'echo cb' -c 1 a <<< x; echo \"status=$?\""),
    ("C2-37", "exit with too many arguments",
     'exit 1 2; echo after'),
    ("C2-38", "break with a zero count in nested loops",
     'for i in 1 2; do for j in a b; do break 0; done; echo $i; done; echo "end $?"'),
    ("C2-39", "break in a pipeline stage",
     'for i in 1 2; do echo x | break; echo $i; done'),
    ("C2-40", "kill of a subshell by BASHPID",
     '( kill -TERM $BASHPID; echo not ) 2>/dev/null; echo "status=$?"'),
    ("C2-41", "BASH_SUBSHELL in a pipeline stage",
     'echo $BASH_SUBSHELL | cat'),
    ("C2-42", "nested subshell with a space",
     '( (echo spaced) )'),
    ("C2-43", "failed redirection on a group",
     '{ echo in; } > /tmp/no/x; echo "status=$?"'),
    ("C2-44", "noclobber and the both-streams operator",
     'cd /tmp; echo old > f; set -C; echo new &> f; echo "status=$?"; cat f'),
    ("C2-45", "line continuation in a here-document",
     'cat <<EOF\na \\\nb\nEOF'),
    ("C2-46", "alias ending in a space",
     "shopt -s expand_aliases\nalias run='echo run '\nalias w=word\nrun w"),
    ("C2-47", "alias value with a lone quote",
     "alias z='echo it'\\''s'; alias"),
    ("C2-48", "DEBUG trap before arithmetic and conditional commands",
     'trap \'echo "> $BASH_COMMAND"\' DEBUG; (( 1 )); [[ x ]]; trap - DEBUG'),
    ("C2-49", "RETURN trap after source",
     "echo 'echo body' > /tmp/s.sh; trap 'echo ret' RETURN; . /tmp/s.sh"),
    ("C2-50", "ERR trap for a failing group",
     "trap 'echo err' ERR; { false; }"),
    ("C2-51", "EXIT trap when killed by TERM",
     "trap 'echo cleanup' EXIT; kill -TERM $$; echo after"),
    ("C2-52", "unset last background pid under nounset",
     'set -u; echo "[$!]"; echo after'),
    ("C2-53", "PS4 expansion",
     "PS4='+$LINENO: '; set -x; echo a"),
    ("C2-54", "empty TIMEFORMAT",
     'TIMEFORMAT=; time true'),
    ("C2-55", "dot without a file name",
     '.; echo "status=$?"'),
    ("C2-56", "printed function with a here-document sourced back",
     "f() {\ncat <<EOF\nhi\nEOF\n}\ndeclare -f f > /tmp/f.sh; unset -f f; . /tmp/f.sh; f"),
    ("C2-57", "test with -o and -a precedence",
     "test x -o '' -a ''; echo $?"),
    ("C2-58", "GLOBIGNORE with a bracket pattern",
     "cd /tmp; : > a; : > b; : > c; GLOBIGNORE='[ab]'; echo *"),
    ("C2-59", "globstar after a directory star",
     'cd /tmp; mkdir -p d; : > d/f; : > g; shopt -s globstar; echo */**'),
    ("C2-60", "negated extglob against the empty string",
     'shopt -s extglob\n[[ "" == !(*) ]] && echo matched-empty'),
    ("C2-61", "failglob inside a function",
     'shopt -s failglob; f() { echo nomatch*; echo in-f; }; f; echo "status=$?"'),
    ("C2-62", "for with an invalid variable name",
     'for 1x in a; do echo "[$1x]"; done; echo "status=$?"'),
    ("C2-63", "return in a pipeline stage",
     'f() { echo x | return 5; echo "after $?"; }; f'),
    ("C2-64", "caller in a command string",
     'f() { caller 0; }; g() { f; }\ng'),
    ("C2-65", "export of a name without a value",
     'export ev; declare -p ev'),
    ("C2-66", "test -ef on a missing file",
     "test x -ef x; echo $?"),
    ("C2-67", "redirection to an empty file name",
     "echo x > ''; echo \"status=$?\""),
    ("C2-68", "kill -l of an exit status",
     'kill -l 130'),
    ("C2-69", "close redirection followed by a word",
     'cd /tmp; echo x >&-1; echo "status=$?"'),
    ("C2-70", "negation after a pipe",
     '! true | ! true'),
    ("C2-71", "assignment with a failed redirection",
     'v=1 > /tmp/no/x; echo "[${v-unset}] $?"'),
    ("C2-72", "set dash turns off xtrace",
     'set -x; set -; echo quiet'),
    ("C2-73", "USR1 trap",
     "trap 'echo usr1' USR1; kill -USR1 $$; echo after"),
    ("C2-74", "here-document expansion side effect with cat",
     'n=0; cat <<EOF\n$((n+=1))\nEOF\necho "n=$n"'),
    ("C2-75", "local nameref named like its target",
     'f() { local -n v=v; v=x; }; v=orig; f; echo "$v"'),
    ("C2-76", "mapfile with an invalid array name",
     'mapfile 1bad <<< x; echo "status=$?"'),
    ("C2-77", "lowercase and uppercase attributes together",
     'declare -lu v=MiX; echo $v'),
    ("C2-78", "status seen by a RETURN trap",
     'f() { trap \'echo "ret $?"\' RETURN; return 4; }; f'),
    ("C2-79", "EXIT trap in a command substitution",
     'x=$(trap \'echo cs-exit\' EXIT; echo in); echo "[$x]"'),
    ("C2-80", "uppercasing sharp s",
     "v='élan ß'; echo \"${v^^}\""),
    ("C2-81", "empty associative key",
     'declare -A m; m[\'\']=v; echo "status=$?"'),
    ("C2-82", "read of zero characters",
     "read -n 0 x <<< abc; echo \"[$x]\""),
    ("C2-83", "ANSI-C quote inside a double-quoted default",
     'unset u; x="${u:-$\'a\\tb\'}"; echo "$x"'),
    ("C2-84", "read with blanks around a non-blank IFS delimiter",
     "IFS=': ' read -r k v <<< 'key : value'; echo \"[$k] [$v]\""),
]

CASES = [("gram minimal " + cid + ": " + label, script) for cid, label, script in MINIMAL]
