"""Option sweep, part A: every option of the checksum, encoding, cat, comm, cp, csplit and cut
commands, with their error paths and meaningful combinations.

Error paths print the status and then the diagnostic through `sed`, which folds GNU's curly
quotes (which it uses under the oracle's UTF-8 locale; see UTF8_QUOTES in the existing corpora)
into ASCII ones, so a case compares the words and the status rather than the quote style.
"""

TIER = "sweep"
CASES = []


def err(script):
    """Run SCRIPT, then print its status and its stderr with curly quotes made ASCII."""
    return "{ " + script + "; } 2>/tmp/err; echo \"status=$?\"; sed \"s/[‘’]/'/g\" /tmp/err"


def add(cmd, label, script, error=False):
    tags = [f"cmd.{cmd}"]
    if error:
        tags += [f"cmd.{cmd}.error", "error"]
        script = err(script)
    CASES.append((f"opt {cmd}: {label}", script, tags))


# --- checksum commands -------------------------------------------------------------------------
SUMS = ["md5sum", "sha1sum", "sha256sum", "sha512sum", "b2sum"]
TWO = r"printf 'hello\n' >/tmp/a; printf '' >/tmp/b; "
for s in SUMS:
    add(s, "stdin", "printf 'abc' | " + s)
    add(s, "dash operand", "printf 'abc' | " + s + " -")
    add(s, "two files", TWO + s + " /tmp/a /tmp/b")
    add(s, "tag", TWO + s + " --tag /tmp/a")
    add(s, "binary mode marker", TWO + s + " -b /tmp/a")
    add(s, "text mode", TWO + s + " -t /tmp/a")
    add(s, "zero terminated", TWO + s + " -z /tmp/a | od -An -c | tail -n 2")
    add(s, "check ok", TWO + s + " /tmp/a /tmp/b >/tmp/sums; " + s + " -c /tmp/sums")
    add(s, "check quiet", TWO + s + " /tmp/a /tmp/b >/tmp/sums; printf x >>/tmp/b; " + s + " -c --quiet /tmp/sums; echo \"status=$?\"")
    add(s, "check status only", TWO + s + " /tmp/a >/tmp/sums; " + s + " -c --status /tmp/sums; echo \"status=$?\"; printf y >/tmp/a; " + s + " --status -c /tmp/sums; echo \"status=$?\"")
    add(s, "check missing file", TWO + s + " /tmp/a /tmp/b >/tmp/sums; rm /tmp/b; " + s + " -c /tmp/sums", error=True)
    add(s, "check ignore missing", TWO + s + " /tmp/a /tmp/b >/tmp/sums; rm /tmp/b; " + s + " -c --ignore-missing /tmp/sums; echo \"status=$?\"")
    add(s, "check malformed lines warn", TWO + s + " /tmp/a >/tmp/sums; echo garbage >>/tmp/sums; " + s + " -c -w /tmp/sums", error=True)
    add(s, "check strict", TWO + s + " /tmp/a >/tmp/sums; echo garbage >>/tmp/sums; " + s + " -c --strict /tmp/sums", error=True)
    add(s, "check no valid lines", "echo nothing >/tmp/sums; " + s + " -c /tmp/sums", error=True)
    add(s, "check tagged format", TWO + s + " --tag /tmp/a >/tmp/sums; " + s + " -c /tmp/sums")
    add(s, "missing file", s + " /tmp/nosuch", error=True)
    add(s, "directory operand", "mkdir /tmp/d; " + s + " /tmp/d", error=True)
    add(s, "unknown option", s + " --bogus", error=True)
    add(s, "status with no check", s + " --status /tmp/a", error=True)
    add(s, "escaped file name", "printf x >'/tmp/a\\b'; " + s + " '/tmp/a\\b'")
    add(s, "newline in file name", "printf x >'/tmp/a\nb'; " + s + " '/tmp/a\nb'")
    add(s, "check from stdin", TWO + s + " /tmp/a | " + s + " -c")
    add(s, "tag with text mode rejected", TWO + s + " --tag -t /tmp/a", error=True)
add("b2sum", "length 256", "printf abc | b2sum -l 256")
add("b2sum", "length 8", "printf abc | b2sum --length=8")
add("b2sum", "length not multiple of 8", "printf abc | b2sum -l 12", error=True)
add("b2sum", "length too big", "printf abc | b2sum -l 1024", error=True)
add("b2sum", "length tagged", "printf abc | b2sum -l 128 --tag")
add("b2sum", "check with length", "printf abc >/tmp/a; b2sum -l 128 /tmp/a >/tmp/s; b2sum -c /tmp/s")

# --- cksum ---------------------------------------------------------------------------------------
ABC = "printf 'abc\\n' >/tmp/a; "
for algo in ["sysv", "bsd", "crc", "crc32b", "md5", "sha1", "sha224", "sha256", "sha384", "sha512", "blake2b", "sm3"]:
    add("cksum", f"algorithm {algo}", ABC + f"cksum -a {algo} /tmp/a")
add("cksum", "default crc on stdin", "printf 'abc\\n' | cksum")
add("cksum", "two files", ABC + "printf '' >/tmp/b; cksum /tmp/a /tmp/b")
add("cksum", "sha2 with length", ABC + "cksum -a sha2 -l 256 /tmp/a")
add("cksum", "sha3 with length", ABC + "cksum -a sha3 -l 256 /tmp/a")
add("cksum", "sha2 without length", ABC + "cksum -a sha2 /tmp/a", error=True)
add("cksum", "untagged", ABC + "cksum -a sha256 --untagged /tmp/a")
add("cksum", "base64 digest", ABC + "cksum -a md5 --base64 /tmp/a")
add("cksum", "raw digest", ABC + "cksum -a md5 --raw /tmp/a | od -An -tx1")
add("cksum", "raw crc", ABC + "cksum --raw /tmp/a | od -An -tx1")
add("cksum", "blake2b length", ABC + "cksum -a blake2b -l 64 /tmp/a")
add("cksum", "zero terminated", ABC + "cksum -a md5 -z /tmp/a | od -An -c | tail -n 1")
add("cksum", "check tagged", ABC + "cksum -a sha1 /tmp/a >/tmp/s; cksum -c /tmp/s")
add("cksum", "check untagged needs algorithm", ABC + "cksum -a sha1 --untagged /tmp/a >/tmp/s; cksum -a sha1 -c /tmp/s")
add("cksum", "check crc rejected", ABC + "cksum /tmp/a >/tmp/s; cksum -c /tmp/s", error=True)
add("cksum", "check mismatch", ABC + "cksum -a md5 /tmp/a >/tmp/s; echo z >/tmp/a; cksum -c /tmp/s", error=True)
add("cksum", "check quiet and status", ABC + "cksum -a md5 /tmp/a >/tmp/s; cksum -c --quiet /tmp/s; echo \"q=$?\"; cksum -c --status /tmp/s; echo \"s=$?\"")
add("cksum", "invalid algorithm", ABC + "cksum -a nope /tmp/a", error=True)
add("cksum", "length with md5", ABC + "cksum -a md5 -l 128 /tmp/a", error=True)
add("cksum", "missing file", "cksum /tmp/nosuch", error=True)
add("cksum", "empty input", "cksum </dev/null")
add("cksum", "bsd on stdin", "printf 'abc\\n' | cksum -a bsd")
add("cksum", "sysv two files", ABC + "printf 'xyz' >/tmp/b; cksum -a sysv /tmp/a /tmp/b")

# --- base32 / base64 -----------------------------------------------------------------------------
for b in ["base32", "base64"]:
    add(b, "encode stdin", "printf 'hello world' | " + b)
    add(b, "encode file", "printf 'hello' >/tmp/a; " + b + " /tmp/a")
    add(b, "wrap 4", "printf 'hello world' | " + b + " -w 4")
    add(b, "wrap 0", "printf '%0100d' 0 | " + b + " --wrap=0; echo")
    add(b, "default wrap 76", "printf '%0100d' 0 | " + b)
    add(b, "decode", "printf 'hello' | " + b + " | " + b + " -d")
    add(b, "decode long option", "printf 'hi there' | " + b + " | " + b + " --decode")
    add(b, "decode with newlines", "printf 'hello world, longer text' | " + b + " -w 5 | " + b + " -d")
    add(b, "decode garbage", "printf '@@@@' | " + b + " -d", error=True)
    add(b, "decode ignore garbage", "printf 'hello' | " + b + " | sed 's/./&!/2' | " + b + " -d -i")
    add(b, "invalid wrap", "printf x | " + b + " -w x", error=True)
    add(b, "negative wrap", "printf x | " + b + " -w -1", error=True)
    add(b, "extra operand", "printf x >/tmp/a; " + b + " /tmp/a /tmp/a", error=True)
    add(b, "missing file", b + " /tmp/nosuch", error=True)
    add(b, "empty input", b + " </dev/null; echo \"status=$?\"")
    add(b, "binary bytes", "printf '\\377\\000\\200' | " + b)
    add(b, "decode truncated input", "printf 'aGVsbG8' | " + b + " -d", error=True)
    add(b, "dash operand", "printf abc | " + b + " -")
    add(b, "decode alias D", "printf 'hi' | " + b + " | " + b + " -D", error=True)
add("base64", "decode without padding", "printf 'aGk' | base64 -d", error=True)
add("base64", "decode url alphabet rejected", "printf '__8=' | base64 -d", error=True)
add("base32", "decode lowercase", "printf 'nbswy3dp' | base32 -d", error=True)

# --- basenc ------------------------------------------------------------------------------------
ENC = ["base64", "base64url", "base32", "base32hex", "base16", "base2lsbf", "base2msbf", "z85", "base58"]
for e in ENC:
    data = "abcd" if e == "z85" else "hi?>"
    add("basenc", f"{e} encode", f"printf '{data}' | basenc --{e}")
    add("basenc", f"{e} round trip", f"printf '{data}' | basenc --{e} | basenc --{e} -d")
add("basenc", "z85 bad length", "printf 'abc' | basenc --z85", error=True)
add("basenc", "base16 decode lowercase", "printf '6869' | basenc --base16 -d", error=True)
add("basenc", "base16 wrap", "printf 'hello' | basenc --base16 -w 4")
add("basenc", "base2msbf decode bad digit", "printf '0120' | basenc --base2msbf -d", error=True)
add("basenc", "no encoding", "printf x | basenc", error=True)
add("basenc", "two encodings last wins", "printf 'hi' | basenc --base64 --base16")
add("basenc", "ignore garbage", "printf '68!69' | basenc --base16 -d -i")
add("basenc", "base64url decode", "printf '__8=' | basenc --base64url -d | od -An -tx1")
add("basenc", "base32hex decode", "printf 'D1KG====' | basenc --base32hex -d")

# --- basename / dirname --------------------------------------------------------------------------
add("basename", "trailing slashes", "basename /usr/lib/")
add("basename", "root", "basename /; basename //; basename ///")
add("basename", "empty string", "basename ''")
add("basename", "suffix operand equals name", "basename .txt .txt")
add("basename", "suffix not matched", "basename a.txt .log")
add("basename", "multiple", "basename -a /a/b /c/d/ e")
add("basename", "suffix option", "basename -s .c /x/a.c b.c c.h")
add("basename", "suffix long option", "basename --suffix=.c /x/a.c")
add("basename", "zero terminated", "basename -z /a/b | od -An -c")
add("basename", "missing operand", "basename", error=True)
add("basename", "extra operand", "basename a b c", error=True)
add("basename", "multiple long option", "basename --multiple a/b c/d")
add("basename", "dash-leading name", "basename -- -x/y")
add("basename", "unknown option", "basename -q x", error=True)
add("dirname", "no slash", "dirname file")
add("dirname", "trailing slash", "dirname /a/b/")
add("dirname", "root forms", "dirname /; dirname //; dirname /a")
add("dirname", "multiple", "dirname /a/b c/d e")
add("dirname", "zero terminated", "dirname -z /a/b c/d | od -An -c")
add("dirname", "missing operand", "dirname", error=True)
add("dirname", "empty string", "dirname ''")
add("dirname", "double slashes inside", "dirname a//b//c")
add("dirname", "dot components", "dirname ./a; dirname ../b; dirname .")
add("dirname", "unknown option", "dirname --bogus x", error=True)

# --- cat -----------------------------------------------------------------------------------------
CATIN = r"printf 'a\tb\n\n\n\nc\001d\177\n\200\377x\r\n' >/tmp/f; "
for flag in ["-A", "-b", "-e", "-E", "-n", "-s", "-t", "-T", "-u", "-v", "--show-all", "--number-nonblank", "--show-ends", "--number", "--squeeze-blank", "--show-tabs", "--show-nonprinting"]:
    add("cat", f"{flag} option", CATIN + f"cat {flag} /tmp/f")
for combo in ["-bn", "-ns", "-bs", "-sE", "-nT", "-vE", "-An", "-et", "-sb"]:
    add("cat", f"{combo} combination", CATIN + f"cat {combo} /tmp/f")
add("cat", "number across files", "printf 'a\\nb\\n' >/tmp/x; printf 'c\\n' >/tmp/y; cat -n /tmp/x /tmp/y")
add("cat", "number without trailing newline", "printf 'a\\nb' >/tmp/x; cat -n /tmp/x /tmp/x")
add("cat", "show ends without trailing newline", "printf 'a\\nb' | cat -E")
add("cat", "stdin between files", "printf 'x\\n' >/tmp/x; printf 'in\\n' | cat /tmp/x - /tmp/x")
add("cat", "missing file continues", "printf 'x\\n' >/tmp/x; cat /tmp/x /tmp/nosuch /tmp/x", error=True)
add("cat", "directory operand", "mkdir /tmp/d; cat /tmp/d", error=True)
add("cat", "unknown short option", "cat -z", error=True)
add("cat", "unknown long option", "cat --number-all", error=True)
add("cat", "squeeze at start", "printf '\\n\\n\\na\\n' | cat -s")
add("cat", "number nonblank with only blanks", "printf '\\n\\n' | cat -b")
add("cat", "show nonprinting high bytes", "printf '\\201\\233\\240\\376' | cat -v; echo")
add("cat", "crlf with show ends", "printf 'a\\r\\nb\\r\\n' | cat -E")
add("cat", "empty file", "printf '' >/tmp/e; cat /tmp/e; echo \"status=$?\"")
add("cat", "double dash", "printf 'x\\n' >/tmp/-n; cd /tmp && cat -- -n")

# --- comm ----------------------------------------------------------------------------------------
CM = r"printf 'a\nb\nd\n' >/tmp/1; printf 'b\nc\nd\ne\n' >/tmp/2; "
for f in ["", "-1", "-2", "-3", "-12", "-13", "-23", "-123"]:
    add("comm", f"columns {f or 'all'}", CM + f"comm {f} /tmp/1 /tmp/2")
add("comm", "output delimiter", CM + "comm --output-delimiter=: /tmp/1 /tmp/2")
add("comm", "output delimiter multi-char", CM + "comm --output-delimiter='<>' -3 /tmp/1 /tmp/2")
add("comm", "empty output delimiter", CM + "comm --output-delimiter= /tmp/1 /tmp/2 | od -An -c")
add("comm", "total", CM + "comm --total /tmp/1 /tmp/2")
add("comm", "total with suppression", CM + "comm --total -12 /tmp/1 /tmp/2")
add("comm", "zero terminated", "printf 'a\\0b\\0' >/tmp/1; printf 'b\\0c\\0' >/tmp/2; comm -z /tmp/1 /tmp/2 | od -An -c")
add("comm", "unsorted input warns", "printf 'b\\na\\n' >/tmp/1; printf 'a\\nb\\n' >/tmp/2; comm /tmp/1 /tmp/2", error=True)
add("comm", "check order fails", "printf 'b\\na\\n' >/tmp/1; printf 'c\\n' >/tmp/2; comm --check-order /tmp/1 /tmp/2", error=True)
add("comm", "nocheck order", "printf 'b\\na\\n' >/tmp/1; printf 'a\\nb\\n' >/tmp/2; comm --nocheck-order /tmp/1 /tmp/2; echo \"status=$?\"")
add("comm", "stdin as first", CM + "cat /tmp/1 | comm - /tmp/2")
add("comm", "one operand", CM + "comm /tmp/1", error=True)
add("comm", "three operands", CM + "comm /tmp/1 /tmp/2 /tmp/2", error=True)
add("comm", "missing second file", CM + "comm /tmp/1 /tmp/nosuch", error=True)
add("comm", "missing final newline", "printf 'a\\nb' >/tmp/1; printf 'b\\nc' >/tmp/2; comm /tmp/1 /tmp/2")
add("comm", "empty files", "printf '' >/tmp/1; printf 'x\\n' >/tmp/2; comm /tmp/1 /tmp/2")

# --- cp ------------------------------------------------------------------------------------------
CP = "mkdir -p /tmp/s/sub; printf one >/tmp/s/a; printf two >/tmp/s/sub/b; cd /tmp; "
add("cp", "file to file", CP + "cp s/a c; cat c")
add("cp", "file into directory", CP + "mkdir d; cp s/a d; cat d/a")
add("cp", "several into directory", CP + "mkdir d; cp s/a s/sub/b d; ls d")
add("cp", "directory without recursive", CP + "cp s t", error=True)
add("cp", "recursive", CP + "cp -r s t; find t | sort")
add("cp", "recursive capital", CP + "cp -R s t; cat t/sub/b")
add("cp", "recursive into existing directory", CP + "mkdir t; cp -r s t; find t | sort")
add("cp", "archive", CP + "cp -a s t; find t | sort")
add("cp", "verbose", CP + "cp -v s/a c", error=True)
add("cp", "verbose recursive", CP + "cp -rv s t | sort", error=True)
add("cp", "no clobber", CP + "printf keep >c; cp -n s/a c; echo \"status=$?\"; cat c")
add("cp", "force", CP + "printf old >c; cp -f s/a c; cat c")
add("cp", "interactive no", CP + "printf old >c; echo n | cp -i s/a c", error=True)
add("cp", "interactive yes", CP + "printf old >c; echo y | cp -i s/a c 2>/dev/null; cat c")
add("cp", "hard link", CP + "cp -l s/a c; printf more >>c; cat s/a")
add("cp", "symbolic link relative", "mkdir -p /tmp/w; cd /tmp/w; printf x >a; cp -s a b; readlink b; cat b")
add("cp", "target directory option", CP + "mkdir d; cp -t d s/a s/sub/b; ls d")
add("cp", "no target directory", CP + "mkdir d; cp -T s/a d", error=True)
add("cp", "no target directory file", CP + "cp -T s/a c; cat c")
add("cp", "backup simple", CP + "printf old >c; cp -b s/a c; cat c c~")
add("cp", "backup numbered", CP + "printf old >c; cp --backup=numbered s/a c; cp --backup=numbered s/a c; ls c*")
add("cp", "backup existing", CP + "printf old >c; cp --backup=existing s/a c; ls c*")
add("cp", "backup suffix", CP + "printf old >c; cp -b -S .bak s/a c; ls c*; cat c.bak")
add("cp", "backup none", CP + "printf old >c; cp --backup=none s/a c; ls c*")
add("cp", "backup invalid control", CP + "cp --backup=bogus s/a c", error=True)
add("cp", "update older", CP + "printf new >c; touch -d 2000-01-01 s/a; cp -u s/a c; cat c")
add("cp", "update none", CP + "printf new >c; cp --update=none s/a c; cat c")
add("cp", "update all", CP + "printf new >c; cp --update=all s/a c; cat c")
add("cp", "update none-fail", CP + "printf new >c; cp --update=none-fail s/a c", error=True)
add("cp", "parents", CP + "mkdir d; cp --parents s/sub/b d; find d | sort")
add("cp", "preserve timestamps", CP + "touch -d '2001-02-03 04:05:06' s/a; cp -p s/a c; date -u -r c +%F")
add("cp", "preserve timestamps long", CP + "touch -d '2001-02-03 04:05:06' s/a; cp --preserve=timestamps s/a c; date -u -r c +%F")
add("cp", "no preserve by default", CP + "touch -d '2001-02-03 04:05:06' s/a; cp s/a c; [ \"$(date -u -r c +%Y)\" = 2001 ] && echo same || echo fresh")
add("cp", "remove destination", CP + "printf old >c; cp --remove-destination s/a c; cat c")
add("cp", "strip trailing slashes", CP + "cp -r --strip-trailing-slashes s/ t; ls t")
add("cp", "attributes only", CP + "printf old >c; cp --attributes-only s/a c; cat c; echo")
add("cp", "same file", CP + "cp s/a s/a", error=True)
add("cp", "missing source", CP + "cp nosuch c", error=True)
add("cp", "missing operand", "cp", error=True)
add("cp", "missing destination", CP + "cp s/a", error=True)
add("cp", "target not a directory", CP + "cp s/a s/sub/b c", error=True)
add("cp", "directory into itself", CP + "cp -r s s/sub", error=True)
add("cp", "dereference symlink", "mkdir -p /tmp/w; cd /tmp/w; printf x >a; ln -s a l; cp -L l c; [ -L c ] && echo link || cat c")
add("cp", "no dereference symlink", "mkdir -p /tmp/w; cd /tmp/w; printf x >a; ln -s a l; cp -P l c; readlink c")
add("cp", "recursive copies symlink as link", "mkdir -p /tmp/w/s; cd /tmp/w; printf x >s/a; ln -s a s/l; cp -r s t; readlink t/l")
add("cp", "dash-d keeps links", "mkdir -p /tmp/w; cd /tmp/w; printf x >a; ln -s a l; cp -d l c; readlink c")
add("cp", "copy file over directory", CP + "mkdir c; cp s/a c; ls c")
add("cp", "copy directory over file", CP + "printf x >t; cp -r s t", error=True)
add("cp", "unknown option", "cp --bogus a b", error=True)
add("cp", "empty file", "cd /tmp; printf '' >e; cp e f; wc -c f")
add("cp", "dot slash names", CP + "cp ./s/a ./c; cat c")

# --- csplit --------------------------------------------------------------------------------------
CS = "seq 1 12 >/tmp/n; cd /tmp; "
SHOW = "; for f in xx*; do echo \"== $f\"; cat \"$f\"; done"
add("csplit", "line number", CS + "csplit n 5" + SHOW)
add("csplit", "two line numbers", CS + "csplit n 4 8" + SHOW)
add("csplit", "regex", CS + "csplit n /7/" + SHOW)
add("csplit", "regex with offset", CS + "csplit n /7/+1" + SHOW)
add("csplit", "regex negative offset", CS + "csplit n /7/-2" + SHOW)
add("csplit", "skip to regex", CS + "csplit n %5% /9/" + SHOW)
add("csplit", "repeat count", CS + "csplit n /[0-9]/ '{2}'" + SHOW)
add("csplit", "repeat line pattern", CS + "csplit n 3 '{2}'" + SHOW)
add("csplit", "repeat forever", CS + "csplit -k n /1/ '{*}'" + SHOW)
add("csplit", "prefix", CS + "csplit -f part n 6; ls part*")
add("csplit", "suffix format", CS + "csplit -b '%03d.txt' n 6; ls xx*")
add("csplit", "digits", CS + "csplit -n 4 n 6; ls xx*")
add("csplit", "quiet", CS + "csplit -s n 6; ls xx*")
add("csplit", "silent long", CS + "csplit --silent n 6; ls xx*")
add("csplit", "elide empty", CS + "csplit -z n /1/ '{*}'; ls xx*")
add("csplit", "suppress matched", CS + "csplit --suppress-matched n /6/" + SHOW)
add("csplit", "keep files on error", CS + "csplit -k n 5 20; echo \"status=$?\"; ls xx*", error=False)
add("csplit", "line out of range", CS + "csplit n 20; ls xx* 2>/dev/null; echo end", error=True)
add("csplit", "regex no match", CS + "csplit n /abc/", error=True)
add("csplit", "unterminated regex", CS + "csplit n /abc", error=True)
add("csplit", "line zero", CS + "csplit n 0", error=True)
add("csplit", "decreasing lines", CS + "csplit n 8 4", error=True)
add("csplit", "bad repeat", CS + "csplit n 3 '{x}'", error=True)
add("csplit", "bad suffix format", CS + "csplit -b '%s' n 3", error=True)
add("csplit", "missing pattern", CS + "csplit n", error=True)
add("csplit", "missing file", "csplit /tmp/nosuch 2", error=True)
add("csplit", "stdin input", "cd /tmp; seq 1 5 | csplit - 3" + SHOW)
add("csplit", "repeat exceeds input", CS + "csplit n 5 '{3}'", error=True)
add("csplit", "regex first line", CS + "csplit n /1/" + SHOW)

# --- cut -----------------------------------------------------------------------------------------
CT = r"printf 'a:b:c:d\nno delim\n1:2\n::\n' >/tmp/f; "
for lst in ["1", "2", "1,3", "2-", "-2", "2-3", "1-2,4", "3,1", "1-1", "4-", "5"]:
    add("cut", f"fields {lst}", CT + f"cut -d: -f{lst} /tmp/f")
for lst in ["1", "2-4", "-3", "3-", "1,3,5", "2,2", "10"]:
    add("cut", f"bytes {lst}", "printf 'abcdef\\nxy\\n' | cut -b " + lst)
add("cut", "characters", "printf 'abcdef\\n' | cut -c 2-4")
add("cut", "characters multibyte", "printf 'étés\\n' | cut -c 2-3")
add("cut", "bytes multibyte no partial", "printf 'été\\n' | cut -b 1 -n | od -An -c")
add("cut", "only delimited", CT + "cut -d: -s -f2 /tmp/f")
add("cut", "complement fields", CT + "cut -d: --complement -f2 /tmp/f")
add("cut", "complement bytes", "printf 'abcdef\\n' | cut --complement -b 2-3")
add("cut", "output delimiter", CT + "cut -d: -f1,3 --output-delimiter=' | ' /tmp/f")
add("cut", "output delimiter with bytes", "printf 'abcdef\\n' | cut -b 1-2,4-5 --output-delimiter=-")
add("cut", "default tab delimiter", "printf 'a\\tb\\tc\\nx\\n' | cut -f2")
add("cut", "space delimiter", "printf 'a b  c\\n' | cut -d' ' -f3")
add("cut", "zero terminated", "printf 'a:b\\0c:d\\0' | cut -z -d: -f2 | od -An -c")
add("cut", "whitespace delimited", "printf 'a  b\\tc\\n' | cut -w -f2")
add("cut", "whitespace trimmed", "printf '  a  b\\n' | cut -w=trimmed -f1")
add("cut", "capital F", "printf 'a   b c\\n' | cut -F 2,3")
add("cut", "capital O", CT + "cut -d: -f1,2 -O + /tmp/f")
add("cut", "long options", CT + "cut --delimiter=: --fields=2 --only-delimited /tmp/f")
add("cut", "no list", "echo x | cut", error=True)
add("cut", "field zero", "echo x | cut -f0", error=True)
add("cut", "decreasing range", "echo x | cut -f3-1", error=True)
add("cut", "invalid list", "echo x | cut -f a", error=True)
add("cut", "bytes and fields", "echo x | cut -b1 -f1", error=True)
add("cut", "delimiter without fields", "echo x | cut -d: -b1", error=True)
add("cut", "multi-char delimiter", "echo x | cut -d ab -f1", error=True)
add("cut", "only delimited with bytes", "echo x | cut -s -b1", error=True)
add("cut", "missing file", "cut -f1 /tmp/nosuch", error=True)
add("cut", "empty list range", "echo x | cut -f -", error=True)
add("cut", "open ranges overlap", "printf 'abcdefgh\\n' | cut -c -3,2-,5")
add("cut", "no trailing newline", "printf 'a:b' | cut -d: -f2")
add("cut", "empty delimiter", "printf 'a\\0b\\n' | cut -d '' -f2 | od -An -c")
add("cut", "stdin dash with file", CT + "echo 'x:y' | cut -d: -f2 - /tmp/f")
