[package]
name = "golem_it_tool_streaming_rust_caller"
version = "0.0.1"
edition = "2024"

[profile.release]
opt-level = "s"
lto = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
capable-streaming-tool-guest-client = { path = "../golem-temp/bridge-sdk/rust/internal/capable-streaming-tool-guest-client" }
futures-concurrency = "7.6.3"
golem-rust = { path = "../../../sdks/rust/golem-rust", features = ["export_golem_agentic"] }
streaming-tool-guest-client = { path = "../golem-temp/bridge-sdk/rust/internal/streaming-tool-guest-client" }
