//! `-b`/`--cookie` and `-c`/`--cookie-jar`: a Netscape-format cookie jar.
//!
//! Scope: this loads/saves the classic `curl`/`wget`-shared Netscape jar format, matches cookies
//! to a request by domain suffix + path prefix (+ `Secure`), and merges `Set-Cookie` from the
//! response. Redirect handling relies on `whttp`'s existing origin check (it already drops the
//! `Cookie` header — `is_credential_header` — on a cross-origin hop and keeps it verbatim on a
//! same-origin one): this module does not re-derive a fresh `Cookie` header per redirect hop, so a
//! same-origin redirect to a DIFFERENT PATH that a real per-hop matcher would reconsider instead
//! just keeps sending what the first hop computed. Full RFC 6265 semantics (path narrowing across
//! redirects, `Max-Age`, `HttpOnly`) are not implemented.

use iri_string::types::UriAbsoluteStr;

/// One stored cookie.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Cookie {
    /// `example.com` (no leading dot — `include_subdomains` carries that bit instead, matching
    /// the Netscape file's own `flag` column rather than embedding it in the domain text).
    pub domain: String,
    /// The Netscape file's `flag` column: whether subdomains of `domain` also match.
    pub include_subdomains: bool,
    pub path: String,
    pub secure: bool,
    /// Unix seconds; 0 means a session cookie (curl writes `0` for these too).
    pub expires: u64,
    pub name: String,
    pub value: String,
}

/// Parse a Netscape-format cookie file: `# comment` lines and blank lines are skipped; each other
/// line is `domain\tflag\tpath\tsecure\texpires\tname\tvalue`.
pub(crate) fn parse_jar(text: &str) -> Vec<Cookie> {
    text.lines()
        .filter_map(|line| {
            let line = line.trim_end_matches('\r');
            if line.trim().is_empty() || line.trim_start().starts_with('#') {
                return None;
            }
            let mut fields = line.split('\t');
            let domain = fields.next()?.to_string();
            let include_subdomains = fields.next()? == "TRUE";
            let path = fields.next()?.to_string();
            let secure = fields.next()? == "TRUE";
            let expires = fields.next()?.parse().unwrap_or(0);
            let name = fields.next()?.to_string();
            let value = fields.next().unwrap_or("").to_string();
            Some(Cookie {
                domain,
                include_subdomains,
                path,
                secure,
                expires,
                name,
                value,
            })
        })
        .collect()
}

/// Render a jar back to Netscape format, header comment included (matches curl's own jar files,
/// which tools that read them — including a later `wcurl -b`, or real curl/wget — expect).
pub(crate) fn write_jar(cookies: &[Cookie]) -> String {
    let mut out = String::from(
        "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n\
         # This file was generated by libcurl! Edit at your own risk.\n\n",
    );
    for c in cookies {
        out.push_str(&c.domain);
        out.push('\t');
        out.push_str(if c.include_subdomains {
            "TRUE"
        } else {
            "FALSE"
        });
        out.push('\t');
        out.push_str(&c.path);
        out.push('\t');
        out.push_str(if c.secure { "TRUE" } else { "FALSE" });
        out.push('\t');
        out.push_str(&c.expires.to_string());
        out.push('\t');
        out.push_str(&c.name);
        out.push('\t');
        out.push_str(&c.value);
        out.push('\n');
    }
    out
}

/// A literal `-b name=value[; name2=value2...]` argument becomes cookies scoped to `host`/`path`
/// with no expiry (session-only) — curl treats a `-b` value containing `=` this way rather than as
/// a jar filename.
pub(crate) fn parse_literal(value: &str, host: &str, path: &str) -> Vec<Cookie> {
    value
        .split(';')
        .filter_map(|pair| {
            let (name, value) = pair.trim().split_once('=')?;
            if name.is_empty() {
                return None;
            }
            Some(Cookie {
                domain: host.to_string(),
                include_subdomains: false,
                path: request_path_for_matching(path),
                secure: false,
                expires: 0,
                name: name.trim().to_string(),
                value: value.trim().to_string(),
            })
        })
        .collect()
}

/// `-b`'s value is a jar filename unless it contains `=` (curl's own rule).
pub(crate) fn is_literal(value: &str) -> bool {
    value.contains('=')
}

/// The directory portion of a URL path, the way cookie matching uses it (curl/RFC 6265's
/// "default-path": everything up to and including the last `/`, or `/` if there is none).
fn request_path_for_matching(path: &str) -> String {
    match path.rfind('/') {
        Some(0) | None => "/".to_string(),
        Some(i) => path[..i].to_string(),
    }
}

/// `host`/`path`/`scheme` split out of an absolute URL, for matching and for scoping newly parsed
/// `Set-Cookie` cookies. `None` if the URL will not parse.
fn url_parts(url: &str) -> Option<(String, String, bool)> {
    let uri = UriAbsoluteStr::new(url.split('#').next().unwrap_or(url)).ok()?;
    let host = uri.authority_components()?.host().to_ascii_lowercase();
    let path = uri.path_str();
    let path = if path.is_empty() { "/" } else { path };
    let secure = uri.scheme_str().eq_ignore_ascii_case("https");
    Some((host, path.to_string(), secure))
}

/// Whether `cookie` should be sent on a request to `host`/`path` under `request_secure`.
fn matches(cookie: &Cookie, host: &str, path: &str, request_secure: bool) -> bool {
    if cookie.secure && !request_secure {
        return false;
    }
    let domain_ok = if cookie.include_subdomains {
        host == cookie.domain || host.ends_with(&format!(".{}", cookie.domain))
    } else {
        host == cookie.domain
    };
    if !domain_ok {
        return false;
    }
    path == cookie.path || path.starts_with(&format!("{}/", cookie.path.trim_end_matches('/')))
}

/// The `Cookie:` header value to send for `url`, from every jar entry that matches — `None` if
/// nothing matches (so the caller adds no header at all, rather than an empty one).
pub(crate) fn header_value(jar: &[Cookie], url: &str) -> Option<String> {
    let (host, path, secure) = url_parts(url)?;
    let matching: Vec<String> = jar
        .iter()
        .filter(|c| matches(c, &host, &path, secure))
        .map(|c| format!("{}={}", c.name, c.value))
        .collect();
    if matching.is_empty() {
        None
    } else {
        Some(matching.join("; "))
    }
}

/// Merge `Set-Cookie` response header values into `jar`, scoped by `response_url` (the response's
/// own effective URL — `final_url`, so a cookie set by a redirect target is scoped to THAT origin,
/// not the original request's). An existing cookie with the same name/domain/path is replaced (the
/// newest `Set-Cookie` for that identity wins, as real cookie jars do); `Max-Age`/`Expires` are not
/// parsed (every merged cookie is session-scoped: `expires = 0`).
pub(crate) fn merge_set_cookie(
    jar: &mut Vec<Cookie>,
    response_url: &str,
    set_cookie_values: &[&str],
) {
    let Some((host, default_path, _)) = url_parts(response_url) else {
        return;
    };
    for raw in set_cookie_values {
        let Some(cookie) = parse_set_cookie(raw, &host, &default_path) else {
            continue;
        };
        jar.retain(|c| {
            !(c.name == cookie.name && c.domain == cookie.domain && c.path == cookie.path)
        });
        jar.push(cookie);
    }
}

/// Parse one `Set-Cookie: name=value; Domain=...; Path=...; Secure` value. Only `Domain`, `Path`,
/// and `Secure` attributes are honored; anything else (`Max-Age`, `Expires`, `HttpOnly`,
/// `SameSite`) is accepted syntactically and ignored.
fn parse_set_cookie(raw: &str, request_host: &str, default_path: &str) -> Option<Cookie> {
    let mut parts = raw.split(';');
    let (name, value) = parts.next()?.trim().split_once('=')?;
    if name.is_empty() {
        return None;
    }
    let mut domain = request_host.to_string();
    let mut include_subdomains = false;
    let mut path = default_path.to_string();
    let mut secure = false;
    for attr in parts {
        let attr = attr.trim();
        if let Some(d) = attr
            .strip_prefix("Domain=")
            .or_else(|| attr.strip_prefix("domain="))
        {
            // A leading dot is the classic (pre-RFC-6265) explicit "include subdomains" marker;
            // RFC 6265 makes every `Domain` attribute imply it, so treat both forms the same.
            domain = d.trim_start_matches('.').to_ascii_lowercase();
            include_subdomains = true;
        } else if let Some(p) = attr
            .strip_prefix("Path=")
            .or_else(|| attr.strip_prefix("path="))
        {
            path = p.to_string();
        } else if attr.eq_ignore_ascii_case("secure") {
            secure = true;
        }
    }
    // RFC 6265 §5.3 step 6: a `Domain` attribute must domain-match the response's own host --
    // `request_host` itself, or a subdomain of `domain` -- or the WHOLE cookie is rejected.
    // Without this, `attacker.example` could set a cookie for `Domain=example.com` and have it
    // sent on later, unrelated requests to `example.com`.
    if include_subdomains
        && request_host != domain
        && !request_host.ends_with(&format!(".{domain}"))
    {
        return None;
    }
    Some(Cookie {
        domain,
        include_subdomains,
        path,
        secure,
        expires: 0,
        name: name.trim().to_string(),
        value: value.trim().to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_the_netscape_format() {
        let text = "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n\
                    # This file was generated by libcurl! Edit at your own risk.\n\n\
                    example.com\tTRUE\t/\tFALSE\t0\tsid\tabc123\n";
        let jar = parse_jar(text);
        assert_eq!(jar.len(), 1);
        assert_eq!(jar[0].domain, "example.com");
        assert!(jar[0].include_subdomains);
        assert_eq!(jar[0].name, "sid");
        assert_eq!(jar[0].value, "abc123");
        assert_eq!(write_jar(&jar), text);
    }

    #[test]
    fn comments_and_blank_lines_are_skipped() {
        let jar = parse_jar("# comment\n\nexample.com\tFALSE\t/\tFALSE\t0\ta\tb\n");
        assert_eq!(jar.len(), 1);
    }

    #[test]
    fn literal_cookie_string_is_not_a_filename() {
        assert!(is_literal("sid=abc; other=1"));
        assert!(!is_literal("cookies.txt"));
    }

    #[test]
    fn literal_cookies_scope_to_the_request_host_and_directory() {
        let cookies = parse_literal("a=1; b=2", "example.com", "/dir/page");
        assert_eq!(cookies.len(), 2);
        assert_eq!(cookies[0].domain, "example.com");
        assert_eq!(cookies[0].path, "/dir");
        assert!(!cookies[0].include_subdomains);
    }

    #[test]
    fn header_value_matches_domain_and_path() {
        let jar = vec![
            Cookie {
                domain: "example.com".into(),
                include_subdomains: false,
                path: "/".into(),
                secure: false,
                expires: 0,
                name: "a".into(),
                value: "1".into(),
            },
            Cookie {
                domain: "other.test".into(),
                include_subdomains: false,
                path: "/".into(),
                secure: false,
                expires: 0,
                name: "b".into(),
                value: "2".into(),
            },
        ];
        assert_eq!(
            header_value(&jar, "http://example.com/x").as_deref(),
            Some("a=1")
        );
        assert_eq!(header_value(&jar, "http://unrelated.test/"), None);
    }

    #[test]
    fn subdomain_cookies_match_only_when_flagged() {
        let jar = vec![Cookie {
            domain: "example.com".into(),
            include_subdomains: true,
            path: "/".into(),
            secure: false,
            expires: 0,
            name: "a".into(),
            value: "1".into(),
        }];
        assert_eq!(
            header_value(&jar, "http://sub.example.com/").as_deref(),
            Some("a=1")
        );
    }

    #[test]
    fn secure_cookies_are_withheld_from_plain_http() {
        let jar = vec![Cookie {
            domain: "example.com".into(),
            include_subdomains: false,
            path: "/".into(),
            secure: true,
            expires: 0,
            name: "a".into(),
            value: "1".into(),
        }];
        assert_eq!(header_value(&jar, "http://example.com/"), None);
        assert_eq!(
            header_value(&jar, "https://example.com/").as_deref(),
            Some("a=1")
        );
    }

    #[test]
    fn set_cookie_is_merged_and_replaces_an_existing_entry() {
        let mut jar = vec![Cookie {
            domain: "example.com".into(),
            include_subdomains: false,
            path: "/".into(),
            secure: false,
            expires: 0,
            name: "sid".into(),
            value: "old".into(),
        }];
        merge_set_cookie(&mut jar, "http://example.com/login", &["sid=new; Path=/"]);
        assert_eq!(jar.len(), 1);
        assert_eq!(jar[0].value, "new");
    }

    #[test]
    fn set_cookie_domain_and_secure_attributes_are_honored() {
        let mut jar = Vec::new();
        merge_set_cookie(
            &mut jar,
            "https://example.com/",
            &["sid=abc; Domain=.example.com; Secure; HttpOnly"],
        );
        assert_eq!(jar.len(), 1);
        assert_eq!(jar[0].domain, "example.com");
        assert!(jar[0].include_subdomains);
        assert!(jar[0].secure);
    }

    // a `Domain` attribute that does not domain-match the response's own host must be
    // rejected outright (RFC 6265 §5.3 step 6), or a server could set a cookie for a domain it
    // does not own.
    #[test]
    fn set_cookie_for_an_unrelated_domain_is_rejected() {
        let mut jar = Vec::new();
        merge_set_cookie(
            &mut jar,
            "https://attacker.example/",
            &["sid=abc; Domain=example.com"],
        );
        assert!(
            jar.is_empty(),
            "a cookie for a domain the host doesn't own must be dropped"
        );
    }

    #[test]
    fn set_cookie_for_a_subdomain_of_the_host_is_still_rejected() {
        let mut jar = Vec::new();
        // `attacker.example` cannot set a cookie for `sub.attacker.example` either: the
        // domain-match rule requires the REQUEST host to be `domain` or a subdomain of it, not
        // the reverse.
        merge_set_cookie(
            &mut jar,
            "https://attacker.example/",
            &["sid=abc; Domain=sub.attacker.example"],
        );
        assert!(jar.is_empty());
    }

    #[test]
    fn set_cookie_for_the_hosts_own_parent_domain_is_accepted() {
        let mut jar = Vec::new();
        merge_set_cookie(
            &mut jar,
            "https://www.example.com/",
            &["sid=abc; Domain=example.com"],
        );
        assert_eq!(jar.len(), 1);
        assert_eq!(jar[0].domain, "example.com");
    }
}
