/// Variant enum
/// Variant doc
enum Variant {
   /// Stirng constructor
   /// String doc
   String(String)
   /// Number constructor
   /// Number doc
   Number(Double) // comment3
   /// Boolean constructor
   /// Boolean doc
   Boolean(Bool)
   /// Array constructor
   Sequence(Array[Variant])
}

/// Location struct
/// Location doc
struct Location {
  /// X coordinate
  x : Int
  /// Y coordinate
  y : Int
  /// Z coordinate
  /// The type is Double
  z : Double
}







