
fn init {
  println(114514)
  println(1_1_4_5_1_4)
  let x : Double = 0x1_1_4_.5_14_p+2_33
  fn(x: Double) {
    ()
  }(x)
  let x : Double = 1_1_4_.5_14_e-2_33
  fn(x: Double) {
    ()
  }(x)
  println(0x114514)
  println(0x1_1_4_5_1_4)
  println(0b110010)
  println(0b1_1_0_0_1_0)
  println(0o114514)
  println(0X114514)
  println(0B110010)
  println(0O114514)
  let x = -2147483648
  let x = 0-2147483647-1
}

fn init {
  let f = -1.1
  println(f)
  let f1 = f-1.1
  println(f1)
  let f2 = f+1.1-1.1-2.2
  println(f2)
}

let y : Double = 1.111
