// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://license.golem.cloud/LICENSE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub mod header {
    pub const GOLEM_CLI_VERSION: &str = "x-golem-cli-version";
    pub const GOLEM_CLI_PLATFORM: &str = "x-golem-cli-platform";
}

pub mod error_code {
    // --- Authentication / Authorization ---
    pub const AUTH_FORBIDDEN: &str = "AUTH_FORBIDDEN";
    pub const AUTH_UNAUTHORIZED: &str = "AUTH_UNAUTHORIZED";
    pub const BUILTIN_PLUGIN_GRANT_CANNOT_BE_DELETED: &str =
        "BUILTIN_PLUGIN_GRANT_CANNOT_BE_DELETED";
    pub const FEATURE_DISABLED: &str = "FEATURE_DISABLED";

    // --- Limits ---
    pub const LIMIT_EXCEEDED: &str = "LIMIT_EXCEEDED";

    // --- CLI ---
    pub const CLI_UPDATE_REQUIRED: &str = "CLI_UPDATE_REQUIRED";

    // --- Not found ---
    pub const ACCOUNT_NOT_FOUND: &str = "ACCOUNT_NOT_FOUND";
    pub const AGENT_NOT_FOUND: &str = "AGENT_NOT_FOUND";
    pub const AGENT_SECRET_NOT_FOUND: &str = "AGENT_SECRET_NOT_FOUND";
    pub const AGENT_TYPE_NOT_FOUND: &str = "AGENT_TYPE_NOT_FOUND";
    pub const APPLICATION_NOT_FOUND: &str = "APPLICATION_NOT_FOUND";
    pub const COMPONENT_NOT_FOUND: &str = "COMPONENT_NOT_FOUND";
    pub const DEPLOYMENT_NOT_FOUND: &str = "DEPLOYMENT_NOT_FOUND";
    pub const DOMAIN_REGISTRATION_NOT_FOUND: &str = "DOMAIN_REGISTRATION_NOT_FOUND";
    pub const ENVIRONMENT_NOT_FOUND: &str = "ENVIRONMENT_NOT_FOUND";
    pub const FILE_NOT_FOUND: &str = "FILE_NOT_FOUND";
    pub const PLAN_NOT_FOUND: &str = "PLAN_NOT_FOUND";
    pub const PLUGIN_REGISTRATION_NOT_FOUND: &str = "PLUGIN_REGISTRATION_NOT_FOUND";
    pub const RESOURCE_DEFINITION_NOT_FOUND: &str = "RESOURCE_DEFINITION_NOT_FOUND";
    pub const RETRY_POLICY_NOT_FOUND: &str = "RETRY_POLICY_NOT_FOUND";
    pub const RESOURCE_NOT_FOUND: &str = "RESOURCE_NOT_FOUND";
    pub const ROUTE_NOT_FOUND: &str = "ROUTE_NOT_FOUND";
    pub const SECURITY_SCHEME_NOT_FOUND: &str = "SECURITY_SCHEME_NOT_FOUND";
    pub const TOKEN_NOT_FOUND: &str = "TOKEN_NOT_FOUND";

    // --- Already exists / conflicts ---
    pub const ACCOUNT_EMAIL_ALREADY_IN_USE: &str = "ACCOUNT_EMAIL_ALREADY_IN_USE";
    pub const AGENT_CONFIG_DUPLICATE_VALUE: &str = "AGENT_CONFIG_DUPLICATE_VALUE";
    pub const AGENT_CONFIG_NOT_DECLARED: &str = "AGENT_CONFIG_NOT_DECLARED";
    pub const AGENT_CONFIG_OLD_CONFIG_INVALID: &str = "AGENT_CONFIG_OLD_CONFIG_INVALID";
    pub const AGENT_CONFIG_SECRET_SCOPE_INVALID: &str = "AGENT_CONFIG_SECRET_SCOPE_INVALID";
    pub const AGENT_CONFIG_TYPE_MISMATCH: &str = "AGENT_CONFIG_TYPE_MISMATCH";
    pub const AGENT_SECRET_ALREADY_EXISTS: &str = "AGENT_SECRET_ALREADY_EXISTS";
    pub const AGENT_SECRET_VALUE_TYPE_MISMATCH: &str = "AGENT_SECRET_VALUE_TYPE_MISMATCH";
    pub const APPLICATION_ALREADY_EXISTS: &str = "APPLICATION_ALREADY_EXISTS";
    pub const COMPONENT_ALREADY_EXISTS: &str = "COMPONENT_ALREADY_EXISTS";
    pub const COMPONENT_NAME_ALREADY_EXISTS: &str = "COMPONENT_NAME_ALREADY_EXISTS";
    pub const COMPONENT_VERSION_ALREADY_EXISTS: &str = "COMPONENT_VERSION_ALREADY_EXISTS";
    pub const CONCURRENT_UPDATE: &str = "CONCURRENT_UPDATE";
    pub const DEPLOYMENT_NOOP: &str = "DEPLOYMENT_NOOP";
    pub const DEPLOYMENT_VERSION_ALREADY_EXISTS: &str = "DEPLOYMENT_VERSION_ALREADY_EXISTS";
    pub const DOMAIN_ALREADY_EXISTS: &str = "DOMAIN_ALREADY_EXISTS";
    pub const DOMAIN_NOT_REGISTERED: &str = "DOMAIN_NOT_REGISTERED";
    pub const ENVIRONMENT_ALREADY_EXISTS: &str = "ENVIRONMENT_ALREADY_EXISTS";
    pub const ENVIRONMENT_NOT_DEPLOYED: &str = "ENVIRONMENT_NOT_DEPLOYED";
    pub const ENVIRONMENT_PLUGIN_GRANT_ALREADY_EXISTS: &str =
        "ENVIRONMENT_PLUGIN_GRANT_ALREADY_EXISTS";
    pub const ENVIRONMENT_PLUGIN_GRANT_CONFLICT: &str = "ENVIRONMENT_PLUGIN_GRANT_CONFLICT";
    pub const ENVIRONMENT_SHARE_ALREADY_EXISTS: &str = "ENVIRONMENT_SHARE_ALREADY_EXISTS";
    pub const HTTP_API_DEPLOYMENT_ALREADY_EXISTS: &str = "HTTP_API_DEPLOYMENT_ALREADY_EXISTS";
    pub const MCP_DEPLOYMENT_ALREADY_EXISTS: &str = "MCP_DEPLOYMENT_ALREADY_EXISTS";
    pub const PLUGIN_PRIORITY_CONFLICT: &str = "PLUGIN_PRIORITY_CONFLICT";
    pub const PLUGIN_REGISTRATION_ALREADY_EXISTS: &str = "PLUGIN_REGISTRATION_ALREADY_EXISTS";
    pub const RESOURCE_ALREADY_EXISTS: &str = "RESOURCE_ALREADY_EXISTS";
    pub const RETRY_POLICY_ALREADY_EXISTS: &str = "RETRY_POLICY_ALREADY_EXISTS";
    pub const RESOURCE_DEFINITION_ALREADY_EXISTS: &str = "RESOURCE_DEFINITION_ALREADY_EXISTS";
    pub const SECURITY_SCHEME_ALREADY_EXISTS: &str = "SECURITY_SCHEME_ALREADY_EXISTS";
    pub const TOKEN_ALREADY_EXISTS: &str = "TOKEN_ALREADY_EXISTS";

    // --- Validation ---
    pub const AGENT_TYPE_NOT_DECLARED: &str = "AGENT_TYPE_NOT_DECLARED";
    pub const BAD_FILE_TYPE: &str = "BAD_FILE_TYPE";
    pub const COMPONENT_PROCESSING_ERROR: &str = "COMPONENT_PROCESSING_ERROR";
    pub const DEPLOYMENT_HASH_MISMATCH: &str = "DEPLOYMENT_HASH_MISMATCH";
    pub const DEPLOYMENT_VALIDATION_FAILED: &str = "DEPLOYMENT_VALIDATION_FAILED";
    pub const DOMAIN_CANNOT_BE_PROVISIONED: &str = "DOMAIN_CANNOT_BE_PROVISIONED";
    pub const ENVIRONMENT_PLUGIN_NOT_FOUND: &str = "ENVIRONMENT_PLUGIN_NOT_FOUND";
    pub const INITIAL_COMPONENT_FILE_NOT_FOUND: &str = "INITIAL_COMPONENT_FILE_NOT_FOUND";
    pub const INVALID_AGENT_FILTER: &str = "INVALID_AGENT_FILTER";
    pub const INVALID_COMPONENT_FILE_PATH: &str = "INVALID_COMPONENT_FILE_PATH";
    pub const INVALID_COMPONENT_NAME: &str = "INVALID_COMPONENT_NAME";
    pub const INVALID_COMPONENT_REFERENCE: &str = "INVALID_COMPONENT_REFERENCE";
    pub const INVALID_CUSTOM_PROVIDER_ISSUER_URL: &str = "INVALID_CUSTOM_PROVIDER_ISSUER_URL";
    pub const INVALID_FILE_NAME: &str = "INVALID_FILE_NAME";
    pub const INVALID_FILE_PATH: &str = "INVALID_FILE_PATH";
    pub const INVALID_OAUTH_SESSION: &str = "INVALID_OAUTH_SESSION";
    pub const INVALID_OPLOG_QUERY_PARAMS: &str = "INVALID_OPLOG_QUERY_PARAMS";
    pub const INVALID_OPLOG_PROCESSOR_PLUGIN: &str = "INVALID_OPLOG_PROCESSOR_PLUGIN";
    pub const INVALID_PLUGIN_SCOPE: &str = "INVALID_PLUGIN_SCOPE";
    pub const INVALID_REDIRECT_URL: &str = "INVALID_REDIRECT_URL";
    pub const INVALID_SCAN_CURSOR: &str = "INVALID_SCAN_CURSOR";
    pub const INVALID_WORKER_ID: &str = "INVALID_WORKER_ID";
    pub const MALFORMED_COMPONENT_ARCHIVE: &str = "MALFORMED_COMPONENT_ARCHIVE";
    pub const OAUTH_STATE_NOT_FOUND: &str = "OAUTH_STATE_NOT_FOUND";
    pub const OIDC_SCHEME_MISMATCH: &str = "OIDC_SCHEME_MISMATCH";
    pub const OIDC_TOKEN_EXCHANGE_FAILED: &str = "OIDC_TOKEN_EXCHANGE_FAILED";
    pub const OPLOG_PROCESSOR_COMPONENT_NOT_FOUND: &str = "OPLOG_PROCESSOR_COMPONENT_NOT_FOUND";
    pub const PLUGIN_INSTALLATION_NOT_FOUND: &str = "PLUGIN_INSTALLATION_NOT_FOUND";
    pub const REFERENCED_PLUGIN_NOT_FOUND: &str = "REFERENCED_PLUGIN_NOT_FOUND";
    pub const REQUEST_BODY_INVALID_JSON: &str = "REQUEST_BODY_INVALID_JSON";
    pub const REQUEST_DOMAIN_EXTRACTION_FAILED: &str = "REQUEST_DOMAIN_EXTRACTION_FAILED";
    pub const REQUEST_HEADER_NOT_ASCII: &str = "REQUEST_HEADER_NOT_ASCII";
    pub const REQUEST_JSON_BODY_PARSING_FAILED: &str = "REQUEST_JSON_BODY_PARSING_FAILED";
    pub const REQUEST_MALFORMED_PATH: &str = "REQUEST_MALFORMED_PATH";
    pub const REQUEST_MISSING_VALUE: &str = "REQUEST_MISSING_VALUE";
    pub const REQUEST_TOO_MANY_VALUES: &str = "REQUEST_TOO_MANY_VALUES";
    pub const REQUEST_UNSUPPORTED_MIME_TYPE: &str = "REQUEST_UNSUPPORTED_MIME_TYPE";
    pub const REQUEST_VALUE_PARSING_FAILED: &str = "REQUEST_VALUE_PARSING_FAILED";
    pub const RETRY_POLICY_INVALID_POLICY_JSON: &str = "RETRY_POLICY_INVALID_POLICY_JSON";
    pub const RETRY_POLICY_INVALID_PREDICATE_JSON: &str = "RETRY_POLICY_INVALID_PREDICATE_JSON";
    pub const RESOURCE_LIMIT_TYPE_IMMUTABLE: &str = "RESOURCE_LIMIT_TYPE_IMMUTABLE";
    pub const TYPE_CHECKER_ERROR: &str = "TYPE_CHECKER_ERROR";
    pub const UNKNOWN_OIDC_STATE: &str = "UNKNOWN_OIDC_STATE";
    pub const VALIDATION_ERROR: &str = "VALIDATION_ERROR";

    // --- Internal errors ---
    pub const INTERNAL_AGENT_EXECUTION_FAILED: &str = "INTERNAL_AGENT_EXECUTION_FAILED";
    pub const INTERNAL_AGENT_RESUME_FAILED: &str = "INTERNAL_AGENT_RESUME_FAILED";
    pub const INTERNAL_CLIENT_ERROR: &str = "INTERNAL_CLIENT_ERROR";
    pub const INTERNAL_COMPONENT_DOWNLOAD_FAILED: &str = "INTERNAL_COMPONENT_DOWNLOAD_FAILED";
    pub const INTERNAL_COMPONENT_PARSE_FAILED: &str = "INTERNAL_COMPONENT_PARSE_FAILED";
    pub const INTERNAL_DEPENDENCY_FAILURE: &str = "INTERNAL_DEPENDENCY_FAILURE";
    pub const INTERNAL_FILESYSTEM_ERROR: &str = "INTERNAL_FILESYSTEM_ERROR";
    pub const INTERNAL_INVARIANT_VIOLATION: &str = "INTERNAL_INVARIANT_VIOLATION";
    pub const INTERNAL_PREVIOUS_INVOCATION_FAILED: &str = "INTERNAL_PREVIOUS_INVOCATION_FAILED";
    pub const INTERNAL_ROUTING_FAILURE: &str = "INTERNAL_ROUTING_FAILURE";
    pub const INTERNAL_SHARDING_NOT_READY: &str = "INTERNAL_SHARDING_NOT_READY";
    pub const INTERNAL_UNKNOWN: &str = "INTERNAL_UNKNOWN";
}
