[package]
name = "golem-tool-metadata"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
harness = false

[features]
guest = ["golem-schema/guest"]

[dependencies]
golem-schema = { path = "../../../golem-schema", version = "0.0.0", features = ["derive"] }

[dev-dependencies]
test-r = "3.0.9"
