package golem:it-stub;

interface stub-child-component {
  use golem:rpc/types@0.1.0.{uri};
  use wasi:io/poll@0.2.0.{pollable};
  use golem:it/api.{data};

  resource future-echo-result {
    subscribe: func() -> pollable;
    get: func() -> option<string>;
  }
  resource future-calculate-result {
    subscribe: func() -> pollable;
    get: func() -> option<u64>;
  }
  resource future-process-result {
    subscribe: func() -> pollable;
    get: func() -> option<list<data>>;
  }
  resource api {
    constructor(location: uri);
    blocking-echo: func(input: string) -> string;
    echo: func(input: string) -> future-echo-result;
    blocking-calculate: func(input: u64) -> u64;
    calculate: func(input: u64) -> future-calculate-result;
    blocking-process: func(input: list<data>) -> list<data>;
    process: func(input: list<data>) -> future-process-result;
  }

}

world wasm-rpc-stub-child-component {
  export stub-child-component;
}
