package golem-it:ifs-update;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-it-ifs-update-api {
  load-file: func();
  get-file-content: func() -> string;
}

world golem-it-ifs-update {
  export golem-it-ifs-update-api;

  export golem:api/save-snapshot@1.1.6;
  export golem:api/load-snapshot@1.1.6;
}
