package cloud.golem.ksp

import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.configureKsp
import com.tschuchort.compiletesting.kspSourcesDir
import java.io.File
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Verifies the processor's GENERATED SOURCE TEXT and, for compilation tests,
 * that the generated registration compiles against a JVM stub of GolemKotlinSdk.
 *
 * Most tests use withCompilation=false because the generated registration is
 * Kotlin/JS-specific (GolemKotlinSdk @JsModule namespace + JS lambda/dynamic
 * interop) and cannot be compiled by the JVM test compiler. The dedicated
 * withCompilation=true test (T1) instead provides a JVM-compatible stub
 * GolemKotlinSdk in the same package so compilation succeeds — this catches
 * unresolved-helper regressions that text-only assertions miss.
 */
class GolemAgentProcessorTest {

    private fun annotationStubs() = SourceFile.kotlin(
        "Annotations.kt",
        """
        package cloud.golem.annotations

        annotation class Agent(val mount: String = "", val description: String = "")
        annotation class Endpoint(
            val post: String = "",
            val get: String = "",
            val put: String = "",
            val delete: String = "",
            val path: String = ""
        )
        annotation class Prompt(val hint: String = "")
        annotation class Description(val text: String = "")
        """.trimIndent()
    )

    private fun baseAgentStub() = SourceFile.kotlin(
        "BaseAgent.kt",
        """
        package cloud.golem
        abstract class BaseAgent
        """.trimIndent()
    )

    private fun runProcessor(vararg agents: SourceFile): KotlinCompilation {
        val compilation = KotlinCompilation().apply {
            sources = listOf(annotationStubs(), baseAgentStub(), *agents)
            inheritClassPath = true
            messageOutputStream = System.out
        }
        compilation.configureKsp {
            symbolProcessorProviders += GolemAgentProcessorProvider()
            // Run KSP but do NOT compile the generated sources: the generated
            // registration is Kotlin/JS-specific (GolemKotlinSdk namespace + JS
            // interop) and won't compile on the JVM test compiler. We assert on
            // the generated source text instead.
            withCompilation = false
        }
        compilation.compile()
        return compilation
    }

    private fun generated(compilation: KotlinCompilation, fileName: String): String {
        val file = compilation.kspSourcesDir.walkTopDown().firstOrNull { it.name == fileName }
        assertNotNull(file, "$fileName was not generated under ${compilation.kspSourcesDir}")
        return file.readText()
    }

    private fun generatedWit(compilation: KotlinCompilation): File? =
        compilation.kspSourcesDir.walkTopDown().firstOrNull { it.extension == "wit" }

    @Test
    fun `generates Registration and WIT for CounterAgent`() {
        val agent = SourceFile.kotlin(
            "CounterAgent.kt",
            """
            package counter

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.annotations.Prompt
            import cloud.golem.annotations.Description
            import cloud.golem.BaseAgent

            @Agent(mount = "/counters/{name}", description = "A durable counter agent")
            class CounterAgent(val name: String) : BaseAgent() {
                private var value = 0

                @Prompt("Increase the count by one")
                @Endpoint(post = "/increment")
                fun increment(): Int { value++; return value }

                @Prompt("Get the current count")
                @Endpoint(get = "/value")
                fun getValue(): Int = value
            }
            """.trimIndent()
        )
        val compilation = runProcessor(agent)

        val reg = generated(compilation, "CounterAgentRegistration.kt")
        assertContains(reg, "AUTO-GENERATED by golem-kotlin-ksp")
        assertContains(reg, "fun registerCounterAgent()")
        assertContains(reg, "import cloud.golem.runtime.GolemAgentRuntime")
        assertContains(reg, "GolemAgentRuntime.registerAgent(")
        assertContains(reg, "AgentDescriptor(")
        assertContains(reg, "\"CounterAgent\"")
        assertContains(reg, "\"A durable counter agent\"")
        assertContains(reg, "\"/counters/{name}\"")
        assertContains(reg, "listOf(ParamSchema(\"name\", \"string\"))")
        assertContains(reg, "MethodDescriptor(\"increment\", \"s32\", emptyList(), listOf(HttpEndpoint(\"POST\", \"/increment\")))")
        assertContains(reg, "wrapInt((instance as CounterAgent).increment())")
        assertContains(reg, "wrapInt((instance as CounterAgent).getValue())")
        assertContains(reg, "CounterAgent(extractString(input, 0))")

        val main = generated(compilation, "GolemGeneratedMain.kt")
        assertContains(main, "fun registerAllAgents()")
        assertContains(main, "counter.registerCounterAgent()")
        assertContains(main, "fun main()")

        val wit = generatedWit(compilation)
        assertNotNull(wit, "counter-agent.wit was not generated")
        val witSrc = wit.readText()
        assertContains(witSrc, "package kotlin:counter@0.1.0")
        assertContains(witSrc, "world counter-agent {")
        assertContains(witSrc, "include golem:agent/agent-guest@2.0.0;")
        assertContains(witSrc, "// agent CounterAgent {")
        assertContains(witSrc, "//   mount: \"/counters/{name}\"")
        assertContains(witSrc, "//   constructor(name: string)")
        assertContains(witSrc, "//   method increment() -> s32")
        assertContains(witSrc, "//   method getValue() -> s32")
        assertContains(witSrc, "post: \"/increment\"")
        assertContains(witSrc, "prompt: \"Increase the count by one\"")
    }

    @Test
    fun `handles agent with no methods`() {
        val agent = SourceFile.kotlin(
            "EmptyAgent.kt",
            """
            package example

            import cloud.golem.annotations.Agent
            import cloud.golem.BaseAgent

            @Agent(mount = "/empty")
            class EmptyAgent : BaseAgent()
            """.trimIndent()
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "EmptyAgentRegistration.kt")
        assertContains(reg, "fun registerEmptyAgent()")
        assertContains(reg, "emptyList()") // empty constructorParams + methods
        assertContains(reg, "{ _ -> EmptyAgent() }") // no-arg factory
    }

    @Test
    fun `handles void Unit return type`() {
        val agent = SourceFile.kotlin(
            "ResetAgent.kt",
            """
            package example

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/reset")
            class ResetAgent : BaseAgent() {
                @Endpoint(post = "/reset")
                fun reset() {}
            }
            """.trimIndent()
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "ResetAgentRegistration.kt")
        assertContains(reg, "(instance as ResetAgent).reset(); wrapUnit()")
        assertTrue(generatedWit(compilation) != null)
    }

    // T1: withCompilation=true — proves the generated registration actually
    // compiles against a matching GolemKotlinSdk boundary. Would have caught C1/I2.
    // GolemKotlinSdk is declared in `package counter` (same as the generated file)
    // using JVM-compatible types (Any? in place of `dynamic`).
    @Test
    fun `generated registration compiles against JVM stub GolemKotlinSdk`() {
        val sdkStub = SourceFile.kotlin(
            "GolemRuntimeStub.kt",
            """
            package cloud.golem.runtime

            // JVM-compilable stub mirroring the SDK's cloud.golem.runtime surface the generated
            // code uses. Uses Any? in place of `dynamic` (not available on JVM).
            class ParamSchema(val name: String, val witType: String)
            class HttpEndpoint(val verb: String, val path: String)
            class MethodDescriptor(
                val name: String,
                val outputWitType: String,
                val inputParams: List<ParamSchema>,
                val httpEndpoints: List<HttpEndpoint>,
                val handler: (Any, Any?) -> Any?
            )
            class AgentDescriptor(
                val typeName: String,
                val description: String,
                val mountPath: String,
                val constructorParams: List<ParamSchema>,
                val methods: List<MethodDescriptor>,
                val factory: (Any?) -> Any
            )
            object GolemAgentRuntime { fun registerAgent(descriptor: AgentDescriptor) {} }
            fun extractString(dataValue: Any?, index: Int = 0): String = ""
            fun extractInt(dataValue: Any?, index: Int = 0): Int = 0
            fun extractLong(dataValue: Any?, index: Int = 0): Long = 0
            fun wrapInt(n: Int): Any? = n
            fun wrapLong(n: Long): Any? = n
            fun wrapString(s: String): Any? = s
            fun wrapUnit(): Any? = Unit
            """.trimIndent()
        )

        val agent = SourceFile.kotlin(
            "CounterAgentCompile.kt",
            """
            package counter

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/counters/{name}", description = "A durable counter agent")
            class CounterAgentCompile(val name: String) : BaseAgent() {
                private var value = 0

                @Endpoint(post = "/increment")
                fun increment(): Int { value++; return value }
            }
            """.trimIndent()
        )

        val compilation = KotlinCompilation().apply {
            sources = listOf(annotationStubs(), baseAgentStub(), sdkStub, agent)
            inheritClassPath = true
            messageOutputStream = System.out
        }
        compilation.configureKsp {
            symbolProcessorProviders += GolemAgentProcessorProvider()
            withCompilation = true
        }
        val result = compilation.compile()
        assertTrue(
            result.exitCode == KotlinCompilation.ExitCode.OK,
            "Generated registration did not compile: ${result.messages}"
        )
    }

    // T1 (branch coverage): text assertions for a method WITH an Int param and String return,
    // verifying extractInt and wrapString branches are emitted correctly.
    @Test
    fun `generates extractInt and wrapString for Int param and String return`() {
        val agent = SourceFile.kotlin(
            "GreetAgent.kt",
            """
            package greet

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/greet", description = "Greet agent")
            class GreetAgent : BaseAgent() {
                @Endpoint(post = "/hello")
                fun hello(times: Int): String = "hello".repeat(times)
            }
            """.trimIndent()
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "GreetAgentRegistration.kt")
        assertContains(reg, "extractInt(input, 0)")
        assertContains(reg, "wrapString((instance as GreetAgent).hello(")
    }
}
