package cloud.golem.ksp

import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.configureKsp
import com.tschuchort.compiletesting.kspSourcesDir
import java.io.File
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Verifies the processor's GENERATED SOURCE TEXT and, for the dedicated compilation test, that
 * the generated registration + entry point compile against a JVM stub of the native SDK's
 * `cloud.golem.runtime` surface.
 *
 * Most tests use withCompilation=false because the generated code targets Kotlin/Wasm
 * (`kotlin.wasm.WasmExport`, which does not exist on the JVM classpath) and cannot be compiled by
 * the JVM test compiler as-is. The dedicated withCompilation=true test instead provides a
 * JVM-compatible stub of `cloud.golem.runtime` (NativeAgentDescriptor/SchemaValue/etc.) plus a
 * stub `@WasmExport` annotation, so compilation succeeds — this catches unresolved-helper
 * regressions that text-only assertions miss.
 */
class GolemAgentProcessorTest {

    private fun annotationStubs() = SourceFile.kotlin(
        "Annotations.kt",
        """
        package cloud.golem.annotations

        annotation class Agent(val mount: String = "", val description: String = "")
        annotation class Endpoint(
            val post: String = "",
            val get: String = "",
            val put: String = "",
            val delete: String = "",
            val path: String = ""
        )
        annotation class Prompt(val hint: String = "")
        annotation class Description(val text: String = "")
        """.trimIndent(),
    )

    private fun baseAgentStub() = SourceFile.kotlin(
        "BaseAgent.kt",
        """
        package cloud.golem
        abstract class BaseAgent
        interface Snapshotted<S> {
            var state: S
        }
        """.trimIndent(),
    )

    private fun runProcessor(vararg agents: SourceFile): KotlinCompilation {
        val compilation = KotlinCompilation().apply {
            sources = listOf(annotationStubs(), baseAgentStub(), *agents)
            inheritClassPath = true
            messageOutputStream = System.out
        }
        compilation.configureKsp {
            symbolProcessorProviders += GolemAgentProcessorProvider()
            // Run KSP but do NOT compile the generated sources: the generated registration
            // targets Kotlin/Wasm (kotlin.wasm.WasmExport) and won't compile on the JVM test
            // compiler without stubs. We assert on the generated source text instead.
            withCompilation = false
        }
        compilation.compile()
        return compilation
    }

    private fun generated(compilation: KotlinCompilation, fileName: String): String {
        val file = compilation.kspSourcesDir.walkTopDown().firstOrNull { it.name == fileName }
        assertNotNull(file, "$fileName was not generated under ${compilation.kspSourcesDir}")
        return file.readText()
    }

    private fun generatedWit(compilation: KotlinCompilation): File? = compilation.kspSourcesDir.walkTopDown().firstOrNull { it.extension == "wit" }

    @Test
    fun `generates native Registration, entry point, and WIT for CounterAgent`() {
        val agent = SourceFile.kotlin(
            "CounterAgent.kt",
            """
            package counter

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.annotations.Prompt
            import cloud.golem.annotations.Description
            import cloud.golem.BaseAgent

            @Agent(mount = "/counters/{name}", description = "A durable counter agent")
            class CounterAgent(val name: String) : BaseAgent() {
                private var value = 0

                @Prompt("Increase the count by one")
                @Endpoint(post = "/increment")
                fun increment(): Int { value++; return value }

                @Prompt("Get the current count")
                @Endpoint(get = "/value")
                fun getValue(): Int = value
            }
            """.trimIndent(),
        )
        val compilation = runProcessor(agent)

        val reg = generated(compilation, "CounterAgentRegistration.kt")
        assertContains(reg, "AUTO-GENERATED by golem-kotlin-ksp")
        assertContains(reg, "fun registerCounterAgent()")
        assertContains(reg, "import cloud.golem.runtime.NativeAgentRuntime")
        assertContains(reg, "NativeAgentRuntime.registerAgent(")
        assertContains(reg, "NativeAgentDescriptor(")
        assertContains(reg, "\"CounterAgent\"")
        assertContains(reg, "\"A durable counter agent\"")
        assertContains(reg, "\"/counters/{name}\"")
        assertContains(reg, "listOf(NativeParamSchema(\"name\", \"string\"))")
        assertContains(reg, "NativeMethodDescriptor(\"increment\", \"s32\", emptyList(), listOf(NativeHttpEndpoint(\"POST\", \"/increment\", false, emptyList())), \"Increase the count by one\", null)")
        assertContains(reg, "SchemaValue.S32((instance as CounterAgent).increment())")
        assertContains(reg, "SchemaValue.S32((instance as CounterAgent).getValue())")
        assertContains(reg, "CounterAgent((input[0] as SchemaValue.Str).v)")

        val entry = generated(compilation, "GolemGeneratedGuest.kt")
        assertContains(entry, "fun registerAllAgents()")
        assertContains(entry, "counter.registerCounterAgent()")
        assertContains(entry, "@WasmExport(\"golem:agent/guest@2.0.0#initialize\")")
        assertContains(entry, "@WasmExport(\"golem:agent/guest@2.0.0#invoke\")")
        assertContains(entry, "@WasmExport(\"golem:agent/guest@2.0.0#get-definition\")")
        assertContains(entry, "@WasmExport(\"golem:agent/guest@2.0.0#discover-agent-types\")")
        assertContains(entry, "@WasmExport(\"cabi_post_golem:agent/guest@2.0.0#initialize\")")
        assertContains(entry, "cloud.golem.runtime.initialize(argsPtr)")
        assertContains(entry, "@WasmExport(\"golem:api/save-snapshot@1.5.0#save\")")
        assertContains(entry, "@WasmExport(\"cabi_post_golem:api/save-snapshot@1.5.0#save\")")
        assertContains(entry, "@WasmExport(\"golem:api/load-snapshot@1.5.0#load\")")
        assertContains(entry, "@WasmExport(\"cabi_post_golem:api/load-snapshot@1.5.0#load\")")
        assertContains(entry, "cloud.golem.runtime.saveSnapshot()")
        assertContains(entry, "cloud.golem.runtime.cabiPostSaveSnapshot(resultPtr)")
        assertContains(entry, "fun golemLoadSnapshot(payloadPtr: Int, payloadLen: Int, mimeTypePtr: Int, mimeTypeLen: Int): Int")
        assertContains(entry, "cloud.golem.runtime.loadSnapshotFlat(payloadPtr, payloadLen, mimeTypePtr, mimeTypeLen)")
        assertContains(entry, "cloud.golem.runtime.cabiPostLoadSnapshot(resultPtr)")

        val wit = generatedWit(compilation)
        assertNotNull(wit, "counter-agent.wit was not generated")
        val witSrc = wit.readText()
        assertContains(witSrc, "package kotlin:counter@0.1.0")
        assertContains(witSrc, "world counter-agent {")
        assertContains(witSrc, "include golem:agent/agent-guest@2.0.0;")
        assertContains(witSrc, "// agent CounterAgent {")
        assertContains(witSrc, "//   mount: \"/counters/{name}\"")
        assertContains(witSrc, "//   constructor(name: string)")
        assertContains(witSrc, "//   method increment() -> s32")
        assertContains(witSrc, "//   method getValue() -> s32")
        assertContains(witSrc, "post: \"/increment\"")
        assertContains(witSrc, "prompt: \"Increase the count by one\"")
    }

    @Test
    fun `handles agent with no methods`() {
        val agent = SourceFile.kotlin(
            "EmptyAgent.kt",
            """
            package example

            import cloud.golem.annotations.Agent
            import cloud.golem.BaseAgent

            @Agent(mount = "/empty")
            class EmptyAgent : BaseAgent()
            """.trimIndent(),
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "EmptyAgentRegistration.kt")
        assertContains(reg, "fun registerEmptyAgent()")
        assertContains(reg, "emptyList()") // empty constructorParams + methods
        assertContains(reg, "{ _ -> EmptyAgent() }") // no-arg factory
    }

    @Test
    fun `handles void Unit return type`() {
        val agent = SourceFile.kotlin(
            "ResetAgent.kt",
            """
            package example

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/reset")
            class ResetAgent : BaseAgent() {
                @Endpoint(post = "/reset")
                fun reset() {}
            }
            """.trimIndent(),
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "ResetAgentRegistration.kt")
        assertContains(reg, "(instance as ResetAgent).reset(); SchemaValue.Unit_")
        assertTrue(generatedWit(compilation) != null)
    }

    // Proves the generated registration + entry point actually compile against a matching
    // native-runtime boundary (JVM-stubbed). Would catch unresolved-helper regressions.
    // Only the Kotlin language itself may declare anything in the `kotlin.*` package (the
    // compiler rejects user code doing so), so `kotlin.wasm.WasmExport` cannot be stubbed for a
    // JVM test -- meaning GolemGeneratedGuest.kt (which references it) can never compile on the
    // JVM test compiler, structurally. So: run KSP once (withCompilation=false) to capture the
    // generated REGISTRATION file's text, then compile ONLY that captured source (a plain
    // second pass, no KSP, no @WasmExport-referencing file involved) against a JVM stub of
    // cloud.golem.runtime. This still catches unresolved-helper regressions in the emitter.
    @Test
    fun `generated registration compiles against JVM stub native runtime`() {
        val sdkStub = SourceFile.kotlin(
            "GolemRuntimeStub.kt",
            """
            package cloud.golem.runtime

            // JVM-compilable stub mirroring the native SDK's cloud.golem.runtime surface the
            // generated registration code uses (NOT the @WasmExport entry point -- see above).
            sealed class SchemaValue {
                data class S32(val v: Int) : SchemaValue()
                data class Str(val v: String) : SchemaValue()
                data class Record(val fields: List<SchemaValue>) : SchemaValue()
                object Unit_ : SchemaValue()
            }

            class NativeParamSchema(val name: String, val witType: String)
            class NativeHttpEndpoint(
                val verb: String,
                val path: String,
                val auth: Boolean = false,
                val cors: List<String> = emptyList()
            )
            class NativeMethodDescriptor(
                val name: String,
                val outputWitType: String,
                val inputParams: List<NativeParamSchema>,
                val httpEndpoints: List<NativeHttpEndpoint>,
                val promptHint: String = "",
                val readOnlyCache: String? = null,
                val handler: (Any, List<SchemaValue>) -> SchemaValue
            )
            class NativeAgentDescriptor(
                val typeName: String,
                val description: String,
                val mountPath: String,
                val constructorParams: List<NativeParamSchema>,
                val methods: List<NativeMethodDescriptor>,
                val factory: (List<SchemaValue>) -> Any,
                val mountAuth: Boolean = false,
                val mountCors: List<String> = emptyList(),
                val mode: String = "durable",
                val snapshotting: String = "disabled"
            )
            object NativeAgentRuntime {
                fun registerAgent(descriptor: NativeAgentDescriptor) {}
            }
            """.trimIndent(),
        )

        val agent = SourceFile.kotlin(
            "CounterAgentCompile.kt",
            """
            package counter

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/counters/{name}", description = "A durable counter agent")
            class CounterAgentCompile(val name: String) : BaseAgent() {
                private var value = 0

                @Endpoint(post = "/increment")
                fun increment(): Int { value++; return value }
            }
            """.trimIndent(),
        )

        // Pass 1: run KSP (no compilation) to capture the generated registration file's text.
        val kspCompilation = runProcessor(agent)
        val registrationSource = generated(kspCompilation, "CounterAgentCompileRegistration.kt")

        // Pass 2: compile the ORIGINAL agent source + the captured registration text + the JVM
        // stub together (plain compilation, no KSP, no @WasmExport-referencing file involved).
        val compilation = KotlinCompilation().apply {
            sources = listOf(
                annotationStubs(),
                baseAgentStub(),
                sdkStub,
                agent,
                SourceFile.kotlin("CounterAgentCompileRegistration.kt", registrationSource),
            )
            inheritClassPath = true
            messageOutputStream = System.out
        }
        val result = compilation.compile()
        assertTrue(
            result.exitCode == KotlinCompilation.ExitCode.OK,
            "Generated registration did not compile: ${result.messages}",
        )
    }

    @Test
    fun `derives SnapshotCodec for an agent implementing Snapshotted with a data class state`() {
        val state = SourceFile.kotlin(
            "CounterState.kt",
            """
            package snap
            data class CounterState(val value: Int, val label: String)
            """.trimIndent(),
        )
        val agent = SourceFile.kotlin(
            "SnapAgent.kt",
            """
            package snap

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent
            import cloud.golem.Snapshotted

            @Agent(mount = "/snap")
            class SnapAgent : BaseAgent(), Snapshotted<CounterState> {
                override var state = CounterState(0, "")

                @Endpoint(post = "/inc")
                fun inc(): Int { state = state.copy(value = state.value + 1); return state.value }
            }
            """.trimIndent(),
        )
        val reg = generated(runProcessor(state, agent), "SnapAgentRegistration.kt")
        // The snapshot codec argument is spliced after the snapshotting argument.
        assertContains(reg, "snapshotCodec = cloud.golem.runtime.SnapshotCodec(")
        assertContains(reg, "save = { inst -> cloud.golem.runtime.SchemaValueBytes.encode(")
        assertContains(reg, "load = { inst, bytes -> (inst as SnapAgent).state =")
        // Round-trips through the record encoder for the data-class state.
        assertContains(reg, "(inst as SnapAgent).state")
        assertContains(reg, "cloud.golem.runtime.SchemaValueBytes.decode(bytes)")
    }

    // Proves the derived SnapshotCodec compiles against a JVM stub of the native runtime surface
    // (mirrors the registration-compile test, extended with SnapshotCodec/SchemaValueBytes and the
    // snapshotCodec descriptor param). Catches unresolved-helper / mis-spliced-expression regressions
    // in the generated save/load bodies that text-only assertions miss.
    @Test
    fun `derived SnapshotCodec compiles against JVM stub native runtime`() {
        val sdkStub = SourceFile.kotlin(
            "GolemRuntimeStubSnap.kt",
            """
            package cloud.golem.runtime

            sealed class SchemaValue {
                data class S32(val v: Int) : SchemaValue()
                data class Str(val v: String) : SchemaValue()
                data class Record(val fields: List<SchemaValue>) : SchemaValue()
                object Unit_ : SchemaValue()
            }

            object SchemaValueBytes {
                fun encode(v: SchemaValue): ByteArray = ByteArray(0)
                fun decode(bytes: ByteArray): SchemaValue = SchemaValue.Unit_
            }
            class SnapshotCodec(
                val save: (Any) -> ByteArray,
                val load: (Any, ByteArray) -> Unit,
            )

            class NativeParamSchema(val name: String, val witType: String)
            class NativeHttpEndpoint(
                val verb: String,
                val path: String,
                val auth: Boolean = false,
                val cors: List<String> = emptyList()
            )
            class NativeMethodDescriptor(
                val name: String,
                val outputWitType: String,
                val inputParams: List<NativeParamSchema>,
                val httpEndpoints: List<NativeHttpEndpoint>,
                val promptHint: String = "",
                val readOnlyCache: String? = null,
                val handler: (Any, List<SchemaValue>) -> SchemaValue
            )
            class NativeAgentDescriptor(
                val typeName: String,
                val description: String,
                val mountPath: String,
                val constructorParams: List<NativeParamSchema>,
                val methods: List<NativeMethodDescriptor>,
                val factory: (List<SchemaValue>) -> Any,
                val mountAuth: Boolean = false,
                val mountCors: List<String> = emptyList(),
                val mode: String = "durable",
                val snapshotting: String = "disabled",
                val snapshotCodec: SnapshotCodec? = null
            )
            object NativeAgentRuntime {
                fun registerAgent(descriptor: NativeAgentDescriptor) {}
            }
            """.trimIndent(),
        )
        val state = SourceFile.kotlin(
            "CounterStateCompile.kt",
            """
            package snap
            data class CounterStateCompile(val value: Int, val label: String)
            """.trimIndent(),
        )
        val agent = SourceFile.kotlin(
            "SnapAgentCompile.kt",
            """
            package snap

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent
            import cloud.golem.Snapshotted

            @Agent(mount = "/snap")
            class SnapAgentCompile : BaseAgent(), Snapshotted<CounterStateCompile> {
                override var state = CounterStateCompile(0, "")

                @Endpoint(post = "/inc")
                fun inc(): Int = state.value
            }
            """.trimIndent(),
        )

        // Pass 1: run KSP (no compilation) to capture the generated registration file's text.
        val kspCompilation = runProcessor(state, agent)
        val registrationSource = generated(kspCompilation, "SnapAgentCompileRegistration.kt")

        // Pass 2: compile the agent + captured registration + JVM stub together (no KSP).
        val compilation = KotlinCompilation().apply {
            sources = listOf(
                annotationStubs(),
                baseAgentStub(),
                sdkStub,
                state,
                agent,
                SourceFile.kotlin("SnapAgentCompileRegistration.kt", registrationSource),
            )
            inheritClassPath = true
            messageOutputStream = System.out
        }
        val result = compilation.compile()
        assertTrue(
            result.exitCode == KotlinCompilation.ExitCode.OK,
            "Generated SnapshotCodec did not compile: ${result.messages}",
        )
    }

    @Test
    fun `generates asInt and Str wrap for Int param and String return`() {
        val agent = SourceFile.kotlin(
            "GreetAgent.kt",
            """
            package greet

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent

            @Agent(mount = "/greet", description = "Greet agent")
            class GreetAgent : BaseAgent() {
                @Endpoint(post = "/hello")
                fun hello(times: Int): String = "hello".repeat(times)
            }
            """.trimIndent(),
        )
        val compilation = runProcessor(agent)
        val reg = generated(compilation, "GreetAgentRegistration.kt")
        assertContains(reg, "(input[0] as SchemaValue.S32).v")
        assertContains(reg, "SchemaValue.Str((instance as GreetAgent).hello(")
    }

    @Test
    fun `resolves Datetime to datetime and Either to result`() {
        val datetime = SourceFile.kotlin(
            "Datetime.kt",
            """
            package cloud.golem
            data class Datetime(val seconds: Long, val nanoseconds: Int)
            """.trimIndent(),
        )
        val either = SourceFile.kotlin(
            "Either.kt",
            """
            package cloud.golem.runtime
            sealed class Either<out L, out R> {
                data class Left<out L>(val value: L) : Either<L, Nothing>()
                data class Right<out R>(val value: R) : Either<Nothing, R>()
            }
            """.trimIndent(),
        )
        val agent = SourceFile.kotlin(
            "EventAgent.kt",
            """
            package events

            import cloud.golem.annotations.Agent
            import cloud.golem.annotations.Endpoint
            import cloud.golem.BaseAgent
            import cloud.golem.Datetime
            import cloud.golem.runtime.Either

            @Agent(mount = "/events/{name}")
            class EventAgent(val name: String) : BaseAgent() {
                @Endpoint(post = "/at")
                fun at(t: Datetime): Either<String, Int> = Either.Right(t.nanoseconds)
            }
            """.trimIndent(),
        )
        val reg = generated(runProcessor(datetime, either, agent), "EventAgentRegistration.kt")
        // Datetime param -> "datetime"; Either<String,Int> return -> result<s32,string> (Right=ok).
        assertContains(reg, "NativeParamSchema(\"t\", \"datetime\")")
        assertContains(reg, "\"result<s32,string>\"")
        // param decode builds a Datetime; return encode branches on Either.
        assertContains(reg, "cloud.golem.Datetime(")
        assertContains(reg, "cloud.golem.runtime.Either.Right ->")
    }
}
