package rpc:counters;

interface api {
  use golem:api/host@1.1.6.{promise-id};

  resource counter {
    constructor(name: string);
    inc-by: func(value: u64);
    get-value: func() -> u64;

    create-promise: func() -> promise-id;
    block-on-promise: func(promise: promise-id) -> ();

    get-args: func() -> list<string>;
    get-env: func() -> list<tuple<string, string>>;
  }

  inc-global-by: func(value: u64);
  get-global-value: func() -> u64;

  get-all-dropped: func() -> list<tuple<string, u64>>;

  variant timeline-node {
    leaf,
  }

  bug-wasm-rpc-i32: func(in: timeline-node) -> timeline-node;

  bug-golem1265: func(s: string) -> result<_, string>;
}

world counters {
  import wasi:clocks/monotonic-clock@0.2.0;
  import golem:api/host@1.1.6;
  export api;
}
