package golem:it;

world shopping-cart {
  record product-item {
    product-id: string,
    name: string,
    price: f32,
    quantity: u32,
  }

  record order {
    order-id: string,
    items: list<product-item>,
    total: f32,
    timestamp: u64,
  }

  record order-confirmation {
    order-id: string,
  }

  variant checkout-result {
    error(string),
    success(order-confirmation),
  }

  export initialize-cart: func(user-id: string) -> ();

  export add-item: func(item: product-item) -> ();

  export remove-item: func(product-id: string) -> ();

  export update-item-quantity: func(product-id: string, quantity: u32) -> ();

  export checkout: func() -> checkout-result;

  export get-cart-contents: func() -> list<product-item>;
}
