package it:scheduled-invocation-stubless-client;

interface client-api {
  test1: func() -> ();
  test2: func() -> ();
}

world server {
  import wasi:clocks/wall-clock@0.2.0;
  import golem:api/host@1.1.5;

  export client-api;
}
