name: 'Docker Publish Setup'
description: 'Common setup for Docker image publishing jobs'
inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-password:
    description: 'Docker Hub password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fetch tag
      shell: bash
      run: git fetch origin --deepen=1
    - name: Prepare platforms
      shell: bash
      run: echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
    - name: Download Targets
      uses: actions/download-artifact@v4
      with:
        pattern: docker-targets-build-*
        path: target
        merge-multiple: true
    - name: Extract Targets
      shell: bash
      run: |
        ls -R target
        cd target
        for f in *.tar; do tar xvf "$f"; done
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set Docker version
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == 'push' ] && [ "${{ github.ref_type }}" == 'tag' ]; then
          DOCKER_VERSION=$(echo "${{ github.ref }}" | sed 's|^refs/tags/v||')
          echo "DOCKER_VERSION=${DOCKER_VERSION}" >> $GITHUB_ENV
        else
          COMMIT_SHORT_HASH=$(git rev-parse --short=7 HEAD)
          echo "DOCKER_VERSION=${COMMIT_SHORT_HASH}" >> $GITHUB_ENV
        fi
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
