// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://license.golem.cloud/LICENSE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Runtime trait surface for converting Rust values to and from the
//! recursive schema model.
//!
//! The two core traits are:
//!
//! - [`IntoSchema`] — emits a self-contained [`SchemaGraph`] for a type and
//!   converts a Rust value of that type into a matching [`SchemaValue`].
//! - [`FromSchema`] — decodes a [`SchemaValue`] back into a Rust value.
//!
//! Hand-written impls for the standard primitive set live below. Derived
//! impls are generated by the `golem-schema-derive` crate, but the traits
//! themselves can be implemented by hand for any type that needs a custom
//! mapping.

use crate::schema::graph::{SchemaGraph, SchemaTypeDef};
use crate::schema::metadata::{MetadataEnvelope, TypeId};
use crate::schema::schema_type::SchemaType;
use crate::schema::schema_value::{
    BinaryValuePayload, DurationValuePayload, SchemaValue, SecretValuePayload, TextValuePayload,
};
use crate::schema::validation::{SchemaError, validate_graph};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::{self, Display, Formatter};

// =====================================================================
// Trait surface
// =====================================================================

/// Convert a Rust type into a self-contained schema graph and a
/// [`SchemaValue`] tree.
///
/// The Rust-SDK default `type_id()` is derived from
/// [`core::any::type_name`] by replacing `::` with `.` so the identifier
/// matches the language-independent dotted-FQN form (`a.b.c.Xyz`, see
/// §4.20 of the value-type spec). Generic instantiations keep the angle
/// brackets and normalize their contents the same way:
/// `my_crate::Container<my_crate::user::Profile>` becomes
/// `my_crate.Container<my_crate.user.Profile>`.
///
/// `#[schema(named = "shared.foo")]` overrides the base name. For a
/// generic type the derive auto-suffixes the explicit name with the
/// resolved arguments so each instantiation gets its own definition.
pub trait IntoSchema {
    fn type_id() -> TypeId;
    fn register_in(builder: &mut SchemaBuilder) -> SchemaType;
    fn to_value(&self) -> SchemaValue;
}

/// Decode a [`SchemaValue`] back into a Rust value.
pub trait FromSchema: Sized {
    fn from_value(value: &SchemaValue) -> Result<Self, FromSchemaError>;
}

/// Build a self-contained graph for `T` and run well-formedness
/// validation on the result. Returns the first reported [`SchemaError`]
/// if the graph is malformed.
pub fn try_into_schema_graph<T: IntoSchema + ?Sized>() -> Result<SchemaGraph, SchemaError> {
    let mut builder = SchemaBuilder::new();
    let root = T::register_in(&mut builder);
    let graph = SchemaGraph {
        defs: builder.finish(),
        root,
    };
    match validate_graph(&graph) {
        Ok(()) => Ok(graph),
        Err(mut errors) => Err(errors.remove(0)),
    }
}

// =====================================================================
// Builder
// =====================================================================

/// Mutable working set used while a graph is being built up.
///
/// Derived `register_in` bodies call [`SchemaBuilder::reserve`] before
/// recursing into inner fields so back-references through
/// [`SchemaType::Ref`] can close without infinite recursion. Once the
/// body is fully constructed they call [`SchemaBuilder::commit`] to
/// promote the reservation to a real definition.
#[derive(Default)]
pub struct SchemaBuilder {
    defs: Vec<SchemaTypeDef>,
    reserved: HashSet<TypeId>,
}

impl SchemaBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    /// `true` when `id` is already reserved or committed in this builder.
    pub fn is_registered(&self, id: &TypeId) -> bool {
        self.reserved.contains(id) || self.defs.iter().any(|d| &d.id == id)
    }

    /// Reserve a slot for `id` so recursive references close without
    /// infinite recursion. Must be followed by a matching
    /// [`Self::commit`] call once the body is built.
    pub fn reserve(&mut self, id: TypeId) {
        self.reserved.insert(id);
    }

    /// Promote a reservation to a real definition.
    pub fn commit(
        &mut self,
        id: TypeId,
        name: Option<String>,
        metadata: MetadataEnvelope,
        body: SchemaType,
    ) {
        self.reserved.remove(&id);
        // De-duplicate: if a definition with this id already exists
        // (because of a parallel registration in a sibling subtree) the
        // first one wins; later registrations are idempotent overwrites.
        if let Some(existing) = self.defs.iter_mut().find(|d| d.id == id) {
            *existing = SchemaTypeDef {
                id,
                name,
                metadata,
                body,
            };
        } else {
            self.defs.push(SchemaTypeDef {
                id,
                name,
                metadata,
                body,
            });
        }
    }

    /// Consume the builder and return the accumulated definitions.
    pub fn finish(self) -> Vec<SchemaTypeDef> {
        self.defs
    }

    /// Build a [`SchemaGraph`] using `root` as the entry point.
    pub fn into_graph(self, root: SchemaType) -> SchemaGraph {
        SchemaGraph {
            defs: self.finish(),
            root,
        }
    }
}

// =====================================================================
// TypeId helpers — used by generated code
// =====================================================================

/// Normalize a Rust path-form name into the dotted FQN used by [`TypeId`].
///
/// Every `::` becomes `.`; the inside of any `<…>` argument list is
/// normalized recursively by the same rule (because `::` only occurs in
/// path-like positions, a plain string replacement suffices). See §4.20.
pub fn normalize_type_path(raw: &str) -> String {
    raw.replace("::", ".")
}

/// Build a [`TypeId`] for a generic instantiation. `base` is the
/// already-normalized base name (e.g., `"my_crate.Container"`) and
/// `args` are the resolved argument [`TypeId`]s in declaration order.
///
/// `Container<u32>` → `my_crate.Container<u32>`.
/// `Container<u32, String>` → `my_crate.Container<u32, alloc.string.String>`.
pub fn type_id_with_args(base: &str, args: &[TypeId]) -> TypeId {
    if args.is_empty() {
        TypeId::new(base.to_string())
    } else {
        let mut s = String::with_capacity(base.len() + 16);
        s.push_str(base);
        s.push('<');
        for (i, a) in args.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            s.push_str(a.as_str());
        }
        s.push('>');
        TypeId::new(s)
    }
}

/// Default [`TypeId`] derivation from a `core::any::type_name::<Self>()`
/// output. Equivalent to `normalize_type_path` but exposed under a
/// generated-code-friendly name.
pub fn default_type_id_from(raw: &str) -> TypeId {
    TypeId::new(normalize_type_path(raw))
}

// =====================================================================
// Errors
// =====================================================================

/// Errors produced by [`FromSchema::from_value`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FromSchemaError {
    /// The expected value shape does not match what was provided.
    ShapeMismatch {
        expected: String,
        actual: String,
        context: String,
    },
    /// A variant or enum case index is out of range.
    OutOfRange {
        index: u32,
        len: u32,
        context: String,
    },
    /// A union tag was not matched by any branch.
    UnknownUnionTag(String),
    /// Free-form error message produced by generated decoders.
    Custom(String),
}

/// Backwards-compatible alias kept for codegen and consumers.
pub type DecodeError = FromSchemaError;

impl FromSchemaError {
    pub fn shape_mismatch(
        expected: impl Into<String>,
        actual: impl Into<String>,
        context: impl Into<String>,
    ) -> Self {
        Self::ShapeMismatch {
            expected: expected.into(),
            actual: actual.into(),
            context: context.into(),
        }
    }

    pub fn out_of_range(index: u32, len: u32, context: impl Into<String>) -> Self {
        Self::OutOfRange {
            index,
            len,
            context: context.into(),
        }
    }

    pub fn custom(msg: impl Into<String>) -> Self {
        Self::Custom(msg.into())
    }
}

impl Display for FromSchemaError {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            FromSchemaError::ShapeMismatch {
                expected,
                actual,
                context,
            } => write!(
                f,
                "shape mismatch in {context}: expected {expected}, got {actual}"
            ),
            FromSchemaError::OutOfRange {
                index,
                len,
                context,
            } => write!(f, "index {index} out of range (len {len}) in {context}"),
            FromSchemaError::UnknownUnionTag(tag) => write!(f, "unknown union tag `{tag}`"),
            FromSchemaError::Custom(msg) => f.write_str(msg),
        }
    }
}

impl std::error::Error for FromSchemaError {}

/// Stringify the kind of a [`SchemaValue`] for error messages.
pub fn value_kind(v: &SchemaValue) -> &'static str {
    match v {
        SchemaValue::Bool(_) => "bool",
        SchemaValue::S8(_) => "s8",
        SchemaValue::S16(_) => "s16",
        SchemaValue::S32(_) => "s32",
        SchemaValue::S64(_) => "s64",
        SchemaValue::U8(_) => "u8",
        SchemaValue::U16(_) => "u16",
        SchemaValue::U32(_) => "u32",
        SchemaValue::U64(_) => "u64",
        SchemaValue::F32(_) => "f32",
        SchemaValue::F64(_) => "f64",
        SchemaValue::Char(_) => "char",
        SchemaValue::String(_) => "string",
        SchemaValue::Record { .. } => "record",
        SchemaValue::Variant(_) => "variant",
        SchemaValue::Enum { .. } => "enum",
        SchemaValue::Flags { .. } => "flags",
        SchemaValue::Tuple { .. } => "tuple",
        SchemaValue::List { .. } => "list",
        SchemaValue::FixedList { .. } => "fixed-list",
        SchemaValue::Map { .. } => "map",
        SchemaValue::Option { .. } => "option",
        SchemaValue::Result(_) => "result",
        SchemaValue::Text(_) => "text",
        SchemaValue::Binary(_) => "binary",
        SchemaValue::Path { .. } => "path",
        SchemaValue::Url { .. } => "url",
        SchemaValue::Datetime { .. } => "datetime",
        SchemaValue::Duration(_) => "duration",
        SchemaValue::Quantity(_) => "quantity",
        SchemaValue::Union(_) => "union",
        SchemaValue::Secret(_) => "secret",
        SchemaValue::QuotaToken(_) => "quota-token",
    }
}

// =====================================================================
// Rich-scalar codec helpers (used by codegen for #[schema(text(...))]
// etc.)
// =====================================================================

pub fn text_to_value(body: String, language: Option<String>) -> SchemaValue {
    SchemaValue::Text(TextValuePayload {
        text: body,
        language,
    })
}

pub fn text_from_value(v: &SchemaValue, context: &'static str) -> Result<String, FromSchemaError> {
    match v {
        SchemaValue::Text(p) => Ok(p.text.clone()),
        other => Err(FromSchemaError::shape_mismatch(
            "text",
            value_kind(other),
            context,
        )),
    }
}

pub fn binary_to_value(bytes: Vec<u8>, mime_type: Option<String>) -> SchemaValue {
    SchemaValue::Binary(BinaryValuePayload { bytes, mime_type })
}

pub fn binary_from_value(
    v: &SchemaValue,
    context: &'static str,
) -> Result<Vec<u8>, FromSchemaError> {
    match v {
        SchemaValue::Binary(p) => Ok(p.bytes.clone()),
        other => Err(FromSchemaError::shape_mismatch(
            "binary",
            value_kind(other),
            context,
        )),
    }
}

pub fn path_to_value(path: String) -> SchemaValue {
    SchemaValue::Path { path }
}

pub fn path_from_value(v: &SchemaValue, context: &'static str) -> Result<String, FromSchemaError> {
    match v {
        SchemaValue::Path { path } => Ok(path.clone()),
        other => Err(FromSchemaError::shape_mismatch(
            "path",
            value_kind(other),
            context,
        )),
    }
}

pub fn url_to_value(url: String) -> SchemaValue {
    SchemaValue::Url { url }
}

pub fn url_from_value(v: &SchemaValue, context: &'static str) -> Result<String, FromSchemaError> {
    match v {
        SchemaValue::Url { url } => Ok(url.clone()),
        other => Err(FromSchemaError::shape_mismatch(
            "url",
            value_kind(other),
            context,
        )),
    }
}

pub fn secret_to_value(secret_ref: String) -> SchemaValue {
    SchemaValue::Secret(SecretValuePayload { secret_ref })
}

pub fn secret_from_value(
    v: &SchemaValue,
    context: &'static str,
) -> Result<String, FromSchemaError> {
    match v {
        SchemaValue::Secret(p) => Ok(p.secret_ref.clone()),
        other => Err(FromSchemaError::shape_mismatch(
            "secret",
            value_kind(other),
            context,
        )),
    }
}

// =====================================================================
// Primitive impls
// =====================================================================

macro_rules! impl_primitive {
    ($ty:ty, $type_id:literal, $schema_ty:expr, $variant:ident) => {
        impl IntoSchema for $ty {
            fn type_id() -> TypeId {
                TypeId::new($type_id)
            }
            fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
                $schema_ty
            }
            fn to_value(&self) -> SchemaValue {
                SchemaValue::$variant(*self)
            }
        }
        impl FromSchema for $ty {
            fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
                match v {
                    SchemaValue::$variant(x) => Ok(*x),
                    other => Err(FromSchemaError::shape_mismatch(
                        stringify!($variant),
                        value_kind(other),
                        stringify!($ty),
                    )),
                }
            }
        }
    };
}

impl_primitive!(bool, "bool", SchemaType::Bool, Bool);
impl_primitive!(i8, "i8", SchemaType::S8, S8);
impl_primitive!(i16, "i16", SchemaType::S16, S16);
impl_primitive!(i32, "i32", SchemaType::S32, S32);
impl_primitive!(i64, "i64", SchemaType::S64, S64);
impl_primitive!(u8, "u8", SchemaType::U8, U8);
impl_primitive!(u16, "u16", SchemaType::U16, U16);
impl_primitive!(u32, "u32", SchemaType::U32, U32);
impl_primitive!(u64, "u64", SchemaType::U64, U64);
impl_primitive!(f32, "f32", SchemaType::F32, F32);
impl_primitive!(f64, "f64", SchemaType::F64, F64);
impl_primitive!(char, "char", SchemaType::Char, Char);

impl IntoSchema for String {
    fn type_id() -> TypeId {
        TypeId::new("alloc.string.String")
    }
    fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::String
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::String(self.clone())
    }
}

impl FromSchema for String {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::String(s) => Ok(s.clone()),
            other => Err(FromSchemaError::shape_mismatch(
                "string",
                value_kind(other),
                "String",
            )),
        }
    }
}

// =====================================================================
// Option / Vec / Map / Result / Box / Rc / Arc / tuples
// =====================================================================

impl<T: IntoSchema + ?Sized> IntoSchema for Box<T> {
    fn type_id() -> TypeId {
        T::type_id()
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        T::register_in(b)
    }
    fn to_value(&self) -> SchemaValue {
        (**self).to_value()
    }
}

impl<T: FromSchema> FromSchema for Box<T> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        Ok(Box::new(T::from_value(v)?))
    }
}

impl<T: IntoSchema + ?Sized> IntoSchema for std::rc::Rc<T> {
    fn type_id() -> TypeId {
        T::type_id()
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        T::register_in(b)
    }
    fn to_value(&self) -> SchemaValue {
        (**self).to_value()
    }
}

impl<T: FromSchema> FromSchema for std::rc::Rc<T> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        Ok(std::rc::Rc::new(T::from_value(v)?))
    }
}

impl<T: IntoSchema + ?Sized> IntoSchema for std::sync::Arc<T> {
    fn type_id() -> TypeId {
        T::type_id()
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        T::register_in(b)
    }
    fn to_value(&self) -> SchemaValue {
        (**self).to_value()
    }
}

impl<T: FromSchema> FromSchema for std::sync::Arc<T> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        Ok(std::sync::Arc::new(T::from_value(v)?))
    }
}

impl<T: IntoSchema> IntoSchema for Option<T> {
    fn type_id() -> TypeId {
        type_id_with_args("core.option.Option", &[T::type_id()])
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Option {
            inner: Box::new(T::register_in(b)),
        }
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Option {
            inner: self.as_ref().map(|x| Box::new(x.to_value())),
        }
    }
}

impl<T: FromSchema> FromSchema for Option<T> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Option { inner: Some(x) } => Ok(Some(T::from_value(x)?)),
            SchemaValue::Option { inner: None } => Ok(None),
            other => Err(FromSchemaError::shape_mismatch(
                "option",
                value_kind(other),
                "Option",
            )),
        }
    }
}

impl<T: IntoSchema> IntoSchema for Vec<T> {
    fn type_id() -> TypeId {
        type_id_with_args("alloc.vec.Vec", &[T::type_id()])
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::List {
            element: Box::new(T::register_in(b)),
        }
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::List {
            elements: self.iter().map(|x| x.to_value()).collect(),
        }
    }
}

impl<T: FromSchema> FromSchema for Vec<T> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::List { elements } => elements.iter().map(T::from_value).collect(),
            other => Err(FromSchemaError::shape_mismatch(
                "list",
                value_kind(other),
                "Vec",
            )),
        }
    }
}

impl<K: IntoSchema, V: IntoSchema> IntoSchema for HashMap<K, V> {
    fn type_id() -> TypeId {
        type_id_with_args("std.collections.HashMap", &[K::type_id(), V::type_id()])
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Map {
            key: Box::new(K::register_in(b)),
            value: Box::new(V::register_in(b)),
        }
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Map {
            entries: self
                .iter()
                .map(|(k, v)| (k.to_value(), v.to_value()))
                .collect(),
        }
    }
}

impl<K, V> FromSchema for HashMap<K, V>
where
    K: FromSchema + std::hash::Hash + Eq,
    V: FromSchema,
{
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Map { entries } => entries
                .iter()
                .map(|(k, v)| Ok((K::from_value(k)?, V::from_value(v)?)))
                .collect(),
            other => Err(FromSchemaError::shape_mismatch(
                "map",
                value_kind(other),
                "HashMap",
            )),
        }
    }
}

impl<K: IntoSchema, V: IntoSchema> IntoSchema for BTreeMap<K, V> {
    fn type_id() -> TypeId {
        type_id_with_args("alloc.collections.BTreeMap", &[K::type_id(), V::type_id()])
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Map {
            key: Box::new(K::register_in(b)),
            value: Box::new(V::register_in(b)),
        }
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Map {
            entries: self
                .iter()
                .map(|(k, v)| (k.to_value(), v.to_value()))
                .collect(),
        }
    }
}

impl<K, V> FromSchema for BTreeMap<K, V>
where
    K: FromSchema + Ord,
    V: FromSchema,
{
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Map { entries } => entries
                .iter()
                .map(|(k, v)| Ok((K::from_value(k)?, V::from_value(v)?)))
                .collect(),
            other => Err(FromSchemaError::shape_mismatch(
                "map",
                value_kind(other),
                "BTreeMap",
            )),
        }
    }
}

// =====================================================================
// Tuples (1..12)
// =====================================================================

macro_rules! impl_tuple {
    ( $name:literal => $( $idx:tt : $t:ident ),+ ) => {
        impl< $( $t : IntoSchema ),+ > IntoSchema for ( $( $t, )+ ) {
            fn type_id() -> TypeId {
                type_id_with_args($name, &[ $( <$t as IntoSchema>::type_id() ),+ ])
            }
            fn register_in(b: &mut SchemaBuilder) -> SchemaType {
                SchemaType::Tuple {
                    elements: vec![ $( <$t as IntoSchema>::register_in(b) ),+ ],
                }
            }
            fn to_value(&self) -> SchemaValue {
                SchemaValue::Tuple {
                    elements: vec![ $( IntoSchema::to_value(&self.$idx) ),+ ],
                }
            }
        }
        impl< $( $t : FromSchema ),+ > FromSchema for ( $( $t, )+ ) {
            fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
                match v {
                    SchemaValue::Tuple { elements } => {
                        let expected = [ $( stringify!($t) ),+ ].len();
                        if elements.len() != expected {
                            return Err(FromSchemaError::custom(format!(
                                "tuple length mismatch: expected {expected}, got {}",
                                elements.len()
                            )));
                        }
                        Ok(( $( <$t as FromSchema>::from_value(&elements[$idx])? , )+ ))
                    }
                    other => Err(FromSchemaError::shape_mismatch(
                        "tuple",
                        value_kind(other),
                        "tuple",
                    )),
                }
            }
        }
    };
}

impl_tuple!("core.tuple.Tuple1" => 0: T0);
impl_tuple!("core.tuple.Tuple2" => 0: T0, 1: T1);
impl_tuple!("core.tuple.Tuple3" => 0: T0, 1: T1, 2: T2);
impl_tuple!("core.tuple.Tuple4" => 0: T0, 1: T1, 2: T2, 3: T3);
impl_tuple!("core.tuple.Tuple5" => 0: T0, 1: T1, 2: T2, 3: T3, 4: T4);
impl_tuple!("core.tuple.Tuple6" => 0: T0, 1: T1, 2: T2, 3: T3, 4: T4, 5: T5);
impl_tuple!("core.tuple.Tuple7" => 0: T0, 1: T1, 2: T2, 3: T3, 4: T4, 5: T5, 6: T6);
impl_tuple!("core.tuple.Tuple8" => 0: T0, 1: T1, 2: T2, 3: T3, 4: T4, 5: T5, 6: T6, 7: T7);

impl IntoSchema for () {
    fn type_id() -> TypeId {
        TypeId::new("core.tuple.Unit")
    }
    fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Tuple { elements: vec![] }
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Tuple { elements: vec![] }
    }
}

impl FromSchema for () {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Tuple { elements } if elements.is_empty() => Ok(()),
            other => Err(FromSchemaError::shape_mismatch(
                "unit tuple",
                value_kind(other),
                "()",
            )),
        }
    }
}

// =====================================================================
// Result<T, E>
// =====================================================================

impl<T: IntoSchema, E: IntoSchema> IntoSchema for Result<T, E> {
    fn type_id() -> TypeId {
        type_id_with_args("core.result.Result", &[T::type_id(), E::type_id()])
    }
    fn register_in(b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Result(crate::schema::schema_type::ResultSpec {
            ok: Some(Box::new(T::register_in(b))),
            err: Some(Box::new(E::register_in(b))),
        })
    }
    fn to_value(&self) -> SchemaValue {
        use crate::schema::schema_value::ResultValuePayload;
        match self {
            Ok(x) => SchemaValue::Result(ResultValuePayload::Ok {
                value: Some(Box::new(x.to_value())),
            }),
            Err(e) => SchemaValue::Result(ResultValuePayload::Err {
                value: Some(Box::new(e.to_value())),
            }),
        }
    }
}

impl<T: FromSchema, E: FromSchema> FromSchema for Result<T, E> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        use crate::schema::schema_value::ResultValuePayload;
        match v {
            SchemaValue::Result(ResultValuePayload::Ok { value: Some(x) }) => {
                Ok(Ok(T::from_value(x)?))
            }
            SchemaValue::Result(ResultValuePayload::Err { value: Some(x) }) => {
                Ok(Err(E::from_value(x)?))
            }
            SchemaValue::Result(_) => Err(FromSchemaError::custom(
                "Result<T, E> requires non-unit ok/err payloads",
            )),
            other => Err(FromSchemaError::shape_mismatch(
                "result",
                value_kind(other),
                "Result",
            )),
        }
    }
}

// =====================================================================
// chrono / std::time
// =====================================================================

impl IntoSchema for chrono::DateTime<chrono::Utc> {
    fn type_id() -> TypeId {
        TypeId::new("chrono.DateTime<chrono.Utc>")
    }
    fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Datetime
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Datetime { value: *self }
    }
}

impl FromSchema for chrono::DateTime<chrono::Utc> {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Datetime { value } => Ok(*value),
            other => Err(FromSchemaError::shape_mismatch(
                "datetime",
                value_kind(other),
                "DateTime<Utc>",
            )),
        }
    }
}

impl IntoSchema for std::time::Duration {
    fn type_id() -> TypeId {
        TypeId::new("core.time.Duration")
    }
    fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Duration
    }
    fn to_value(&self) -> SchemaValue {
        let nanos = self.as_nanos();
        let clamped: i64 = if nanos > i64::MAX as u128 {
            i64::MAX
        } else {
            nanos as i64
        };
        SchemaValue::Duration(DurationValuePayload {
            nanoseconds: clamped,
        })
    }
}

impl FromSchema for std::time::Duration {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Duration(p) => {
                if p.nanoseconds < 0 {
                    Err(FromSchemaError::custom(
                        "std::time::Duration cannot decode a negative duration",
                    ))
                } else {
                    Ok(std::time::Duration::from_nanos(p.nanoseconds as u64))
                }
            }
            other => Err(FromSchemaError::shape_mismatch(
                "duration",
                value_kind(other),
                "Duration",
            )),
        }
    }
}

impl IntoSchema for chrono::Duration {
    fn type_id() -> TypeId {
        TypeId::new("chrono.Duration")
    }
    fn register_in(_b: &mut SchemaBuilder) -> SchemaType {
        SchemaType::Duration
    }
    fn to_value(&self) -> SchemaValue {
        SchemaValue::Duration(DurationValuePayload {
            nanoseconds: self
                .num_nanoseconds()
                .unwrap_or(self.num_seconds() * 1_000_000_000),
        })
    }
}

impl FromSchema for chrono::Duration {
    fn from_value(v: &SchemaValue) -> Result<Self, FromSchemaError> {
        match v {
            SchemaValue::Duration(p) => Ok(chrono::Duration::nanoseconds(p.nanoseconds)),
            other => Err(FromSchemaError::shape_mismatch(
                "duration",
                value_kind(other),
                "chrono::Duration",
            )),
        }
    }
}
