package golem:it;

interface api {
    use golem:api/host@1.1.7.{promise-id};

    create: func() -> promise-id;
    await: func(id: promise-id) -> list<u8>;
    poll: func(id: promise-id) -> option<list<u8>>;
}

world promise {
  import golem:api/host@1.1.7;
  export api;
}
