use wit_value::*;

fn main() {
    let wit_value = WitValue::builder()
        .record()
        .item()
        .u8(1)
        .item()
        .record()
        .item()
        .u8(2)
        .item()
        .f64(0.1)
        .item()
        .variant(1)
        .record()
        .item()
        .string("xyz")
        .item()
        .bool(true)
        .finish()
        .finish()
        .finish()
        .item()
        .string("A record with a nested record.")
        .item()
        .tuple()
        .item()
        .f64(1.0)
        .item()
        .f64(2.0)
        .item()
        .f64(3.0)
        .finish()
        .item()
        .list()
        .item()
        .string("tag1")
        .item()
        .string("tag2")
        .finish()
        .finish();
    println!("wit_value: {:?}", wit_value);
}
