// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     golem:core@2.0.0
//     wasi:clocks@0.3.0
//     golem:api@1.5.0
//     golem:agent@2.0.0
//     golem:rdbms@1.5.0
//     golem:durability@1.5.0
//     golem:quota@1.5.0
//     golem:secrets@0.1.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:blobstore
//     wasi:keyvalue@0.1.0
//     wasi:config@0.2.0-draft
//     wasi:logging
//     golem:websocket@1.5.0
//     wasi:http@0.3.0
//     golem:agent-guest
//     golem:tool@0.1.0
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:http@0.2.6

package golem_websocket_client

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type CloseInfo struct {
	Code   uint16
	Reason string
}

const (
	ErrorConnectionFailure uint8 = 0
	ErrorSendFailure       uint8 = 1
	ErrorReceiveFailure    uint8 = 2
	ErrorProtocolError     uint8 = 3
	ErrorClosed            uint8 = 4
	ErrorOther             uint8 = 5
)

type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) ConnectionFailure() string {
	if self.tag != ErrorConnectionFailure {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) SendFailure() string {
	if self.tag != ErrorSendFailure {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) ReceiveFailure() string {
	if self.tag != ErrorReceiveFailure {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) ProtocolError() string {
	if self.tag != ErrorProtocolError {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Closed() witTypes.Option[CloseInfo] {
	if self.tag != ErrorClosed {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Option[CloseInfo])
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorConnectionFailure(value string) Error {
	return Error{ErrorConnectionFailure, value}
}
func MakeErrorSendFailure(value string) Error {
	return Error{ErrorSendFailure, value}
}
func MakeErrorReceiveFailure(value string) Error {
	return Error{ErrorReceiveFailure, value}
}
func MakeErrorProtocolError(value string) Error {
	return Error{ErrorProtocolError, value}
}
func MakeErrorClosed(value witTypes.Option[CloseInfo]) Error {
	return Error{ErrorClosed, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

const (
	MessageText   uint8 = 0
	MessageBinary uint8 = 1
)

// A WebSocket message — text or binary
type Message struct {
	tag   uint8
	value any
}

func (self Message) Tag() uint8 {
	return self.tag
}

func (self Message) Text() string {
	if self.tag != MessageText {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Message) Binary() []uint8 {
	if self.tag != MessageBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeMessageText(value string) Message {
	return Message{MessageText, value}
}
func MakeMessageBinary(value []uint8) Message {
	return Message{MessageBinary, value}
}

//go:wasmimport golem:websocket/client@1.5.0 [resource-drop]websocket-connection
func resourceDropWebsocketConnection(handle int32)

// A WebSocket connection resource
type WebsocketConnection struct {
	handle *witRuntime.Handle
}

func (self *WebsocketConnection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *WebsocketConnection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *WebsocketConnection) Handle() int32 {
	return self.handle.Use()
}

func (self *WebsocketConnection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropWebsocketConnection(handle)
	}
}

func WebsocketConnectionFromOwnHandle(handleValue int32) *WebsocketConnection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &WebsocketConnection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropWebsocketConnection(handleValue)
		}
	}, 0)
	return value
}

func WebsocketConnectionFromBorrowHandle(handleValue int32) *WebsocketConnection {
	handle := witRuntime.MakeHandle(handleValue)
	return &WebsocketConnection{handle}
}

//go:wasmimport golem:websocket/client@1.5.0 [static]websocket-connection.connect
func wasm_import_static_websocket_connection_connect(arg0 uintptr, arg1 uint32, arg2 int32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func WebsocketConnectionConnect(url string, headers witTypes.Option[[]witTypes.Tuple2[string, string]]) witTypes.Result[*WebsocketConnection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(url))
	pinner.Pin(utf8)
	var option int32
	var option2 uintptr
	var option3 uint32
	switch headers.Tag() {
	case witTypes.OptionNone:

		option = int32(0)
		option2 = 0
		option3 = 0
	case witTypes.OptionSome:
		payload := headers.Some()
		slice := payload
		length := uint32(len(slice))
		result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result, index*(4*4))
			utf80 := unsafe.Pointer(unsafe.StringData((element).F0))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))
			utf81 := unsafe.Pointer(unsafe.StringData((element).F1))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf81)))

		}

		option = int32(1)
		option2 = uintptr(result)
		option3 = length
	default:
		panic("unreachable")
	}
	wasm_import_static_websocket_connection_connect(uintptr(utf8), uint32(len(url)), option, option2, option3, returnArea)
	var result10 witTypes.Result[*WebsocketConnection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result10 = witTypes.Ok[*WebsocketConnection, Error](WebsocketConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailure(value)

		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorSendFailure(value4)

		case 2:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorReceiveFailure(value5)

		case 3:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorProtocolError(value6)

		case 4:
			var option8 witTypes.Option[CloseInfo]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option8 = witTypes.None[CloseInfo]()
			case 1:
				value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

				option8 = witTypes.Some[CloseInfo](CloseInfo{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), value7})
			default:
				panic("unreachable")
			}

			variant = MakeErrorClosed(option8)

		case 5:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value9)

		default:
			panic("unreachable")
		}

		result10 = witTypes.Err[*WebsocketConnection, Error](variant)
	default:
		panic("unreachable")
	}
	result11 := result10
	return result11

}

//go:wasmimport golem:websocket/client@1.5.0 [method]websocket-connection.send
func wasm_import_method_websocket_connection_send(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func (self *WebsocketConnection) Send(message Message) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	var variant int32
	var variant0 uintptr
	var variant1 uint32
	switch message.Tag() {
	case MessageText:
		payload := message.Text()
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)

		variant = int32(0)
		variant0 = uintptr(utf8)
		variant1 = uint32(len(payload))

	case MessageBinary:
		payload := message.Binary()
		data := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data)

		variant = int32(1)
		variant0 = uintptr(data)
		variant1 = uint32(len(payload))

	default:
		panic("unreachable")
	}
	wasm_import_method_websocket_connection_send((self).Handle(), variant, variant0, variant1, returnArea)
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant7 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorConnectionFailure(value)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorSendFailure(value2)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorReceiveFailure(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorProtocolError(value4)

		case 4:
			var option witTypes.Option[CloseInfo]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option = witTypes.None[CloseInfo]()
			case 1:
				value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

				option = witTypes.Some[CloseInfo](CloseInfo{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), value5})
			default:
				panic("unreachable")
			}

			variant7 = MakeErrorClosed(option)

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorOther(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant7)
	default:
		panic("unreachable")
	}
	result8 := result
	return result8

}

//go:wasmimport golem:websocket/client@1.5.0 [async-lower][method]websocket-connection.receive
func wasm_import_method_websocket_connection_receive(arg0 int32, arg1 uintptr) int32

func (self *WebsocketConnection) Receive() witTypes.Result[Message, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_websocket_connection_receive((self).Handle(), returnArea)))
	var result witTypes.Result[Message, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var variant Message
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMessageText(value)

		case 1:
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMessageBinary(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Ok[Message, Error](variant)
	case 1:
		var variant7 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorConnectionFailure(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorSendFailure(value2)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorReceiveFailure(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorProtocolError(value4)

		case 4:
			var option witTypes.Option[CloseInfo]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option = witTypes.None[CloseInfo]()
			case 1:
				value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

				option = witTypes.Some[CloseInfo](CloseInfo{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), value5})
			default:
				panic("unreachable")
			}

			variant7 = MakeErrorClosed(option)

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorOther(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[Message, Error](variant7)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport golem:websocket/client@1.5.0 [async-lower][method]websocket-connection.receive-with-timeout
func wasm_import_method_websocket_connection_receive_with_timeout(arg0 int32, arg1 int64, arg2 uintptr) int32

func (self *WebsocketConnection) ReceiveWithTimeout(timeoutMs uint64) witTypes.Result[witTypes.Option[Message], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_websocket_connection_receive_with_timeout((self).Handle(), int64(timeoutMs), returnArea)))
	var result witTypes.Result[witTypes.Option[Message], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[Message]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = witTypes.None[Message]()
		case 1:
			var variant Message
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))

				variant = MakeMessageText(value)

			case 1:
				value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))

				variant = MakeMessageBinary(value0)

			default:
				panic("unreachable")
			}

			option = witTypes.Some[Message](variant)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[Message], Error](option)
	case 1:
		var variant8 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant8 = MakeErrorConnectionFailure(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant8 = MakeErrorSendFailure(value2)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant8 = MakeErrorReceiveFailure(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant8 = MakeErrorProtocolError(value4)

		case 4:
			var option6 witTypes.Option[CloseInfo]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option6 = witTypes.None[CloseInfo]()
			case 1:
				value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

				option6 = witTypes.Some[CloseInfo](CloseInfo{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), value5})
			default:
				panic("unreachable")
			}

			variant8 = MakeErrorClosed(option6)

		case 5:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant8 = MakeErrorOther(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[Message], Error](variant8)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport golem:websocket/client@1.5.0 [method]websocket-connection.close
func wasm_import_method_websocket_connection_close(arg0 int32, arg1 int32, arg2 int32, arg3 int32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func (self *WebsocketConnection) Close(code witTypes.Option[uint16], reason witTypes.Option[string]) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	var option int32
	var option0 int32
	switch code.Tag() {
	case witTypes.OptionNone:

		option = int32(0)
		option0 = 0
	case witTypes.OptionSome:
		payload := code.Some()

		option = int32(1)
		option0 = int32(payload)
	default:
		panic("unreachable")
	}
	var option1 int32
	var option2 uintptr
	var option3 uint32
	switch reason.Tag() {
	case witTypes.OptionNone:

		option1 = int32(0)
		option2 = 0
		option3 = 0
	case witTypes.OptionSome:
		payload := reason.Some()
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)

		option1 = int32(1)
		option2 = uintptr(utf8)
		option3 = uint32(len(payload))
	default:
		panic("unreachable")
	}
	wasm_import_method_websocket_connection_close((self).Handle(), option, option0, option1, option2, option3, returnArea)
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailure(value)

		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorSendFailure(value4)

		case 2:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorReceiveFailure(value5)

		case 3:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorProtocolError(value6)

		case 4:
			var option8 witTypes.Option[CloseInfo]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option8 = witTypes.None[CloseInfo]()
			case 1:
				value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

				option8 = witTypes.Some[CloseInfo](CloseInfo{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), value7})
			default:
				panic("unreachable")
			}

			variant = MakeErrorClosed(option8)

		case 5:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value9)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result10 := result
	return result10

}
