name: 'Restore Test Components'
description: 'Restore test component WASMs and install them'
runs:
  using: 'composite'
  steps:
    - name: Download built test component WASMs
      uses: actions/download-artifact@v8
      with:
        name: golem-test-components
        path: tmp/test-components-wasm
    - name: Install test component WASMs
      shell: bash
      run: cp -v tmp/test-components-wasm/*.wasm test-components/
