// Copyright 2024-2026 Golem Cloud
//
// Licensed under the Golem Source License v1.1 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://license.golem.cloud/LICENSE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Model → WIT conversions for retry-policy tree types.
//!
//! Simple record/enum types (`PredicateValue`, `PropertyComparison`, etc.) have their
//! `From` impls generated by the `IntoValue` / `FromValue` derive macros via
//! `#[wit]` annotations. The recursive tree types (`Predicate`, `RetryPolicy`,
//! `NamedRetryPolicy`) require manual flattening into the WIT node-list
//! representation, so their conversions live here.

use super::{NamedRetryPolicy, Predicate, PredicateValue, RetryPolicy, duration_to_nanos};
use crate::model::agent::bindings::golem::api::retry::{
    AddDelayConfig, ClampConfig, CountBoxConfig, ExponentialConfig, FibonacciConfig,
    FilteredConfig, JitterConfig, NamedRetryPolicy as WitNamedRetryPolicy, PolicyNode,
    PredicateNode, PredicateValue as WitPredicateValue, PropertyComparison, PropertyPattern,
    PropertySetCheck, RetryPolicy as WitRetryPolicy, RetryPredicate, TimeBoxConfig,
};
use std::time::Duration;

// ── PredicateValue ──────────────────────────────────────────────────

impl From<PredicateValue> for WitPredicateValue {
    fn from(v: PredicateValue) -> Self {
        match v {
            PredicateValue::Text(s) => WitPredicateValue::Text(s),
            PredicateValue::Integer(i) => WitPredicateValue::Integer(i),
            PredicateValue::Boolean(b) => WitPredicateValue::Boolean(b),
        }
    }
}

impl From<WitPredicateValue> for PredicateValue {
    fn from(v: WitPredicateValue) -> Self {
        match v {
            WitPredicateValue::Text(s) => PredicateValue::Text(s),
            WitPredicateValue::Integer(i) => PredicateValue::Integer(i),
            WitPredicateValue::Boolean(b) => PredicateValue::Boolean(b),
        }
    }
}

// ── WitNamedRetryPolicy → NamedRetryPolicy (unflatten) ──────────────

impl From<WitNamedRetryPolicy> for NamedRetryPolicy {
    fn from(w: WitNamedRetryPolicy) -> Self {
        Self {
            name: w.name,
            priority: w.priority,
            predicate: predicate_from_wit(&w.predicate),
            policy: policy_from_wit(&w.policy),
        }
    }
}

impl From<WitRetryPolicy> for RetryPolicy {
    fn from(w: WitRetryPolicy) -> Self {
        policy_from_wit(&w)
    }
}

fn nanos_to_duration(nanos: u64) -> Duration {
    Duration::from_nanos(nanos)
}

fn predicate_from_wit(pred: &RetryPredicate) -> Predicate {
    predicate_node_from_wit(&pred.nodes, 0)
}

fn predicate_node_from_wit(nodes: &[PredicateNode], idx: i32) -> Predicate {
    match &nodes[idx as usize] {
        PredicateNode::PropEq(c) => Predicate::PropEq {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropNeq(c) => Predicate::PropNeq {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropGt(c) => Predicate::PropGt {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropGte(c) => Predicate::PropGte {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropLt(c) => Predicate::PropLt {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropLte(c) => Predicate::PropLte {
            property: c.property_name.clone(),
            value: c.value.clone().into(),
        },
        PredicateNode::PropExists(name) => Predicate::PropExists(name.clone()),
        PredicateNode::PropIn(check) => Predicate::PropIn {
            property: check.property_name.clone(),
            values: check
                .values
                .iter()
                .cloned()
                .map(PredicateValue::from)
                .collect(),
        },
        PredicateNode::PropMatches(p) => Predicate::PropMatches {
            property: p.property_name.clone(),
            pattern: p.pattern.clone(),
        },
        PredicateNode::PropStartsWith(p) => Predicate::PropStartsWith {
            property: p.property_name.clone(),
            prefix: p.pattern.clone(),
        },
        PredicateNode::PropContains(p) => Predicate::PropContains {
            property: p.property_name.clone(),
            substring: p.pattern.clone(),
        },
        PredicateNode::PredAnd((l, r)) => Predicate::And(
            Box::new(predicate_node_from_wit(nodes, *l)),
            Box::new(predicate_node_from_wit(nodes, *r)),
        ),
        PredicateNode::PredOr((l, r)) => Predicate::Or(
            Box::new(predicate_node_from_wit(nodes, *l)),
            Box::new(predicate_node_from_wit(nodes, *r)),
        ),
        PredicateNode::PredNot(i) => Predicate::Not(Box::new(predicate_node_from_wit(nodes, *i))),
        PredicateNode::PredTrue => Predicate::True,
        PredicateNode::PredFalse => Predicate::False,
    }
}

fn policy_from_wit(policy: &WitRetryPolicy) -> RetryPolicy {
    policy_node_from_wit(&policy.nodes, 0)
}

fn policy_node_from_wit(nodes: &[PolicyNode], idx: i32) -> RetryPolicy {
    match &nodes[idx as usize] {
        PolicyNode::Periodic(d) => RetryPolicy::Periodic(nanos_to_duration(*d)),
        PolicyNode::Exponential(c) => RetryPolicy::Exponential {
            base_delay: nanos_to_duration(c.base_delay),
            factor: c.factor,
        },
        PolicyNode::Fibonacci(c) => RetryPolicy::Fibonacci {
            first: nanos_to_duration(c.first),
            second: nanos_to_duration(c.second),
        },
        PolicyNode::Immediate => RetryPolicy::Immediate,
        PolicyNode::Never => RetryPolicy::Never,
        PolicyNode::CountBox(c) => RetryPolicy::CountBox {
            max_retries: c.max_retries,
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::TimeBox(c) => RetryPolicy::TimeBox {
            limit: nanos_to_duration(c.limit),
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::ClampDelay(c) => RetryPolicy::Clamp {
            min_delay: nanos_to_duration(c.min_delay),
            max_delay: nanos_to_duration(c.max_delay),
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::AddDelay(c) => RetryPolicy::AddDelay {
            delay: nanos_to_duration(c.delay),
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::Jitter(c) => RetryPolicy::Jitter {
            factor: c.factor,
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::FilteredOn(c) => RetryPolicy::FilteredOn {
            predicate: predicate_from_wit(&c.predicate),
            inner: Box::new(policy_node_from_wit(nodes, c.inner)),
        },
        PolicyNode::AndThen((l, r)) => RetryPolicy::AndThen(
            Box::new(policy_node_from_wit(nodes, *l)),
            Box::new(policy_node_from_wit(nodes, *r)),
        ),
        PolicyNode::PolicyUnion((l, r)) => RetryPolicy::Union(
            Box::new(policy_node_from_wit(nodes, *l)),
            Box::new(policy_node_from_wit(nodes, *r)),
        ),
        PolicyNode::PolicyIntersect((l, r)) => RetryPolicy::Intersect(
            Box::new(policy_node_from_wit(nodes, *l)),
            Box::new(policy_node_from_wit(nodes, *r)),
        ),
    }
}

// ── NamedRetryPolicy → WitNamedRetryPolicy (flatten) ────────────────

impl From<NamedRetryPolicy> for WitNamedRetryPolicy {
    fn from(p: NamedRetryPolicy) -> Self {
        Self {
            name: p.name,
            priority: p.priority,
            predicate: predicate_to_wit(p.predicate),
            policy: policy_to_wit(p.policy),
        }
    }
}

// ── RetryPolicy ─────────────────────────────────────────────────────

impl From<RetryPolicy> for WitRetryPolicy {
    fn from(p: RetryPolicy) -> Self {
        policy_to_wit(p)
    }
}

// ── Predicate helpers ───────────────────────────────────────────────

fn predicate_to_wit(pred: Predicate) -> RetryPredicate {
    let mut nodes = Vec::new();
    push_predicate_node_wit(pred, &mut nodes);
    RetryPredicate { nodes }
}

fn push_predicate_node_wit(pred: Predicate, nodes: &mut Vec<PredicateNode>) -> i32 {
    let idx = nodes.len() as i32;
    // placeholder
    nodes.push(PredicateNode::PredTrue);

    let node = match pred {
        Predicate::PropEq { property, value } => PredicateNode::PropEq(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropNeq { property, value } => PredicateNode::PropNeq(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropGt { property, value } => PredicateNode::PropGt(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropGte { property, value } => PredicateNode::PropGte(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropLt { property, value } => PredicateNode::PropLt(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropLte { property, value } => PredicateNode::PropLte(PropertyComparison {
            property_name: property,
            value: value.into(),
        }),
        Predicate::PropExists(property) => PredicateNode::PropExists(property),
        Predicate::PropIn { property, values } => PredicateNode::PropIn(PropertySetCheck {
            property_name: property,
            values: values.into_iter().map(Into::into).collect(),
        }),
        Predicate::PropMatches { property, pattern } => {
            PredicateNode::PropMatches(PropertyPattern {
                property_name: property,
                pattern,
            })
        }
        Predicate::PropStartsWith { property, prefix } => {
            PredicateNode::PropStartsWith(PropertyPattern {
                property_name: property,
                pattern: prefix,
            })
        }
        Predicate::PropContains {
            property,
            substring,
        } => PredicateNode::PropContains(PropertyPattern {
            property_name: property,
            pattern: substring,
        }),
        Predicate::And(l, r) => {
            let li = push_predicate_node_wit(*l, nodes);
            let ri = push_predicate_node_wit(*r, nodes);
            PredicateNode::PredAnd((li, ri))
        }
        Predicate::Or(l, r) => {
            let li = push_predicate_node_wit(*l, nodes);
            let ri = push_predicate_node_wit(*r, nodes);
            PredicateNode::PredOr((li, ri))
        }
        Predicate::Not(inner) => {
            let i = push_predicate_node_wit(*inner, nodes);
            PredicateNode::PredNot(i)
        }
        Predicate::True => PredicateNode::PredTrue,
        Predicate::False => PredicateNode::PredFalse,
    };

    nodes[idx as usize] = node;
    idx
}

// ── Policy helpers ──────────────────────────────────────────────────

fn policy_to_wit(policy: RetryPolicy) -> WitRetryPolicy {
    let mut nodes = Vec::new();
    push_policy_node_wit(policy, &mut nodes);
    WitRetryPolicy { nodes }
}

fn push_policy_node_wit(policy: RetryPolicy, nodes: &mut Vec<PolicyNode>) -> i32 {
    let idx = nodes.len() as i32;
    // placeholder
    nodes.push(PolicyNode::Never);

    let node = match policy {
        RetryPolicy::Periodic(d) => PolicyNode::Periodic(duration_to_nanos(d)),
        RetryPolicy::Exponential { base_delay, factor } => {
            PolicyNode::Exponential(ExponentialConfig {
                base_delay: duration_to_nanos(base_delay),
                factor,
            })
        }
        RetryPolicy::Fibonacci { first, second } => PolicyNode::Fibonacci(FibonacciConfig {
            first: duration_to_nanos(first),
            second: duration_to_nanos(second),
        }),
        RetryPolicy::Immediate => PolicyNode::Immediate,
        RetryPolicy::Never => PolicyNode::Never,
        RetryPolicy::CountBox { max_retries, inner } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::CountBox(CountBoxConfig {
                max_retries,
                inner: i,
            })
        }
        RetryPolicy::TimeBox { limit, inner } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::TimeBox(TimeBoxConfig {
                limit: duration_to_nanos(limit),
                inner: i,
            })
        }
        RetryPolicy::Clamp {
            min_delay,
            max_delay,
            inner,
        } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::ClampDelay(ClampConfig {
                min_delay: duration_to_nanos(min_delay),
                max_delay: duration_to_nanos(max_delay),
                inner: i,
            })
        }
        RetryPolicy::AddDelay { delay, inner } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::AddDelay(AddDelayConfig {
                delay: duration_to_nanos(delay),
                inner: i,
            })
        }
        RetryPolicy::Jitter { factor, inner } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::Jitter(JitterConfig { factor, inner: i })
        }
        RetryPolicy::FilteredOn { predicate, inner } => {
            let i = push_policy_node_wit(*inner, nodes);
            PolicyNode::FilteredOn(FilteredConfig {
                predicate: predicate_to_wit(predicate),
                inner: i,
            })
        }
        RetryPolicy::AndThen(l, r) => {
            let li = push_policy_node_wit(*l, nodes);
            let ri = push_policy_node_wit(*r, nodes);
            PolicyNode::AndThen((li, ri))
        }
        RetryPolicy::Union(l, r) => {
            let li = push_policy_node_wit(*l, nodes);
            let ri = push_policy_node_wit(*r, nodes);
            PolicyNode::PolicyUnion((li, ri))
        }
        RetryPolicy::Intersect(l, r) => {
            let li = push_policy_node_wit(*l, nodes);
            let ri = push_policy_node_wit(*r, nodes);
            PolicyNode::PolicyIntersect((li, ri))
        }
    };

    nodes[idx as usize] = node;
    idx
}
