@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class)

package cloud.golem.wasm

import kotlin.wasm.unsafe.Pointer
import kotlin.wasm.unsafe.withScopedMemoryAllocator

// Persistent bump allocator over a high linear-memory region. Force one growth so the pages exist;
// the stdlib's scoped allocator works in low addresses (resetting per scope), so a hand-managed
// bump pointer above BASE persists across the host's realloc -> invoke -> post-return calls.
private const val BASE = 16 * 1024 * 1024
private const val SIZE = 16 * 1024 * 1024
private var bump = 0

private fun ensureInit() {
    if (bump == 0) {
        withScopedMemoryAllocator { a -> a.allocate(BASE + SIZE) } // grow; pages persist after free
        bump = BASE
    }
}

fun alloc(size: Int, align: Int): Int {
    ensureInit()
    val mask = align - 1
    bump = (bump + mask) and mask.inv()
    val p = bump
    bump += size
    return p
}

fun resetHeap() {
    if (bump != 0) bump = BASE
}

// NOT @WasmExport here: a Kotlin/Wasm library dependency's @WasmExport declarations do not
// survive into a consuming executable's final linked module (verified empirically -- the
// same class of cross-module DCE limitation documented on Guest.kt). The actual
// `cabi_realloc` export is generated by KSP (NativeRegistrationEmitter) in the agent's own
// module, delegating to this function.
fun cabiRealloc(oldPtr: Int, oldSize: Int, align: Int, newSize: Int): Int = alloc(newSize, if (align == 0) 1 else align)

fun storeByte(ptr: Int, v: Byte) = Pointer(ptr.toUInt()).storeByte(v)
fun loadByte(ptr: Int): Byte = Pointer(ptr.toUInt()).loadByte()
fun storeInt(ptr: Int, v: Int) = Pointer(ptr.toUInt()).storeInt(v)
fun loadInt(ptr: Int): Int = Pointer(ptr.toUInt()).loadInt()
fun storeLong(ptr: Int, v: Long) = Pointer(ptr.toUInt()).storeLong(v)
fun loadLong(ptr: Int): Long = Pointer(ptr.toUInt()).loadLong()
fun storeShort(ptr: Int, v: Short) = Pointer(ptr.toUInt()).storeShort(v)
fun loadShort(ptr: Int): Short = Pointer(ptr.toUInt()).loadShort()

// kotlin.wasm.unsafe.Pointer has no store/loadFloat/Double -- reinterpret bits via the
// existing store/loadInt (Float, 32 bits) and store/loadLong (Double, 64 bits).
fun storeFloat(ptr: Int, v: Float) = Pointer(ptr.toUInt()).storeInt(v.toRawBits())
fun loadFloat(ptr: Int): Float = Float.fromBits(Pointer(ptr.toUInt()).loadInt())
fun storeDouble(ptr: Int, v: Double) = Pointer(ptr.toUInt()).storeLong(v.toRawBits())
fun loadDouble(ptr: Int): Double = Double.fromBits(Pointer(ptr.toUInt()).loadLong())

// The wasmWasi target is declared as an executable (binaries.executable()); it requires a `main`.
// The real reactor entrypoint (agent registration) arrives with the native runtime.
fun main() {}
