name: On Demand Benchmark
on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  WASM_RQUICKJS_VERSION: "v0.1.5"
  WASI_SDK_VERSION: "25"
  WASI_SDK_PATH: /opt/wasi-sdk

jobs:
  run-benchmark:
    runs-on: blacksmith-32vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-rust
        with:
          cache-prefix-key: 'v3-rust'
          cache-shared-key: 'release'
          cache-save-if: 'true'
          rust-targets: 'wasm32-wasip1 wasm32-wasip2'
          install-cargo-binstall: 'true'
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1.35.1
        with:
          redis-version: latest
          auto-start: false

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install WASI SDK
        run: |
          curl -sSfL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_VERSION}/wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux.tar.gz | sudo tar xz -C /opt
          sudo mv /opt/wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux /opt/wasi-sdk

      - name: Install cargo-component
        run: cargo binstall --force cargo-component@0.21.1

      - name: Install wasm-rquickjs
        run: cargo install wasm-rquickjs-cli --git https://github.com/golemcloud/wasm-rquickjs.git --tag $WASM_RQUICKJS_VERSION

      - name: Building release executables
        run: cargo make --profile ci build-release

      - name: Build benchmark test components
        run: cargo make build-benchmark-components

      - name: Checkout benchmark results repository
        uses: actions/checkout@v5
        with:
          repository: 'golemcloud/benchmark-results'
          token: ${{ secrets.BENCHMARK_RESULTS_TOKEN }}
          path: benchmark-results

      - name: Run benchmark suite
        run: cargo run --profile benchmarks -p integration-tests --bin benchmarks '--' --primary-only suite --add-to-json benchmark-results/results/results.json integration-tests/benchmark_suites/ci.yaml spawned

      - name: Commit results
        run: |
          cd benchmark-results
          git config user.name  'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add results/results.json
          git diff --staged --quiet || (git commit -m "Appended new benchmark results" && git push)
