name: Daily Windows Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  checks: write

jobs:
  build-windows:
    runs-on: windows-latest-large
    env:
      CARGO_BUILD_JOBS: 10
    steps:
      - uses: ./.github/actions/setup-rust
        with:
          cache-prefix-key: 'v3-rust'
          cache-shared-key: 'windows-daily'
          cache-save-if: 'true'
          purge-v8: 'false'

      - name: Building all executables
        env:
          QUIET: true
        run: cargo make --profile ci build-all-bins-including-tests
        timeout-minutes: 120
