INSERT INTO usage_types (usage_type, name) VALUES (10, 'MONTHLY_DURABLE_AGENT_STORAGE_BYTE_SECONDS');
INSERT INTO usage_types (usage_type, name) VALUES (11, 'MONTHLY_EPHEMERAL_STORAGE_BYTE_SECONDS');
